### ISSUE TITLE
Include `tap-runner`

### ISSUE THREAD

**Issue by indexzero** [tapjs/tapjs#1]
Been seeing this pop up across my installation of node/npm:

```
  npm WARN tap-runner 0.x Unmet dependency in /usr/local/lib/node_modules/sudojitsu/node_modules/optimist/node_modules/wordwrap/node_modules/tap
```

Looks like it exists in the `package.json` file, using the `0.x` syntax. `npm view tap-runner` does in-fact yield a package, so it's even stranger to see these warnings. No clue really where the bug could be, but worth mentioning.

**Comment by isaacs** [comment]
Looks like maybe an issue with wordwrap bundling a half-installed tap package?

**Comment by indexzero** [comment]
Yeah, like I said I'm not sure exactly. One question for you regarding your comment on the other thread:

> Dependencies should be published if any of the following are true:
> 
> The dependency is on the "bundledDependencies" list.
> The dependency is not in the "dependencies" or "devDependencies" hash."

Is there an option for disabling this by default? (i.e. don't publish things in `node_modules` that don't meet the above criteria). I install `eyes` into a lot of libraries when debugging and I consistently forget to uninstall it.
