### ISSUE TITLE
[FEAT] `--disable-coverage` should imply `--allow-empty-coverage`

### ISSUE THREAD

**Issue by grahamb** [tapjs/tapjs#1001]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the `CONTRIBUTING` guide on posting bugs, and `CODE_OF_CONDUCT`?

- [X] yes I read the things

### This issue exists in the latest tap version

- [X] I am using the latest tap

### Description

This seems like a repeat of, or at least related to, #110. I have a file containing test helpers that I skip using the `--exclude` flag. When I run my tests, `tap` exits with a `1` exit code.

![image](https://github.com/tapjs/tapjs/assets/146111/5b91c4b7-8ea6-48cb-bf2a-a887882e20d4)

### Reproduction

1. Use `--exclude` to exclude a file or pattern of files from tests
2. Run tap
3. Inspect value of `$?`. If all test pass, it *should* be `0` but it will be `1`.

### Environment

```
❯ npm ls tap                      
PROJECT_REDACTED@2.0.0 PATH_REDACTED
└── tap@18.7.0

❯ npx tap versions                                                     
tap: 18.7.0
"@tapjs/config": 2.4.15
"@tapjs/core": 1.5.0
"@tapjs/run": 1.5.0
"@tapjs/stack": 1.2.7
"@tapjs/test": 1.4.0
tap-parser: 15.3.1
tap-yaml: 2.2.1
tcompare: 6.4.5
plugins:
  "@tapjs/after": 1.1.18
  "@tapjs/after-each": 1.1.18
  "@tapjs/asserts": 1.1.18
  "@tapjs/before": 1.1.18
  "@tapjs/before-each": 1.1.18
  "@tapjs/filter": 1.2.18
  "@tapjs/fixture": 1.2.18
  "@tapjs/intercept": 1.2.18
  "@tapjs/mock": 1.3.0
  "@tapjs/node-serialize": 1.3.0
  "@tapjs/snapshot": 1.2.18
  "@tapjs/spawn": 1.1.18
  "@tapjs/stdin": 1.1.18
  "@tapjs/typescript": 1.4.0
  "@tapjs/worker": 1.1.18

❯ npx tap config list
# vim: set filetype=yaml :
color: true
coverage-report:
  - text
exclude:
  - "**/@(fixture*(s)|dist)/**"
include:
  - "**/@(test?(s)|__test?(s)__)/**/*.@(js|cjs|mjs|tap|cts|jsx|mts|ts|tsx)"
  - "**/*.@(test?(s)|spec).@(js|cjs|mjs|tap|cts|jsx|mts|ts|tsx)"
  - "**/test?(s).@(js|cjs|mjs|tap|cts|jsx|mts|ts|tsx)"
jobs: 3
reporter: base
snapshot-clean-cwd: true
timeout: 30

❯ npx tap plugin list
@tapjs/after
@tapjs/after-each
@tapjs/asserts
@tapjs/before
@tapjs/before-each
@tapjs/filter
@tapjs/fixture
@tapjs/intercept
@tapjs/mock
@tapjs/node-serialize
@tapjs/snapshot
@tapjs/spawn
@tapjs/stdin
@tapjs/typescript
@tapjs/worker

❯ uname -a                            
Linux [HOSTNAME_REDACTED] 4.18.0-477.21.1.el8_8.x86_64 #1 SMP Thu Jul 20 08:38:27 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by isaacs** [comment]
`--allow-empty-coverage`

Probably that should be implied if `--disable-coverage` is set, or maybe `--disable-coverage` could be renamed to `--mysteriously-fail-and-post-a-github-issue-about-it` 😅

**Comment by isaacs** [comment]
(You're not the first to fall for that trap, it's a terrible footgun, I'm sorry.)

**Comment by grahamb** [comment]
Thanks for the pointer, @isaacs; that solved the issue, just like the help docs says it would 🤦 . I should have read those more closely.

I can open a separate issue for this, but the reason I'm disabling coverage in my CI tests is that I'm using the JUnit reporter, and it seems to produce invalid XML. For example:

![image](https://github.com/tapjs/tapjs/assets/146111/4496145e-5965-4136-996a-77dfc02e1913)

You can see that it starts the XML file, but then the coverage detail gets written to STDOUT, followed by the rest of the XML. I use a junit parser in my GitHub Actions workflow, and it barfs trying to parse this because it's invalid XML.

**Comment by isaacs** [comment]
The coverage details are being written to stderr, so you can split them out that way if you'd like. Or you can use `--reporter-file=junit.xml` and then use the file it creates, rather than trying to parse the combined stderr/stdout data.

**Comment by isaacs** [comment]
Aha, my mistake, the coverage report is indeed going to stdout.

You can also turn it off the _report_ with `--coverage-report=none`, but it'll still fail if you don't generate full coverage, unless `--allow-incomplete-coverage` is set.
