### ISSUE TITLE
[BUG] Long standing bug in ink is causing crash on start.

### ISSUE THREAD

**Issue by bn-l** [tapjs/tapjs#1010]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the `CONTRIBUTING` guide on posting bugs, and `CODE_OF_CONDUCT`?

- [X] yes I read the things

### This issue exists in the latest tap version

- [x] I am using the latest tap

### Description

This is about a year long bug. 

Currently ink will try and load react dev tools if the env var **"DEV"** is set to "true" (note: not NODE_ENV or INK_ENV--which makes it easy to accidentally have this flag flipped. Like I did today, basically this env var is always true on my machine.)

Also, Ink (via react) will block if it can't access dev tools (it's unreliable I think on windows) even if the event loop is empty as there is a worker long polling the server.

I'm trying tap for the first time. Coincidentally I reported it last week: https://github.com/vadimdemedes/ink/issues/648.

What I see when running tap:
```powershell
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'react-devtools-core' imported from \\node_modules\ink\build\devtools.js
    at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
    at new NodeError (node:internal/errors:405:5)
    at packageResolve (node:internal/modules/esm/resolve:890:9)
    at moduleResolve (node:internal/modules/esm/resolve:939:20)
    at defaultResolve (node:internal/modules/esm/resolve:1132:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v18.18.2
```

If dev tools is not installed (it's an optional peer dependency) then tap will crash. The error handling doesn't give much information also. 

I'm a little surprised there isn't an issue already on this in particular.

[This](https://github.com/vadimdemedes/ink/blob/168244470cd3e4b85e19b968a55938d013232761/src/reconciler.ts#L24) is the location of the issue:

```typescript
if (process.env['DEV'] === 'true') {
	try {
		await import('./devtools.js');
	} catch (error: any) {
		if (error.code === 'MODULE_NOT_FOUND') {
			console.warn(
				`
Debugging with React Devtools requires \`react-devtools-core\` dependency to be installed.

$ npm install --save-dev react-devtools-core
				`.trim() + '\n'
			);
		} else {
			// eslint-disable-next-line @typescript-eslint/no-throw-literal
			throw error;
		}
	}
}
```

### Reproduction

Use node 18 (officially supported by the package.json), set the env var to DEV=true then run npx tap in a node 18 project folder with tap tests.

### Environment

which tap: `npx tap`

npm ls tap: `npx tap`

tap versions: `18.7.1`

tap config list:
`# vim: set filetype=yaml :
color: true
coverage-report:
  - text
exclude:
  - "**/@(fixture*(s)|dist)/**"
include:
  - "**/@(test?(s)|__test?(s)__)/**/*.@(js|cjs|mjs|tap|cts|jsx|mts|ts|tsx)"
  - "**/*.@(test?(s)|spec).@(js|cjs|mjs|tap|cts|jsx|mts|ts|tsx)"
  - "**/test?(s).@(js|cjs|mjs|tap|cts|jsx|mts|ts|tsx)"
jobs: 9
reporter: base
snapshot-clean-cwd: true
timeout: 30`

**Comment by bn-l** [comment]
https://github.com/vadimdemedes/ink/pull/651

**Comment by isaacs** [comment]
Haha wow, I'm also surprised that never came up before. I wonder if we can set it before loading ink. It should only matter in the runner/reporter, so it shouldn't matter what's in the test process envs, since they don't load ink.

**Comment by bn-l** [comment]
The pr “fixed” it (but it will still spam unfortunately). My own solution was the same as your idea and it’s working great (save value of env var, dynamically import ink, reload value). I made a wrapper for it. I’ll put in a pr here if you like.
