### ISSUE TITLE
[BUG] matchSnapshot returns RangeError

### ISSUE THREAD

**Issue by kingjerod** [tapjs/tapjs#1013]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the `CONTRIBUTING` guide on posting bugs, and `CODE_OF_CONDUCT`?

- [X] yes I read the things

### This issue exists in the latest tap version

- [X] I am using the latest tap

### Description

Just trying to get a basic matchSnapshot to work. I haven't done anything to Tap besides install it. 
Running this command: `npx tap --snapshot test/a.ts`
Returns this error:
![image](https://github.com/tapjs/tapjs/assets/2287252/706395e8-ec2e-4fde-baa1-03f6ccda3727)

If I move the 2 lines inside the test to outside and remove the Tap.test, I get this error:
![image](https://github.com/tapjs/tapjs/assets/2287252/96e7f153-c8b1-4a66-a0cd-e33b51a02168)

Seems like it can't do something with the CWD?

### Reproduction

```typescript
import Tap from "tap";

function sayHello(name) {
  return "Hello " + name + "!";
}

Tap.test("test hello", async (t) => {
  const result = sayHello("Sparky");
  t.matchSnapshot(result, "sparky");
});

```

### Environment

```
Node Docker image: node:18.17.1-slim

Tap versions:
tap@18.7.1
@tapjs/core@1.5.1
@tapjs/snapshot@1.2.19
@tapjs/typescript@1.4.1
@tapjs/test@1.4.1

tap config list
# vim: set filetype=yaml :
color: true
coverage-report:
  - text
exclude:
  - "**/@(fixture*(s)|dist)/**"
include:
  - "**/@(test?(s)|__test?(s)__)/**/*.@(js|cjs|mjs|tap|cts|jsx|mts|ts|tsx)"
  - "**/*.@(test?(s)|spec).@(js|cjs|mjs|tap|cts|jsx|mts|ts|tsx)"
  - "**/test?(s).@(js|cjs|mjs|tap|cts|jsx|mts|ts|tsx)"
jobs: 2
reporter: base
snapshot-clean-cwd: true
timeout: 30

tap plugin list
@tapjs/after
@tapjs/after-each
@tapjs/asserts
@tapjs/before
@tapjs/before-each
@tapjs/filter
@tapjs/fixture
@tapjs/intercept
@tapjs/mock
@tapjs/node-serialize
@tapjs/snapshot
@tapjs/spawn
@tapjs/stdin
@tapjs/typescript
@tapjs/worker

# if using typescript:
npm ls @isaacs/ts-node-temp-fork-for-pr-2009
`-- tap@18.7.1
  +-- @tapjs/test@1.4.1
  | `-- @isaacs/ts-node-temp-fork-for-pr-2009@10.9.5
  `-- @tapjs/typescript@1.4.1
    `-- @isaacs/ts-node-temp-fork-for-pr-2009@10.9.5

npm ls typescript
+-- tap@18.7.1
| +-- @tapjs/test@1.4.1
| | +-- @isaacs/ts-node-temp-fork-for-pr-2009@10.9.5
| | | `-- typescript@5.2.2 deduped
| | +-- tshy@1.12.0
| | | `-- typescript@5.3.3
| | `-- typescript@5.2.2
| `-- @tapjs/typescript@1.4.1
|   `-- @isaacs/ts-node-temp-fork-for-pr-2009@10.9.5
|     `-- typescript@5.2.2
`-- typescript@4.3.2
```

**Comment by isaacs** [comment]
Hm. What's the cwd that you're running this in? If I'm reading the code there correctly (big if 😅) it looks like this would only happen if the cwd is less than 5 characters long.

Easy enough fix, just checking to make sure I'm fixing the right problem.

**Comment by kingjerod** [comment]
I was running it in `/app`. Awesome, thanks for the quick fix. How often do you do releases?

**Comment by isaacs** [comment]
> How often do you do releases?

Depends, usually when I have some fixes and I'm not imminently fixing anything else, I'll cut a release. I'll get this out tomorrow. I'd hoped to take a look at the mochaglobals plugin stuff, but that seems a bit more complicated, so I'll punt it to the next one.
