### ISSUE TITLE
[BUG] TypeError: Cannot read private member #Class from an object whose class did not declare it

### ISSUE THREAD

**Issue by bnwa** [tapjs/tapjs#1014]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the `CONTRIBUTING` guide on posting bugs, and `CODE_OF_CONDUCT`?

- [X] yes I read the things

### This issue exists in the latest tap version

- [X] I am using the latest tap

### Description

TypeError being thrown whenever `tap run` is fired regardless of input test file from `@tapjs/test/test-built/src/index.ts:740`:
```
this.#Class,
     ^
TypeError: Cannot read private member #Class from an object whose class
did not declare it
```

### Reproduction

Smallest reproducible demostration source, executed on Node@`v21.6.2`:
```
import * as tap from 'tap'

tap.test("This will err", t => { t.end() })
```

### Environment

`which tap`:

`npm ls tap`:
regarder@0.0.1 /Path/to/Repo
└── tap@18.7.1

`tap versions`:
tap: 18.7.1
"@tapjs/config": 2.4.16
"@tapjs/core": 1.5.1
"@tapjs/run": 1.5.1
"@tapjs/stack": 1.2.7
"@tapjs/test": 1.4.1
tap-parser: 15.3.1
tap-yaml: 2.2.1
tcompare: 6.4.5
plugins:
  "@tapjs/after": 1.1.19
  "@tapjs/after-each": 1.1.19
  "@tapjs/asserts": 1.1.19
  "@tapjs/before": 1.1.19
  "@tapjs/before-each": 1.1.19
  "@tapjs/filter": 1.2.19
  "@tapjs/fixture": 1.2.19
  "@tapjs/intercept": 1.2.19
  "@tapjs/mock": 1.3.1
  "@tapjs/node-serialize": 1.3.1
  "@tapjs/snapshot": 1.2.19
  "@tapjs/spawn": 1.1.19
  "@tapjs/stdin": 1.1.19
  "@tapjs/typescript": 1.4.1
  "@tapjs/worker": 1.1.19

`tap config list`:
// vim: set filetype=yaml :
color: false
coverage-report:
  - text
exclude:
  - "**/@(fixture*(s)|dist)/**"
include:
  - "**/@(test?(s)|__test?(s)__)/**/*.@(js|cjs|mjs|tap|cts|jsx|mts|ts|tsx)"
  - "**/*.@(test?(s)|spec).@(js|cjs|mjs|tap|cts|jsx|mts|ts|tsx)"
  - "**/test?(s).@(js|cjs|mjs|tap|cts|jsx|mts|ts|tsx)"
jobs: 6
reporter: tap
snapshot-clean-cwd: true
timeout: 30

`tap plugin list`:
@tapjs/after
@tapjs/after-each
@tapjs/asserts
@tapjs/before
@tapjs/before-each
@tapjs/filter
@tapjs/fixture
@tapjs/intercept
@tapjs/mock
@tapjs/node-serialize
@tapjs/snapshot
@tapjs/spawn
@tapjs/stdin
@tapjs/typescript
@tapjs/worker

# if using typescript:
`npm ls @isaacs/ts-node-temp-fork-for-pr-2009`:
regarder@0.0.1 /Path/to/Repo
└─┬ tap@18.7.1
  ├─┬ @tapjs/test@1.4.1
  │ └── @isaacs/ts-node-temp-fork-for-pr-2009@10.9.5
  └─┬ @tapjs/typescript@1.4.1
    └── @isaacs/ts-node-temp-fork-for-pr-2009@10.9.5 deduped

`npm ls typescript`:
regarder@0.0.1 /Users/barberousse/Developer/regarder
├─┬ tap@18.7.1
│ └─┬ @tapjs/test@1.4.1
│   ├─┬ @isaacs/ts-node-temp-fork-for-pr-2009@10.9.5
│   │ └── typescript@5.2.2 deduped
│   ├─┬ tshy@1.12.0
│   │ └── typescript@5.3.3
│   └── typescript@5.2.2 deduped
└─┬ ts-node@10.9.2
  └── typescript@5.2.2

# posix:
`uname -a`
Darwin {device address} 23.3.0 Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:27 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T8103 arm64

**Comment by bnwa** [comment]
Great, Node ESM/TS config madness. Apologies for calling your attention.

**Comment by isaacs** [comment]
You can either `import { test } from 'tap'` or `import t from tap`, but `* as tap` isn't supported. Maybe could make it work somehow, not sure, but it doesn't work like that right now.

**Comment by bnwa** [comment]
@isaacs Yeah, that was apart of the problem I'd addressed. Appreciate the response at any rate.
