### ISSUE TITLE
[BUG] Timeout error when running Node.js HTTP Server with TAP

### ISSUE THREAD

**Issue by pedrollmatias** [tapjs/tapjs#1015]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the `CONTRIBUTING` guide on posting bugs, and `CODE_OF_CONDUCT`?

- [X] yes I read the things

### This issue exists in the latest tap version

- [X] I am using the latest tap

### Description

When launching a Node.js application server using the [fastify](https://www.npmjs.com/package/fastify-cli) framework (not tested with other frameworks such as express, etc), even if there are no explicit tests implemented (no calls to the `test` function of tap), a timeout error occurs after 30 seconds while the server is listening on the specified port. In theory, there is no direct relationship between tests and the fastify server.

The error only occurs when there is an explicit import/require of the test function from tap.

### Reproduction

Create a Node.js project with the following 2 files:

```js
// package.json
{
  "name": "fastify-tap-timeout",
  "version": "1.0.0",
  "scripts": {
    "start": "npx fastify start -l info -P -w index.js -p 9000 -o"
  },
  "devDependencies": {
    "tap": "18.7.1"
  }
}
```
and

```js
// index.js
const { test } = require("tap"); // <<< If this line is commented out, the bug does not occur.

module.exports = async (fastify, opts) => {};
```

Simply run `npm install` and then `npm start` to observe the following bug being reproduced:
```
[14:52:06.720] INFO (150594): Server listening at http://127.0.0.1:9000
TAP version 14
not ok 1 - timeout!
  ---
  signal: null
  handles:
    - type: Pipe
    - type: Server
      events:
        - request
        - connection
        - listening
        - clientError
      connectionKey: 4:127.0.0.1:9000
  expired: TAP
  test: TAP
  ...

1..1
# { total: 1, pass: 0, fail: 1 }
# time=30032.312ms
```

It's important to note that this behavior did not occur with version 16.x of tap.

The expected behavior was simply not to encounter a timeout error when the server is running, since no tests are being executed.

### Environment

```
tap 18.7.1 
node 18.19.0
npm 10.2.3
Ubuntu 22.04
```

**Comment by globalexport** [comment]
tap@18.5.2 is working for me; everything after is failing.

**Comment by isaacs** [comment]
`t.teardown(() => server.close())`

Send `connection: close` headers with all responses when testing. (Or, if you are specifically testing http connection pooling/reuse/pipelining/etc, make sure to destroy the connections when you're done testing them.)

**Comment by isaacs** [comment]
Oh, wait, you're loading tap in your actual server file?

Lol, yeah, it's going to "time out" at a certain point, because you've started a test program, and it never ends. Working as designed.

What are you _trying_ to do?

**Comment by pedrollmatias** [comment]
> Oh, wait, you're loading tap in your actual server file?
> 
> Lol, yeah, it's going to "time out" at a certain point, because you've started a test program, and it never ends. Working as designed.
> 
> What are you _trying_ to do?

I'm simply running a local server to debug. In my scenario, there's a test-helper (which imports Tap) function exported when this development server is running. However, i'm not invoking any testing function exported by tap API, only importing the tap dependency. I believe the timeout error should only occur if there's an explicit call to the test function, but that isn't the case.

It's important to say that this bahvior only occurs in 18.x version.
