### ISSUE TITLE
[FEATURE] I can't use path aliases for typescript projects

### ISSUE THREAD

**Issue by AnggaaIs** [tapjs/tapjs#1019]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the `CONTRIBUTING` guide on posting issues, and `CODE_OF_CONDUCT`?

- [X] yes I read the things

### Description

![Screenshot_2024-04-17-16-25-42-863_com android chrome](https://github.com/tapjs/tapjs/assets/84172981/b258d32e-8176-4158-a5c4-ad4f23c47aab)
![Screenshot_2024-04-17-16-26-04-857_com android chrome](https://github.com/tapjs/tapjs/assets/84172981/9cfa0da2-62b9-4564-93e7-682b5bfccfd0)
I included the screenshot above, anyone can help me

**Comment by AnggaaIs** [comment]
thank you, i have found the solution, namely adding `--node-arg=--require=tsconfig-paths/register` in cli

**Comment by mirageN1349** [comment]
Thanks 

> thank you, i have found the solution, namely adding `--node-arg=--require=tsconfig-paths/register` in cli

**Comment by MkLHX** [comment]
Hello, i have the same kind of issue when trying to use specific tsconfig.json file.
First i'm trying to use --tsconfig argument
```
npx tap --tsconfig=test/tsconfig.json test/unit/utils/base64.utils.test.ts
```
but get this error 

Error: Cannot find package '@src/utils' imported from /<..>/api/test/unit/utils/base64.utils.test.ts

next i try to use tsconfig-paths/register
```
npx tap -r ts-node/register -r tsconfig-paths/register  --node-arg=--require=tsconfig-paths/register  test/unit/utils/base64.utils.test.ts
```
But i'm still getting the same result.

How to allow tap to resolve path alias ?
