### ISSUE TITLE
[BUG] Tap.END does fully close the project with success

### ISSUE THREAD

**Issue by MarianoFacundoArch** [tapjs/tapjs#1020]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the `CONTRIBUTING` guide on posting bugs, and `CODE_OF_CONDUCT`?

- [X] yes I read the things

### This issue exists in the latest tap version

- [X] I am using the latest tap

### Description

I have tried everything, but for some reason, even tap.end or whatever method I used does not fully close the project, and as I test resource-intensive operations, I use --timeout=0, but I need at a specific point in time to fully force the close of the test and program to mark success. Right now, I am stuck at hitting CTRL + C, or it never ends.

### Reproduction

Using tap.end() with an app with multiple listeners and complex code.

### Environment

18.7.2

**Comment by isaacs** [comment]
Well, if node isn't closing, then something in your program is keeping the event loop open.

I recommend against using `--timeout=0`, as you generally want tests to run quickly, and a test taking too long is a sign that something is wrong.

There's nothing in tap itself that would keep the event loop polling, but without access to your program, I can't even begin to guess what it is.

Try checking `process._getActiveHandles()` and `process._getActiveRequests()` for some clues as to what might be keeping node alive. Usually it's a server or interval that isn't closed when it should be.

**Comment by isaacs** [comment]
Oh, another tip, if you're doing a lot of http server/client stuff in your tests, you might want to configure your test server to send a `connection: close` header, so that the it doesn't keep the socket open to re-use.
