### ISSUE TITLE
[BUG] Plugin add command has issues with tsconfig (missing arguments)

### ISSUE THREAD

**Issue by kingjerod** [tapjs/tapjs#1029]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the `CONTRIBUTING` guide on posting bugs, and `CODE_OF_CONDUCT`?

- [X] yes I read the things

### This issue exists in the latest tap version

- [X] I am using the latest tap

### Description

I am trying to install the sinon plugin. When executing the command to add, it errors with missing arguments.

```
root@386783afb9aa:/application# npx tap plugin add @tapjs/sinon
adding plugins: [ '@tapjs/sinon' ]
error TS6046: Argument for '--module' option must be: 'none', 'commonjs', 'amd', 'system', 'umd', 'es6', 'es2015', 'es2020', 'esnext'.
error TS6046: Argument for '--moduleResolution' option must be: 'node', 'classic'.
error TS6046: Argument for '--target' option must be: 'es3', 'es5', 'es6', 'es2015', 'es2016', 'es2017', 'es2018', 'es2019', 'es2020', 'es2021', 'esnext'.
```

I have a tsconfig.json in the same directory as I'm running the command, those arguments look like they match up with the tsconfig. I do not have a moduleResolution key set, but I tried setting it to node and classic and neither one helped. I can can compile the Typescript successfully.

### Reproduction

Install tap using yarn
Run `npx tap plugin add @tapjs/sinon`

### Environment

tap versions:
```
tap: 19.0.2
"@tapjs/config": 3.0.1
"@tapjs/core": 2.0.1
"@tapjs/run": 2.0.2
"@tapjs/stack": 2.0.1
"@tapjs/test": 2.0.1
tap-parser: 16.0.1
tap-yaml: 2.2.2
tcompare: 7.0.1
plugins:
  "@tapjs/after": 1.1.24
  "@tapjs/after-each": 2.0.1
  "@tapjs/asserts": 2.0.1
  "@tapjs/before": 2.0.1
  "@tapjs/before-each": 2.0.1
  "@tapjs/filter": 2.0.1
  "@tapjs/fixture": 2.0.1
  "@tapjs/intercept": 2.0.1
  "@tapjs/mock": 2.0.1
  "@tapjs/node-serialize": 2.0.1
  "@tapjs/snapshot": 2.0.1
  "@tapjs/spawn": 2.0.1
  "@tapjs/stdin": 2.0.1
  "@tapjs/typescript": 1.4.6
  "@tapjs/worker": 2.0.1
```
tap config list:
```
# vim: set filetype=yaml :
color: true
coverage-report:
  - text
exclude:
  - "**/@(fixture*(s)|dist)/**"
include:
  - "**/@(test?(s)|__test?(s)__)/**/*.@(js|cjs|mjs|tap|cts|jsx|mts|ts|tsx)"
  - "**/*.@(test?(s)|spec).@(js|cjs|mjs|tap|cts|jsx|mts|ts|tsx)"
  - "**/test?(s).@(js|cjs|mjs|tap|cts|jsx|mts|ts|tsx)"
jobs: 12
reporter: base
snapshot-clean-cwd: true
timeout: 30
```
tap plugin list:
```
@tapjs/after
@tapjs/after-each
@tapjs/asserts
@tapjs/before
@tapjs/before-each
@tapjs/filter
@tapjs/fixture
@tapjs/intercept
@tapjs/mock
@tapjs/node-serialize
@tapjs/snapshot
@tapjs/spawn
@tapjs/stdin
@tapjs/typescript
@tapjs/worker
```
# if using typescript:
npm ls @isaacs/ts-node-temp-fork-for-pr-2009:
```
`-- tap@19.0.2
  +-- @tapjs/test@2.0.1
  | `-- @isaacs/ts-node-temp-fork-for-pr-2009@10.9.7
  `-- @tapjs/typescript@1.4.6
    `-- @isaacs/ts-node-temp-fork-for-pr-2009@10.9.7
```
typescript version 4.3.2

npx tsc --showConfig:
```
{
    "compilerOptions": {
        "lib": [
            "es2020"
        ],
        "module": "commonjs",
        "target": "es2020",
        "strict": false,
        "strictNullChecks": false,
        "esModuleInterop": true,
        "skipLibCheck": true,
        "noImplicitAny": false,
        "noImplicitThis": false,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "sourceMap": true
    },
    "files": [
        // lots of source files here
    ],
    "include": [
        "src",
        "test"
    ],
    "exclude": [
        "node_modules"
    ],
    "compileOnSave": true
}
```

node -v: v18.17.1

docker image: node:18.17.1

**Comment by isaacs** [comment]
What version of typescript are you using?

**Comment by kingjerod** [comment]
> What version of typescript are you using?

version 4.3.2

**Comment by isaacs** [comment]
Ah, I think that's the problem, then. The tsconfig being used depends on having typescript version 5.4.

But it should be working with tap 19, since it now builds the plugins in a separate location, with their own typescript/tshy install and tsconfig.json file. You're using 19.0.2 here, so I'm a little surprised that isn't working. Will have to get a repro setup going so I can see what's happening.

**Comment by kingjerod** [comment]
I hope this helps:
https://github.com/kingjerod/tap-plugin-bug-1029

**Comment by isaacs** [comment]
Thanks.

I see what's going on. Instead of just building the build script as a normal module, I'm shipping it as ts, and then have a js file that loads it using my ts-node fork. But then that ts-node fork is getting ts version 4, which the build script can't build under, and it fails.

Will have a fix on the next release.

**Comment by isaacs** [comment]
Ok, 19.1.1 should work now. Care to give it a try? If it's still broken, happy to re-open this and keep investigating.

**Comment by kingjerod** [comment]
Seems to be working with 19.2.1, thanks!
