### ISSUE TITLE
[BUG] t.context properties are not enumerable?

### ISSUE THREAD

**Issue by jsumners-nr** [tapjs/tapjs#1031]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the `CONTRIBUTING` guide on posting bugs, and `CODE_OF_CONDUCT`?

- [X] yes I read the things

### This issue exists in the latest tap version

- [X] I am using the latest tap

### Description

Attempting to use `t.context` in `Object.assign({}, thing, t.context)` is not overwriting defined properties.

This is a pattern that I have used extensively in multiple projects, but specifically:

1. https://github.com/newrelic/node-newrelic/blob/7cd6aef7ecc32d8647f0313b36be368bfa14a0e9/test/unit/llm-events/aws-bedrock/chat-completion-message.test.js
2. https://github.com/newrelic/node-newrelic/blob/7cd6aef7ecc32d8647f0313b36be368bfa14a0e9/lib/llm-events/aws-bedrock/chat-completion-message.js#L39

### Reproduction

Run `node test.js` and `foo.foo` will still be set to `empty` instead of `testing`.

<details>
<summary>package.json</summary>

```json
{
  "dependencies": {
    "tap": "^19.2.3"
  }
}
```

</details>

<details>
<summary>index.js</summary>

```js
'use strict'

const defaultParams = {
	foo: 'empty'
}

class Foo {
	#foo

	constructor(params) {
		const opts = Object.assign({}, defaultParams, params)
		this.#foo = opts.foo
	}

	get foo() {
		return this.#foo
	}
}

module.exports = Foo
```

</details>

<details>
<summary>test.js</summary>

```js
'use strict'

const tap = require('tap')
const Foo = require('./index')

tap.beforeEach(t => {
	t.context = {
		foo: 'testing'
	}
})


tap.test('does it work?', async t => {
	const foo = new Foo(t.context)
	t.equal(foo.foo, 'testing')
})
```

</details>

### Environment

```
❯ which tap
./node_modules/.bin/tap
```

```
❯ npm ls tap
foo@ /private/tmp/10/foo
└── tap@19.2.3
```

```
❯ tap versions
tap: 19.2.3
"@tapjs/config": 3.1.4
"@tapjs/core": 2.1.4
"@tapjs/run": 2.1.5
"@tapjs/stack": 2.0.1
"@tapjs/test": 2.2.2
tap-parser: 16.0.1
tap-yaml: 2.2.2
tcompare: 7.0.1
plugins:
  "@tapjs/after": 1.1.29
  "@tapjs/after-each": 2.0.6
  "@tapjs/asserts": 2.0.6
  "@tapjs/before": 2.0.6
  "@tapjs/before-each": 2.0.6
  "@tapjs/chdir": 1.1.2
  "@tapjs/filter": 2.0.6
  "@tapjs/fixture": 2.0.6
  "@tapjs/intercept": 2.0.6
  "@tapjs/mock": 2.1.4
  "@tapjs/node-serialize": 2.0.6
  "@tapjs/snapshot": 2.0.6
  "@tapjs/spawn": 2.0.6
  "@tapjs/stdin": 2.0.6
  "@tapjs/typescript": 1.4.11
  "@tapjs/worker": 2.0.6
```

```
❯ tap config list
# vim: set filetype=yaml :
browser: true
color: true
coverage-report:
  - text
exclude:
  - "**/@(fixture*(s)|dist)/**"
include:
  - "**/@(test?(s)|__test?(s)__)/**/*.@(js|cjs|mjs|tap|cts|jsx|mts|ts|tsx)"
  - "**/*.@(test?(s)|spec).@(js|cjs|mjs|tap|cts|jsx|mts|ts|tsx)"
  - "**/test?(s).@(js|cjs|mjs|tap|cts|jsx|mts|ts|tsx)"
jobs: 8
reporter: base
snapshot-clean-cwd: true
timeout: 30
```

```
❯ tap plugin list
@tapjs/after
@tapjs/after-each
@tapjs/asserts
@tapjs/before
@tapjs/before-each
@tapjs/chdir
@tapjs/filter
@tapjs/fixture
@tapjs/intercept
@tapjs/mock
@tapjs/node-serialize
@tapjs/snapshot
@tapjs/spawn
@tapjs/stdin
@tapjs/typescript
@tapjs/worker
```

```
❯ uname -a
Darwin TJF0CM7VDG 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000 arm64
```

**Comment by isaacs** [comment]
Ah, I see what's going on.

It's intended to do `t.context = Object.create(parent.context)` if it's not already set. But, when it _was_ set to an object prior to the test function running, it was effectively doing `t.context = Object.create(t.context)`.

Then, because you're doing `Object.assign({}, t.context)`, it's not picking up those inherited props, because `Object.assign` only looks at own properties.

Will be fixed shortly.

**Comment by jsumners-nr** [comment]
Thank you.
