### ISSUE TITLE
[BUG] Unexpected support dropping for active LTS node.js versions

### ISSUE THREAD

**Issue by Mister-Hope** [tapjs/tapjs#1035]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the `CONTRIBUTING` guide on posting bugs, and `CODE_OF_CONDUCT`?

- [X] yes I read the things

### This issue exists in the latest tap version

- [X] I am using the latest tap

### Description

Same as https://github.com/isaacs/node-lru-cache/issues/343

I did not find any actual needs to drop node 18. It will be an active LTS for the next 11 months. Why should it being dropped?

### Reproduction

Not needed

### Environment

not needed.

**Comment by isaacs** [comment]
Please stop this.
