### ISSUE TITLE
tap exits with failure on skipped tests

### ISSUE THREAD

**Issue by sam-github** [tapjs/tapjs#110]
https://github.com/isaacs/node-tap/commit/d3ed42634288278d048972a8fe269f9c404e59c1 was quite helpful, except it doesn't deal with skipped tests.

```
1..8
# tests 8
# pass  6
# skip  2
% echo $?
1
```

So now tap runner says a test has failed if tests are skipped, which I think is the opposite of the intention of skipping a test. I don't have to skip it if its going to cause the tests to fail, skipped or not.

**Comment by xavierchow** [comment]
yes, I found the same problem, skipped one causes test failed is annoying.

```
TAP version 13
# test.js
# TAP version 13
# make sure the thingie is a thing
ok 1 thingie should be thing
ok 2 array has foo and bar elements
ok 3 this is always true
ok 4 this is never true
ok 5 can also skip individual assertions # SKIP
# tests 5
# pass  4
# skip  1
not ok 6 ./test.js
  ---
    exit:    1
    command: "/usr/local/bin/node test.js"
  ...


1..6
# tests 6
# pass  4
# fail  1
# skip  1
```
