### ISSUE TITLE
can tap bump to 1.0.0, so we can depend on tap:^1.x and get new features?

### ISSUE THREAD

**Issue by sam-github** [tapjs/tapjs#118]
Like the ones in v0.6. Thanks for that.

**Comment by rmg** [comment]
I like this idea. I'm actually a little surprised it hadn't been done already.

@isaacs thoughts?

**Comment by rmg** [comment]
I can't speak for @isaacs, but I did notice he created a [v1 branch](https://github.com/isaacs/node-tap/tree/v1) very recently :-)

**Comment by isaacs** [comment]
v1 will be a significant refactor, with no user-facing changes, some very significant API changes internally, and some breaking TAP-format changes (to bring it more in line with other languages' TAP implementations, particularly perl and java.)

You can depend on `^0.6 || 1` to get the new features in 0.6 and also be prepared for 1.x.

**Comment by sam-github** [comment]
Well, you could bump to 1, and release the refactor as 2.x. But I'm OK with 0.7, as long as new features hit it. Last time there was a backwards compatible feature addition, the minor jumped. Its hard to depend on 0.x minors with semver.

**Comment by isaacs** [comment]
The next significant release will be 1.0
