### ISSUE TITLE
asynchronously defined tests sometimes hang until another timer fires

### ISSUE THREAD

**Issue by wraithan** [tapjs/tapjs#123]
I'm not 100% sure this is a node-tap bug, very well could be a node core bug. That said, I have an asynchronously defined test, using plan to be able to do that, that hangs because the test functions are never called. Adding logging in various places it comes to: https://github.com/isaacs/node-tap/blob/master/lib/tap-harness.js#L44 (the `process.nextTick(p)` line) where the next test gets queued for execution via `nextTick` but doesn't fire until another timer or callback happens.

I do not have a trivial example broken out, I spent more time debugging the suite as is than breaking it down to prove the bug in node-tap or node core.

https://github.com/newrelic/node-newrelic/blob/master/test/integration/instrumentation/pg-native.tap.js is the file that fails, specifically it is the tests that are defined in https://github.com/newrelic/node-newrelic/blob/master/test/integration/instrumentation/pg.common.js#L124 that only start executing when the timeout happens.

Interestingly enough, if I add a `setImmediate(function() {})` or `setTimeout(function () {}, 0)`next to `nextTick` mentioned above, it is enough to get the `nextTick` queue to be drained an the tests to start executing like they should.

**Comment by rmg** [comment]
I've never gotten nested tests to work unless the parent test _only_ had child tests (no `t.plan`, `t.ok`, etc., only `t.test`), so I just assumed I was doing it wrong. It looks like there's a test for this: https://github.com/isaacs/node-tap/blob/master/test/nested-async.js and it is definitely passing.

@wraithan Since you're basically doing something I specifically avoid, it was easy for me to come up with a reproduction of what I think your tests are doing.

The following hangs, though I would expect it to fail early since the plan is exceeded:

``` js
var test = require('../').test;

test('outer', function(t) {
  t.plan(3);
  t.test('inner 1', function(tt) {
    tt.ok(true, '1-1');
  });
  t.test('inner 2', function(tt) {
    tt.ok(true, '2-1');
  });
  t.test('inner 3', function(tt) {
    tt.ok(true, '3-1');
  });
});
```

**Comment by wraithan** [comment]
Interesting, if that hangs then I can definitely see that being the same bug. I'm avoiding work stuff until Monday (need to detox a bit) but on Monday I'll play with this to see if it is the same bug for sure. Thanks for looking into it @rmg!

**Comment by wraithan** [comment]
Oh, also the test plan isn't exceeded, because the test plan only counts asserts and tests created directly from it's own `t`.

**Comment by isaacs** [comment]
@rmg It's hanging because the child blocks aren't planned or ended.

**Comment by rmg** [comment]
@isaacs yep, and that makes sense. It also happens to be something that is happening in @wraithan's tests ;-)

This may ultimately be a "documentation bug" if @wraithan had the same expectation as I did at first that the sub tests would somehow inherit some aspect of the parent's test plan.

**Comment by wraithan** [comment]
I'm not so sure that it is because they aren't planned, I see the
`nextTIck` get called when I instrument it. It just isn't firing until some
other timer goes off.

**Comment by jakelau** [comment]
It sounds like this is the same issue. This hangs, but commenting out the `createClient` line works fine.

```js
var test = require("tap").test;
var redis = require("redis");

var client = redis.createClient();

test("foo", function(t) {
  t.end();
});
```

**Comment by isaacs** [comment]
Cannot reproduce on 1.x
