### ISSUE TITLE
tap needs to be invoked differently on windows and linux

### ISSUE THREAD

**Issue by dotnetCarpenter** [tapjs/tapjs#128]
`tap` needs to be invoked differently on windows and linux, which means that `npm test` fails to be cross-platform.
Example: in [jfhbrook/node-ecstatic](https://github.com/jfhbrook/node-ecstatic/) I can write `"test": "tap test/"` and it works on windows but not [linux](https://travis-ci.org/jfhbrook/node-ecstatic/jobs/62287525) and the other way. I can write `"tap test/*.js"` and it works on [linux](https://travis-ci.org/jfhbrook/node-ecstatic/jobs/62252400) but not in windows.

I even think it is a regression. I'm not 100% sure but I believe `tap test/*.js` used to work in Windows back in v0.4

**Comment by dotnetCarpenter** [comment]
wow, didn't see that you pushed a new version. Just updated and it works fine in windows (even took care of the weird spawn error after the tests, I was seeing). Now I'm just waiting for [confirmation on travis](https://travis-ci.org/jfhbrook/node-ecstatic/builds/62292176) before closing this one.

**Comment by rmg** [comment]
#126 & #127 :-)

**Comment by dotnetCarpenter** [comment]
@rmg thanks! I spend an hour trying to test this on travis. I've stared the yellow dot to death, finally gave up an made an issue report and then I see #126! Perfect dramatic curve ;)

**Comment by isaacs** [comment]
I think `tap test/` should absolutely work on unix as well as Windows.  Are there tests in the `test/` folder?  What happens?

**Comment by dotnetCarpenter** [comment]
tap test/*.js works. I just updated tap from 0.4 to 1.0 and moved all .js files, that was not tests, into a sub directory. As you can see on [travis](https://travis-ci.org/jfhbrook/node-ecstatic/jobs/62292181), it is working. I got another issue with a missing file, that works on windows but not linux. I don't think it has anything to do with tap, though.

**Comment by dotnetCarpenter** [comment]
and yes, `tap test/` does also work on windows in v1.0.3. I was using v1.0.2 before

**Comment by dotnetCarpenter** [comment]
hmm.. I just test on linux via [cloud9](c9.io) and `tap test/` did **not** work, whereas tap test/*.js did.

**Comment by dotnetCarpenter** [comment]
@isaacs here is the failed test case: https://travis-ci.org/jfhbrook/node-ecstatic/jobs/62297377
Hmm hang on. This might be something else. I think that `tap test/*.js` runs the test independently, so I can see  the progress. While `tap test/` runs everything before reporting back. So it might be failing tests that screw up `tap`.

**Comment by isaacs** [comment]
Running `tap test/` will recursively go through everything in the `test/` folder running it with tap.

But in jfhbrook/node-ecstatic, you've got a TON of stuff in test/public/ that is not tests.  It's broken symlinks and text files and other junk. So, yeah, running tap on that stuff breaks.

I suppose it could be made to skip over things at are not either js or executables, patch welcome.

**Comment by isaacs** [comment]
Even then, this will always fail:

```
$ tap test/public/d.js
C!!!
total ................................................. 0/2


  0 passing (121.359ms)
  1 pending
  1 failing
```

So, the requirement would be for `tap test/ --no-recurse` or something.

**Comment by dotnetCarpenter** [comment]
ahh ok. I only meant to run the _test_ in the test/ directory. In v0.4, it seemingly worked. I just realized that it was giving false test numbers. Everything should be fixed in [my latest commit](https://github.com/jfhbrook/node-ecstatic/pull/143), though.

The d.js broken symlink put me off for a while. Possibly a windows side-effect - not sure. But it was easily detectable and fixable once I got it on the cloud9 box.

**Comment by isaacs** [comment]
@dotnetCarpenter Right, but how would tap know what is a test and what isn't?  It just arbitrarily crawls all the dirs it encounters.

In this case `tap test/*.js` is absolutely the right thing to be doing.  We just broke that on Windows, but it's fixed now.

**Comment by dotnetCarpenter** [comment]
well, tap could look for tap.test. I'm not sure if it's worth the trouble to implement. [Ractive](http://www.ractivejs.org/) does something like that with [esprima](http://esprima.org/) but also uses regex for that in the [component loader](https://github.com/ractivejs/rcu/issues/4).

But I really think it's a documentation issue not a missing feature.

**Comment by isaacs** [comment]
Yeah, I'm not gonna have the tap runner read tests and try to figure out if they're loading or calling tap.  That's both too magical _and_ a ton of work.

Besides, you might have something that outputs TAP format, but isn't actually loading `reuquire('tap')` to do it.  And you don't need to call `tap.test()` any more, you can just do `var t = require('tap'); t.pass('ok')` and it'll work.

Doc patch welcome.
