### ISSUE TITLE
behaviour changes in tap@1

### ISSUE THREAD

**Issue by rmg** [tapjs/tapjs#129]
Some breaking changes are expected, but now that I've converted (or attempted to convert) a handful of small and large modules, here are some notes.
#### sensitivity to debug messages

The new architecture combines stdout from tests with TAP output, so `console.log()` in tests can easily corrupt the test results. This is particularly troublesome when upgrading tests that make liberal use of the previous behaviour of auto-commenting stdout from tests and is the main thing blocking me from upgrading some modules.
#### only first child test is run if tests aren't ended

Another change is that nested tests that contain only nested tests are no longer ended when the grandchildren have all ended. Ultimately this is probably more of a correctness improvement, so it might make sense to just add some sort of detection so people's previously passing tests don't just fail with `not ok missing plan`.

The following passes under tap@0.7.1:

``` js
var tap = require('tap')

var grandChildren = []

tap.test('parent', function(t) {
  t.test('child 1', function(t) {
    t.test('grandchild 1', function(t) {
      grandChildren.push('grandchild 1')
      t.ok(1, 'child 1')
      t.end()
    })
  })
  t.test('child 2', function(t) {
    t.test('grandchild 2', function(t) {
      grandChildren.push('grandchild 2')
      t.ok(1, 'child 2')
      t.end()
    })
  })
})

tap.test('grandchildren', function(t) {
  t.equal(grandChildren[0], 'grandchild 1', 'grandchild 1 is run')
  t.equal(grandChildren[1], 'grandchild 2', 'grandchild 2 is run')
  t.end()
})
```

The above can be made to pass under tap@1 by adding a `t.end()` at the end of the `child 1` test.

@isaacs I didn't want to bother opening a PR to add the above failing test because I haven't looked yet at if/how it might be fixed.

**Comment by isaacs** [comment]
> sensitivity to debug messages

Yeah, this is actually one of the things that has been a common complaint from mocha & lab users; they can't use `console.log` for arbitrary debugging, because TAP turns it into a comment, which is then ignored by the reporter.

Perhaps it'd be better to send `'extra'` events to stderr rather than passing up the chain?

> only first child test is run if tests aren't ended

I'm surprised that ever worked!  It definitely shouldn't!

I think in this case, we should detect that the process is exiting before all the tests have completed, emit a failure on the top-level, and `tap.endAll()`.  There's already a `process.on('exit')` handler in `lib/root.js` to auto-end the top level test, so it should be easy enough to just make it a bit smarter.  That should come along with a `test/test/*.js` test to solidify the behavior.

**Comment by rmg** [comment]
The unfortunate thing about my example is if you remove the `grandchildren` test at the end, the test overall passes, it just doesn't execute the `grandchild 2` test.

My guess is tap previously queued up the tests synchronously before executing the queue lazily but now the queueing is also done lazily?

**Comment by isaacs** [comment]
Here's what I'm thinking that it should do:

``` javascript
// test/test/unfinished.js
var tap = require('../..')

tap.test('parent', function(t) {
  t.test('child 1', function(t) {
    t.test('grandchild 1', function(t) {
      t.pass('1')
      t.end()
    })
  })
  t.test('child 2', function(t) {
    t.test('grandchild 2', function(t) {
      t.pass('2')
      t.end()
    })
  })
})
```

Output:

```
TAP version 13
    # Subtest: parent
        # Subtest: child 1
            # Subtest: grandchild 1
            ok 1 - 1
            1..1
        ok 1 - grandchild 1 # time=0.873ms

        not ok 2 - test left unfinished: no end(), no plan()
          ---
          at:
            file: test/test/unfinished.js
            line: 3
            column: 5
          source: |
            tap.test('parent', function(t) {
          ...
        1..2
        # failed 1 of 2 tests
    not ok 1 - child 1 # time=8.673ms
      ---
      at:
        file: test/test/unfinished.js
        line: 4
        column: 5
      results:
        plan:
          start: 1
          end: 2
        count: 2
        pass: 1
        ok: false
        fail: 1
        time: 8.673
      source: |
        t.test('child 1', function(t) {
      ...

    not ok 2 - test left unfinished: no end(), no plan()
    1..2
    # failed 2 of 2 tests
not ok 1 - parent # time=14.188ms
  ---
  at:
    file: test/test/unfinished.js
    line: 3
    column: 5
  results:
    plan:
      start: 1
      end: 2
    count: 2
    pass: 0
    ok: false
    fail: 2
    time: 14.188
  source: |
    tap.test('parent', function(t) {
  ...

1..1
# failed 1 of 1 tests
# time=19.936ms
```

**Comment by isaacs** [comment]
@rmg Welp, I meant to push that to a branch, but I accidentally the master.  So... if you wanna review 22680b0e15428fff218e12615d4f10d4a28b1546 that'd be swell.  If it's problematic, I'll revert it, but if it seems like it addresses the issue to your liking, I'll push a patch release.

**Comment by rmg** [comment]
@isaacs left a comment. Looks like it is at least better than nothing, but it look like it wouldn't fully recurse.. not sure whether that's good or bad.
