### ISSUE TITLE
tap test/test.js cwd behaviour change

### ISSUE THREAD

**Issue by rmg** [tapjs/tapjs#131]
This is a big one I forgot to mention in #129.

`tap` no longer spawns its tests with cwd set to the directory the script is in.

Previsously, when running `tap test/foo.js`, `foo.js` would be run with cwd = `test/`. This has the biggest impact on non-node tests, like shell scripts that want to `source ./helpers.sh`, but it would also affect js tests using the `tap` module if they make references to relative paths assuming `process.cwd()` is equivalent to `__dirname`.

The behaviour was always a little odd, so maybe it's best to restore it in a patch release and then revert it in a 2.0 release that makes the change more explicitly?

**Comment by isaacs** [comment]
This was changed on purpose.  You're right, it was always hella odd that it changed cwd like that.

I'd be happy with a doc update to explain all the changes that happened in 1.x, including this.  However, I'm not willing to ever change it back.  Going from 0.x to 1.x is a major version bump already; we don't need a 2.x for this.

**Comment by isaacs** [comment]
Just to be clear: the reason why this vexed me so much is that it meant that doing `node test/foo.js` is _fundamentally different_ from what gets run when you do `tap test/foo.js`, and that sucks.  Running with the tap runner should parse output, pretty it up, ensure a non-zero exit code if failures are reported, etc.  But changing the environment in which the code runs was always a design bug.

**Comment by michaelnisi** [comment]
This breaks a lot of my tests, but I agree, it is much cleaner to run in a consistent environment. No magic tricks and behind the back trickery. 1.x is the bump—having to resolve paths in the tests is no big deal—it makes the code clearer and more portable (as unit).

**Comment by isaacs** [comment]
I've already had to add a lot of `process.chdir(__dirname)` to some old tests, just so that I can do `node test/foo.js` and see the full output.
