### ISSUE TITLE
Support for promises in mocha-like tests

### ISSUE THREAD

**Issue by bajtos** [tapjs/tapjs#137]
The Mocha framework detects when a test returns a promise, which allows developers to write asynchronous tests without repeating `if (err) return done(err)` all over the place (see https://github.com/mochajs/mocha/pull/329):

``` js
it('reads file via promise', function() {
  return fs.readFileAsync('foo.txt')
    .then(function(text) {
      expect(text).to.contain('foo');
    });
  });
});
// the test runner waits until the returned promise is resolved
```

I am proposing to implement this support in node-tap too, I am happy to contribute the implementation myself.

Thoughts?

**Comment by isaacs** [comment]
Seems fine to me, as long as tap itself doesn't have to start using promises all over the place.  How does mocha detect?  Just check for a `.then` method on the returned object?

**Comment by bajtos** [comment]
> As long as tap itself doesn't have to start using promises all over the place.

Yes, my intention is to make a small isolated change just to support promise-returning test functions, see below.

> How does mocha detect? Just check for a `.then` method on the returned object?

Yes, exactly like that. See [lib/runnable.js#L265-L279](https://github.com/mochajs/mocha/blob/ebe9ceab96fc1a05d4c89b13c23824b94b01ec43/lib/runnable.js#L265-L279)

``` js
var result = fn.call(ctx);
if (result && typeof result.then === 'function') {
  result
    .then(function() {
      done()
    },
    function(reason) {
      done(reason || new Error('Promise rejected with no or falsy reason'))
    });
}
```

**Comment by bajtos** [comment]
Frankly, I won't have time to contribute this feature as soon as I originally thought. Feel free to close this issue so that it doesn't clutter project's issue list.

**Comment by isaacs** [comment]
I'm happy to leave it open in case someone comes along and wants to do it.  That someone may even be me one day :)

**Comment by cesarandreu** [comment]
+1

I use [is-promise](https://github.com/then/is-promise) to detect promises.

One HUGE benefit of adding support for returned promises is that it lets node-tap work out of the box with async functions. An async function always returns a Promise. Async arrow functions are also a thing. 

Here's an example of a random mocha test that uses babel:

``` js
// ... imports

describe('Request:Users', () => {
  describe('GET /api/users/current', () => {
    it('returns current user', async () => {
      const user = await factories.createUser()
      const headers = buildUserHeaders(user)

      const res = await request
        .get('/api/users/current')
        .set(headers)
        .expect(200)

      expect(res.body).to.eql(JSON.parse(JSON.stringify(user)))
    })

    it('creates a user for you', async () => {
      await request
        .get('/api/users/current')
        .expect(200)
    })
  })
})
```

Oh, and it'd also play nicely with co, if someone doesn't want to use babel to transpile their code:

``` js
const co = require('co')
const assert = require('assert')
const asyncThing = require('./asyncThing')

describe('co test', function () {
  it('does async thing', co.wrap(function * () {
    const result = yield asyncThing()
    assert.equal(result, 'success')
  }))
})
```

**Comment by hybrist** [comment]
Is this still free for grabs in terms of implementing?

**Comment by bajtos** [comment]
> Is this still free for grabs in terms of implementing?

I think it should be still free. The author of the issue (means me) is certainly not working on the implementation.

**Comment by isaacs** [comment]
@jkrems I think @aredridel was interested in taking a look at how to make tap promisey, not necessarily specifically around the mochalike tests (which, tbh, should probably be moved to a separate module or something, because it turns out that Mocha's BDD interface is actually quite huge).

I'm not saying this to discourage you, but to say that there may be some overlap in what you two are doing, so chat about it maybe?

**Comment by aredridel** [comment]
Definitely interested.

**Comment by hybrist** [comment]
Thanks! I just realized that I actually misread the issue and didn't realize this was about the mocha-like interface in particular. Oops. What I had in mind was just a small addition to the basic interface to handle `t.end` and failing tests. Example: https://github.com/isaacs/node-tap/compare/master...jkrems:jk-promise-return?expand=1#diff-dd2e881af3311f834199c7b515cff0c7R398. Sorry for storming ahead with a first pass at implementing it, definitely happy to discuss better or more widely useful approaches.

I modeled it after [`blue-tape`](https://github.com/spion/blue-tape/blob/master/blue-tape.js). Should I create a separate issue and/or PR to discuss this since it's technically not matching this issue's description?

**Comment by isaacs** [comment]
@jkrems Neat.  It seems like that wouldn't support stuff like `t.test(...).then(...).then(...)`, would it?  (And, is that a thing to actually want to do?  Should those promise-returning blocks be additional tests, or what?)

**Comment by hybrist** [comment]
That's correct. Right now this could not be used to control the order of tests but from my current understanding that's handled by `tap` out-of-the-box (ensuring tests run in sequence).

For me the main use case of this feature would be async functions ([example using blue-tape and babel](https://github.com/buggerjs/bugger-v8-client/blob/0e3575915612cd39ee1346886c264dbad5790990/test/commands/scripts.js#L10-L20)). But maybe I'm missing a use case where `t.test(...).then` would be important.

**Comment by isaacs** [comment]
How about if `t.test` returned `this`, so you could do this?

``` javascript
t.test('first', function (t) {
  return somePromise().then(function () {
    return someOtherPromise()
  }).then(function () {
    return yetAnotherPromise()
  })
}).test('second', function (t) {
  ...
}).end()
```

**Comment by isaacs** [comment]
Ugh, actually having `t.test` return `t` is weird, and I wish I hadn't suggested it.  Nevermind.
