### ISSUE TITLE
Subtests don't Run

### ISSUE THREAD

**Issue by ashb** [tapjs/tapjs#14]
Best illustrated by an example:

```
var test = require("tap").test;
test("parent", function (t) {
  t.plan(1)
  t.test("subtest", function (t) {
    t.ok()
    t.end()
  })
  t.end()
})
```

The output of running this via `node foo.t.js` is:

```
# parent

1..0
# tests 0
```

   # ok

(This is basically a cut down version of the example from the README.md)

**Comment by jdeal** [comment]
same here, from an npm install today

**Comment by stevemolitor** [comment]
I get a different error:  

```
tap ta.test.js
not ok ta.test.js ................... 0/1
   Command: "node" "ta.test.js"
   not ok 1 test count != plan
```

But it's the same basic problem:  it's not running the subtest, so the actual assertion count count doesn't equal the plan.

I can get it to work by removing the plan line:

``` javascript
var test = require("tap").test;
test("parent", function (t) {
  t.test("subtest", function (t) {
    t.ok(1)
    t.end()
  })
  t.end()
})
```

```
tap ta.test.js
ok ta.test.js ....................... 1/1
total ............................... 2/2

ok
```

It seems like t.plan() doesn't always work right with subtests.

**Comment by isaacs** [comment]
Yes, there are gremlins there.  Nested tests are wonky;.
