### ISSUE TITLE
Test counts next to execution time

### ISSUE THREAD

**Issue by tjconcept** [tapjs/tapjs#145]
It would be nice with a count of tests.

**Comment by rmg** [comment]
@tjconcept the test count _is_ next to the execution time.. What are you seeing?

**Comment by tjconcept** [comment]
I'm only seeing counts for the current level of tests. With nested tests I would have to manually sum up each subtest's count.

**Comment by isaacs** [comment]
@tjconcept Can you give an example of what you're seeing and what you'd like it to show instead?

**Comment by tjconcept** [comment]
Of course. I'm seeing this:

``` js
TAP version 13
    # Subtest: show user
        # Subtest: response on fetching a user
        1..2
        ok 1 - status code
        ok 2 - expected complete result
    ok 1 - response on fetching a user # time=1323.855ms

        # Subtest: without a jwt
        1..2
        ok 1 - status code
        ok 2 - status message
    ok 2 - without a jwt # time=342.176ms

        # Subtest: unknown user id
        1..2
        ok 1 - status code
        ok 2 - status message
    ok 3 - unknown user id # time=410.334ms

        # Subtest: wrong jwt
        1..2
        ok 1 - status code
        ok 2 - status message
    ok 4 - wrong jwt # time=399.816ms

    1..4
ok 1 - show user # time=2481.94ms
```

This is 8 tests, or if you count in the blocks it's 12. I would just like any of those numbers printed somewhere. I guess it would be practical for each block to have a count and then bubble up and accumulate.

Something like:

``` js
TAP version 13
    # Subtest: show user
        # Subtest: response on fetching a user
        1..2
        ok 1 - status code
        ok 2 - expected complete result
    ok 1 - response on fetching a user # time=1323.855ms count=2

        # Subtest: without a jwt
        1..2
        ok 1 - status code
        ok 2 - status message
    ok 2 - without a jwt # time=342.176ms count=2

        # Subtest: unknown user id
        1..2
        ok 1 - status code
        ok 2 - status message
    ok 3 - unknown user id # time=410.334ms count=2

        # Subtest: wrong jwt
        1..2
        ok 1 - status code
        ok 2 - status message
    ok 4 - wrong jwt # time=399.816ms count=2

    1..4
ok 1 - show user # time=2481.94ms count=8
```

**Comment by isaacs** [comment]
Using the 'classic' default reporter, I see this output, which seems like it's somewhat close to what you want:

```
show user ............................................. 8/8
total ................................................. 8/8

  8 passing (11ms)

  ok
```

But I can see the value in putting it in the TAP itself.  I just worry that it starts to become very difficult to specify, since we're adding Yet Another Arbitrary Data Thingie in the protocol.

**Comment by tjconcept** [comment]
Ah, right. Using the default reporter is a fine work around for me. I have just grown to like the raw TAP output :-)

**Comment by isaacs** [comment]
Strictly speaking, this is a discussion for https://github.com/TestAnything/Specification (spec) and https://github.com/substack/tap-parser (implementation).

I'm going to leave this issue open until we get the discussion started over there, though, so it's not forgotten.

**Comment by tjconcept** [comment]
:+1:
