### ISSUE TITLE
Diff does not handle objects with custom `hasOwnProperty` property

### ISSUE THREAD

**Issue by bajtos** [tapjs/tapjs#148]
Test code:

``` js
var tap = require('tap');
tap.deepEqual(
  { foo: { hasOwnProperty: true, key: 'value' } },
  { foo: false });
```

TAP output (`node tap-bug.js`)

```
TAP version 13
not ok 1 - should be equivalent
  ---
  found:
    foo:
      hasOwnProperty: true
      key: value
  wanted:
    foo: false
  at:
    file: tap-bug.js
    line: 2
    column: 5
  source: |
    tap.deepEqual(
  stack: |
    Object.<anonymous> (tap-bug.js:2:5)
    node.js:948:3
  ...
1..1
# failed 1 of 1 tests
# time=18.961ms
```

Pretty output (`tap tap-bug.js`):

```
tap-bug.js ............................................ 0/1
  not ok should be equivalent
    +++ found
    --- wanted
     {
    -  "foo": false
    +  "foo": {}
     }
    at:
      file: tap-bug.js
      line: 2
      column: 5
    source: |
      tap.deepEqual(
    stack: |
      Object.<anonymous> (tap-bug.js:2:5)
      node.js:948:3

total ................................................. 0/1


  0 passing (197.881ms)
  1 failing

```

The diff says the actual object was empty, which makes it rather difficult to find out why the test is failing.

**Comment by bajtos** [comment]
LOL, this is what `jshint` thinks about the code sample:

```
tap-bug.js: line 3, col 26, 'hasOwnProperty' is a really bad name.
```

Note that I don't have `hasOwnProperty` in my code, it's a part of a message exchanged between the debugger front-end and the back-end, the message lists all properties of an inspected object.

**Comment by isaacs** [comment]
This is a bug in the diff creator thingie.  I'll take a look at it soon.

**Comment by isaacs** [comment]
In latest and greatest `tap-mocha-reporter` (fresh install of `tap`)

```
$ tap t.js
t.js .................................................. 0/1
  not ok should be equivalent
    +++ found
    --- wanted
     {
    -  "foo": false
    +  "foo": {
    +    "hasOwnProperty": true
    +    "key": "value"
    +  }
     }
    at:
      file: t.js
      line: 2
      column: 5
    source: |
      tap.deepEqual(
    stack: |
      Object.<anonymous> (t.js:2:5)
      node.js:946:3

total ................................................. 0/1


  0 passing (187.794ms)
  1 failing

```

**Comment by isaacs** [comment]
I didn't get the same results you did, though.

Maybe you meant `hasOwnProperty: function () { return true }`?  That would have resulted in an empty object.  Now it calls off the Object.prototype, so it isn't as easily confused.

**Comment by bajtos** [comment]
Thank you for fixing the issue quickly :bow: 

> I didn't get the same results you did, though.

That's weird, perhaps I was running an older tap version (e.g. pre-1.3)?

Anyways, let's not worry about that right now. I'll leave a comment in case that I run into this issue again with a different test code.
