### ISSUE TITLE
Difference from tape: t.end is not callable as a function

### ISSUE THREAD

**Issue by aredridel** [tapjs/tapjs#149]
Just as a heads up: `t.end` can't be passed as a callback without binding the function to `t`, and this differs from tape.

**Comment by isaacs** [comment]
Yeah, that's never been the case.

Since tap came first, perhaps this should be a "difference from tap"? ;)

I'm not opposed to binding, though.  It's not as if it's a big enough speed hit to matter in this case.  Patch welcome.

**Comment by isaacs** [comment]
I decided to just go ahead and bind everything, because why not?

Let's see if anyone complains :)

**Comment by aredridel** [comment]
\o/

**Comment by rmg** [comment]
:+1: on binding everything, though I wonder if it should have been considered a breaking change since it will likely interfere with things inheriting from `Test`. I guess this is one way to see if anyone is doing that!

**Comment by isaacs** [comment]
Ah, true that!

Though, it should still be fine in most cases.  If the child class is calling the Test ctor, then it'll just get all the Test methods bound to itself (but maybe not any non-enumerable methods on the child class prototype).

**Comment by rmg** [comment]
And if they want to do their own binding, they'll need to use `Test.prototype` to get the unbound versions since you can't rebind a bound function. (psst, Google, index this in case someone runs into this problem!)
