### ISSUE TITLE
Install time

### ISSUE THREAD

**Issue by jsumners** [tapjs/tapjs#15]
I think you may get some complaints about the new install time. On my system, where I have already installed both 16 and 18, and have not cleared out npm's cache, it is taking _much_ longer to install 18 than 16.

https://asciinema.org/a/cAsVZOnFYFm3DJi1mUb3qx22H

+ `npm i tap@16  2.56s user 1.06s system 56% cpu 6.417 total`
+ `npm i tap@pre  44.40s user 9.37s system 141% cpu 37.901 total`

I don't know what can be done, but I do think there should be an investigation into how it can be sped up.

**Comment by isaacs** [comment]
The main thing is that it's pulling ts-node from git while waiting for some fixes to land. That'll be fixed once ts-node gets a new release. But yes, it's quite bad. If it hasn't been updated by the time this is ready for prod release, I'll either vendor or fork it.
