### ISSUE TITLE
its not clear when tests must be ended

### ISSUE THREAD

**Issue by sam-github** [tapjs/tapjs#154]
This test passes, as I thought it should:

```
var tap = require('tap');                                                        

tap.test('super', function(t) {                                                  
  t.test(function(t) {                                                           
    t.end()                                                                      
  });                                                                            

  t.test(function(t) {                                                           
    t.end()                                                                      
  });                                                                            
});                  
```

However,  I am beginning to suspect that what is actually happening is that this test is malformed, and is exiting by accident on an empty event loop, it just happens to exit after both tests have run, so it _appears_ to be OK.

In particular, if the test has a minor modification to workaround #152, then tap considers the test malformed, in that "super" never ends, so it times out:

```
tap.test('super', {timeout: 1000}, function(t) {
// ... as before
```

tap requires an explicit end for subtests, at least it does when a timeout is used, this passes:

```
var tap = require('tap');

tap.test('super', {timeout: 1000}, function(t) {
  t.test(function(t) {
    t.end()
  });

  t.test(function(t) {
    t.end()
  });

  t.end(); // NOTE VERY WELL
});
```

Strangely, IIRC, a `t.end()` in that position would actually cause problems in either tap 0.x, or early tap 1.x, since the super test would be ending before its children.

I think that the versions of the test _without a trailing `t.end()`_ should either both pass (with or without a timeout), or both **_not pass**_. In the non-timeout case, the "not pass" would be that the test script will simply never exit because it is not ended, as happens with leaked node handles, so the runner will kill it.

Personally, I would much prefer that the child test queue be "auto ended" when the parent test callback returns so that the tests both pass. I guess that would disallow async creation of tests, but I think that's a corner use-case that should be explicitly enabled if its desired, by an test option, or test method.

If it goes the other way, I'll need to update many tests, but that's OK. At the moment, I don't really know if those tests are running, anyway (due to #152).

**Comment by isaacs** [comment]
As of the latest release, tests must always be ended, either by calling `t.end()` or by fulfilling a planned number of tests.

**Comment by rmg** [comment]
Already updated a side project that this affected, We'll find out on Monday what the impact is on StrongLoop modules :+1:
