### ISSUE TITLE
t.error fails on circular references

### ISSUE THREAD

**Issue by tmcw** [tapjs/tapjs#156]
Test case:

``` js
var test = require('tap').test;
var cycle = { };

cycle.foo = cycle;

test('foo', function(t) {
  t.ifError(cycle, 'foo');
  t.end();
});
```

This fails with a `RangeError: Maximum call stack size exceeded`.

A less-obviously-made-to-fail case where this happens is if the argument to `ifError` is a response object that contains circular references.

---

The culprit is the [cleanYamlObj](https://github.com/isaacs/node-tap/blob/master/lib/test.js#L876-912) method that recurses down the object.

**Comment by isaacs** [comment]
Good catch, thanks!  That function needs to keep track of objects it's already seen.  Patch welcome.
