### ISSUE TITLE
Upgrade to nyc@3?

### ISSUE THREAD

**Issue by rmg** [tapjs/tapjs#158]
Does the change in nyc@3.0.0 break anything in tap?

In my limited local testing, the only "breaking change" from a tap perspective is that a text report is generated _in addition_ to whatever format is specified with `--coverage-report`. For my uses that's actually convenient, but I could see how it might annoy others.

@bcoe @isaacs thoughts?

**Comment by rmg** [comment]
This would also likely be required for bcoe/nyc#38 to make a difference for tap users.

**Comment by bcoe** [comment]
@rmg @isaacs pulled in a patch for windows users:

https://github.com/bcoe/nyc/pull/38

The flag `--silent` can be set on `nyc` to prevent the double output perhaps?

**Comment by isaacs** [comment]
I'm totally fine with pulling it in. I just haven't gotten a chance to take a look yet.

@rmg @bcoe if you two give it the :+1: then go ahead and land it.  Lmk if you want a release to happen.

**Comment by bcoe** [comment]
@isaacs I'll have to dig in a bit this weekend and figure out how to stop the double output.
