### ISSUE TITLE
highlight colors don't work with terminal forground/background settings (linux, xfce4-terminal)

### ISSUE THREAD

**Issue by sam-github** [tapjs/tapjs#159]
![colors-wrong](https://cloud.githubusercontent.com/assets/17607/9017621/96e36336-378c-11e5-9b27-18beb458a3ce.png)

This doesn't bother me much because I pretty much always run tap as `TAP_BAIL=1 my-file-watcher node  test/test-something.js`, so if I'm running `npm test` its because I'm trying to find a test that fails, or it will pass.

In the process of investigating, I found that if I highlight the colored area with the mouse by selecting in the terminal, the colors reverse, and I can see the values:

![inverted](https://cloud.githubusercontent.com/assets/17607/9017771/791886b4-378d-11e5-836d-f31730940510.png)

In the above I've selected an area from before the not ok, to after the 4003. So selecting is actually a good workaround :-).

Fwiw, I'm on Ubuntu 15.04, using xfce4-terminal, and I used every terminal preset it has, and they all change the colors of the various bits on the screen, but none of them allow the expected/found text to be read through the green/red.

**Comment by sam-github** [comment]
The highlight workaround only works sometimes :-(

**Comment by isaacs** [comment]
Is the terminal not 256 colors?  It's weird that you're getting those fallbacks, they aren't even close to what it's trying to print.

What does `echo $TERM` say?

**Comment by sam-github** [comment]
`screen-256color`, I'm running inside tmux.

**Comment by isaacs** [comment]
In my limited testing, it looks like most terminals that don't start with `xterm` can't handle 256 colors pretty much at all.

So, what would you _like_ it to look like?

**Comment by sam-github** [comment]
Honestly, don't care as long as I can read the text!

I looked harder, it turns out I need to use `tmux -2` to get it to support 256 colors, so now I get lime green and pink, and can read the text.

**Comment by isaacs** [comment]
Ugh.  Ok.  I can't figure out how to detect if the tmux session can handle 256 colors by looking at the env.  Any idea?  It shows `TERM=screen` no matter how I start tmux.

**Comment by sam-github** [comment]
This http://unix.stackexchange.com/a/118903 makes me think that color support detection is an unsolveable problem.

I'm setting "set -g default-terminal "screen-256color" in my tmux.conf (which should convince tap there are 256 colors, I think), and calling `tmux -2`, which should convince tmux my terminal supports 256 colors, and it works fine.

Fwiw, when starting tmux, TERM=xterm, and my terminal is xfce4-terminal 0.6.3.

I don't think there is anything else for you to do, but you know more about this than me, Issacs, thanks for spending some time on it.
