### ISSUE TITLE
CLI argument aliases

### ISSUE THREAD

**Issue by jsumners** [tapjs/tapjs#16]
It seems some aliases from prior versions have not made it over to the upcoming 18. For example, `--cov` used to be an alias for `--coverage` and is no longer recognized -- https://github.com/fastify/fastify/actions/runs/5917350207/job/16045634042#step:5:26

**Comment by isaacs** [comment]
Yeah, those aren't happening, sorry. Way too much overhead for a very niche feature, and since the config stuff changed so much anyway, it seems like it's not really worth it.

Thanks for the note, though, it's a good reminder for the changelog.
