### ISSUE TITLE
Exit process on root test bailout

### ISSUE THREAD

**Issue by isaacs** [tapjs/tapjs#167]
It seems like it might be reasonable to do this pretty much always:

``` javascript
tap.on('bailout', function () {
  process.exit(1)
})
```

(Since bailouts bubble up synchronously, this would also mean that a bailout anywhere results in immediate process termination.)

The hazard could be that any post-test code wouldn't be executed if the tests bail on the first tick, but as seen in #166, that may be what users would expect anyway.

Opening this issue to discuss ramifications.  If no one objects, then the patch is pretty straightforward, and a new `test/test/exit-on-bail.js` or something could be added that does nothing but bail out on the first tick, and verify that a `console.log` below the test isn't executed.

**Comment by rmg** [comment]
This seems like it would make certain types of cleanup significantly harder (thinking of https://mktmp.io style services), but I guess as long as the person writing the tests is the one deciding whether to bailout or not it should be OK.
