### ISSUE TITLE
Programmatically set the Reporter

### ISSUE THREAD

**Issue by tooolbox** [tapjs/tapjs#168]
How does one programmatically set the reporter, to `spec` for example??  The docs assume that you're running from the command-line with flags, and I can't determine from examining the source how to do this.

**Comment by rmg** [comment]
@tooolbox the reporters are done outside of this module.

Basically, this module _only_ spits out TAP and feeds it to https://github.com/isaacs/tap-mocha-reporter which implements the different reporters.

**Comment by tooolbox** [comment]
@rmg Aha!  Thought I was missing something, thanks.

I managed to get this working programmatically with the following:

``` js
var tap = require('tap');
var TMR = require('tap-mocha-reporter');

tap.mochaGlobals();
tap._bail = true;
tap.on('bailout', function(){
    process.exit(1);
});

var tmr = new TMR('spec');
tap.unpipe(process.stdout);
tap.pipe(tmr);

// ...
```

Pretty straightforward now that I have the pieces together.
So now Tap is piping into the reporter and I'm getting output:

```
# node test_tap.js
the file when we start
  ✓ should have content
Adding Lara...
the file when we end
  ✓ should now have Lara's name
Adding Joe...
the file when we end
  1) should now have Bob's name
```

Okay, so that's great.  Having used the `spec` reporter with Mocha, it seems to be missing the big report with the diffs at the end.  Any thoughts?  I tried to trace through the source of TMR to see if I was missing something, but no dice.

(If this is a TMR question at this point, I can make an issue over there.)

**Comment by tooolbox** [comment]
It's fine, my original question was answered, so thank you.
