### ISSUE TITLE
pnpm fails trying to install `@tapjs/test`

### ISSUE THREAD

**Issue by jsumners** [tapjs/tapjs#17]
Given the `package.json`:

```json
{
  "devDependencies": {
    "tap": "^18.0.0-18"
  }
}
```

Running `pnpm i` results in:

```
ERR_PNPM_LINKED_PKG_DIR_NOT_FOUND  Could not install from "/path/to/project/test-built" as it does not exist.
```

Which looks to be referencing https://github.com/tapjs/tapjs/tree/main/src/test/test-built

```sh
$ pnpm --version
7.33.6
```

cc: @zkochan

**Comment by isaacs** [comment]
This looks pretty clearly like it's a bug in pnpm's handling of `file:` dependencies. Link deps should be relative to the dependent, not the cwd.

But, since we require node 16 at least, I think I can probably work around it with package-local import paths, or failing that, just relative paths. Naming it as an actual dependency is a bit of a holdover from a previous approach that ended up not working for other reasons anyway.

**Comment by isaacs** [comment]
Ok, this should work now with the latest release, assuming that pnpm doesn't do something to break the package local imports (I don't think it does).

**Comment by jsumners** [comment]
That worked, but now we are hitting https://github.com/tapjs/tapjs/issues/15#issuecomment-1685372086

```
❯ pnpm i
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/jsumners/Library/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
../../../../Library/pnpm/store/v3/tmp/_tmp_68303_2487a8e7eac81208cf840b14d0b0edd8 [ts-node@10.9.1]: Running yarn-install script...
Packages: +687
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 ERR_PNPM_PREPARE_PACKAGE  Failed to prepare git-hosted package fetched from "https://codeload.github.com/TypeStrong/ts-node/tar.gz/8f6f4e5": ts-node@10.9.1 yarn-install: `yarn install`
spawn ENOENT
Progress: resolved 686, reused 333, downloaded 350, added 0
```

**Comment by zkochan** [comment]
Some git-hosted dependencies should be built and their dependencies are installed with the package manager that is used in the repository. `TypeStrong/ts-node` uses Yarn, so you need to have yarn installed if you want to install it from github directly, not from the registry.

**Comment by isaacs** [comment]
Once ts-node has the fixes I need on a published version, this will not be an issue. In the meantime, yeah, I guess you just need all the package managers. Idk why it's using yarn, though, it installs fine with npm.

**Comment by jsumners** [comment]
In my opinion, this is a blocker. I am sure Fastify isn't the only project verifying installs with pnpm.

**Comment by isaacs** [comment]
Installing ts-node from GitHub is a blocker anyway, just because it's hella slow. But I can vendor it if needed.
