### ISSUE TITLE
Issue when using promises

### ISSUE THREAD

**Issue by louisameline** [tapjs/tapjs#171]
Hello, I'm seeing a weird behavior when using promises.

This dummy example works as expected : 

```
tap.test('test', function(t){

    $.Deferred().resolve()
        .then(function(){
            var def = $.Deferred();
            setTimeout(def.resolve, 1000);
            return def.promise();
        })
        .then(function(){
            t.ok(true);
        })
        .always(function(){
            t.end();
        });
});
```

while my real-life example fails :

```
tap.test('kvstore', function(t){

    $.Deferred().resolve()
        .then(function(){
            console.log('A');
            return KVStore.connect();
        })
        .then(function(){
            console.log('B');
            t.ok(true);
        })
        .always(function(){
            console.log('C');
            t.end();
        });
});
```

This is the output : 

```
A
B
C
test/lib/KVStore.test.js .............................. 1/3 30s
  not ok timeout
  not ok missing plan
    results:
      ok: false
      count: 2
      pass: 1
      fail: 1
      failures:
        - ok: false
          id: 2
          name: timeout
          parent: ''

total ................................................. 1/3


  1 passing (30s)
  2 failing

```

Note: my KVStore.connect currently returns a promise on the connection to a postgres database. Using `t.plan(1)` does not work either.

There are no other tests scheduled before or after this one. Using Node 0.12 and Tap 1.4.1. Thanks

**Comment by rmg** [comment]
What does `KVStore.connect()` do? If it opens a connection, that will keep the event loop alive. Then, even if your tests complete, the process won't exit and will timeout instead.

**Comment by louisameline** [comment]
Oh, I wouldn't have guessed that. Thank you !

**Comment by rmg** [comment]
@isaacs is there a way to list active handles in the timeout failure message that doesn't rely on the undocumented methods in core? Might be useful.. I know I often end up adding it in as debug output when trying to figure out why a process isn't exiting when I think it should..

**Comment by isaacs** [comment]
Since the timeout happens at the parent process, and the handles are in the child process, no, it would be impossible.

One option might be to listen on `SIGTERM` and emit a failure in those cases?  It still won't help with child procs that aren't running node-tap, but oh well.

**Comment by rmg** [comment]
Ah, right.
