### ISSUE TITLE
Incorrect plan could can give false positives

### ISSUE THREAD

**Issue by konobi** [tapjs/tapjs#178]
So I have a test script where I declared 15 tests within a block. I ran this and it all passed... I added another 2 tests, but didn't update the plan count. In this scenario, the new tests aren't even run and even though they were failing. When I updated the plan count to the correct number, the tests were run as expected.

**Comment by rmg** [comment]
@konobi which version of tap?

**Comment by konobi** [comment]
1.3.1

**Comment by rmg** [comment]
Can you reproduce the problem with a newer version? There have been 9 releases since the version you are suing. v1.3.3 in particular made some changes around plan mismatches and unfinished tests.

**Comment by konobi** [comment]
It's still occuring with 1.3.3.

**Comment by rmg** [comment]
Can you provide an example test suite (preferably reduced) that exhibits this behaviour?

**Comment by konobi** [comment]
Sure... you can run t/options.js from https://github.com/konobi/node-dhcpjs

There should be 2 failing tests. Right now the plan has 15... bump to 17 to see them actually fail.

**Comment by rmg** [comment]
That's an interesting corner case...

So it turns out the logic that is in place to suppress over-reporting failures on plan mismatches gets tripped up if the first _extra_ test fails. In other words, if the 16th assertion in that example was a `t.pass()`, the suite would fail as expected.

This should definitely be fixed.

**Comment by rmg** [comment]
The problem spot is [lib/test.js:856-860](https://github.com/isaacs/node-tap/blob/8051a72eb3875014b37889f75baebd29a79e7c0c/lib/test.js#L856-L860).

@isaacs my preliminary testing suggests that fixing this **might** be another one of those ripple cases that ends up uncovering a bunch of broken tests.

**Comment by isaacs** [comment]
Ah, I see the problem.  The `fail` method is setting `this._ok = false` before the call to `_printResult`, which is where we check to see if we've already failed before printing out the plan exceeded notice.  So if you have a plan full of successes, and then a failure, it won't alert.

Will fix shortly.

**Comment by rmg** [comment]
@isaacs :+1:
