### ISSUE TITLE
Please move required tap-* modules into this repo

### ISSUE THREAD

**Issue by joshwilsdon** [tapjs/tapjs#18]
To use node-tap at all you need several other repos including:

https://github.com/isaacs/tap-runner.git
https://github.com/isaacs/tap-producer.git
https://github.com/isaacs/tap-results.git
https://github.com/isaacs/tap-consumer.git
https://github.com/isaacs/tap-global-harness.git
https://github.com/isaacs/tap-assert.git

which seem like they generally belong in this repo.  My suggestion is to move these into this node-tap repo to decrease the number of dependencies.

**Comment by trentm** [comment]
Note that it should affect this, but I think that nodeunit (for one) is already using some of these modules as independent modules: https://github.com/caolan/nodeunit/tree/master/node_modules

**Comment by isaacs** [comment]
Fixed by @kusor, published as 0.1.0
