### ISSUE TITLE
Pipe coverage to both Coveralls AND Codecov

### ISSUE THREAD

**Issue by dotnetCarpenter** [tapjs/tapjs#181]
> If a COVERALLS_REPO_TOKEN environment variable is set, then coverage is
> captured by default and sent to the coveralls.io service. If a CODECOV_TOKEN
> environment variable is set, then coverage is captured by default and sent to the
> codecov.io service.

I am checking out both [Coveralls](https://coveralls.io/) and [Codecov](https://codecov.io/) for the first time and it's pretty easy with `node-tap`. Unfortunately not at the same time(!)

If COVERALLS_REPO_TOKEN is set in travis then `tap` only pipe to Coveralls regardless that CODECOV_TOKEN is also set. The order doesn't matter, coverage data is only piped to Codecov if there is no COVERALLS_REPO_TOKEN variable.

**Comment by dotnetCarpenter** [comment]
I think line 236-256 in run.js should be re-factored to pipe to both services. https://github.com/isaacs/node-tap/blob/master/bin/run.js#L236

**Comment by dotnetCarpenter** [comment]
I gave it a shot with PR #182

**Comment by isaacs** [comment]
Landed in 3.1
