### ISSUE TITLE
tap's coverage does not work with nsolid

### ISSUE THREAD

**Issue by evanlucas** [tapjs/tapjs#188]
When testing [nsolid](https://nodesource.com/products/nsolid), I realized that the coverage aspect of node-tap does not actually instrument and check coverage. 

@julianduque did some awesome investigative work and diagnosed the problem to be in `spawn-wrap`.

https://github.com/isaacs/spawn-wrap/pull/6 has a proposed solution that is working for me locally.

**Comment by dotnetCarpenter** [comment]
I might be seeing the same issue with [ecstatic](/jfhbrook/node-ecstatic). Using tap `2.3.*`, no code is instrumented and the coverage is always 100%.

**Comment by julianduque** [comment]
A PR by @evanlucas landed on `spawn-wrap` https://github.com/isaacs/spawn-wrap/pull/6 and it should be available on versions `>=1.0.2` so `node-tap` needs to update their `nyc` dependency to `5.1.0` to have this patch landed.

**Comment by dotnetCarpenter** [comment]
I just read the [PR](https://github.com/isaacs/spawn-wrap/pull/6) and it seems to be about the node executable having different names. Seems to be a different issue from mine, as tap's coverage instrumentation has worked before, albeit in a different project, on the same machine, with the same major node version. I'll butt out.

**Comment by julianduque** [comment]
@dotnetCarpenter so no related to N|Solid?

**Comment by dotnetCarpenter** [comment]
No. I haven't had time to investigate. I have only observed that doing `tap --coverage test/*.js` in [ecstatic](/jfhbrook/node-ecstatic/) doesn't work on Windows, with tap v2.3.5.

**Comment by isaacs** [comment]
This should be working now with tap 3.1.1 and above.
