### ISSUE TITLE
calling t.end twice doesn’t throw

### ISSUE THREAD

**Issue by gr2m** [tapjs/tapjs#194]
I’d expect tap to give me an error or some kind of warning if that happens

``` js
var test = require('tap').test

test('test 1', function (t) {
    t.end()
    t.end()
})
```

I've been hunting a bug in an entire different package but turns out that in one passing test there was a `t.end` in the middle, and an important uninstall method didn't get called, so the test caused side effects

**Comment by isaacs** [comment]
Yeah, I agree, that should probably be an error.

What about this?

```
t.plan(1)
t.ok(true) // implicit t.end() here
t.end()
```

**Comment by gr2m** [comment]
yeah we use `t.plan` in async tests, but in linear sync tests, it’s nicer to use `t.end` as we don’t need to keep the `t.plan` up to date

**Comment by gr2m** [comment]
Thanks so much!!!
