### ISSUE TITLE
Extra assertion beyond plan not causing a failure.

### ISSUE THREAD

**Issue by jamestalmage** [tapjs/tapjs#198]
See https://github.com/sindresorhus/ava/commit/5e6327de2dcdc7a63d7d53f505673dbfd7973393

We had an incorrect plan count, and it was not failing our test suite.

It did print out an error message to console, but it was an `unhandledRejection` notice. I suspect this is because exceeding the plan count causes an error to be thrown, but since that happened inside a promise handler, the error was caught and turned into a rejection. 

I would expect this to cause a failure regardless of whether the error is caught.

**Comment by isaacs** [comment]
What version of node-tap are you using?  Seems to work as expected using the latest and greatest.

https://gist.github.com/isaacs/0972a1dc51f74118e544

**Comment by jamestalmage** [comment]
https://gist.github.com/jamestalmage/ae4b2790fef88a7d0642

It seems you are using a thrown error to signal the failure. That is problematic if it is wrapped in a `try`/`catch` (which is a pretty easy situation to get into with Promises).

>  I suspect this is because exceeding the plan count causes an error to be thrown, but since that happened inside a promise handler, the error was caught and turned into a rejection.

**Comment by isaacs** [comment]
Yet Another reason why promises catching all errors is a terrible antipattern.

Yep, this is a good test.  It should be doing `this.threw(er)` and then returning, rather than throwing.  Patch + test welcome.

**Comment by isaacs** [comment]
I guess this would fall under the same deal, then?

``` javascript
var tap = require('tap');

tap.test(function (t) {
  try {
    t.pass()
    t.end()
    t.pass()
  } catch (e) {
    // noop
  }
});
```

**Comment by isaacs** [comment]
What about this?

``` javascript
var tap = require('tap');

tap.test(function (t) {
  try {
    t.pass()
    t.end()
    t.end()  // throws "end called more than once"
  } catch (e) {
    // noop
  }
});
```

At some point, do we _ever_ throw, or only ever report failures, and let them throw only iff there's no parent test to catch it?

**Comment by jamestalmage** [comment]
> Yet Another reason why promises catching all errors is a terrible antipattern.

That's not an argument I've heard before. What would the alternative have been?
