### ISSUE TITLE
tap --coverage is broken on Windows

### ISSUE THREAD

**Issue by dotnetCarpenter** [tapjs/tapjs#199]
I haven't had time to investigate. But I have observed that doing `tap --coverage test/*.js` in [ecstatic](/jfhbrook/node-ecstatic/) doesn't work on Windows, with tap v2.3.5.

**Comment by isaacs** [comment]
Awesome, thanks. I'll take a look soon. 

It's about time to get this module on appveyor as well.

**Comment by isaacs** [comment]
In the meantime, can you run the tests with `tap test/*.js -C --coverage` and share the output?

**Comment by isaacs** [comment]
Issue fixed and published.  Need to pull https://github.com/jfhbrook/node-ecstatic/issues/182 to apply fix.

**Comment by dotnetCarpenter** [comment]
I've been offline the past week. I can see that you have fixed the issue but anyway here is the result for `tap test/*.js -C --coverage`: https://gist.github.com/dotnetCarpenter/4e929a16751449339b07

**Comment by isaacs** [comment]
Hm, seems like that gist is not found.

**Comment by dotnetCarpenter** [comment]
@isaacs I've updated the link. Must have been a paste error. https://gist.github.com/dotnetCarpenter/4e929a16751449339b07

**Comment by jamestalmage** [comment]
What does your directory structure and `package.json` look like? `nyc` recently changed  it's config options from RegExp strings to glob strings. If you were configuring `nyc` in `package.json` that could cause issues.

**Comment by dotnetCarpenter** [comment]
There is no nyc configuration in the [package.json](https://github.com/jfhbrook/node-ecstatic/blob/master/package.json).

Here is the output of `tap -C --coverage test/*.js` with tap v5.0.0: https://gist.github.com/dotnetCarpenter/7ab264c66841816d44cd

**Comment by jamestalmage** [comment]
Sorry, I was on mobile and missed the comment that it was already fixed.
