### ISSUE TITLE
output doesn't show full relative path to test files

### ISSUE THREAD

**Issue by trentm** [tapjs/tapjs#20]
```
$ find tst
tst
tst/agent.test.js
tst/master
tst/master/get.test.js
tst/relay.test.js
$ bin/tap tst
ok agent.test.js .................... 1/1
ok get.test.js ...................... 1/1
ok relay.test.js .................... 1/1
total ............................... 6/6

ok
```

That should show:

```
...
ok master/get.test.js ...................... 1/1
...
```

right?  Or perhaps, it would be nice for it to show that. My naive studying of TAP suggests that TAP doesn't require this.

Opinion one way or the other? If it sounds good, i can look at working up a patch for this.

**Comment by isaacs** [comment]
Sure, it should probably show more of the filename.  Note: that's not actually "TAP" output, it's more human-friendly shorthand.  To see the TAP output, do `TAP=1 bin/tap tst`

**Comment by trentm** [comment]
I believe pedro has already fix this in a coming pull request of his.

**Comment by isaacs** [comment]
Yep.  This is fixed by @kusor.  Going to review and pull in the next few days, after we get 0.6.4 out the door.
