### ISSUE TITLE
make website more good

### ISSUE THREAD

**Issue by isaacs** [tapjs/tapjs#208]
There's a website now!  http://www.node-tap.org

It's pretty OK, I think.  Here are some requirements:
1. It should look good (or at least, not bad) on small devices and also on screens
2. It should be [much smaller than most well-known works of Russian literature](http://idlewords.com/talks/website_obesity.htm).  There's no need for very much clutter, what it needs is more content.
3. It should provide useful info and stay up to date with the project.

It's a Jekyll thingie in the gh-pages branch, as is the custom of our time.
- If anyone wants to write more tutorials and stuff, that'd be rad.  There's a "getting started" guide, but it might be good to add guides for some of the more interesting features, like using `--save=fails.txt` and re-running tests until passing, or `--bail` to exit on the first failure.
- Syntax highlighting would also be nice.
- <strike>Maybe if there's some way to automatically keep bits of it generated by the "real" docs, that'd be good?</strike>
- <strike>Maybe the README should have less stuff in it, and direct people to the website?</strike> gh-pages IS the "real docs" now.  The readme got too big and was removed.
- Probably would be good to add some kind of "why tap?" page.

**Comment by sam-github** [comment]
It would be great if we could link into pages... I just tried to send someone a direct link to `t.equal()` docs... but had to settle for the asserts page and note telling them to scroll down.

**Comment by isaacs** [comment]
Agreed!  I don't know how to make Jekyll (or kramdown?) auto-anchor headings, but I imagine there's a way to since this is a GitHub thing and they're all about that for README.md's and such, right?

**Comment by Freyert** [comment]
Where's the repo for the website and how does one contribute to that?

**Comment by isaacs** [comment]
It's the same repo, just the `gh-pages` branch.  https://github.com/tapjs/node-tap/tree/gh-pages

**Comment by isaacs** [comment]
New site is live!  Thanks, @tanyabrassie!

**Comment by tanyabrassie** [comment]
Woot! @isaacs I found one really tiny css issue -- there's a missing semicolon on line 27 in  `/hero.js` (the `InnerCircle` styles) that's causing right: 0 not to be picked up, so the circles are misaligned. 🙈

**Comment by isaacs** [comment]
Fixed  on
https://github.com/tapjs/node-tap/commit/c03d5f85852b04bebcf1a788039649b545e1a2d1

Thanks!
