### ISSUE TITLE
`t.bailout` results in a hang

### ISSUE THREAD

**Issue by trentm** [tapjs/tapjs#21]
The following hangs:

```
$ ../bin/node --version
v0.4.12
$ cat foo.test.js
var test = require('tap').test;
test("first", function(t) {
    t.end();
});
test("bail", function(t) {
    t.bailout("boom");
    t.end();
});
test("last", function(t) {
    t.end();
});
$ ../bin/node foo.test.js
# first
^C
```

I see this with both tap 0.0.14 and 0.0.1. My understanding from the example test file is that this should abort all subsequent tests in the test file.

**Comment by isaacs** [comment]
Your understanding is correct.  This is a bug.

**Comment by bigeasy** [comment]
It hangs because the timeout is not cleared. It will hang until the timeout is cleared. Setting no timeout, timeout as infinity, causes the program to end on bailout. The processes exists with no output, but should send with "Bail out!" to let the harness know that things are not good.
