### ISSUE TITLE
stack.js TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by keithamus** [tapjs/tapjs#211]
I'm reading a file in my test suite that may or may not exist.

When it doesn't exist, I get this error:

``` js
Error
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
... and some more lines
```

The important bit is `at Error (native)` - which makes stack.js `parseLine` fail because it expects every error line to have a file. [here is the offending line in stack.js](https://github.com/tapjs/node-tap/blob/5183ec8ee8536fbad6f2f3edb8774bd8b456ecfa/lib/stack.js#L218) that assumes `file` (`match[8]`) is defined. In this case it is not; `line.match(re)` produces this output for me:

``` js
[
  '    at Error (native)', // 0
  undefined, // 1
  'Error', // 2
  undefined, // 3
  undefined, // 4
  undefined, // 5
  undefined, // 6
  undefined, // 7
  undefined, // 8
  undefined, // 9
  undefined, // 10
  'native', // 11
  index: 0, // 12
  input: '    at Error (native)' // 13
]
```

**Comment by isaacs** [comment]
Indeed, this is a bug.  cc @jamestalmage who is working on refactoring this module out to https://github.com/jamestalmage/stack-utils.  I'll land a fix in node-tap in the meantime.

**Comment by jamestalmage** [comment]
> I'll land a fix in node-tap in the meantime.

I should have the `stack-utils` PR ready shortly if you just want to wait for that. I've got a fix for this in there already.
