### ISSUE TITLE
 not ok child test left in queue:

### ISSUE THREAD

**Issue by smartmouse** [tapjs/tapjs#212]
I am using node-tap for our tests, and our tests sometimes fail with this error not ok: child test left in queue but the tests pass most of the time. This issue is intermitten,
Is this a tap issue?

**Comment by isaacs** [comment]
That means that the test script is exiting without calling `end()` or satisfying the `plan()` of all the child tests.

The error output should tell you the test that's being left unfinished.

Example: https://gist.github.com/isaacs/ade55a7b5c3ee915e1d0

**Comment by smartmouse** [comment]
Thank you for the info. Closing this.
