### ISSUE TITLE
Try tests twice on AppVeyor

### ISSUE THREAD

**Issue by jamestalmage** [tapjs/tapjs#214]
I noticed there are two AppVeyor webhooks, I'm guessing the goal was to try running twice since AppVeyor is so darn finicky.

We [solved it a different way](https://github.com/sindresorhus/ava/blob/master/appveyor.yml) for AVA, and I think it works better than this approach. Rather than trying to rerun the entire matrix, it only reruns the failed build (albeit on the same VM).

**Comment by isaacs** [comment]
I'm not sure what you mean.  We only run the test once on Appveyor, I thought.

**Comment by jamestalmage** [comment]
There are two Appveyor webhooks. I've since realized it wasn't intentional, but an artifact of moving the repo into an org. Same thing happened to me when moving stack-utils. I ended up keeping the one with the additional suffix.

If you're sufficiently happy with test reliability on Windows, just ignore.

**Comment by isaacs** [comment]
It looks like one of those is testing pushes, and the other is testing PR's.  If you push to a branch on this repo, and also make a PR, then it'll run both.  But most of the time, we want it to test pushes, and also we want to test PR's coming from folks who don't have write access.  It'd be nice if it detected the same commit hash and skip it, but whatever.

I'm fine with it.

**Comment by isaacs** [comment]
(lmk if there's some problem i'm overlooking, happy to reopen if necessary)

**Comment by jamestalmage** [comment]
My initial assumption was wrong. AppVeyor does not handle moved repos well, and you can end up with two web hooks that way. (Happened to me with stack-utils).

https://github.com/tapjs/node-tap/settings/hooks <- delete the one without the funny suffix

You are actually running 4 times if you make a PR from a different branch on the main repo

**Comment by isaacs** [comment]
Oh, wild.  ok, deleted one.  Thanks!
