### ISSUE TITLE
Feature Request - allow extra assertions to be added at require time

### ISSUE THREAD

**Issue by konobi** [tapjs/tapjs#215]
It would be great if there was a standard way to add extra assertion libraries to the tap instance at import time. This would allow for more sharing and reuse of assertions.

For example:

``` javascript
var tap = require('tap')('tap-assert-more', 'tap-assert-set', 'tap-assert-readline');
```

The hope would be to enable developers adding new assertion libraries to be able to build their assertions using the pre-existing, well tested, battle hardened assertions. This should also help with being able to create libraries like "test-npmready' or the like.

**Comment by isaacs** [comment]
You can already do this! http://www.node-tap.org/api/#t-addassert-name-length-fn

``` javascript
// assert-readline.js
require('tap').Test.prototype.addAssert('readline', 2, function (stream, expect, message, extra) {
  var line = readOneLineFromStream(stream)
  return this.match(line, expect, message, extra)
})
```

To add asserts to all test objects, add them to the Test.prototype object.  To add them to just one test object, you can call addAssert on that test object.

**Comment by jtlapp** [comment]
That installs it on everything but the root-most test itself. You also need to call `require('tap').addAssert()`.

**Comment by isaacs** [comment]
Adding it to the prototype also adds it to the root test. That's how all the root test assert functions get there in the first place.

**Comment by jtlapp** [comment]
Try it. I tested it, and the code requires it. When you've a handle to the module, you have an instance of Test. Changing the prototype doesn't change all of the instances previously made. From root.js:

``` js
var Test = require('./test.js')

var tap = new Test()
module.exports = tap
```

**Comment by jtlapp** [comment]
You call `addAssert()` prior to `tap = new Test()` because this is the last line of test.js:

``` js
tapAsserts.decorate(Test.prototype)
```

**Comment by isaacs** [comment]
@jtlapp Incorrect.  Additions to the prototype affect all instances.

``` javascript
var t = require('tap')
var myTest = new t.Test()

t.Test.prototype.addAssert('foo', 1, function (ok) {
  this.comment('foo! %j', ok)
  return this.ok(ok, 'foo foo foo')
})

t.foo(true)
t.end()

myTest.pipe(process.stdout)
myTest.foo(false)
myTest.end()

// output
// TAP version 13
// # foo! true
// ok 1 - foo foo foo
// 1..1
// # time=25.005ms
// TAP version 13
// # foo! false
// not ok 1 - foo foo foo
//   ---
//   at:
//     line: 13
//     column: 8
//     file: t.js
//   stack: |
//     Object.<anonymous> (t.js:13:8)
//   source: |
//     myTest.foo(false)
//   ...
// 1..1
// # failed 1 of 1 tests
// # time=15.383ms
```

**Comment by jtlapp** [comment]
Ah poo. I'm not batting well. Here's what I'm really doing:

``` js
var t = require('tap')
var Test = t.Test;

Test.prototype._overriddenStrictSame = Test.prototype.strictSame;
Test.prototype.strictSame = function subtapStrictSame(f, w, m, e) {
    f._instanceof_ = 'DummyClass';
    return this._overriddenStrictSame(f, w, m, e);
};

t.strictSame({ x:1 }, { x:1 });

/* YIELDS... */

// TAP version 13
// ok 1 - should be equivalent strictly
// 1..1

/* WANT... */

// TAP version 13
// not ok 1 - should be equivalent strictly
//   ---
//   found:
//     x: 1
//     _instanceof_: DummyClass
//   wanted:
//     x: 1
//   ...
// 1..1
// # failed 1 of 1 tests
```

Can't say I understand why it works in one case but not the other.

**Comment by isaacs** [comment]
Test methods are bound to the instance, so _overwriting_ something on the prototype (or adding a prototype method that they already have) won't have any effect.

That's to support passing methods around, like `someCallbackFunction(t.end)`

**Comment by isaacs** [comment]
Here's the code that does that: https://github.com/tapjs/node-tap/blob/master/lib/test.js#L109-L127

**Comment by jtlapp** [comment]
Thank you for your continued patience educating me on tap, node, and JS. I'll look into your response shortly. My tool is shaping up nicely, want to get it up.

**Comment by isaacs** [comment]
@jtlapp No problem.  Glad you're having fun with it :)
