### ISSUE TITLE
Should we add the ability to pass arbitrary nyc flags?

### ISSUE THREAD

**Issue by evanlucas** [tapjs/tapjs#222]
nyc has a few flags like `--cache` and `--all`. Instead of manually adding each nyc flag as a tap option, should we add the ability to pass arbitrary flags to the nyc process if coverage is enabled? I'd be happy to implement this, just wanted to make sure it is something that you would consider. Thanks!

**Comment by isaacs** [comment]
You already can!  `--nyc-arg=--cache --nyc-arg=--all` etc.  Specify multiple args by using `--nyc-arg` multiple times.

**Comment by evanlucas** [comment]
wow. Yay!!!!
