### ISSUE TITLE
Browserifiability

### ISSUE THREAD

**Issue by isaacs** [tapjs/tapjs#225]
It'd be nice to be able to browserify this module.  Maybe it's not possible, and the answer is to port features to tape that make sense to have in a browser.  But at least, I'd like to push on that barrier and see what would actually have to change.

**Comment by isaacs** [comment]
Looks like the biggest immediate hurdles are just some things that try to load `buffertools`, and creating shims for `process.hrtime` and `process.stdout` if they're missing.

<img width="608" alt="screenshot 2016-01-31 12 22 06" src="https://cloud.githubusercontent.com/assets/9287/12704725/982bd74a-c815-11e5-9f1c-d723103a72f7.png">

Probably coverage is going to be tricky, though, and it'd be nice if there was a way to dump colored output to a div in the page instead of just raw TAP in the console.

**Comment by isaacs** [comment]
(note the `time=0ms` because my process.hrtime shim isn't very sophisticated.  literally just returns `[0,0]` always.)

**Comment by Hypercubed** [comment]
Hello @isaacs, wonder if there is anything holding this up.  Using the `browser` branch I can run `node-tap` using `browserify` and `tape-run` (also `testling`).  Only issue was that the browser does not close when the tests are done, unlike when using `tape` and `blue-tape`.

**Comment by TehShrike** [comment]
[`tap-browser-color`](https://github.com/kirbysayshi/tap-browser-color) should work as well for `node-tap` as it does for `tape` - it doesn't hook into `tape`, it overwrites `console.log` and watches for "ok" or "not ok" strings to determine what color to show.

**Comment by isaacs** [comment]
@TehShrike node-tap doesn't use console.log inherently, it's a stream that gets piped to process.stdout.  The shim here creates a new process.stdout that uses console.log, though, so maybe it would work?

@Hypercubed I haven't done anything to make this work.  If you care about this, I recommend picking it up and woking on it.  I'm happy to answer any questions you run into.
