### ISSUE TITLE
Use .taprc to set defaults

### ISSUE THREAD

**Issue by isaacs** [tapjs/tapjs#228]
Read a config file at ~/.taprc for setting default colors, reporters, etc.

**Comment by kgraves** [comment]
I'm looking into working on this, but I'm curious on how you want it done.

There are modules out there that parse rc files. Are you against using any of these?
What format do you want to support? (e.g. .ini, .json, .yml, etc)
Any other ideas on features/support that you would like to see?
Should cli args trump the .rc file or vice versa? (I'm thinking the former)

**Comment by isaacs** [comment]
Command line flags always are highest priority.  (Near is a higher indicator of intent than far-away.)

Only one file should be parsed: `require('os').homedir() + '/.taprc'`  (So no need for hierarchical RC file stuff.)

I'm thinking _probably_ yaml makes the most sense?  Since tap uses yaml already and js-yaml is already a dep?  And then JSON would work as well, since it's a subset of yaml.

Keys should match the CLI args.

Args that can be set multiple times (`nyc-arg` and `node-arg`) can be specified either as a single string, or an array of strings.  (Since you can't set a key multiple times in yaml like you can on a command line.)

**Comment by isaacs** [comment]
Also, thanks!  Looking forward to it :)

**Comment by isaacs** [comment]
Use [os-homedir](https://www.npmjs.com/package/os-homedir) to polyfill for 0.10 and before.

**Comment by kgraves** [comment]
Now that I'm working on this issue, I have a question. When it comes to rc file format (json vs yml), did you want me to support both json and yml, or just choose one over the other? I couldn't decipher this from your response :)

**Comment by kgraves** [comment]
@isaacs ^ There's my first pass, let me know what you think.

**Comment by isaacs** [comment]
@kgraves Json is a subset of yaml. So, use yaml, and then anyone who wants json is taken care of.

**Comment by kgraves** [comment]
(facepalm) Gotcha, I probably should have thought about that a little more. Now that I reread that, it's pretty clear.

**Comment by isaacs** [comment]
Landed in 6.0.0
