### ISSUE TITLE
Unexpected .plan() behavior

### ISSUE THREAD

**Issue by micnic** [tapjs/tapjs#230]
While testing my web framework module I found a very strange behavior of my tests when I used `test.plan()` method. Here is the simplest example that will fail to run correctly:

``` js
var http = require('http'),
    tap = require('tap');

tap.test('Dummy test', function (test) {
    test.plan(0); // If test.plan(0) is omitted everything works as expected
    http.createServer(function (req, res) {
        // no requests
    }).listen(12345, function () {
        this.close(function () {
            test.end();
        });
    });
});

tap.test('Dummy test', function (test) {
    test.plan(0); // If test.plan(0) is omitted everything works as expected
    http.createServer(function (req, res) {
        // no requests
    }).listen(12345, function () { // HERE I get an exception that port 12345 is in use
        this.close(function () {
            test.end();
        });
    });
});

// In the output I receive 2/3 tests passing (but there are only 2 tests!)
```

As you can see I have 2 identical tests which use the `http` module to create a HTTP server and close them after their start. Somehow adding `test.plan(0)` breaks the tests, I can not start the second server because the port is already occupied (but the first server should be already closed!) and the output show 2 out of 3 tests passing (but there are only 2 tests!). In this case if I add a timeout for the second server start works.

If I set `test.plan(1)` and add an assertion I get the same exception, but this time I get 1 out of 2 tests passing.

**Comment by isaacs** [comment]
Here's what's going on:  When you set a plan, you're specifying exactly how many tests will run, _and the test ends as soon as that many tests have been run_.

So, for example, with this test script:

``` javascript
var t = require('tap')

t.test('first', function (t) {
  console.error('in first test')
  setTimeout(function () {
    console.error('timeout in first test')
  })
  t.pass('this is fine')
  t.plan(1)
  console.error('after plan(1) in first test')
})

t.test('second test', function (t) {
  console.error('in second test')
  t.plan(0)
  console.error('after plan(0) in second test')
})

t.test('third test', function (t) {
  t.pass('this is fine')
  t.end()
})
```

the output looks like this:

```
TAP version 13
    # Subtest: first
in first test
    ok 1 - this is fine
    1..1
ok 1 - first # time=8.794ms

after plan(1) in first test
    # Subtest: second test
in second test
    1..0
ok 2 - second test # time=4.968ms

after plan(0) in second test
    # Subtest: third test
    ok 1 - this is fine
    1..1
ok 3 - third test # time=1.785ms

timeout in first test
1..3
# time=38.094ms
```

Calling `t.plan(0)` is equivalent of calling `t.end()` (unless you had some tests already, in which case, it's an error.)  Note that the timeout function in the first test doesn't fire until after the other tests have already run, because the plan is already fulfilled, so it moved on immediately.

You don't have any assertions in the test, so if you want to ensure that no assertions happened, you can use `t.plan(0)` _instead of_ calling `t.end()`, or you can just call `t.end()` and not set `t.plan(0)`.

Setting a plan at the start is 100% optional.

**Comment by micnic** [comment]
@isaacs thanks for the explanation, now I understood why it is working like this. I have one question related to this issue: it would make sense or is it possible to create a method (example name: `t.expect(n)`) to assert the current number of assertions?

I have an use case where I need to check how many times a function was called, right now everytime I do an assertion I increment a local variable and I assert its value at the end of the test or even before some other assertions. Sometimes I have to check the 0 assertions value for consistency, that's why I had to use `t.plan(0)`. I want to be able to control when exactly the test should end, that's why I don't really like `t.plan(n)` in this case.

**Comment by isaacs** [comment]
Just call t.plan(0) or t.plan(n) at the end, rather than at the beginning.
