### ISSUE TITLE
Question: sourcemap support with coverage

### ISSUE THREAD

**Issue by remy** [tapjs/tapjs#231]
It's a bit of a long shot, but do you know if it's possible to get accurate stacktraces when the coverage is enabled during a test?

i.e. I run my default `npm test` with `tap test/*.test.js --cov` which instruments the code and gives me coverage stats. The downside being when I get a stacktrace, although I'll get the filename (and sometimes/all times?) the function name, the line number will be completely wrong (...because of the instrumentation).

I honestly don't know if this is supported anywhere, but wondered if sourcemaps would a) fix this, b) supported from tap to pass to the coverage thingymejig?

**Comment by isaacs** [comment]
Yeah, I've noticed that as well.

@bcoe is there an option in nyc to use sourcemaps?  Does istanbul use them?

**Comment by bcoe** [comment]
@isaacs @remy good news, nyc has solid source-map support:

https://github.com/bcoe/nyc#support-for-custom-require-hooks-babel-es2015

**Comment by isaacs** [comment]
@bcoe So, that's the thing for custom source-map support for babel et al.  But @remy's asking if there's sourcemap support for Istanbul itself, so that the stack traces are accurate.

**Comment by bcoe** [comment]
@isaacs @remy gotcha. I feel like some of this functionality might exist in Istanbul, and it wouldn't be hard to use the same remapping logic we use when outputting coverage reports to remap errors.

This seems like a great thing to investigate, CC: @jamestalmage, @gotwarlost

**Comment by gotwarlost** [comment]
Apologies, I haven't been paying attention to istanbul references for a couple of weeks now.

There is actually a pull request on master that fixes the stack traces but it is lower on my pipeline of things to do. I have been wanting to push out the 1.x branch with "proper" source map support (for coverage, not stack traces) for some time and this has still not happened.

https://github.com/gotwarlost/istanbul/pull/422

**Comment by isaacs** [comment]
I'm going to go ahead and close this.  When/if it lands in istanbul, it'll get picked up in tap, but there's nothing to do here.
