### ISSUE TITLE
Coverage generates unequivalent code

### ISSUE THREAD

**Issue by ranisalt** [tapjs/tapjs#236]
I'm not sure where to report this issue, so please point me if I'm wrong.

I'm trying to test the following code:

``` js
for (const key of Object.keys(limits)) {
    const curr = limits[key], value = options[key];
```

Without coverage, on Node 5.6, it works properly. `key` varies on every iteration, `curr` and `value` do too, as they are all well scoped variables.

When I activate coverage (`npm t -- --cov`) the generated code is not equivalent, as it probably hoists (incorrectly) all variables and both `key`, `curr` and `value` are immutable across all iterations over `Object.keys(limits)` and fail silently (not so, as tests fail then).

**Comment by isaacs** [comment]
This is an istanbul bug, not a tap bug.
