### ISSUE TITLE
Don't autoend until returned promise has fulfilled/rejected

### ISSUE THREAD

**Issue by novemberborn** [tapjs/tapjs#240]
Tests end when the planned assertion count is reached, even if a returned promise is still pending.

This is problematic when assertions are run in response to events that are triggered while the promise is pending. More events could occur but tap moves on to the next test.

Here's a reduced example:

``` js
const test = require('tap').test

test('example', t => {
  t.plan(1)

  return new Promise(resolve => {
    setTimeout(resolve, 1000)
    t.pass()
  }).then(() => console.error('fulfilled'))
})

test('after', t => {
  console.log('after')
  t.end()
})
```

Results in:

``` console
$ $(npm bin)/tap -R spec test.js

test.js
  example
    ✓ (unnamed test)

after
fulfilled
  ✓ after

  2 passing (1s)
```

But I would have expected:

``` console
$ $(npm bin)/tap -R spec test.js

test.js
  example
    ✓ (unnamed test)

fulfilled
after
  ✓ after

  2 passing (1s)
```

**Comment by ranisalt** [comment]
You can increase your test plan by 1 and just `t.pass` after the promise is fullfilled.

**Comment by novemberborn** [comment]
@ranisalt that doesn't help if my test _exceeds_ the test plan. It ends when the plan is reached, but the test can legitimately continue until the promise is fulfilled. It'll start to interfere with the next test.

I just ran into this actually. Because a second test started to run it actually caused assertions to fail.

**Comment by ranisalt** [comment]
Can't you just don't plan, rather just run until `t.end()` is called?

**Comment by novemberborn** [comment]
Planning helps catch async assertions that fail to run.

**Comment by isaacs** [comment]
I think that @novemberborn makes a good point.

If a Promise is returned, then that's a clear expression of intent, that the Promise lifecycle (either conclusion or failure) should be the definition of the test lifecycle.

Patch welcome for this, or I'll probably get to it relatively soon if no one else volunteers.

I'm not sure whether it should count as a breaking change or not.  It _is_ a change to the contract, but not one that's likely to cause any test failures.  At worst, it'll make some tests run a bit slower.

**Comment by novemberborn** [comment]
@isaacs I think I have a solution. It's getting late here but I might have a PR for you over the weekend.
