### ISSUE TITLE
Create hooks into Diagnostic Information

### ISSUE THREAD

**Issue by Freyert** [tapjs/tapjs#243]
It would be nice to hook into the diagnostic information in order to add arbitrary (but safely namespaced) data to passing tests and failing tests.

The specific issue I'm confronted with is adding req/res cycle timings to the output, which I'm hacking with a `t.comment`, but it'd be nice to be able to conform to a stable format like YAML.

Ideally it'd play out like the below:

```
t.diagnostic({ responseTime: 300 }); //Merges safely into test diagnostic info.
==== Dreamy Output ====

TAP Version 13
ok 1 yay

---
responseTime: 300

...
```

**Comment by isaacs** [comment]
You can already do this with the `extra` object passed to any assertion.

``` javascript
t.pass('yay', { responseTime: 300 })
```

**Comment by isaacs** [comment]
Oh, wait, nevermind, it doesn't _show_ diags for passing test points, though.  So, you still need a way to tell it "please do print out diags, even though this is not a failure".

**Comment by isaacs** [comment]
Ok, this works on tap 6.1 now.

**Comment by Freyert** [comment]
Thank you @isaacs! You're wonderful!

**Comment by isaacs** [comment]
Np.  Hey, in 7.1, you can also do `t.fail('just fail, no diags please', { diagnostic: false })` to suppress yaml diagnostics as well.
