### ISSUE TITLE
Name argument of Test.prototype.test is not optional when providing options object

### ISSUE THREAD

**Issue by maarten-t** [tapjs/tapjs#244]
Calling `tap.test(options, testFunction)` will create a subtest with the name "[object Object]", instead of "(unnamed test)". The subtest ignores the supplied options object.

This behaviour surprises me because the documentation of Test.prototype.test suggests that all three arguments are optional:

> t.test([name], [options], [function])

**Comment by isaacs** [comment]
Huh.  Yeah, that seems like a bug for sure.

Patch welcome!
