### ISSUE TITLE
Support question - produce tap failing result

### ISSUE THREAD

**Issue by ORESoftware** [tapjs/tapjs#247]
I am looking for a way to produce tap output.

The problem is that my tests aren't run with a tap-based test runner, so if I were to call tap.fail() to log a failing result for instance, the stack trace would be way far removed from the actual code that could have produced the error.

So my question is - is there a way to produce tap output from say a JSON object that represents a test? I see that there's a module to pipe mocha results through some tap transform stream to convert them to tap output. I think I need something like that. Since this is for a library I am writing, perhaps I should I write a module that does this transform for my lib and kinda copy what the mocha-tap-transform thing does? Thanks for help.

**Comment by isaacs** [comment]
Well, it's kind of diving into internals and a bit kludgey, but you could do this:

``` javascript
var Test = require('tap').Test

var t = new Test()

// test object is a stream, so you can pipe it wherever
var output = ''
t.on('data', function (c) {
  output += c
})
t.on('end', function () {
  console.error('test said\n---\n%s---', output)
})

t.printResult(false, 'this is the message', {
  stack: 'some\nstack\ntrace',
  at: {
    file: 'some-file.js',
    line: 123
  },
  todo: false, // can also be a string or true
  skip: false  // can also be a string or true
})

t.end()
```

```
$ node t.js
test said
---
TAP version 13
not ok 1 - this is the message
  ---
  stack: |-
    some
    stack
    trace
  at:
    file: some-file.js
    line: 123
  ...
1..1
# failed 1 of 1 tests
# time=19.221ms
---
```

**Comment by jamestalmage** [comment]
I started work on [`tap-emitter`](https://github.com/avajs/tap-emitter/blob/master/test/messages.js) to improve AVA's TAP output.

It is intended to be a very low level TAP generator. It only generates correctly formatted TAP output. It does not provide a means to run tests, or anything of the sort.

I got sidetracked, so it hasn't seen active development in a few months. It's undocumented, but well tested.

You could generate @isaacs example above with the following:

``` js
var Messages = require('tap-emitter/lib/messages');

var messages = new Messages('13', 0);

console.log([
  messages.version(),
  messages.test({
    ok: false,
    testNumber: 1,
    description: 'this is the message'
  }),
  messages.yaml(someError),
  messages.plan(1),
  messages.diagnostic('failed 1 of 1 tests'),
  messages.diagnostic('time=19.221ms')
].join('\n'));
```

**Comment by ORESoftware** [comment]
@jamestalmage thanks I may use that, sorry didn't see your message until now, but may prove useful - one question though - if you have a stack-trace, you are supposed to put that as the argument to `yaml()`?
