### ISSUE TITLE
Tests don't timeout in long sync ops

### ISSUE THREAD

**Issue by remy** [tapjs/tapjs#248]
Take the following test:

``` js
var test = require('tap').test;
test('timeout test', { timeout: 1000 }, function (t) {
  var start = Date.now();
  while (true) {
    var diff = Date.now() - start;
    if (diff > 2000) {
      break;
    }
  }

  t.ok('did not timeout');
  t.end();
});
```

This succeeds (testing with tap@5.7.0), even though the test takes 2 seconds, and the timeout is 1 second.

It's because (roughly reading the code) because the timeout logic is based around the `setTimeout` firing, which in this sync op, it doesn't have time to, so the test appears to pass.

I've only roughly tried to fix this (which is why I don't have a PR), but I added the following directly after [this line](https://github.com/tapjs/node-tap/blob/master/lib/test.js#L1041):

``` js
  if (this._timeout && final.time > this._timeout) {
    this._onTimeout();
  }
```

And the above test fails correctly.

However, the reason I didn't pull up a PR is because I wasn't 100% sure of the impact of this "tweak" - i.e. there's no validation, I wasn't sure if this is the time for all tests or a single test, etc.

Happy to help put together a PR if I can get some direction (or happy for someone else to, too :smile: ).

**Comment by isaacs** [comment]
Good catch!

Your patch is on the right track, but has to happen in a different spot, or else it'll trigger "test after end()" failures in some cases.

Fixed on 0ca1678e93e82060fdaae9e5484ad7c326413cc3
