### ISSUE TITLE
keeps running test function after failed assert

### ISSUE THREAD

**Issue by mvolkmann** [tapjs/tapjs#25]
tap continues executing the code in a test method after an assert fails. This allows other errors to mask the failed assertion. In the example below, getObj fails to return an object. The assertion t.ok(obj) fails as expected, but execution of the test function continues and we get the following error:
"not ok 3 TypeError: Cannot call method 'someMethod' of undefined".

I think it should stop on the first failed assertion in each test function and report that error. Most other test frameworks work that way and I think that is less confusing.

```
var test = require('tap').test;

function getObj(cb) {
  cb(null);
}

test('keeps going', function (t) {
  getObj(function (err, obj) {
    t.notOk(err);
    t.ok(obj);
    console.log('obj =', obj);
    obj.someMethod();
    t.end();
  });
});
```

**Comment by isaacs** [comment]
That's by design.  I have some projects that run a few hundred assertions, and it's very useful to see exactly which tests pass and which fail, rather than just the first failure.

That being said, it'd be nice to have it return the result so that you can check it to decide whether or not to keep going.

**Comment by mvolkmann** [comment]
I can somewhat understand that design choice, but I still think there's an issue. Notification of failed assertions is lost if an error occurs after those assertions. In many cases the cause of the error is directly related to those failed assertions. My example demonstrates that. I think it would be far less confusing if tap output messages about the failed assertions even if an error occurs after them.

**Comment by isaacs** [comment]
I see.  So, you're saying a throw should sort of imply a .end(), and print out the assertions that were run up to that point?  Seems reasonable.

**Comment by mvolkmann** [comment]
Yes, I think that would be a nice improvement.

**Comment by felixge** [comment]
+1 I strongly agree with this. @isaacs would you accept a patch?

**Comment by aredridel** [comment]
Hm. We do the opposite at work, and it's very useful to get the full output -- sometimes the later errors give some info as to what happened, too.
