### ISSUE TITLE
Run tap via API

### ISSUE THREAD

**Issue by ibc** [tapjs/tapjs#260]
Can `tap` be executed via JS API (instead of shell CLI)? I mean:

Instead of running this in a shell:

``` bash
$ tap --bail --color --reporter=spec test1.js test2.js
```

do the same in Node:

``` js
var tap = require('tap');

tap.xxxxx
```

**Comment by ibc** [comment]
Well, even the [`tap`](https://github.com/tapjs/node-tap/blob/master/bin/run.js) provided executable spawns a process, so the answer is not :)

**Comment by isaacs** [comment]
You can spawn it as a child process if you want?

```
var tapprocess = child_process.spawn(process.execPath, [
  require.resolve('tap/bin/run.js'), '--bail', '--color', ... ])
```

Or you can use `t.spawn()` to run the various tests (which is basically what the included `bin/run.js` file does)

**Comment by ibc** [comment]
Sure. What I meant is running `tap` via pure JS API without spawning a child process. But that's ok.

Thanks.
