### ISSUE TITLE
Replace codecov.io dependency

### ISSUE THREAD

**Issue by jvincilione** [tapjs/tapjs#265]
The codecov.io dependency (https://github.com/cainus/codecov.io) is being deprecated, and is using outdated dependencies. They suggest using codecov-node(https://github.com/codecov/codecov-node) as a replacement.

Currently, tap has an insecure dependency a few levels deep because of codecov.io using an ancient version of request which uses and even older version of hawk. See this thread for details: https://github.com/cainus/codecov.io/issues/29

They decided to deprecate codecov.io instead of fixing the actual issue.

**Comment by jvincilione** [comment]
You can also just update the version of codecov.io as a temporary fix as it looks like they updated their dependency. Either way, they still plan on deprecating the package.

**Comment by rkajbaf** [comment]
+1

**Comment by isaacs** [comment]
I can't switch over at least until https://github.com/codecov/codecov-node/pull/14 is completed and landed.

**Comment by isaacs** [comment]
Went a different way on this, removing codecov in tap 6.0.
