### ISSUE TITLE
Please pin codecov.io to 0.1.16

### ISSUE THREAD

**Issue by fruchtose** [tapjs/tapjs#269]
Release 0.1.17 includes a build-breaking dependency on a version of `request` which does not exist: cainus/codecov.io/issues/33

**Comment by irae** [comment]
To be honest this should be a dev-dependency, not a dependency. This is breaking everyone that depends on node-tap.

**Comment by isaacs** [comment]
It is not a devDependency https://github.com/tapjs/node-tap/commit/e577847553b8905cb5d9bcd0c0397473c0658191#commitcomment-17943382

**Comment by irae** [comment]
OK, I am fine with that. Thanks for the fix and thanks for explaining.

An extra 2¢: It is counter intuitive that services are part of the codebase. We could argue this is a case of coupling. Both Grunt and Karma encourage a more interesting pattern, which is requiring all "plugins" that start with "grunt-" or "karma-" respectively and providing hooks that the plugins can activate at the proper time.
