### ISSUE TITLE
Breaking change RFC: Remove codecov.io support

### ISSUE THREAD

**Issue by isaacs** [tapjs/tapjs#270]
The codecov.io module in use is deprecated, as noted in https://github.com/tapjs/node-tap/issues/265

However, the blessed module for uploading to codecov.io has some issues that are difficult to resolve without quite a lot of work.

I'm considering yanking out tap's support for it, and instead having users just do their own `posttest` upload script or whatever to send coverage there if they want.

This would considerably simplify some of the logic in `bin/run.js`, and I'd feel less guilty about using something that's unmaintained (or committing to maintain something I can't be expected to keep up with).

If you are currently using and relying on this feature, can you please weigh in on this?  How terrible will this be for you?  What is the best workaround to suggest?

cc: @evanlucas @dotnetCarpenter @alexindigo, because you have touched this bit of code in the past.

I'd like to have either a clear path to fixing this, or some confidence that we can cleanly break it, in the next few weeks or so.  Either way, it'll be in the 6.0.0 release.

Thanks.

**Comment by evanlucas** [comment]
Apologies for essentially putting you in this position with me being the one who implemented it. I have been following some of the issues on it and I think it will be better for tap (long run) to go ahead and remove it. +1 to cleanly breaking from it.

**Comment by isaacs** [comment]
@evanlucas No apologies necessary, it's on my shoulders for accepting the pr ;)  Do you still use codecov.io?  Do you have any suggestions for how we could suggest people work around it?

I'd like to print a message or something when we see a codecov environment var, saying that this has been removed, and suggesting some kind of workaround.

**Comment by evanlucas** [comment]
I personally do not use it anymore (I use coveralls again). I think printing a message would be a good way to help people transition. It does look like the official one has `nyc` support, so maybe we could recommend something like:

``` bash
$ tap --cov test
$ tap --coverage-reporter=text-lcov | codecov
```

or something like that?

**Comment by konobi** [comment]
+1 to removing.

**Comment by alexindigo** [comment]
Thank you for the considering this option, I think it's progress in the right direction. And maybe there is room for an extra step. :)

I was surprised to see any of the reporters baked into the test harness. All the coverage platforms provide nice and clear instructions how to add them to the project regardless of the test harness. And (at least for me) it feels like a waste to install dependecies I don't use, which is most likely the case if I use either of two and especially if I'm using something else.

Also what it would do if developer adds to the project one of that reporters manually, would it double report?

How about removing both (codecov and coveralls) in the next major version? It will make this project more stable and developers will feel it as more fair game. :)

**Comment by Twipped** [comment]
👍  to removing third party services

**Comment by isaacs** [comment]
I'm not interested in removing coveralls, for 2 main reasons:
1. It's super useful, and I personally use it and like the results.
2. It works, the module installs reliably and is well maintained.

I don't personally use codecov (nothing against them, I just happen to use coveralls, and it works for me, so I never really dug into any alternatives), and since the maintained module uses a binary dep, it doesn't install reliably on Windows.  Since I don't use it, and don't have a ton of free time, I can't commit to taking over maintenance of it.

**Comment by dotnetCarpenter** [comment]
I use codecov and tap in a few projects and would hate to loose support. But if it is as simple as writing 

```
tap --coverage-reporter=text-lcov | codecov
```

in `posttest`. I don't have any problem with yanking out codecov support.

**Comment by isaacs** [comment]
Shipped in 6.0.0.

**Comment by dotnetCarpenter** [comment]
@isaacs Could you provide information on how to setup codecov in conjunction with `tap --coverage-reporter=text-lcov`? Perhaps here: http://www.node-tap.org/coverage/

**Comment by isaacs** [comment]
@dotnetCarpenter Good idea!  Done and pushed to docs site.
