### ISSUE TITLE
[Feature] Multiple coverage reports

### ISSUE THREAD

**Issue by francisdb** [tapjs/tapjs#274]
We would for out ci build like to have multiple coverage reports as `cobertura` is used by jenkins and `lcov` for badge generation

something like `--coverage-report=lcov,cobertura`

**Comment by isaacs** [comment]
This is tricky, but I can see the value in it.  Patch welcome.

Normally I'd prefer an option that is set multiple times rather than a delimited thing, but in this case, you want to be able to override it.  (For example, if your test script is `tap test/*.js --reporter=spec` you might want to do `npm test -- -Rtap` to show the raw TAP output.)  Also, the values are a discrete set of strings, so delimiting is simple and deterministic.

**Comment by mourner** [comment]
Note that `nyc` already supports multiple reporters (through multiple `--reporter` settings). So as a workaround for now, you could do `nyc --repoter=lcov --reporter=cobertura tap --no-coverage test/*.js`.

**Comment by evanlucas** [comment]
We use somewhat of a workaround with npm scripts. In your package.json, you can do something like this:

```
{
  "name": "test-project",
  "version": "1.0.0",
  "scripts": {
    "test": "tap test --cov",
    "posttest": "tap --coverage-report=text-summary"
  }
}
```

This also has the added benefit of being able to change the default reporter from the cli without changing your package.json: 

#### Example

``` bash
$ npm test -- --coverage-report=html
```

This will generate the html coverage report and then the text-summary

**Comment by cburroughs** [comment]
I'd also like to specify multiple reporters by way of `.nycrc`.  The problem I'm running into is that if `--coverage-report` is on the tap argv, then the invocation of nyc with `[nycBin, 'report', '--reporter', options.coverageReport]` takes precedence with what is in `.nycrc`.  If there was some sentinel value (config? empty string?) for `--coverage-report` that caused the invocation to be `[nycBin, 'report']` then multiple reporters by way of the config file would just work.

**Comment by isaacs** [comment]
This was a breaking change, so I got it into v14.  Now you can specify multiple coverage reports like `tap --coverage-report=html --coverage-report=text` and it'll pass them all to nyc.
