### ISSUE TITLE
Default reporter gets corrupted with 2>/dev/null

### ISSUE THREAD

**Issue by vladikoff** [tapjs/tapjs#275]
### STR

Example: repo https://github.com/vladikoff/issue-tap-reporter-bad-formatting
clone, `npm install` and run `./run.sh`
### Expected (run `node_modules/.bin/tap example-test.js`)

```
node_modules/.bin/tap example-test.js                                               
example-test.js ....................................... 4/4
total ................................................. 4/4

  4 passing (389.584ms)

  ok
```
### Actual (run `./run.sh`)

```
➜  tap-rep git:(master) ./run.sh 
example-test.js ....example-test.js ....................................... 4/4
total ................................................. 4/4

  4 passing (399.759ms)

  ok
```

^ the test name above is repeated

**Comment by isaacs** [comment]
Good catch!  It was deciding to do fancy stdout stuff based on stdout being a tty, but then would only do the `beginningOfLine` ansi code if _both_ stdout and stderr were tty's.  Should be fixed now.

**Comment by vladikoff** [comment]
Thank you!
