### ISSUE TITLE
Handling exceptions when piping

### ISSUE THREAD

**Issue by jtlapp** [tapjs/tapjs#278]
When I pipe `tap` to `tap-parser` and my handler for `tap-parser`'s 'assert' event throws an exception, the behavior of `tap` is unpredictable. Sometimes `tap` bombs out with the exception, sometimes it outputs a new `not ok` assertion reporting the exception. I originally reported some of this behavior as [an issue for `tap-parser`](https://github.com/tapjs/tap-parser/issues/34). In that discussion, @isaacs suggested that the behavior may be reasonable due to `tap`'s need to report errors that occur in a test.

I post this issue asking whether there might be a more robust way to handle these situations. I'm relatively new to `node` and definitely new to `node` streams, but is there any way that the following code might handle the exception that occurs with a `tap-parser` event handler?

``` js
tap.pipe(parser).on('error', function (err) {
    /* either write err to stderr and exit or throw err and not have tap catch it */
});
```

At the moment, this 'error' event is not being called when any of my parser event handlers throws an exception. I'm not sure when it's supposed to be called.

If there's no way to tell `tap` that an exception is a parser failure, there's still a way for `tap` to recognize exceptions that occur in the parser rather than in the test. `tap` could be configured with a `pipeModulePath`, and `tap` could examine the stack of every exception to see whether it originated within this path. The path could be set either to the path for `tap-parser` or to the path of the module that is handling the `tap-parser` events.

I wrote isolated unit tests for both `tap-parser` ([see here](https://github.com/tapjs/tap-parser/compare/master...jtlapp:exception-tests)) and `tap` ([see here](https://github.com/tapjs/node-tap/compare/master...jtlapp:pipe-exceptions)) hoping to catch these guys in the act of mishandling my event handler exceptions, but these tests all pass. There must be an element of timing that comes into play. Sometimes `tap`propagates the exception from the piped stream, and sometimes it just outputs it as a failed assertion. The fact that this behavior is intermittent suggests to me that there might be a way for `tap` to know whether an error occurred within a test or within the piped stream, but I haven't studied the `tap` code.

**Comment by jtlapp** [comment]
fyi, the following also does not catch the parser-thrown exceptions:

``` js
tap.pipe(parser.on('error', function (err) {
    /* either write err to stderr and exit or throw err and not have tap catch it */
}));
```

**Comment by isaacs** [comment]
Yeah, a tap test will catch any errors thrown in the context of one of its tests running, by design.

I'd be open to a way to turn that off, but it's a change, of course.  (And, given the way that Tap interacts with promises and such, it could be challenging to guarantee.)

Another approach would be to run the actual test in a child process, and then pipe the child process output into the parser?  That's how the tap executable formats output in various ways.

**Comment by jtlapp** [comment]
I'm hatching a plan to do this by overriding `tap` methods in my tool. If you like what I come up with, you might think about carrying it into `tap`.
