### ISSUE TITLE
--save and --bail don't combine

### ISSUE THREAD

**Issue by sam-github** [tapjs/tapjs#279]
The combination would be particularly useful. Running all tests with --bail will make them go faster, quitting and writing the failing test file names to the save file immediately, and then  allowing the failing tests to be looked at in more depth.

**Comment by isaacs** [comment]
Hm.  This could be tricky, right?  I guess if a save file is set, then a bailout should mean that all subsequent tests get written to the file?  That would make these two things work well together, I suppose.
