### ISSUE TITLE
Bailout within tearDown() at wrong indentation

### ISSUE THREAD

**Issue by jtlapp** [tapjs/tapjs#291]
If you think this is important, I can provide a unit test. Given the following:

``` js
t.tearDown(function ()) {
    if (/* some condition*/)
        t.bailout("some reason");
}
```

The resulting "Bail out!" line is one level more deeply nested than a simple `t.bailout("reason")`. `tap-parser` interprets the properly indented bailout as a bailout, but it interprets the too-deeply nested bailout as an "extra" line. `tap` reproduces the bailout line at the left margin, which `tap-parser` does register, but my code will have to look for the extra line to learn whether the bailout occurred within the prior test or in code subsequent to the test.

My use case is obscure. I allow the user to specify the maximum number of failing root-level subtests that may run, and I bail after that. However, there may be more reasonable use cases, such as when `tearDown()` is unable to perform a proper cleanup.

I can look for the "extra" line, but I thought I'd let you know in case you think this is a bug worth fixing.

(Actually, there's an easy fix for me. I can just match the bailout reason and know which test level caused it. So this bug report is just FYI for you.)

**Comment by isaacs** [comment]
This is a bit weird to me, because tearDown means the test is over, so a bailout seems unusual. But I'll try to dig into it and see if I can wrap my head around what you're saying here.

**Comment by jtlapp** [comment]
Yeah, the test is over, but the test run may not be. If you want to know what killed the test run, it would be the test that failed to cleanup. But I've got my workaround, so I'm happy.

**Comment by isaacs** [comment]
Just to make sure I understand you, here's a full example of what I think you're saying:

``` js
// test/test/bail-teardown.js
var t = require('../..')

t.pass('this is fine')
t.test(function child (t) {
  t.pass('child test point')
  t.tearDown(function () {
    t.bailout('i did not want to be torn down')
  })
  t.end()
})
```

```
$ node test/test/bail-teardown.js
TAP version 13
ok 1 - this is fine
# Subtest: child
    ok 1 - child test point
    1..1
ok 2 - child # time=8.055ms

    Bail out! # i did not want to be torn down
Bail out! # i did not want to be torn down
```

So, from a "TAP specification" point of view, it _is_ a "non-TAP line", which the parser emits as an `'extra'` event, and most formatters just dump to stdout.

The event gets proxied up to the top level, so you do get that the thing bailed out, and the correct behavior happens (a full stop of the test run).

It sounds like you're asking for the `Bail out!` line to be included in the child test block.

However, that's not possible.  How can TAP put data into the stream at that point, without knowing the future?  At least based on my understanding of temporal mechanics, we'd have to buffer _literally everything_, and then reconstruct the output based on what happened where.  I'm not willing to do that, because it involves way too much bookkeeping and prevents streaming the test output.

I think I've gotta just say that this is working as designed.

**Comment by jtlapp** [comment]
Try replacing your call to `t.pass()` with `t.fail()` and see if you're still happy with the output.  `tap-parser` properly interprets the output on passing but not on failing.

It does appear that the spec only calls for "Bail out!" at the left margin. Your module is providing the extra information of where the bailout occurred on passing but not on failing. I like the information. It appears to just be an inconsistency in `tap`.

**Comment by jtlapp** [comment]
Ah poo. I'm only seeing this difference in `tap-parser` behavior in my `tap` monkey patch. I should have isolated this test at the start. Sh*t. Sorry about that.

**Comment by jtlapp** [comment]
Now I'm not seeing it. Looks like I didn't identify the specific scenario carefully enough. Looking into it...

**Comment by jtlapp** [comment]
I cannot reproduce the problem now. I was seeing `tap-parser` output multiple bailout events. Now I'm only seeing the extra before the bailout. I'm not sure what has changed. I was only bailing on test failure, and it appeared to have to do with the deeper nesting of a bailout after a failure.

But I agree that this was never an issue of conformance with the TAP spec. I was just seeing an inconsistency in either `tap` or `tap-parser`. I'll pipe up if I see it again.

**Comment by jtlapp** [comment]
I don't know whether you care, but `tearDown()` is not called on bailout. Given:

``` js
var tap = require('tap');

tap.tearDown(function () {
    console.log("clean up");
});

tap.pass("assert 1");
tap.bailout("in tap root");
tap.pass("assert 2");
```

I get:

```
TAP version 13
ok 1 - assert 1
Bail out! # in tap root
```

In my case, I wanted `tearDown()` to send a message to the parent process rather than to write to stdout, but that's not happening either.

**Comment by isaacs** [comment]
Yeah, bailout means "exit the process immediately, do not pass go, do not collect $200."  It's _intended_ to be destructive and prevent any further action.  Everything in tap (including teardown) just aborts as fas as possible when bailout happens, and in fact, the root test object will even process.exit(1) and forcibly kill any child test processes when it gets a bailout.  That's by design.

**Comment by jtlapp** [comment]
Okay thanks. I'll work around it. I'm essentially adding features to `tap` that it was not designed to have, like bailing after the Nth failed root-level subtest.

**Comment by isaacs** [comment]
Right now it does have a `bailOnFail` thing that bails out on the first failed test.  Is that kind of what you're looking for?

**Comment by jtlapp** [comment]
Yeah, I know about that. I take advantage of that with my option `-b`. But `-b2` fails after the 2nd failing subtest (more generally `-bN`). I'm making a subtest-centric tool that facilitates debugging test suites that are organized around subtests. I think the `tap` runner is the better option for baseline testing, regardless. My tool has become quite a pretty-printer, particularly because I find YAML less than ideal (despite being good friends with one of YAML's authors).

Thank you for the tip, though!

**Comment by jtlapp** [comment]
I think I need to dive into the `tap` code. When is `tearDown()` called for `tap` as a whole? Running the following:

``` js
var tap = require('tap');

tap.tearDown(function () {
    console.log("bye bye tap");
});

setTimeout(function() {
    console.log("timed out");
}, 4);
```

I get this:

```
TAP version 13
1..0
# time=23.949ms
bye bye tap
timed out
```

Sometimes `tap` tears down before I've `require`d the file that contains the tests!

(And just to be clear, this even happens within a node fork, which doesn't exit until explicitly told to do so. `tap` tears down before the process exits.)

**Comment by jtlapp** [comment]
Looks like I need to turn autoend off. Can I do that and still use tearDown?

Or maybe I just need to register tearDown after loading the tests. Seems like potential for a race condition there.

That solved the problem. But am I setting myself up for the possibility that all the tests run and finish and tap tears down before my tearDown handler gets installed?

Will `tap` only ever complete on the next tick (or later)? That would prevent the race condition.

Never mind. I don't see how you could possibly expect to wait for all tests to register unless you could only complete on the next tick or later, so I think I'm good.
