### ISSUE TITLE
Get access to child proc from `t.spawn`

### ISSUE THREAD

**Issue by isaacs** [tapjs/tapjs#292]
Maybe `t.spawn` should take a callback that gets the child process object, so it can be interacted with?

**Comment by adi-mat** [comment]
@isaacs  Any updates on this? I am forking a child process from within a "tap.test" block. 

Something like this:

                  child = fork('worker.js', args, {silent:true, cwd:path});
                  child.stdout.on('data', function(data){
                           console.log(data.toString());
                   });

Nothing gets printed out from the above code. Also, i don't hit the end of the tap block. it just times out after 30s. Any help would be much appreciated. Thanks.

**Comment by isaacs** [comment]
@aditya-matukumalli I don't think your question is related to this issue.

Without knowing what's in `worker.js`, I couldn't begin to tell you why you aren't getting output from it.

**Comment by isaacs** [comment]
No, actually, this is a bad idea.
