### ISSUE TITLE
Reports 1 failing even all tests passed

### ISSUE THREAD

**Issue by playground** [tapjs/tapjs#293]
Not sure why it's reporting fail.  Here is my test repo https://github.com/playground/sample

Here is my test server.js

``` javascript
// server.js
var express = require('express');
var app = express();
var users = ['John', 'Joe', 'Moe'];

app.get('/api/users', function (req, res) {
  res.json(users);
});

var port = process.env.PORT || 3000;
app.listen(port, function () {
  console.log('Server running on port %d', port);
});
module.exports = app;
```

``` js
// user.test.js

var request = require('request');

var app = require('../server');

var test = require('tap').test;

test('First test!', function (assert) {
  //assert.plan(1);

  request.get('http://localhost:3000/api/users', function(err, res) {
    let json = JSON.parse(res.body);
    assert.equal(json[0], 'John', 'name should be John');
    //assert.equal(json[1], 'Joe', 'name should be John');
    assert.endAll();
  });
});

test('Second test!', function (assert) {
  //assert.plan(1);

  request.get('http://localhost:3000/api/users', function(err, res) {
    let json = JSON.parse(res.body);
    assert.equal(json[0], 'John', 'name should be John');
    //assert.equal(json[1], 'Joe', 'name should be Joe');
    assert.endAll();
  });
});
```

```
tap --cov -R=spec test/*.test.js --timeout=5


test/user.test.js
Server running on port 3000
  First test!
    ✓ name should be John

  Second test!
    ✓ name should be John

  1) timeout!

  2 passing (5s)
  1 failing

  1) test/user.test.js timeout!:
     timeout!


-----------|----------|----------|----------|----------|----------------|
File       |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-----------|----------|----------|----------|----------|----------------|
All files  |      100 |      100 |      100 |      100 |                |
 server.js |      100 |      100 |      100 |      100 |                |
-----------|----------|----------|----------|----------|----------------|
npm ERR! Test failed.  See above for more details.
```

**Comment by isaacs** [comment]
The problem is that it's timing out because your server never closes.

You can add a final `t.test('shut down server', function (t) { server.close() })` or something, or (if you prefer not to have to put it at the bottom of the file) you can do `t.tearDown(function () { server.close() })`.

If you want to spin the server up in one test file, run a bunch of tests against the server (without starting and stopping it in each test file, which can be slow), you can use https://github.com/tapjs/t-up.  Of course, this means that you have to order your tests, but you can have a `test/00-setup.js` that starts the server, and then a `test/zz-teardown.js` that kills it.  Check out the examples in the t-up docs for more guidance.

**Comment by playground** [comment]
Thanks @isaacs.

Is there an event in node-tap that I can listen to when all tests have finished running?

**Comment by isaacs** [comment]
@playground That's exactly what `tap.tearDown(function () { ... })` does.  Or you can put your teardown logic in a final `t.test(...)` block, since they are run sequentially.

**Comment by playground** [comment]
Closing the server after every test works but that's very slow.   Shut down server at the end of each file or using t-up and shut down the server after all tests are run, each test finished with 1) timeout! failing error.

**Comment by isaacs** [comment]
Not after every test block, just at the end of every test file.

The readme in https://github.com/tapjs/t-up explains what to do pretty clearly.  You won't get timeouts if you do it that way, because the server is not being started in each test, only once in the `00-start.js` test.

**Comment by playground** [comment]
Thanks @isaacs, got it working.  turns out I need to createServer by passing in express app and issue the done() after server.listen such as this

  var server = http.createServer(app);
  server.listen(port, () => {
    console.log('Server listening on port', port, '!');
    done();
  });
