### ISSUE TITLE
Running tap via npm test and node_modules/.bin/tap yeilds different result

### ISSUE THREAD

**Issue by dotnetCarpenter** [tapjs/tapjs#297]
### Step to reproduce:
1. Clone `https://github.com/dotnetCarpenter/decorators.git && cd decorators`
2. Run `npm i && npm run build`
3. Run `npm test`
4. Run `node test/cache.es6`

Examine the output of  step 3 and 4. In step 3, no tests are run. Step 4 run two tests.
### Expected output

```
TAP version 13
# Subtest: caching
    1..2
    ok 1 - a == b should be true (cached)
    ok 2 - should not be equal
ok 1 - caching # time=20.017ms

1..1
# time=66.519ms
```
### Actual output

```
> tap test/cache.es6

total ................................................. 0/0

  0 passing (101.686ms)

  ok
```
### Versions

TAP: 7.0.0
node: v6.2.0
npm: 3.10.6
OS: Linux Ubuntu 16.04.1 LTS

**Comment by isaacs** [comment]
The issue is that `.es6` isn't treated specially like `.js` is, and tap doesn't know that it needs to be run with Node.

Add `#!/usr/bin/env node` to the top of the file, and `chmod 0755 test/cache.es6` so that tap can execute it directly.  Or just give it a name ending in `.js` :)

**Comment by dotnetCarpenter** [comment]
Thanks @isaacs! Both solutions work like a charm.
