### ISSUE TITLE
Wrong documentation for coverage with codecov.io

### ISSUE THREAD

**Issue by dotnetCarpenter** [tapjs/tapjs#298]
I just learned that you can not write `"posttest": "tap --coverage-report=lcov | codecov"` as the [docs](http://www.node-tap.org/coverage/#uploading-coverage-to-other-services) suggest.

You have to write **`"posttest": "tap --coverage-report=lcov > coverage.json && codecov"`**

**Comment by dotnetCarpenter** [comment]
Ping @stevepeak

**Comment by isaacs** [comment]
That's a docs bug. I'll fix it soonish unless someone else beats me to a pr :)

**Comment by dotnetCarpenter** [comment]
@isaacs hang on.
I might have a PR for codecov that enable piped input.

Right now the docs says
`tap --coverage-report=lcov | codecov` which should be `tap --coverage-report=text-lcov | codecov` if piping is supported by _codecov-node_.

What would work now is: `tap --coverage-report=lcov && codecov` - codecov will find the `coverage/lcov.info` file and upload it.

**Comment by isaacs** [comment]
@dotnetCarpenter Gotcha.  i'll update the docs now to what works.  It's easy enough to change again later if there's a better way :)

**Comment by isaacs** [comment]
71b8728a55c135f1bd30c0befdaf8f5bbe7a20ea

**Comment by stevepeak** [comment]
Hey @isaacs and @dotnetCarpenter we are adding partial line coverage support this week.

![image](https://d3vv6lp55qjaqc.cloudfront.net/items/2Q1z1Y3e2b1w2S1M2N1V/Screen%20Shot%202016-08-31%20at%209.45.49%20AM.png?X-CloudApp-Visitor-Id=1462437&v=7ecd41c9)

> https://cl.ly/3I0S172c4736

This requires the `coverage.json` file **only** to be uploaded. Can we arrange this?

**Comment by dotnetCarpenter** [comment]
@stevepeak I assume you mean the `coverage.json` that `istanbul cover` produce. But I don't know what is the difference between _lcov_ and _coverage.json_, besides the data format. Do you mean that you only accept JSON or that the data quality differs between [coverage.json](https://github.com/gotwarlost/istanbul/blob/master/coverage.json.md) and _lcov_?

I'm asking this because I got code that takes _what-ever_ is piped to `codecov-node` and append it to the `upload` variable. E.g. `upload += '# path=piped\n' + args.options.pipe.join('') + '\n<<<<<< EOF\n';`

**Comment by stevepeak** [comment]
> the difference between lcov and coverage.json, besides the data format

The `json` document provides column aware coverage data which enables us to provide higher detailed coverage overlay and more accuracy in detecting partial line coverage (as seen in screenshot above). The `lcov` is simple `line:cov` data and is not column aware.

> Do you mean that you only accept JSON or that the data quality differs between coverage.json and lcov?

Yes. I'm looking into ways of ignoring the `lcov` data entirely as it could override the column aware data. This is still yet to be determined, but we only need the `json` file in the near future.

**Comment by dotnetCarpenter** [comment]
Hmmm.. Not sure how `tap` sends arguments to `nyc`. But if the reporter is `json` and the [file is `-`](https://github.com/istanbuljs/istanbul-reports/blob/master/lib/text-lcov/index.js#L9) then I think we can pipe JSON to codecov.

Something like: `tap test/* --coverage-report=json --file=-` but it doesn't work.

**Comment by stevepeak** [comment]
It's ok to produce the lcov and json reports. We just prefer the json reports for uploading.

Still working on a way to ignore lcov when json is found.
