### ISSUE TITLE
Please add a --stdout and --stderr to the tap runner

### ISSUE THREAD

**Issue by mcavage** [tapjs/tapjs#3]
It's _really_ useful to be able to get my console.log()'s to show up when writing tests, until stuff is in a "steady state".

**Comment by dominictarr** [comment]
essential!

+1

**Comment by timoxley** [comment]
you can kind of get around this by exporting an environment var on your shell:

`export TAP_DIAG=1`

and you'll get the truncated console output as well as some other diagnostic info.

**Comment by timoxley** [comment]
also, another BS workaround is to:

`throw util.inspect(someObject)`

not remotely a good solution but is currently getting me the object inspection I need

**Comment by mvolkmann** [comment]
Setting TAP_DIAG works, but it of course causes much more output than is desired.
The inability to use console.log in test code and in the code being tested is a serious issue for debugging!

**Comment by konobi** [comment]
+1

**Comment by jdeal** [comment]
+1

**Comment by dominictarr** [comment]
I've added a `--debug` option which pipes stderr through from your tests.

+1 these two pull requests:

https://github.com/isaacs/tap-runner/pull/4
https://github.com/isaacs/node-tap/pull/15

**Comment by kusor** [comment]
+1

**Comment by autarch** [comment]
Should this even require an option? I think that stderr should probably just be emitted as is.

For debugging, it'd be nice to have a test.diag() function which outputted TAP diagnostics (http://testanything.org/wiki/index.php/TAP_specification#Diagnostics)

This is somewhat separate from outputting stderr, though.

**Comment by jeffbski** [comment]
I also have a pull request which forwards stderr all the time and includes a test to verify.

https://github.com/isaacs/node-tap/pull/31

FYI. Also for any of those who need this asap, you can use my tap runner (tapr) which provides stderr and stdout, optional colorized output, and a cleaner assert formatting. It was based on the original tap runner and still uses all other original tap components just with a customized runner. There are some screenshots on my github page https://github.com/jeffbski/tapper and it is available in npm as tapr
