### ISSUE TITLE
t.plan() should not hang indefinitely when actual number of tests is less than expected

### ISSUE THREAD

**Issue by sdotson** [tapjs/tapjs#314]
This is a major pain point for me as I'm troubleshooting test files. In addition, when the expected number of tests is less than the actual number, the results just state "Expected x but got x + 1". This result should state the actual number of tests carried out.

**Comment by isaacs** [comment]
Can you provide a script that does the behavior you're describing?  I'm having trouble understanding the issue, but it certainly sounds weird.  Thanks.

**Comment by sdotson** [comment]
@isaacs . I jumped the gun on blaming `tap` for the error I was seeing. The tests I was running were within a framework my employer created using tap, tape, co-tape, and other libraries. When I tried to replicate using just tap, things looked fine. The error is elsewhere.

Apologies for the false alarm. Closing.
