### ISSUE TITLE
Infer test runner timeout(s) from test timeouts

### ISSUE THREAD

**Issue by jfhbrook** [tapjs/tapjs#316]
I'm working on adding docker support to wzrd.in and spinning up a fresh docker image takes quite a bit of time! [I had to add mad timeouts to the test](https://github.com/jfhbrook/wzrd.in/blob/457aa0f8c3b3184bfa659b8dde532325ff0a5528/test/builder.js#L22). However, I _also_ had to add those timeouts a [second](https://github.com/jfhbrook/wzrd.in/blob/457aa0f8c3b3184bfa659b8dde532325ff0a5528/package.json#L43) (actually [3rd](https://github.com/tapjs/node-tap/issues/317)) time to the command being used to run the tests!

It would be pretty dope if I could set the timeouts in my test only, and have the test runner infer the total expected timeout and adjust accordingly.

**Comment by isaacs** [comment]
I'd like to put this in the TAP format itself, actually.  So maybe when a child test does `t.setTimeout(30)` it actually outputs something in the text stream telling the parent test about it.  Then also the runner can also see that know "Ok, I'm going to have to wait a bit longer."

Or maybe just kind of infer this every time a child test happens?  It's already a bit silly to have each child test get a timeout of 30s when the file as a whole only has 30s.

**Comment by jfhbrook** [comment]
Yeah, picking it up from the test file's output works for me. Though, I kinda need the child test bit too.

**Comment by isaacs** [comment]
Right, it'd cover that as well.  If a tap object spawns a child proc, it has to update its timeout based on the stdout, and if it runs a child test in the current process, then it'd do the same thing based on the child test object's stream.  I want to talk to some other TAP implementers and see if there's any opinions around how best to do this.
