### ISSUE TITLE
pipe prematurely terminates when throttling at highwater mark

### ISSUE THREAD

**Issue by jtlapp** [tapjs/tapjs#322]
I've confirmed this in tap@6.3.0 and tap@7.1.2. I don't know if this is something you care to fix, but I'm reporting it just in case. I have a workaround, though it's not ideal.

The following code bombs for me starting at a string size of 16k. The code works if you uncomment the [highWaterMark](https://nodejs.org/api/stream.html#stream_buffering) option. Writable streams [default the highwater mark at 16k](https://nodejs.org/api/stream.html#stream_constructor_new_stream_writable_options).

UPDATE: This code works if you comment out `tap.end()`, so it looks like you're throttling but still prematurely killing the stream. Recall that I have to call 't.end()` per our discussion #288.

``` js
var STRING_SIZE_KB = 16;
var tap = require('tap');
var Writable = require('stream').Writable;

tap.pipe(new Writable({
    write: function(chunk, encoding, done) {
        console.log(chunk.toString());
        done();
    },
    //highWaterMark: (STRING_SIZE_KB + 1)*1024
}));

var bigString = makeLongString(STRING_SIZE_KB, 1023);
tap.equal(bigString, '');

tap.end();

function makeLongString(lines, columns) {
    var line = '+'.repeat(columns) +"\n";
    return line.repeat(lines);
}
```

Here is the exception:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:166:12)
    at Writable.write (_stream_writable.js:217:5)
    at Test.ondata (_stream_readable.js:556:20)
    at emitOne (events.js:96:13)
    at Test.emit (events.js:188:7)
    at Test.Readable.read (_stream_readable.js:382:10)
    at flow (_stream_readable.js:762:34)
    at Writable.<anonymous> (_stream_readable.js:624:7)
    at emitNone (events.js:86:13)
    at Writable.emit (events.js:185:7)
    at onwriteDrain (_stream_writable.js:371:12)
    at afterWrite (_stream_writable.js:359:5)
    at _combinedTickCallback (internal/process/next_tick.js:80:20)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:577:11)
    at run (bootstrap_node.js:352:7)
```

I'm writing `addAssert()` assertions specifically for handling large documents. In particular, I'm presenting to `tap` the formatted subsets of large documents that must show in the TAP output.

My stopgap solution is to set an upper limit on document size and base my highwater mark on that. Ideally, the upper limit would be whatever node is willing to allocate.

**Comment by jtlapp** [comment]
I updated the above text for a discovery about calling `t.end()`, in case you read it before my update.

**Comment by jtlapp** [comment]
The problem is infrequent in less-contrived circumstances, seeming to take a special situation to reveal itself.

**Comment by jtlapp** [comment]
FYI, I've just published my test assertion extensions as [`crumpler`](https://github.com/jtlapp/crumpler), designed to work especially well with [`subtap`](https://github.com/jtlapp/subtap). Thank you for all your help getting here!

**Comment by isaacs** [comment]
This should no longer be possible, since tap uses minipass rather than builtin streams, so no high/low water marks.
