### ISSUE TITLE
Assertion for promise rejection

### ISSUE THREAD

**Issue by tnguyen14** [tapjs/tapjs#324]
Since there is `t.throws` to check a function that expects to throw, does it make sense to add an assertion that would check for a promise that will reject, with an expected error?

**Comment by isaacs** [comment]
Sure, this is a good idea.  Patch welcome.

Maybe `t.rejects(promise, [expected error], [extra], [message])`?  Should be easy enough to add to `lib/asserts.js`.  Tests required, docs should be added to the `gh-pages` branch (in a separate PR, of course.)

**Comment by isaacs** [comment]
Oh, this is actually pretty tricky, because asserts are synchronous, and promise rejections are async.

Consider this:

```js
t.test('promise rejection', t => {
  var p = new Promise((resolve, reject) => reject(new Error('pwn')))
  t.rejects(p)
  t.end()
})
```

which is kind of like doing this:

```js
t.test('promise rejection', t => {
  var p = new Promise((resolve, reject) => reject(new Error('pwn')))
  p.then(() => t.fail('expected to reject'))
  p.catch(() => t.pass('promise rejected as expected'))
  t.end()
})
```

Because Promises _always_ defer their resolution/rejection, the order of operations becomes:

1. create promise
2. test ends with `t.end()`
3. promise resolution/rejection (Error: assertion after test end)

Of course, this _could_ be done by doing:

```js
t.test('promise rejection', t => {
  var p = new Promise((resolve, reject) => reject(new Error('pwn')))
  t.test('reject the promise', t => {
    t.plan(1)
    return p.then(() => t.fail('expected rejection')).catch(() => t.pass('expected rejection'))
  })
  t.end()
})
```

The only result will be that it'll look like a very short subtest in the output.  So instead of TAP output like this:

```tap
ok 1 - reject the promise
1..1
```

it'll look like this:

```tap
# Subtest: reject the promise
    1..1
    ok 1 - expected rejection
ok 1 - reject the promise # time=2.291ms

1..1
```

**Comment by tnguyen14** [comment]
Thanks @isaacs!

**Comment by robophil** [comment]
@isaacs ,
calling `t.end()` would result in `not ok test after end() was called` being called

**Comment by isaacs** [comment]
@robophil `t.rejects` is implemented in tap now. Are you seeing the error you describe? Can you share the test that’s doing that?

**Comment by robophil** [comment]
was doing something like this
```javascript
test('can do something', t => {
    myPromise()
    .then((result) => {
      t.deepInequal(result.counts[productWithBatchId], doc.counts[productWithBatchId], 'product deleted')
    })

      t.end()
}
```
Just like what was done above, in this [comment](https://github.com/tapjs/node-tap/issues/324#issuecomment-309231142)
```javascript
t.test('promise rejection', t => {
  var p = new Promise((resolve, reject) => reject(new Error('pwn')))
  t.test('reject the promise', t => {
    t.plan(1)
    return p.then(() => t.fail('expected rejection')).catch(() => t.pass('expected rejection'))
  })
  t.end()
})
```

that would only work when
```javascript
     t.deepInequal(result.counts[productWithBatchId], doc.counts[productWithBatchId], 'product deleted')
      t.end()
```
as you can see are called together under the `then`

**Comment by robophil** [comment]
Hey @isaacs, i'm doing something like this using `t.rejects`, which works fine but faces a `not ok 2 - test unfinished`.

> promise resolution/rejection (Error: assertion after test end)

How do i end the test when using `t.rejects`?

```javascript
test('returnsAPromise()', (t) => {
    const clock = lolex.install({
      now: 0,
      toFake: ['Date']
    })

    t.test('expect promise rejection on non producId', t => {
      return t.rejects(returnsAPromise(), {}, 'pass a productId to add to this shipment', {})
    })
    clock.uninstall()
    t.end()
  })
```

**Comment by robophil** [comment]
Was finally able to get this working

```javascript
test('should reject', (t) => {
    t.rejects(returnsAPromise(), {}, 'cannot add shipment when missing a valid snapshotId', {})
    t.end()
})
```
