### ISSUE TITLE
Usage with async/await

### ISSUE THREAD

**Issue by raphaelokon** [tapjs/tapjs#332]
Hi there.
Is there a documentation how to use `node-tap` with async/await? I couldn't find anything except an old issue that was marked as resolved albeit didn't solve my question.

Thanks.

**Comment by ORESoftware** [comment]
async/await is an ES7 feature - to be able to use it, you will need to transpile with Babel. I doubt node-tap supports Babel transpilation, you have do that yourself. AVA does support Babel (in fact you must use Babel with AVA), so maybe check that out.

Just FYI you can achieve async/await behavior with ES6 generators + promises. async/await is just syntactic sugar over a special combination of ES6 generators/promises. I'd recommend avoiding transpilation and doing your own research to figure out how to implement async/await using promises + generators.

**Comment by raphaelokon** [comment]
> to be able to use it, you will need to transpile with Babel.

Not true. I am using async/await in Node v7 (behind a flag) and with `async-to-gen` for v4/v6.

> Just FYI you can achieve async/await behavior with ES6 generators + promises

I know that I can use generators + promises to augment the behavior – I explicitly referred to async/await.

**Comment by ORESoftware** [comment]
well then you got it all figured out :)

**Comment by raphaelokon** [comment]
The Node v7 + node-tap part is still open where I do not transpile :-) Or am I missing something here?

**Comment by ORESoftware** [comment]
Node 7 came out like 2 weeks ago, do you really think library support for a library as "old-school" as this one will be ready?

read this article https://www.promisejs.org/generators/

you can use this methodology to avoid transpilation if you want

try this:
http://stackoverflow.com/questions/36196608/difference-between-async-await-and-es6-yield-with-generators/36245227#36245227

**Comment by raphaelokon** [comment]
> Node 7 came out like 2 weeks ago, do you really think library support for a library as "old-school" as this one will be ready?

No. This was not my question. I didn't asked for readiness or an update on the lib itself (or whatever you imply here). 

Also thanks for your articles … I am well aware of these concepts.

The good news are that I got it working with Node v7.
