### ISSUE TITLE
Drop support for unsupported nodes

### ISSUE THREAD

**Issue by isaacs** [tapjs/tapjs#343]
Currently, tap supports all nodes v0.10 and above.  There are some `skip` tests to work around shortcomings in node v0.x, but the bigger issue is that a lot of `.bind(this)` stuff could be removed in the codebase if we moved to 4.x and above.  (Maybe also use proper classes?)

This is a breaking change, so can't happen before tap v11.  Opinions?

**Comment by martinheidegger** [comment]
This will make running tap in the browser even harder, right? Particularly for older tests (where it would count)

**Comment by isaacs** [comment]
Aren't most browsers evergreen these days? They probably have the features I want. If not, babel or whatever works fine.

**Comment by isaacs** [comment]
And "older tests" are presumably not using tap v11. Semver!
