### ISSUE TITLE
reading TAP data from stdin

### ISSUE THREAD

**Issue by ericnewton76** [tapjs/tapjs#349]
Just updated tap to 10.something  Running on windows 10.  Node v4.4.7 

Running `npm test` on log4js project at https://github.com/nomiddlename/log4js.git 

I get: `Reading TAP data from stdin (use "-" argument to suppress)`

does this just mean I need to update package.json scripts test to have "-"?

**Comment by ericnewton76** [comment]
Update: just added - to end up test script:
```
  "scripts": {
    "clean": "find test -type f ! -name '*.json' ! -name '*.js' ! -name '.eslintrc' -delete && rm *.log",
    "lint": "eslint lib/ test/",
    "prepush": "npm test",
    "commitmsg": "validate-commit-msg",
    "posttest": "npm run clean",
    "pretest": "eslint lib/**/*",
    "test": "tap 'test/tap/**/*.js' -",
    "coverage": "tap 'test/tap/**/*.js' --cov",
    "codecov": "tap 'test/tap/**/*.js' --cov --coverage-report=lcov && codecov"
  },
```

but tap still pausing waiting for stdin

**Comment by ericnewton76** [comment]
issue seems to be the single quotes surrounding the path spec

whats the correct cross platform way to do this?

btw, i was able to fix by changing any single quotes to double quotes,
including the test/coverage/codecov scripts

updated scripts section in packages.json looks like this:
```
  "scripts": {
    "clean": "find test -type f ! -name \"*.json\" ! -name \"*.js\" ! -name \".eslintrc\" -delete && rm *.log",
    "lint": "eslint lib/ test/",
    "prepush": "npm test",
    "commitmsg": "validate-commit-msg",
    "posttest": "npm run clean",
    "pretest": "eslint lib/**/*",
    "test": "tap \"test/tap/**/*.js\"",
    "coverage": "tap \"test/tap/**/*.js\" --cov",
    "codecov": "tap \"test/tap/**/*.js\" --cov --coverage-report=lcov && codecov"
  },
```

**Comment by scriptdaemon** [comment]
`Reading TAP data from stdin (use "-" argument to suppress)` will happen if no tests are run. Since you had single quotes before, glob (internally) wasn't working as intended (i.e. it would unpack in the shell before passing to `tap`) and thus `tap` wasn't finding your tests. Since you switched to double quotes, the full string (`"test/tap/**/*.js"`) gets passed to `tap` and `tap` can now find your tests.

**Comment by isaacs** [comment]
Are you having this problem on Windows?

Single-quotes are not "quotes" to cmd.exe.  They're just characters.  So it was looking for a file with the name `'test/tap/**/*.js'`.  This is especially interesting when there's a space in there, so `'foo bar.js'` on cmd.exe would be two args, `'foo` and `bar.js'`.

Seems like you've got it sorted now, so I'm gonna close this. :)
