### ISSUE TITLE
Support table syntax

### ISSUE THREAD

**Issue by subodhpareek18** [tapjs/tapjs#350]
Tools like `nyc` generate a codecoverage report at the end of their tests. For an otherwise TAP compliant output the table is something that currently isn't parsed.

Not sure if tables are a part of TAP, it would be great if they were.

```
------------|----------|----------|----------|----------|----------------|
File        |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
------------|----------|----------|----------|----------|----------------|
All files   |      100 |      100 |      100 |      100 |                |
 filters.js |      100 |      100 |      100 |      100 |                |
 runner.js  |      100 |      100 |      100 |      100 |                |
 sorts.js   |      100 |      100 |      100 |      100 |                |
------------|----------|----------|----------|----------|----------------|
```

**Comment by isaacs** [comment]
Nope, tables aren't part of the TAP format, and since they're very _clearly_ part of the TAP format, they're ignored as "extra" output unless `pragma +strict` is enabled.
