### ISSUE TITLE
Unexpected promise behaviour

### ISSUE THREAD

**Issue by someone235** [tapjs/tapjs#351]
The output of this code is `hello`, while I would expect it to be `world`. Can you please explain why?

    var tap = require("tap");
    var test = tap.test;
    
    test('test', function () {
        return Promise.reject();
    })
    .then(() => console.log('hello'))
    .catch(() => console.log('world'));

**Comment by isaacs** [comment]
Good question!

The promise returned by `t.test()` is not the same promise that is returned by the callback passed to `t.test()`.

The promise returned by `test()` always resolves successfully, when the test is completed.

If the callback to `test()` returns a promise, then the test is considered complete when that promise either resolves or rejects.  If the promise rejects, then the test fails, but the test itself was still _run_ successfully.

In other words, `t.test()` and `promise.then()` are very different animals.

If this was not the case, then you couldn't have a test fail without aborting the whole sequence!  Consider this:

```js
var t = require('tap')
t.test('foo passes', t => Promise.resolve('foo'))
.then(t => t.test('bar fails', t => Promise.reject(new Error('bar'))))
.then(t => t.pass('this is fine'))
```

The expected output is:

```tap
TAP version 13
# Subtest: foo passes
    1..0
ok 1 - foo passes # time=5.01ms

# Subtest: bar fails
    not ok 1 - bar
      ---
      at:
        line: 3
        column: 52
        file: t.js
        function: Test.t.test.t
      test: bar fails
      source: |
        .then(t => t.test('bar fails', t => Promise.reject(new Error('bar'))))
      ...
    
    1..1
    # failed 1 test
not ok 2 - bar fails # time=15.244ms

ok 3 - this is fine
1..3
# failed 1 of 3 tests
# time=29.272ms
```

If a failing test were a rejected promise, then the first failing test encountered would abort the entire suite.

Note that you _can_ do this in TAP-lingo if you want that behavior, but setting `-b` in the tap command, or `TAP_BAIL=1` in the environment.  Then you get this output:

```tap
TAP version 13
# Subtest: foo passes
    1..0
ok 1 - foo passes # time=4.15ms

# Subtest: bar fails
    not ok 1 - bar
      ---
      at:
        line: 3
        column: 52
        file: t.js
        function: Test.t.test.t
      test: bar fails
      source: |
        .then(t => t.test('bar fails', t => Promise.reject(new Error('bar'))))
      ...
    
    Bail out! # bar
Bail out! # bar
```

So, this is working as designed.
