### ISSUE TITLE
Option to tee output to file

### ISSUE THREAD

**Issue by gibfahn** [tapjs/tapjs#352]
If I'm testing npm modules, I nearly always want to run tests differently through CI compared to running them manually. Manually I just want the `classic` reporter and nothing else, so `npm test` is set up to do that. However in CI, I want to use the TAP or Junit reporters, and also tee the output to a file. 

I can get the first with `TAP=1 npm test` (or `npm test -- --reporter=tap`), but I don't know of a good cross-platform way to tee output to a file. Is this something you'd be open to adding? Maybe something like `TEE=test-output.tap npm test` or `npm test -- --tee=test-output.tap`?

**Comment by gdams** [comment]
this would be a really useful feature

**Comment by isaacs** [comment]
How about the common `-o|--output` with a file name? That would only write the TAP, regardless of the reporter.

**Comment by gibfahn** [comment]
>How about the common -o|--output with a file name?

Sounds good to me
