### ISSUE TITLE
Option to output separate .tap file for every test file

### ISSUE THREAD

**Issue by JimtotheB** [tapjs/tapjs#355]
When passing a file glob, or multiple file globs it would be nice to be able to specify a directory to output individual .tap output files to. Possibly just use <incoming file name>.tap or if collisions are a worry <incoming file name>_<index>.tap?

**Comment by isaacs** [comment]
I would just add `.tap` to the filename, probably.

What option would you use to specify the output folder?  (And you know that there's already a `-o` option to output the raw TAP for the entire run?)

**Comment by JimtotheB** [comment]
I'm already using the -o switch, to feed to the Jenkins tap plugin. Having hundreds of tests slammed into its display all at once is pretty overwhelming. It just looks for files in a specified directory and creates a new entry for every one it finds, which obviously is easier to parse when there are a lot of tests.

What about.

```shell
  -O<path>
  --output-dir=<path> 
```

This kind of conflicts with the `-c` switch, with  `-C` negating it.

**Comment by isaacs** [comment]
Wait a sec, every file under test, or every test file?

Otherwise, yes, an output-dir would be fine.  `-O` is already used for `--only` though.  Maybe `-D`? (for `dir`)

**Comment by isaacs** [comment]
Done in v13.  `-d` or `--ouput-dir`.
