### ISSUE TITLE
Can you provide typings for TypeScript

### ISSUE THREAD

**Issue by rajinder-yadav** [tapjs/tapjs#357]
I would like to be able to do `npm i -D @types/tap` so I can build using TypeScript without errors.

I am using the following tsconfig, the important setting is (`"noImplicitAny": true,`) that causes the error!

```js
{
  "compilerOptions": {
    "declaration": true,
    "declarationDir": "./bin",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "module": "commonjs",
    "newLine": "LF",
    "noEmitOnError": true,
    "noImplicitAny": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "outDir": "./bin",
    "removeComments": true,
    "sourceMap": true,
    "target": "es6"
  }
}
```

**Comment by philkunz** [comment]
much needed indeed!

**Comment by styfle** [comment]
You can probably copy the existing typings for [tape](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/tape/index.d.ts) as a starting point.

**Comment by styfle** [comment]
Actually, this is a dupe of #237

**Comment by huan** [comment]
+1

It seems we need to think about to create a @types/tap for convenience because it looks @isaacs is not like to integrate types internally with tap very soon.

**Comment by isaacs** [comment]
Duplicate of #237.  Happy to merge a PR for this, but not without tests for it. https://github.com/tapjs/node-tap/issues/237#issuecomment-299992415
