### ISSUE TITLE
deepEqual turns undefined into [null]

### ISSUE THREAD

**Issue by kivi** [tapjs/tapjs#358]
deepEqual is for some reason treating a undefined value as [null]. Check "zip" values in the example below.

```
  assert.deepEqual(
    {
      mailingAddress:{
        street: '6th Street, 14 1',
        cityState: 'New York, NY',
        zip: undefined
      }
    }, {
      mailingAddress: {
        street: '6th Street, 14 1',
        cityState: 'New York, NY'
    }
  })
```

The test will fail with:
Error: should be equivalent
      + expected - actual
```
             "mailingAddress": {
               "cityState": "New York, NY"
               "street": "some street, 14 1"
      -        "zip": [null]
             }
```

The test won't fail if second argument of deepEqual also has ```zip: undefined``` inside the object like given as an the first argument of deepEqual.

**Comment by isaacs** [comment]
It's failing because the key exists in the first object, but not the second.  `t.same` objects have to have the same set of keys.

Perhaps what you want is `t.match()`?
