### ISSUE TITLE
landing reporter doesn't ever move

### ISSUE THREAD

**Issue by krainboltgreene** [tapjs/tapjs#359]
(This is a gif)

https://media.giphy.com/media/l0IycAKLOO5fuEAik/giphy.gif

**Comment by bcc32** [comment]
I get the same problem with the `progress` reporter. Nothing changes, and then the result is printed out.

**Comment by isaacs** [comment]
Some of those reporters weren't really created with streaming parallel tests in mind. Probably not ever going to be updated, sorry.
