### ISSUE TITLE
Add support to await for promises in describe() and context()

### ISSUE THREAD

**Issue by ilg-ul** [tapjs/tapjs#362]
I tried to use the `should` module with ES6 async/await code, and it was only partly successful, in the sense that it did not fail, but the functions were executed at the end of the test, not when expected, so I guess the code does not properly awaits for async functions.

the code used to test this is:

```js
'use strict'
// eslint valid-jsdoc: "error"

// ----------------------------------------------------------------------------

/**
 * Test BDD 'should' assertions.
 */

// ----------------------------------------------------------------------------

// The `[node-tap](http://www.node-tap.org)` framework.
// const test = require('tap').test

// The Mocha-like DSL http://www.node-tap.org/mochalike/
require('tap').mochaGlobals()
const should = require('should') // eslint-disable-line no-unused-vars

/* global describe, context, it */

// ----------------------------------------------------------------------------

// Temporary example of an asynchronous function.
const doSomethingAsync = function (n) {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve(0)
    }, n)
  })
}

// ----------------------------------------------------------------------------

describe('async it()', function () {
  var array = [1, 2, 3]
  context('when item is not found', function () {
    it('does not throw an error', function () {
      array.indexOf(4)
    })
    it('calls async', async function () {
      let ret = await doSomethingAsync(100)
      ret.should.equal(0)
    })
    it('returns -1', function () {
      array.indexOf(4).should.equal(-1)
    })
  })
})

describe('async context()', function () {
  var array = [1, 2, 3]
  context('when item is not found', async function () {
    let ret = await doSomethingAsync(100)
    it('does not throw an error', function () {
      array.indexOf(4)
    })
    it('checks async return', function () {
      ret.should.equal(0)
    })
    it('returns -1', function () {
      array.indexOf(4).should.equal(-1)
    })
  })
})

describe('async describe()', async function () {
  var array = [1, 2, 3]
  let ret = await doSomethingAsync(100)
  context('when item is not found', function () {
    it('does not throw an error', function () {
      array.indexOf(4)
    })
    it('checks async return', function () {
      ret.should.equal(0)
    })
    it('returns -1', function () {
      array.indexOf(4).should.equal(-1)
    })
  })
})
```

when invoked via `tap`, I get:

```sh
$ npm run tap test/tap/should.js 

> xsvd@0.1.3 tap /Users/ilg/My Files/MacBookPro Projects/xPack/xsvd-js.git
> tap --reporter=spec --timeout 300 "test/tap/should.js"


test/tap/should.js
  async it()
    when item is not found
      ✓ does not throw an error
      ✓ calls async (114.206ms)
      ✓ returns -1

  async context()
    ✓ when item is not found

  ✓ async describe()
  ✓ does not throw an error
  ✓ checks async return
  ✓ returns -1
  when item is not found
    ✓ does not throw an error
    ✓ checks async return
    ✓ returns -1


  11 passing (694.874ms)
ilg-mbp:xsvd-js.git ilg$ ./node_modules/.bin/tap --version
10.3.1
ilg-mbp:xsvd-js.git ilg$ npm --version
4.2.0
ilg-mbp:xsvd-js.git ilg$ 
```

unless I'm not missing something, it looks like `it()` properly awaits, but `context()` and `describe()` do not.

it would be great to extend this otherwise great tool to properly work with promises and to await for them in all cases.

**Comment by ilg-ul** [comment]
any chance to take a look at this issue?

**Comment by morrisallison** [comment]
@ilg-ul Those `await` should be in a `before`, `beforeEach`, `after`, or, `afterEach`

**Comment by ilg-ul** [comment]
@morrisallison, can you provide an example?

**Comment by morrisallison** [comment]
@ilg-ul Sure. I've made a [gist of your example](https://gist.github.com/morrisallison/db67b40e1938e3fb4a3fcd3b14e452c1), and the changes can be seen in the [revision history](https://gist.github.com/morrisallison/db67b40e1938e3fb4a3fcd3b14e452c1/revisions).

**Comment by ilg-ul** [comment]
thank you. I stared at the code for several minutes, but I'm afraid I do not understand why it should be so.

`it()` seems ok, my understanding is that it processes async functions as expected.

the problem seems to be in `describe()` and `context()`, which are processed differently than `it()`, in a way that is not async friendly. the manual states _Run synchronously_, but I don't know exactly what are the consequences.

to me, mandating the use of `before()` and `after()` looks rather like a workaround.

could you explain (with a reasonable degree of details) why `describe()` and `context()` cannot directly process async functions?

**Comment by morrisallison** [comment]
@ilg-ul 

With the Mocha DSL, the order of the test suites are [maintained globally](https://github.com/tapjs/node-tap/blob/master/lib/mocha.js#L18), so the `describe` blocks [don't handle promises](https://github.com/tapjs/node-tap/blob/master/lib/mocha.js#L44-L47). That's the technical limitation.

I see using `before` and `after` as an extension of traditional BDD style. Using those hooks allows for proper encapsulation of setup and teardown code. For example, if an error occurs in a `describe` block, then the tests that follow are never registered in the test suite. In the case of pending or skipped tests, the `before` and `after` hooks allow the test runner to determine whether the setup or teardown code needs to be run at all.

**Comment by ilg-ul** [comment]
I'm afraid things got a bit too cryptic for me. :-(

I'll probably continue to use the simple tap apis and skip the `should` module.
