### ISSUE TITLE
Support --inspect

### ISSUE THREAD

**Issue by dotnetCarpenter** [tapjs/tapjs#363]
When I run `npm test -- --debug-brk` to debug my tests I get a deprecation warning and is suggested to use `--inspect` instead. But *node-tap* fails with `Unknown argument: --inspect`.

> gulp-tap@0.4.0 test /home/dotnet/projects/opensource/gulp-tap
> tap tests/*.js "--debug-brk"
>
>(node:3614) DeprecationWarning: node --debug is deprecated. Please use node --inspect instead.
>Debugger listening on 127.0.0.1:5858

>Error: Unknown argument: --inspect
>    at parseArgs (/home/dotnet/projects/opensource/gulp-tap/node_modules/tap/bin/run.js:384:15)

**Comment by dotnetCarpenter** [comment]
Hmm seems that `--inspect` is for debugging in Chrome. I'm using vscode and need `--debug-brk` in order to stop at my break points. Not sure why `--debug-brk` is deprecated. But this is a matter not regarding *node-tap*.

Feel free to close this, if it's completely irrelevant. Can't really judge right now.

**Comment by isaacs** [comment]
Yeah, I hadn't heard about --debug-brk being deprecated.

I'm open to adding support for `--inspect` or any other useful node flag.  Note that you can also do `--node-arg=--inspect` to pass any arbitrary thing we haven't thought of already.

**Comment by js-choi** [comment]
For what it’s worth, `--debug` itself too is deprecated by [DEP0062](https://nodejs.org/api/deprecations.html#deprecations_dep0062_node_debug) and, in fact, [it and `--debug-brk` are now apparently aliases for `--inspect` and `--inspect-brk`](https://github.com/nodejs/node/pull/11441).
