### ISSUE TITLE
Domain support for Promises

### ISSUE THREAD

**Issue by ORESoftware** [tapjs/tapjs#364]
@isaacs this is for the people

https://github.com/hapijs/lab/issues/695

I recommend using that patch with TapJS. It seems to work.
If you see any problems with it, I would love to know. Try out the code.

The standard problem:

```js
Promise.resolve(null).then(function(){
   setTimeout(function(){
        throw 'this normally cannot be caught by domains, but with the patch, it can!'
   }, 100):
});
```

'nuff said

**Comment by ORESoftware** [comment]
And there's this:
https://github.com/nodejs/node/pull/12489#issuecomment-294935321

**Comment by isaacs** [comment]
Works on node 8, gonna let time fix this one for us.

**Comment by ORESoftware** [comment]
word
