### ISSUE TITLE
split tap into two packages (not 10)

### ISSUE THREAD

**Issue by isaacs** [tapjs/tapjs#37]
tap-core: Basically everything in `lib/` except coverage and runner.  Depends on yamlish and inherits, and that's it.

tap: Depends on tap-core, runforcover, slide.  Adds runner and coverage, and the stuff in `bin/`

Reasoning: it's very useful for other test runners and harnesses to be able to produce and consume tap formatted data, but it's silly for them to install the node-tap runner in their test runner.

**Comment by dignifiedquire** [comment]
I'll probably need tap-core for one of my projects. So the question is are you going to do this yourself or would you accept a PR?

**Comment by isaacs** [comment]
Yes, I would accept a pull req for this.

**Comment by isaacs** [comment]
Note that the interface exposed by `require('tap')` needs to remain the same.

**Comment by dignifiedquire** [comment]
Sure thing. Two other things
1. How do you want the test suite to be split? I'm not sure which tests should belong to which module.
2. For the tap-core interface I would suggest

``` js
  exports.GlobalHarness = require("./tap-global-harness")
  exports.Producer = require("./tap-producer")
  exports.Consumer = require("./tap-consumer")
  exports.Test = require("./tap-test")
  exports.Harness = require("./tap-harness")
  exports.assert = require("./tap-assert")
  exports.yamlish = require("yamlish")  // ?
```

  is this what you had in mind?

**Comment by isaacs** [comment]
Irrelevant in 1.x
