### ISSUE TITLE
Warning: process.on(SIGPROF) is reserved while debugging in Node.js 8.0.0

### ISSUE THREAD

**Issue by EvgenyOrekhov** [tapjs/tapjs#370]
When I run tap with the `--cov` parameter, it produces the following warning:

```text
$ tap 'test/*.js' --cov
(node:12) Warning: process.on(SIGPROF) is reserved while debugging
```

It doesn't affect the execution though.

tap version: 10.3.2
Node.js version: 8.0.0

**Comment by nexdrew** [comment]
See istanbuljs/nyc#587. Will probably need to bump the `nyc` dependency version.

**Comment by isaacs** [comment]
Fixed on latest release.
