### ISSUE TITLE
same() with Map, Set

### ISSUE THREAD

**Issue by bathos** [tapjs/tapjs#372]
The lib used for deep coercive comparisons, `only-shallow`, takes into account objects like `Date` instances but not ES2015+ `Map` and `Set` (it considers any two to be matches regardless of their content).

There’s no one right answer re: object comparison, and I know node-tap isn’t aiming to be a decked out assert lib, but it seems like `same()` handling `Map` and `Set` by comparing membership (but probably not iteration order) might be the most broadly friendly and least surprising choice. Or at least, the current behavior (comparing true) is kind of a false-positives foot gun.

I would open the issue at `only-shallow`, but it seems like that repo might be abandoned (open PRs & issues w/o responses for > 1 year).

**Comment by isaacs** [comment]
> , and I know node-tap isn’t aiming to be a decked out assert lib,

[Ahem...](http://www.node-tap.org/asserts/)

Yes, this is a bug.  I think there's a PR or issue to switch away from only-shallow, probably not a bad idea to either switch to something different or fork and fix it.  I'm a bit hesitant to drop it entirely, because it means either a breaking change, or a lot of work to evaluate the options.

https://github.com/tapjs/tmatch is the thing that does `t.match()` and the like, so it would have to get addressed over there.

**Comment by isaacs** [comment]
Oh, I guess it'd have to be done on only-shallow and deeper as well.  I wouldn't be opposed to merging those into a `tsame` like `tmatch`, and maybe have a strict option on it.

**Comment by isaacs** [comment]
So, I got started merging these two modules into tsame, and I want to implement this.  Here's a question and a proposed answer:

```js
const a = new Set()
const b = new Set()

// similar, not the actual equal same objects
const arr1 = [1,2,3]
const arr2 = [1,2,3]
a.add(arr1)
b.add(arr2)

// this should fail, of course.
t.sameStrict(a, b)

// but what about these?
// for each key in a, there's a "same" key in b
// but this means looping through and testing every key every time,
// which is (at least) O(n^2), vs the O(n) test using Set.has()
t.same(a, b)
t.match(a, b)
```

I'm gonna make it require that every actual key in a has to be in b as well, and vice versa, strict or not.  `t.match(a, b)` will pass if every key in b is in a, but not require b to have all the keys from a.

When testing Maps, the same thing, but the values will be tested using `t.same()` or `t.sameStrict()` or `t.match()`, as appropriate.

So, keys will always be somewhat stricter than values (effectively, using `t.equal()`), but key _order_ won't ever matter (which means it can't just convert to an array and compare that way).

Feedback welcome, proceeding forward with this plan unless anyone objects.

**Comment by bathos** [comment]
I think that’s a good solution. In a situation where shape-matching on keys is needed, if the user does have a predictable iteration order they just need an extra array cast in the test, and if they don’t, well, it seems niche enough to not worry about unless there ends up being consistent evidence of a need.

**Comment by isaacs** [comment]
Added in 10.5
