### ISSUE TITLE
Missing ) after argument list on windows

### ISSUE THREAD

**Issue by tuananh** [tapjs/tapjs#375]
```
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
```

I have this issue when running tests on Windows (AppVeyor).

**Comment by isaacs** [comment]
It seems like you're running the bash `tap` shim that's created for the benefit of windows bash and Cygwin.

How are you running the command?
