### ISSUE TITLE
run standard for bin/ and test/test

### ISSUE THREAD

**Issue by gr2m** [tapjs/tapjs#377]
the current `"posttest": "standard lib test"` script does not run standard for all the JS files in the repository. I would suggest to remove `lib test`, so that it will run for all of them. `node_modules` is ignored by default. 

Happy to do it and to fix the standard errors in the other folders, just wanted to check in first if you’d like that

**Comment by isaacs** [comment]
I'm probably going to abandon standard relatively soon.  It's a perfectly fine linter, but it doesn't exactly match my tastes.  I'm the only one landing patches here usually, and I don't mind doing little fixups for PRs that come in.
