### ISSUE TITLE
v11

### ISSUE THREAD

**Issue by isaacs** [tapjs/tapjs#378]
Drop support for 0.x, clean up code, use a faster stream implementation.

* [x] Use Es Classes instead of function ctors
* [x] Migrate tap to MiniPass
* [x] Migrate tap-parser to MiniPass
* [x] Add unit tests for each file to get to 100% coverage
* [x] t.only() as alias for t.test({ only: true })
* [x] t.skip() as alias for t.test({ skip: true })
* [x] t.todo() as alias for t.test({ todo: true })
* [x] Add `--grep=<pattern>` to cli, filter top-level tests by matching pattern.  Set multiple times to also filter sub-tests, maybe?
* [x] Remove all instances of `function` (replace with `=>` or class methods), and `var` (replace with `const` usually, or `let` in rare cases where it's ok to mutate).
* [x] `use strict` everywhere for v4 compatibility and better optimization.

**Comment by isaacs** [comment]
Still one `function` in lib/test.js, because it needs to use variable arguments.

**Comment by kuroljovc** [comment]
Would you consider adding this thing in 11? https://github.com/tapjs/node-tap/pull/403

**Comment by viktor-ku** [comment]
Could you consider adding this in v11 release? https://github.com/tapjs/node-tap/pull/403

**Comment by isaacs** [comment]
Yes, I would.  Still working on improving test coverage, if you want to port your patch onto the v11 branch, I'd be happy to take a look.

**Comment by viktor-ku** [comment]
Yeah I want to port it because I would love to have this feature. So what should I do? Build my patch on top of v11 branch and change PR?

**Comment by isaacs** [comment]
Sure, or you can close this and create a new PR if that's easier for you.  Either way's fine with me.  Thanks!
