### ISSUE TITLE
Deal with high amount of tests

### ISSUE THREAD

**Issue by thejh** [tapjs/tapjs#38]
I'm doing one `test.ok()` call for every node in an autogenerated AST - maybe this is a bad idea? Anyway, tap dies:

```
[jann@Jann-PC node-astjourney locations]$ npm test

> astjourney@0.2.7 test /home/jann/gitty/node-astjourney
> tap test/*.js

ok find-requires.js ............... 12/12
ok scope.js ......................... 8/8
ok stringify.js ..................... 2/2
ok token-locations.js ............... 2/2
total ............................. 27/28

not ok
npm ERR! astjourney@0.2.7 test: `tap test/*.js`
npm ERR! `sh "-c" "tap test/*.js"` failed with 1
[...]
```

Could this be because the RAM fills up? The test is at https://gist.github.com/72f7acd0bbfb07a908e3 - I'm doing `util.inspect` on a lot of nodes.

**Comment by thejh** [comment]
Works fine (as in "I get a big bunch of failing tests") without `+util.inspect(node, false, null, false)`.

**Comment by isaacs** [comment]
Yes, you are probably running out of memory or something.  What do you get when you run the tests with `TAP=1 npm test`?

**Comment by rmg** [comment]
Closing, since this is very old and most of the code has been re-written by now AFAICT.
