### ISSUE TITLE
consider removing package-lock.json

### ISSUE THREAD

**Issue by rmg** [tapjs/tapjs#380]
As far as I can tell, in the absence of an `npm-shrinkwrap.json`, the use of `package-lock.json` in any package published to npmjs.org invites only increased risk of "works on my machine" problems.

Because `package-lock.json` is _explicitly_ excluded from being published, the main effect is to ensure that the maintainers of a package are using increasingly outdated versions of their dependencies compared to the versions their users end up using the package with.

Am I missing something?

**Comment by rmg** [comment]
According to git, `package-lock.json` was last modified 33 hours ago. Deleting it and regenerating it yields this:
```
$ git diff --stat
 package-lock.json | 37 ++++++++++++++++++-------------------
 1 file changed, 18 insertions(+), 19 deletions(-)
```

This suggests that even at release time, `tap` is being tested against different versions of its dependencies than any user of that that release.

**Comment by isaacs** [comment]
There is, fundamentally, no way to avoid "running with different modules than were tested" other than bundling (or `npm-shrinkwrap.json`-ing them, which is effectively almost the same thing.)

If `a` depends on `b@1.x` and the latest version of `b` is `1.2.3`, but the root project `c` depends on both `a` and `b@1.1.x`, then `a` will be provided `b@1.1.0`, not `b@1.2.3`.

Even without the root-project dependency confounding things, at time of publish, the latest version of `b` may have been `1.1.0`, and `b@1.2.3` only published after the last test of `a`.

To ensure that all users of a module have the same versions of all dependencies that were tested, one must either bundle dependencies, or run all tests with all combinations of dependencies every time any package in the dependency tree is published.

Neither option is acceptable, so the cost is specious.  Having a `package-lock.json` provides many other benefits by simply encouraging consistency across developers of the project.  It stays.  Let's just run `npm update` from time to time.
