### ISSUE TITLE
Object equivalence assertion fails when they contain functions?

### ISSUE THREAD

**Issue by g12mcgov** [tapjs/tapjs#382]
Hello,

I've noticed that the `strictSame()` method doesn't enforce object equivalence if those objects contain a function. Is there any other way around this besides writing my own `addAssert()` method?

Example:

**(Without functions):**
```javascript
const tap = require('tap');
var a = {name: 'bob'};
var b = {name: 'bob'};
tap.strictSame(a, b); // true
```
**(With functions):**
```javascript
const tap = require('tap');
var a = {name: 'bob', uppercase: function() { return this.name.toUpperCase(); }};
var b = {name: 'bob', uppercase: function() { return this.name.toUpperCase(); }};
tap.strictSame(a, b); // false
```

**Comment by isaacs** [comment]
That is correct.  Functions are never equal to each other.  It'll pass if they're the same function.
