### ISSUE TITLE
Run only tests matching a pattern

### ISSUE THREAD

**Issue by gabipetrovay** [tapjs/tapjs#39]
If you have many tests and you only want to run some of them, you want to be able to tell tap to only run tests matching a certain pattern (glob, regex, etc.).

And how could I use this now to call it from npm test where "test" script is in my package.json something like:

`node node_modules/tap/bin/tap.js ./test`

**Comment by isaacs** [comment]
Just put this in your package.json:

``` json
"scripts": { "test": "tap ./test.js" }
```

Globs would work, too, since that command is just run by the shell.

**Comment by gabipetrovay** [comment]
I am not installing tap globally. Therefre I use it through node.

Do globs work recursively? I tried and I could not manage to do it.

None of the following work for the test under `./test/dir1/dir2/test.js`

```
node node_modules/tap/bin/tap.js ./test/*.js
node node_modules/tap/bin/tap.js ./test/*/*.js
```

**Comment by gabipetrovay** [comment]
What I want to do is:

`node node_modules/tap/bin/tap.js miaw`

or

`tap miaw`

to run all the tests that have `miaw` in their path somewhere.

Similar to what the collowing does for CMake:
`cmake -R miaw`

The following tests would be run:

```
./test/miaw1/test.js
./test/mymiaw/test.js
./test/dir/miaw2.js
```

**Comment by isaacs** [comment]
> Do globs work recursively? I tried and I could not manage to do it.

Depends on your shell.  (Probably not.)

You should just use `tap` in your scripts.test, not `node node_modules/tap/bin/tap.js`.  npm will set up the paths for you so it works.

You can pass in multiple arguments.  `tap ./test/*.js ./test/*/*.js ./test/*/*/*.js`

**Comment by isaacs** [comment]
There is no way to have tap find all the files with `miaw` in their path, no.  I think that feature would be confusing.

**Comment by gabipetrovay** [comment]
I run tap an it does not work.

I only install modules locally in my project. That is under node_modules. npm doesn't seem to set up the paths. (I use the latest npm and nodes)

**Comment by isaacs** [comment]
Put this in your package.json:

``` json
"scripts": { "test": "tap test/*.js" }
```

Then run this command: `npm test`

**Comment by gabipetrovay** [comment]
Even if tap would have a parameter like "cmake" (-R), or like "find" (-name)?

**Comment by isaacs** [comment]
Adding this feature would be confusing, for little benefit.

Structure your tests so that they're easier to find, or use some other file-walking utility.

**Comment by gabipetrovay** [comment]
I have two levels below test (and not only there) test files that I want to run.

```
gabriel$ npm test

> mono@0.3.0 test /Users/gabriel/mono
> tap test/*.js

total ................................................... 0/1

not ok

npm ERR! mono@0.3.0 test: `tap test/*.js`
npm ERR! `sh "-c" "tap test/*.js"` failed with 1
npm ERR! 
npm ERR! Failed at the mono@0.3.0 test script.
npm ERR! This is most likely a problem with the mono package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tap test/*.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls mono
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Darwin 11.3.0
npm ERR! command "node" "/usr/local/bin/npm" "test"
npm ERR! cwd /Users/gabriel/mono
npm ERR! node -v v0.6.10
npm ERR! npm -v 1.1.0-3
npm ERR! code ELIFECYCLE
npm ERR! message mono@0.3.0 test: `tap test/*.js`
npm ERR! message `sh "-c" "tap test/*.js"` failed with 1
npm ERR! errno {}
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/gabriel/mono/npm-debug.log
npm not ok
```

**Comment by gabipetrovay** [comment]
Thinking about the utility of such a feature (globbing or pattern given with a parameter)

you have thousand tests that run in 10 minutes and you want to check only the ones that are testing part of the system that you have changed. And those tests are in a subdirectory. Those tests only run in 1 minute. Telling tap to run only tests matching that pattern would let you test only that part of the system and save you some time. And this hierarchy is actually intended to structure the unit tests into components.
