### ISSUE TITLE
Support .taprc lookup from CWD directory

### ISSUE THREAD

**Issue by chrisnicola** [tapjs/tapjs#391]
It is fairly typical to place config files like .taprc in the root of a project rather than the home directory. Would it be reasonable to support this without having to set TAP_RCFILE?

**Comment by isaacs** [comment]
I don't want to have to support multiple config files.  For now, let's stick with setting the env.  Note that you can do `export TAP_RCFILE=./.taprc` if you want, so it's always relative to the cwd.
