### ISSUE TITLE
Allow .taprc to be placed in project root or lookup relative to process.cwd

### ISSUE THREAD

**Issue by chrisnicola** [tapjs/tapjs#392]
It is fairly typical to place config files like .taprc in the root of a project rather than the home directory. Would it be reasonable to support this without having to set TAP_RCFILE?

**Comment by pke** [comment]
I also just expected that to work, since most projects that support config files follow that pattern. I think there is even a node module that manages all the finding of the different (format of) .rc files for you. I have to see if I can find it and create a PR.

**Comment by isaacs** [comment]
Dupe #391.  Not gonna do this for now.  At some point we can pull in a userland node module, but nested config file handling is such an attractive nuisance.
