### ISSUE TITLE
Asserting strict equality of unequal symbols causes YAML-dump error

### ISSUE THREAD

**Issue by js-choi** [tapjs/tapjs#393]
Node-Tap uses its [`obj-to-yaml.js`][] module to convert JavaScript objects to YAML text before displaying them in its reporter, e.g., when a `strictEqual` assertion fails. `obj-to-yaml.js` uses the JS-YAML library’s `safeDump` method with no apparent custom types.

Because of this, strictly comparing unequal symbols (`t.strictEqual(Symbol(''), Symbol(''))`) causes JS-YAML to throw an error (`unacceptable kind of an object to dump [object Symbol]`), instead of printing out its usual colorful comparison. A similar error occurs when comparing unequal objects that contain symbols (e.g., `t.deepStrictEqual({ x: Symbol('') }, { x: Symbol('') })`).

JS-YAML has rejected a proposal to add JavaScript symbols to its default schema (nodeca/js-yaml#359); an owner stated that code that may use JS-YAML on symbol-containing objects should use [JS-YAML’s API for custom YAML types](https://github.com/nodeca/js-yaml/blob/master/examples/custom_types.js). Node-Tap’s reporter should use this API to add support for converting symbols or symbol-containing objects to YAML.

[`obj-to-yaml.js`]: https://github.com/tapjs/node-tap/blob/c41742440869f06ee1eac39d9fc80a3fc3af3f53/lib/obj-to-yaml.js

**Comment by kkeri** [comment]
All reporters (except silent) break on this. It's indeed an inconvenience when the end of the stack trace is cut off, so it's hard to find out which test case has failed.

~~~
  not ok unacceptable kind of an object to dump [object Symbol]
    stack: |
      writeNode (node_modules/js-yaml/lib/js-yaml/dumper.js:754:13)
      writeBlockMapping (node_modules/js-yaml/lib/js-yaml/dumper.js:633:10)
      writeNode (node_modules/js-yaml/lib/js-yaml/dumper.js:726:9)
      writeBlockMapping (node_modules/js-yaml/lib/js-yaml/dumper.js:633:10)
      writeNode (node_modules/js-yaml/lib/js-yaml/dumper.js:726:9)
      writeBlockMapping (node_modules/js-yaml/lib/js-yaml/dumper.js:633:10)
      writeNode (node_modules/js-yaml/lib/js-yaml/dumper.js:726:9)
      writeBlockMapping (node_modules/js-yaml/lib/js-yaml/dumper.js:633:10)
      writeNode (node_modules/js-yaml/lib/js-yaml/dumper.js:726:9)
      writeBlockMapping (node_modules/js-yaml/lib/js-yaml/dumper.js:633:10)
      writeNode (node_modules/js-yaml/lib/js-yaml/dumper.js:726:9)
      writeBlockMapping (node_modules/js-yaml/lib/js-yaml/dumper.js:633:10)
      writeNode (node_modules/js-yaml/lib/js-yaml/dumper.js:726:9)
      writeBlockMapping (node_modules/js-yaml/lib/js-yaml/dumper.js:633:10)
      writeNode (node_modules/js-yaml/lib/js-yaml/dumper.js:726:9)
      writeBlockMapping (node_modules/js-yaml/lib/js-yaml/dumper.js:633:10)
    at:
      line: 754
      column: 13
      file: node_modules/js-yaml/lib/js-yaml/dumper.js
      function: writeNode
    type: YAMLException
    reason: 'unacceptable kind of an object to dump [object Symbol]'
    mark: null
    test: subtype
    source: |
      throw new YAMLException('unacceptable kind of an object to dump ' + type);

Bail out! # unacceptable kind of an object to dump [object Symbol]
~~~

**Comment by isaacs** [comment]
Yeah, I'm not sure how we'd go about defining Symbols as a js-yaml custom type.  I looked at https://github.com/eemeli/yaml which also seems like it has a nicer API and is more actively maintained, but I'm not sure about the perf (or just overall battle-testedness) compared with js-yaml.  It also doesn't support Symbols.

I think the thing to do is abstract out js-yaml (or eemeli/yaml) a bit more, and call our own yaml goober instead.  Then it could handle Symbols, as well as all the other stuff being clumsily shimmed in obj-to-yaml and clean-yaml-object and friends.

**Comment by isaacs** [comment]
Fixed on v13, using the tap-yaml module.
