### ISSUE TITLE
nyc + tap + babel = weird situation

### ISSUE THREAD

**Issue by krainboltgreene** [tapjs/tapjs#398]
So I have:

  - A code in ES5+ syntax
  - A test in ES5+ syntax

I want to test this code and check the code coverage.

While it should be as simple as `npx babel-tap --100 'test.js'` it seems [like there are other issues](https://github.com/istanbuljs/nyc/issues/651).

*However*, I am running into issues using the `tap` interface to pass arguments. Here's what happens:

```
| npx tap --node-arg=--require --node-arg=babel-register --nyc-arg=--require --nyc-arg=babel-register 'test.js'
test.js ............................................... 2/2 656ms
total ................................................. 2/2

  2 passing (666.593ms)

  ok
```

Sweet, but now with coverage checking?

```
| npx tap --node-arg=--require --node-arg=babel-register --nyc-arg=--require --nyc-arg=babel-register --100 'test.js'
/Users/krainboltgreene/Code/unctionjs/mergeRight/test.js:2
import {test} from "tap"
^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:53:10)
    at runInThisContext (vm.js:95:10)
    at Object.vm.runInThisContext (/Users/krainboltgreene/Code/unctionjs/mergeRight/node_modules/nyc/node_modules/istanbul-lib-hook/lib/hook.js:141:16)
    at Module._compile (module.js:543:28)
    at Module.replacementCompile (/Users/krainboltgreene/Code/unctionjs/mergeRight/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (/Users/krainboltgreene/Code/unctionjs/mergeRight/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at Object.<anonymous> (/Users/krainboltgreene/Code/unctionjs/mergeRight/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
test.js ............................................... 0/1
  not ok test.js
    timeout: 240000
    file: test.js
    command: /Users/krainboltgreene/.nvm/versions/node/v7.7.2/bin/node
    args:
      - '--require'
      - babel-register
      - test.js
    cwd: /Users/krainboltgreene/Code/unctionjs/mergeRight
    exitCode: 1

total ................................................. 0/1


  0 passing (552.359ms)
  1 failing

----------|----------|----------|----------|----------|----------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
All files |  Unknown |  Unknown |  Unknown |  Unknown |                |
----------|----------|----------|----------|----------|----------------|
```

I have the latest node, npm, babel, nyc, babel-istanbul, and tap.

**Comment by isaacs** [comment]
I'd love to dig into this, but honestly, I feel like it's getting into ETOOMANYTRANSPILATIONS territory. Have you considered using `require` instead of import? At some point, surely the costs outweigh any benefits?

If you can reduce it to a relatively simple repro case, @bcoe might be interested. The bug likely lives in the Istanbul/babel interaction.

**Comment by krainboltgreene** [comment]
In this case it seems like it might just be that nyc isn't getting the arguments?

(And no, I'm not switching from `import` :P)

**Comment by bcoe** [comment]
@krainboltgreene off the top of my head, from the output, it kind of looks like the nyc argument should be:

`--nyc-arg--require=babel-register`? tldr; you want `nyc` to be doing the instrumentation step.

I might suggest an alternative approach though, if you instead wire up the istanbul instrumentation as an additional babel plugin:

https://github.com/istanbuljs/babel-plugin-istanbul

It simplifies some of the moving parts; you ultimately end up simply using `nyc` for reporting, and your codebase will magically be instrumented with coverage by virtue of the plugin.

**Comment by bcoe** [comment]
@krainboltgreene another potential workaround comes to mind, perhaps try using a `.nycrc` configuration file, rather than passing arguments:

https://github.com/istanbuljs/nyc#configuring-nyc

I _think_ nyc should pick up this config, even though it's being invoked by tap; if this is the case, then just make sure that `babel-register` is loaded by `nyc`.

**Comment by krainboltgreene** [comment]
> `--nyc-arg--require=babel-register? tldr; you want nyc to be doing the instrumentation step.`

```
| npx tap --node-arg=--require --node-arg=babel-register --nyc-arg--require=babel-register --100 'test.js'
Unknown argument: --nyc-arg--require=babel-register
```

@bcoe I'm actually using the babel plugin.

**Comment by krainboltgreene** [comment]
```
--nyc-arg--require=babel-register? tldr; you want nyc to be doing the instrumentation step.
```

results in:

```
| npx tap --node-arg=--require --node-arg=babel-register --nyc-arg--require=babel-register --100 'test.js'
Unknown argument: --nyc-arg--require=babel-register
```


> I might suggest an alternative approach though, if you instead wire up the istanbul instrumentation as an additional babel plugin

I'm actually using that plugin :/

**Comment by krainboltgreene** [comment]
Ah-ha! I put the plugin in only `test` ENV but never called it with `NODE_ENV=test`. Which means: `NODE_ENV=test npx tap --100 'test.js'` works just fine. Now the other ways are still breaking, but at least I got mine.

**Comment by bcoe** [comment]
@krainboltgreene awesome 👍 might be worth pulling in:

https://www.npmjs.com/package/cross-env
