### ISSUE TITLE
[Question] How to pass data between tests?

### ISSUE THREAD

**Issue by tuananh** [tapjs/tapjs#399]
Can someone show me an example on how to pass data between tests?

Thank you.

**Comment by isaacs** [comment]
Between test files, or test blocks in a single file?

The second is pretty easy.

```js
let data = 'foo'
t.test('set data to bar', t => {
  t.equal(data, 'foo')
  data = 'bar'
  t.end()
})
t.test('now data is bar', t => {
  t.equal(data, 'bar')
  t.end()
})
```

Passing data between different _files_ is a little more complicated, and _may_ indicate that your tests are not as isolated as they could be.  Whether or not that's a problem is up to you to decide, but at least, it prevents parallel test execution.

The way to pass data between different test processes would be to write a file and then read it, or start a server as a detached child process (which is later shut down), or something of that nature.  You can look at [t-up](http://npm.im/t-up) as an example of a thing that creates a server and then later destroys it.  You can also just `fs.writeFileSync('data.json', JSON.stringify(data))` and then later do `data = JSON.parse(fs.readFileSync('data.json', 'utf8'))`.

**Comment by tuananh** [comment]
Just test blocks. Thank you Isaacs
