### ISSUE TITLE
Syntax errors result in tap being "mysterious"

### ISSUE THREAD

**Issue by mcavage** [tapjs/tapjs#4]
A syntax error at the top of my file resulted in output like this (basically it tells you nothing):

bluesnoop:node-asn1 mark$ ./node_modules/.bin/tap ./tst
ok ber_decoder.test.js .............. 0/0
total ............................... 0/1

not ok
bluesnoop:node-asn1 mark$ TAP=1 ./node_modules/.bin/tap ./tst
# ber_decoder.test.js

not ok 1 ber_decoder.test.js

1..1
# tests 1
# fail  1

bluesnoop:node-asn1 mark$

**Comment by robertkrimen** [comment]
Just wanted to chime in, this issue is bugging me as well

+1

**Comment by dominictarr** [comment]
unfortunately syntax errors are uncatchable in node. 
node just prints the message to stderr and exits. 
so, the only way to catch this is to report stderr when a test failed...

(ok, there is already an issue for that)

+1

**Comment by isaacs** [comment]
Closed by #12
