### ISSUE TITLE
tap runs very slowly

### ISSUE THREAD

**Issue by defunctzombie** [tapjs/tapjs#40]
I couldn't find a mailing list so I will post here. Apologies if I didn't look hard enough :(

When I create a simple test setup and run tap on it, it seems to take a long time to run (several seconds). The same test setup with nodeunit takes fractions of a second.

I am not running test coverage or doing anything in the test that would be causing such delays. Maybe I setup something else wrong? Is this expected to be slower than other testing options?

There was nothing complex about the testcase but I can provide the example if desired.

node: 0.6.11-pre
tap: 0.2.0

**Comment by isaacs** [comment]
Yes, please share the test case, and the specific command you ran.

**Comment by defunctzombie** [comment]
https://gist.github.com/1861122
