### ISSUE TITLE
t.resolve to assert resolved promise

### ISSUE THREAD

**Issue by json2d** [tapjs/tapjs#401]
Ok so we have `t.reject` to assert that a promise (or promise-returning function) rejects, but no `t.resolve`. 

Is there already a preferred way to assert that a promise resolves?

**Comment by isaacs** [comment]
I'd be fine with adding a t.resolves, but in the mean time, you can either just await the promise (in node 8 and above) or return it from a subtest. 

```js
const p = somePromise()
t.test('resolves', t => p)
```

**Comment by isaacs** [comment]
Added in v11 branch, `t.resolves(promise)` and `t.resolveMatch(promise, pattern)` landing in the next major.

**Comment by json2d** [comment]
Awesome that was quick!

**Comment by isaacs** [comment]
Well, it'll be a while before v11 is done, but sure, you're welcome, glad you're happy about it :)
