### ISSUE TITLE
flag to require message for assertions

### ISSUE THREAD

**Issue by isaacs** [tapjs/tapjs#405]
cc @jefflembeck

If a test like `t.ok(foo)` doesn't have a message, fail it if this flag is set.

**Comment by jaydenseric** [comment]
This might be better as an ESLint plugin rule; see https://github.com/avajs/eslint-plugin-ava/blob/master/docs/rules/assertion-arguments.md for inspiration.

**Comment by isaacs** [comment]
Leaving this here, but I don't actually have any plans to get around to it any time soon.  If anyone wants to pick it up, feel free.

**Comment by isaacs** [comment]
Yes, this should be a linter, not a test setting.

https://www.npmjs.com/package/eslint-plugin-tap
