### ISSUE TITLE
process.env.TAP_CHILD_ID for parallel processes

### ISSUE THREAD

**Issue by chrisdickinson** [tapjs/tapjs#407]
`process.env.TAP_CHILD_ID` provides an integer id for the test process. For instance, given `tap -J4`, test ids would be `0-3`. Test ids could be reused once the given test child process exits. In non-parallel mode, `process.env.TAP_CHILD_ID` would always `=== 0`.

This could be used to provision resources based on the child id. This would make it easier to turn sequential tests into parallel tests.

**Comment by ORESoftware** [comment]
in non-parallel mode, a unique id for each child would be useful..what added-value is given by having 0 for every child id?

**Comment by isaacs** [comment]
@ORESoftware You might want to, say, `server.listen(8000 + process.env.TAP_CHILD_ID)`, and keep it within some reasonable threshold.

But, I kind of agree, just incrementing is likely better than keeping track of which number is currently free, and the `%` operator exists after all.
