### ISSUE TITLE
Is --jobs flag working?

### ISSUE THREAD

**Issue by neonsamurai** [tapjs/tapjs#408]
I tried to run tests in parallel, but it didn't seem to work. When I invoke the runner with `jobs=4` it would still run tests serially. On the other hand if I parallelise tests with the API by setting `t.jobs=4` it will properly parallelise the tests in the file.

I would like to always run all tests in parallel by default, hence the invocation with `jobs=4`

Am I missing something or doing it wrong?

**Comment by isaacs** [comment]
The `--jobs=4` flag on the command line will run 4 test files in parallel.  The test blocks _within_ those files will still run serially, though.

Setting `t.jobs = 4` is the way to run tests within a file in parallel.

The reasoning behind this is that I frequently have tests with setup and teardown test blocks, and while I might be able to run individual files in parallel, I almost never want to run the test blocks in a file in parallel.

That's also why `t.jobs` isn't contagious to child tests.  But you can do `t.test('child', { jobs: 4 }, t => { /* t.jobs is 4 here */ })`

So, working as designed, but I'd happily accept a patch to update the docs if that'd make this more clear.

**Comment by neonsamurai** [comment]
Ah now I understand! Thanks! I will see into the docs in the next days.
