### ISSUE TITLE
No tests run with node v8.9.0 and ECMAScript module syntax

### ISSUE THREAD

**Issue by rogerta** [tapjs/tapjs#409]
When using node-tap 10.7.2 with node 8.9.0 to test code using ECMAScript modules syntax, no tests are executed.  I have put together a minimal test case that demonstrates the issue.

Install and setup test case:
```
$ git clone https://github.com/rogerta/node-tap-esm.git
$ cd node-tap-esm
$ npm install
```

Run CommonJS test code and see that 1 test runs correctly:
```
$ npm run cjs                       
 
> tap-es6-import@1.0.0 cjs /home/rogerta/src/tap
> tap foo_test.js
 
foo_test.js ........................................... 1/1
total ................................................. 1/1
 
  1 passing (146.874ms)
 
  ok
```

Run ESM test code and see that no tests are run:
```
$ npm run esm
 
> tap-es6-import@1.0.0 esm /home/rogerta/src/tap
> tap --node-arg=--experimental-modules foo_test.mjs
 
total ................................................. 0/0
 
  0 passing (4.348ms)
 
  ok
```

However, if I run the test file directly in node, it seems to run correctly:
```
$ node --experimental-modules foo_test.mjs
(node:29237) ExperimentalWarning: The ESM module loader is experimental.
TAP version 13
# Subtest: Foo
    ok 1 - should be equal
    1..1
ok 1 - Foo # time=2.442ms

1..1
# time=6.569ms
```

**Comment by rogerta** [comment]
Changing https://github.com/tapjs/node-tap/blob/v10.7.2/bin/run.js#L749 from:

```
if (file.match(/\.js$/)) {
```

to

```
if (file.match(/\.m?js$/)) {
```

seems to fix the ECMAScript test case above.  However, running with ```--cov``` causes an unknown file extension error:

```
$ ./node_modules/.bin/tap --cov --node-arg=--experimental-modules foo_test.mjs
(node:734) ExperimentalWarning: The ESM module loader is experimental.
Error [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension: /home/rogerta/.node-spawn-wrap-722-8456dcbb8ce6/node
    at exports.resolve (internal/loader/ModuleRequest.js:126:13)
    at Loader.resolve (internal/loader/Loader.js:48:40)
    at Loader.getModuleJob (internal/loader/Loader.js:76:40)
    at Loader.import (internal/loader/Loader.js:98:28)
    at module.js:457:29
    at Function.Module._load (module.js:458:7)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
foo_test.mjs .......................................... 0/1
  not ok foo_test.mjs
    timeout: 240000
    file: foo_test.mjs
    command: /home/rogerta/bin/node-v8.9.0-linux-x64/bin/node
    args:
      - '--experimental-modules'
      - foo_test.mjs
    cwd: /home/rogerta/Documents/node-tap-esm
    exitCode: 1

total ................................................. 0/1
  

  0 passing (119.031ms)
  1 failing

----------|----------|----------|----------|----------|----------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
All files |  Unknown |  Unknown |  Unknown |  Unknown |                |
----------|----------|----------|----------|----------|----------------|
```

**Comment by jaydenseric** [comment]
You can test `.mjs` by using the `node` CLI instead of `tap`:

```sh
node --experimental-modules --no-warnings lib/test | tap-mocha-reporter spec
```

I'm noticing that the traces are different between regular CJS `.js` and ESM `.mjs` files though. Here is the output of both side by side:

```js
'use strict'

const tap = require('tap')

tap.fail('Should pass')
```

<img width="306" alt="screen shot 2018-05-15 at 8 18 28 pm" src="https://user-images.githubusercontent.com/1754873/40051192-34920902-587d-11e8-8dd9-9df45a4345f3.png">

```
TAP version 13
not ok 1 - Should pass
  ---
  at:
    line: 5
    column: 5
    file: lib/test.js
  stack: |
    Object.<anonymous> (lib/test.js:5:5)
  source: |
    tap.fail('Should pass')
  ...

1..1
# failed 1 test
# time=9.787ms
```

```js
import tap from 'tap'

tap.fail('this is fine')
```

<img width="221" alt="screen shot 2018-05-15 at 8 18 33 pm" src="https://user-images.githubusercontent.com/1754873/40051193-34c2ed60-587d-11e8-9694-307dd6320d29.png">

```
TAP version 13
not ok 1 - this is fine
  ---
  at:
    line: 2
    column: 5
    file: 'file:///Users/jaydenseric/Sites/test/lib/test.mjs'
  stack: |
    file://lib/test.mjs:2:5
  ...

1..1
# failed 1 test
# time=14.082ms
```

**Comment by rogerta** [comment]
@isaacs just wondering what your plans are about supporting ECMAScript modules syntax.  Is this something you'd eventually like to do or something you have no interest in?

My use case is that I am writing a typescript app that targets ECMAScript modules syntax.  I write my production and test code in ts, but I need to compile it twice: once with ECMAScript modules syntax for production and a second time with CommonJS modules syntax to run my tests.  It would be great to cut build time in half and also test my real production code rather than a different transformation of it.

(I find this works better for me than all the other hacks mentioned in issues like #313, #357, #237.  What I'm doing does not require hacking source code with shebangs, replacing node with ts-node in scripts, etc. 
 Assuming this gets fixed, I'll just need to delete one target in my gulp file.)

**Comment by isaacs** [comment]
cd562e7a45c006b584c8cb7c2ad15160848a238a
