### ISSUE TITLE
--watch to re-run tests on file changes

### ISSUE THREAD

**Issue by isaacs** [tapjs/tapjs#411]
Requested on twitter by @aearly https://twitter.com/aeflash/status/927958590039527424

`tap test/*.js --watch=lib/` will re-run the test suite every time a file in `lib` changes.

I'd probably want to detect the `--watch` setting and have it run itself as a child process _without_ `--watch` on each change, so that each invocation of the tap runner starts from a clean process.  (That might be overkill/superstition, but it'd certainly make it simpler if there's coverage or other settings that take action on process exit, so that they don't have to be manually executed.)

**Comment by pke** [comment]
I despise jest for taking jasmine and its impure testing approach of globally injected functions as a base but they have figured out the "test only what changes" in watch mode. I'd like node-tap to also support such mode. As far as I can see there is no watch mode for this testing lib yet?

**Comment by isaacs** [comment]
@pke "test only what changes" would be interesting.  It seems like we might benefit from tracking which source files were covered by which test files, and then re-running those on file changes?

In the meantime, a "re-run the whole suite on changes" still seems valuable.

**Comment by pke** [comment]
yes, jest seems to be able to do that, maybe with the help of instrumentation. And since nyc is already instrumenting tap tests it might be a hook into such functionality.
Jest also provides an option to run only the tests for changed files based on the current git working tree.

**Comment by pke** [comment]
Is this already in? Tried `--watch` and it gave me `Unknown argument: --watch=src`

**Comment by isaacs** [comment]
@pke It is not, no.

**Comment by rogaldh** [comment]
@pke Could be easily achieved via [chokidar-cli](https://github.com/kimmobrunfeldt/chokidar-cli):
```
chokidar ./src -c "npm run tap" --polling
```
The only disadvantage is that it runs all the tests.

**Comment by isaacs** [comment]
Work underway in the [watch branch](https://github.com/tapjs/node-tap/tree/watch)

**Comment by isaacs** [comment]
`npm i tap@next` to use this now.  Will be in v13.
