### ISSUE TITLE
tap.throws leaking error

### ISSUE THREAD

**Issue by devsnek** [tapjs/tapjs#415]
i'm getting some strange behavior with my tests:

![](https://gc.gy/遼NS.png)

any ideas or things i might be doing wrong?

**Comment by isaacs** [comment]
It looks like the `() => syncify(Promise.reject(new Error('this is an error'))` function doesn't throw immediately when called.  My suspicion would be that, since Promise rejection is async, it's throwing after the current tick?

**Comment by isaacs** [comment]
Oh, or maybe that's the point that syncify is supposed to be doing, making things sync?  What does this do?

```javascript
try {
  syncify(Promise.reject(new Error('x')))
  t.fail('did not throw!')
} catch (er) {
  t.pass('got expected error')
}
```

**Comment by devsnek** [comment]
yeah it might be leaking into the next tick (things get unpredictable when you start messing with uvloop) i'll close this for now, since it appears to not be a tap issue

**Comment by devsnek** [comment]
i'm getting this issue again, and this time i'm not messing with the event loop. it looks like tap messes with unhandled rejections? Would it be possible to disable this behavior? i can't find a way to do it.

![](https://gc.gy/凜➬ʄ.png)

**Comment by isaacs** [comment]
@devsnek Can you please copy and paste the actual output between ` ``` ` blocks in issues, instead of screenshots? Your low-contrast semi-transparent terminal is quite lovely, but unfortunately nearly impossible for my eyeballs to parse properly :)

Anyway:

```
const PromiseUtil = require('.');
const tap = require('tap');

tap.plan(3);

{
  const p = PromiseUtil.create();
  tap.same(PromiseUtil.getDetails(p), { state: 'pending' }, 'details for pending');
}

{
  const p = Promise.resolve(5);
  tap.same(PromiseUtil.getDetails(p), { state: 'resolved', result: 5 }, 'details for resolved');
}

{
  const e = new Error('error');
  const p = Promise.reject(e);
  tap.same(PromiseUtil.getDetails(p), { state: 'rejected', result: e }, 'details for rejected');
}

tap.end();
```

output:

```
TAP version 13
1..3
ok 1 - details for pending
ok 2 - details for resolved
ok 3 - details for rejected
# time=7.21ms
Error: error
    at Object.<anonymous> (test.js:17:13)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
{ name: 'TAP', test: 'TAP' }
```

My guess here is that the throw is indeed because of an unhandled promise rejection, especially as it comes on the next tick after tap has ended.  Add a `p.catch(er => tap.equal(er, e))` or even more simply just `tap.rejects(p, e)`, so that the rejection is handled.

**Comment by isaacs** [comment]
Also, you don't have to call `tap.end()`, and in fact, it's probably better if you don't, and just let the top-level auto-end handle it, so that anything that happens on next tick is more usefully reported.
