### ISSUE TITLE
Could you expose `require('tap/lib/stack')`?

### ISSUE THREAD

**Issue by evanlucas** [tapjs/tapjs#417]
When writing custom assertions that use subtests, it is quite convenient to `extra.at = stack.at(this.currentAssertion)`. Is that something you would feel comfortable exposing as part of the public API? Having to `const stack = require('tap/lib/stack')` feels a bit dirty, especially considering I doubt its part of the public api.

Thanks!

**Comment by isaacs** [comment]
I'd have to think about that.

In the meantime, you can also use [`t.addAssert()`](http://www.node-tap.org/advanced/#taddassertname-length-fn), which will do all the right stack stuff for you.

**Comment by evanlucas** [comment]
Hm, this was using `t.addAssert()`. The stack trace started where the assert was declared vs where it was called. I'll try to come up with a reproducible test case.

**Comment by isaacs** [comment]
You can set `t.assertAt` and friends to address this: https://www.node-tap.org/advanced/#tassertat-tassertstack-extraat-extrastack

**Comment by evanlucas** [comment]
Thanks a bunch!
