### ISSUE TITLE
Using tap with hapi 17

### ISSUE THREAD

**Issue by yereby** [tapjs/tapjs#419]
Hi there,
I am migrating a project to hapi 17 which pass everything to async/await. And i can't manage to use node-tap even if it was good with hapi 16

I posted an issue there https://github.com/hapijs/discuss/issues/598 to describe it.  
I hope someone here use hapi and have a solution because i am a little stuck.

My test is like that :
```js
const test = require('tap').test
const server = require('../src/index')

test('Home entry', async t => {
  const options = {
    method: 'GET',
    url: '/'
  }

  const response = await server.inject(options)

  t.equal(response.statusCode, 200, 'status code = 200')
  t.equal(response.payload, 'Hello world', 'Text must be Hello world')
})
```

**Comment by isaacs** [comment]
I can't say why Hapi 17 started doing something different than Hapi 16, especially without seeing the output from the test.

This works fine for me, so I think tap is doing the right thing: https://gist.github.com/isaacs/940f29811b479b3309567df02e5189eb

**Comment by yereby** [comment]
From 16 to 17, they passed every promises to async/await.
That's right your gist works fine. Might come from Hapi. 
Thanks for your help.

**Comment by yereby** [comment]
For the record i fixed it with initializing my server in a `beforeAll()` in tests.
cf. https://github.com/hapijs/discuss/issues/598#issuecomment-354723681
