### ISSUE TITLE
lcov coverage report flag launches browser

### ISSUE THREAD

**Issue by ahmadnassri** [tapjs/tapjs#425]
when running `tap` with `--coverage-report=lcov` the browser is automatically opened to `coverage/lcov-report/index.html`.

this seems in conflict with the documentation on the [website](http://www.node-tap.org/coverage/):

> To specify a report format, you can use --coverage-report=<type>. The default type is text, which produces a pretty text-only table on the terminal. **If you specify --coverage-report=html, then tap will attempt to open a web browser to view the report after the test run.**

**Comment by isaacs** [comment]
`lcov` is the same as `html`.  Maybe what you want is `lcov-text`?

Doc patch welcome.

**Comment by ahmadnassri** [comment]
@isaacs gave the docs on this a bit of an update to help future readers: #435
