### ISSUE TITLE
tap.error failing when passed Error object

### ISSUE THREAD

**Issue by timwitty** [tapjs/tapjs#428]
Based off the docs and the projects tests I should be able to do `tap.error(new Error('error test'), 'test tap.error when error passed');` and it should pass. Am I missing something?

It seems nearly identical to this from the tests:
`tt.error(new Error('fail: poop'), 'this error is poop')`

>   not ok test tap.error when error passed
>     found:
>       name: Error
>       stack: |-
>         Error: error test
>             at Object.<anonymous> (/tap-test.js:3:11)
>             at Module._compile (module.js:570:32)
>             at Object.Module._extensions..js (module.js:579:10)
>             at Module.load (module.js:487:32)
>             at tryModuleLoad (module.js:446:12)
>             at Function.Module._load (module.js:438:3)
>             at Module.runMain (module.js:604:10)
>             at run (bootstrap_node.js:394:7)
>             at startup (bootstrap_node.js:149:9)
>             at bootstrap_node.js:509:3
>       message: error test
>     at:
>       line: 3
>       column: 5
>       file: tap-test.js
>     stack: |
>       Object.<anonymous> (tap-test.js:3:5)
>     source: |
>       tap.error(new Error('error test'), 'test tap.error when error passed');

**Comment by isaacs** [comment]
Exact opposite.

> If the object is an error, then the assertion fails.

http://www.node-tap.org/asserts/#terrorobj-message-extra

**Comment by isaacs** [comment]
The tests in this project are verifying that the assertion _fails_ when passed in an object :)

**Comment by timwitty** [comment]
Apparently I can't read 📚, I'll get that checked out.  Thanks for responding and sorry for the bother!
