### ISSUE TITLE
lib/.tap.js.swap in npm package tap@11.1.1

### ISSUE THREAD

**Issue by srl295** [tapjs/tapjs#430]
In the 'oops' category, `lib/.tap.js.swap` is part of the npm package.

No code change needed, except maybe `.gitignore` to taste.

**Comment by isaacs** [comment]
Oops, indeed.  Thanks!

**Comment by srl295** [comment]
welcome, https://github.com/tapjs/node-tap/commit/ddf938b3cc05d1fec67aa830c0d5b9ef8c7dac6b was educational too!
