### ISSUE TITLE
Be true to your world

### ISSUE THREAD

**Issue by rolfen** [tapjs/tapjs#432]
In README.md:

> Most frameworks spend a lot of their documentation telling you why they're the greatest. I'm not going to do that.

But that's exactly what all the Readme is about. The first part reads like an advertisement for the features of tapjs.

Then the part "Why TAP?" enumerates "how testing should be". Since tap is built around these ideas, then you are basically telling me why I should be using TAP, by transitivity.

(I actually want to know why I should use Tap.)

PS: The Readme is actually good, this contradiction just made me uncomfortable.

**Comment by isaacs** [comment]
You seem to have missed this part:

```markdown
### <i lang="it">tutti i gusti sono gusti</i>

Software testing is a software and user experience design challenge
that balances on the intersection of many conflicting demands.

Node-tap is based on [my](http://izs.me) opinions about how a test
framework should work, and what it should let you do.  I do _not_ have
any opinion about whether or not you share those opinions.  If you do
share them, you will probably enjoy this test library.
```

I say, "It's based on my opinions, and if you don't share those opinions, that's fine, but if you do, you might like this library.  Here are those opinions: ..."

Basically, if you agree, it's for you, and if you are saying "um, no, that's not how I see it", then ok, use a different thing (or write your own).  "All tastes are tastes", as they say.
