### ISSUE TITLE
Cannot set property message of ...Error which has only a getter

### ISSUE THREAD

**Issue by mknj** [tapjs/tapjs#437]
er.message is overwritten multiple times in the code.
This is incompatible with assertion libraries that make er.message readonly(getter, but no setter)

Please make "tap" compatible with "should" or update bdd example with compatible assertion library.

# Example
```
var tap = require('tap')
let should = require('should')

tap.test('hello-world', (tap) => {
  x = -1
  x.should.equal(-2)
  tap.end()
})
```
## Expected
```
    not ok 1 - AssertionError: expected -1 to be -2
```

## Actual
```
    not ok 1 - Cannot set property message of AssertionError which has only a getter
```
## Versions
* "should": "^13.2.1"
* "tap": "^11.1.3"
* node v8.10.0

**Comment by isaacs** [comment]
Fixed on 12.1.4.
