### ISSUE TITLE
tap command not working unless tap.js is accessed directly

### ISSUE THREAD

**Issue by oren** [tapjs/tapjs#44]
tap ./test => 
bash: /usr/local/bin/tap: No such file or directory

I had to do this:
./node_modules/tap/bin/tap.js ./test

**Comment by MRdNk** [comment]
If you use scripts.test 'tab ./test' (https://gist.github.com/4469613), you can then use npm test - see the updated readme.

**Comment by andrewdeandrade** [comment]
@oren this is because the value of the `bin` property in `package.json` is `"bin/tap.js"`. Changing `bin` to something like the following would fix this.

``` json
  "bin": {
    "tap.js": "bin/tap.js"
    "tap": "bin/tap.js"
  }
```
