### ISSUE TITLE
Inheriting from Tap

### ISSUE THREAD

**Issue by ericmorand** [tapjs/tapjs#443]
Is there a way to inherit from the Tap class to add some custom assertions?

I'd like to do that:

```
const tap = require('tap');

tap.test('foo', function(test) {
    test.customAssertion();
    test.end();
});
```

**Comment by isaacs** [comment]
You could do this by using the [addAssert method](https://www.node-tap.org/advanced/#taddassertname-length-fn).

**Comment by ericmorand** [comment]
Amazing. How did I miss that?
