### ISSUE TITLE
Duplicate t.resolves and t.rejects message output

### ISSUE THREAD

**Issue by jaydenseric** [tapjs/tapjs#444]
With this test:

```js
'use strict'

const t = require('tap')

t.ok(true, 'Ok.')
t.resolves(Promise.resolve(), 'Resolves.')
```

You get this output:

<img width="277" alt="screen shot 2018-05-15 at 10 39 34 pm" src="https://user-images.githubusercontent.com/1754873/40057194-ee4c49b2-5890-11e8-8f3d-d6801d7f331d.png">

It is unexpected that the `Resolves.` message is duplicated. This behaviour is particularly confusing when using the `list` reporter:

<img width="282" alt="screen shot 2018-05-15 at 10 41 56 pm" src="https://user-images.githubusercontent.com/1754873/40057313-49d67d52-5891-11e8-9cdc-a30a4658f1d9.png">

**Comment by isaacs** [comment]
Fixed in version 13 (coming as soon as node v6 hits EOL, so, in a few weeks.)
