### ISSUE TITLE
Runs test twice when done callback and promise return is used

### ISSUE THREAD

**Issue by bas080** [tapjs/tapjs#448]
Very confusing. This is what I was doing.

```js
beforeEach(done => channel.then(channel => Promise.all([
  channel.assertQueue('my-queue').then(() => channel.purgeQueue('my-queue')),
  channel.assertQueue('my-bound-queue').then(() => channel.purgeQueue('my-bound-queue')),
  channel.assertExchange('my-exchange'),
  channel.bindQueue('my-bound-queue', 'my-exchange', '#'),
]).then(() => done())
```

I know I should be choosing the done callback or promise approach.
It would be nicer if there is a more useful warning or that one approach receives precedence.

I think the done callback should get precedence because it is more explicit and it can be checked before the test function is called.

To recap, the following should result in the tests running once. Currently it will run each test twice.
`beforeEach(done => Promise.resolve().then(() => done()))`

**Comment by isaacs** [comment]
Oh, this is weird and fascinating.  Simpler test:

```js
t.beforeEach(done => Promise.resolve('foo').then(() => done()))
t.test('child', t => t.end())
```

**Comment by isaacs** [comment]
Fixed in v13.
