### ISSUE TITLE
Can’t use both async and regular top level tests

### ISSUE THREAD

**Issue by jaydenseric** [tapjs/tapjs#449]
Using `async` callbacks for all top level tests works:

```js
import t from 'tap'

t.test('1', async t => {
  t.pass()
})

t.test('2', async t => {
  t.pass()
})
```

But mixing async and regular tests like this:

```js
import t from 'tap'

t.test('1', t => {
  t.pass()
})

t.test('2', async t => {
  t.pass()
})
```

Causes errors like this:

<img width="327" alt="screen shot 2018-06-04 at 1 17 57 pm" src="https://user-images.githubusercontent.com/1754873/40896686-cc75a5fe-67f9-11e8-82c3-11c21ccde9db.png">

**Comment by isaacs** [comment]
Yes, there is an error in your test.  It is indeed unfinished.  (Also, it looks like both code samples are the same, maybe a typo?)

The function provided to `t.test()` must do one of three things:

1. Return a `Promise`.  When the promise resolves or rejects, the test is completed.
2. Set a planned number of assertions by calling `t.plan(n)`.  When `n` assertions are filled, the test ends.  (This plan must be set _before_ making any assertions!)
3. Call `t.end()` explicitly.  (If this is done after a plan or promise completion, it's a no-op.)

Since `async` functions return a promise, they're in the first category.  If you want to mix non-async functions with async functions, that's fine.  Just end them by setting a plan, or calling `t.end()` when they're complete.

```js
const t = require('tap')

t.test('plan', t => {
  t.plan(1)
  t.pass('this is fine')
})

t.test('end method', t => {
  t.pass('so is this')
  t.end()
})

t.test('explicit promise', t => {
  t.pass('this is fine')
  return Promise.resolve()
})

t.test('async promise', async t => {
  t.pass('i promise that this is fine')
})
```

**Comment by jaydenseric** [comment]
> it looks like both code samples are the same, maybe a typo?

Yes, it was a typo. Fixed!

> If you want to mix non-async functions with async functions, that's fine. Just end them by setting a plan, or calling t.end() when they're complete.

Thanks for clarifying how it currently works, that is helpful. Would you be open to improving that behavior though? It is not a very intuitive limitation that you need to manually end the test inside a synchronous function; [that is not how other libs like AVA work](https://github.com/avajs/ava#create-your-test-file):

```js
import test from 'ava'

test('foo', t => {
  t.pass()
})

test('bar', async t => {
  const bar = Promise.resolve('bar')
  t.is(await bar, 'bar')
})
```

If there is some sort of technical reason not to, it would be helpful to make the docs more obvious to recommend ***every*** test use an `async` function, or for people with the [`require-await` eslint rule](https://eslint.org/docs/rules/require-await) to alternatively use `t.end()`. Here is what I was doing:

```js
t.test(
  '`execute` middleware options not an object.',
  // eslint-disable-next-line require-await
  async t => {
    try {
      execute(true)
      t.fail('Expected an error.')
    } catch (error) {
      t.matchSnapshot(errorSnapshot(error), 'Creation error.')
    }
  }
)
```

**Comment by jaydenseric** [comment]
Does `t.fail()` properly end the test? Edit: Apparently not.

**Comment by isaacs** [comment]
No, `t.fail(msg)` just prints a failing assertion.  (It's the inverse of `t.pass(message)`.)

> It is not a very intuitive limitation that you need to manually end the test inside a synchronous function; that is not how other libs like AVA work

Well, that's not how _ava_ works.  Most other test frameworks in Node.js either sniff the test function to see if it takes an argument (ie, mocha and lab) and if so, pass in a `done` callback, or (tap, tape, and a few others) provide an object that has to be manually ended, or don't really support asynchrony with callbacks or objects at all (mostly very old test runners, like nodeunit and a few others), so every test has to be 100% synchronous.

Automatically ending tests with sync functions would be a _huge_ change in tap.  There's a massive number of tests out there that do things like:

```js
t.test('foo', t => {
  getSomeFoo(a, b, c, (er, data) => {
    if (er)
      throw er
    t.match(data,  {some: 'thing'})
    t.end()
  })
})
```

Those tests would auto-end and cause a lot of problems if I did what you're suggesting.  Ava started life by doing `t.test.cb(..)` for that use case, but tap follows a different pattern.
