### ISSUE TITLE
Tap bundles a version of yamlish that's out of sync with yamlish repo

### ISSUE THREAD

**Issue by airportyh** [tapjs/tapjs#45]
I found that the tap module on npm bundles with it a yamlish dependency that advertises version 0.0.4 which is out of sync with the 0.0.4 tag on the yamlish repo https://github.com/isaacs/yamlish.git. See https://github.com/isaacs/yamlish/issues/2 for more details on the difference.

**Comment by isaacs** [comment]
Fixed.  Published to 0.0.5

**Comment by airportyh** [comment]
Thanks!
