### ISSUE TITLE
Gigantic object diffs are not helpful

### ISSUE THREAD

**Issue by focusaurus** [tapjs/tapjs#451]
The output for a failed `t.match(found, wanted)` is sometimes huge. A specific example I get is I do `t.match(res, {id: 7})` with a response object instead of using `res.body`. The output of this is like a terabyte and I lose my terminal scrollback buffer and can't see anything else about the output of the test run. Would you consider some reasonable default of truncating this to like 200 lines or something? I briefly looked into this and it seems we are using `util.inspect` to generate this but with `{depth: Infinity}`. I feel like smaller truncated output is a more developer-friendly default and really wanting a gigantic printout is a less common case.

**Comment by jdgriffith** [comment]
+1

**Comment by isaacs** [comment]
Related: #495

**Comment by isaacs** [comment]
It should probably collapse everything outside the immediate diff context, like git does.

**Comment by isaacs** [comment]
Landed in v13 using the tcompare module.
