### ISSUE TITLE
Trailing whitespace in snapshots

### ISSUE THREAD

**Issue by nponeccop** [tapjs/tapjs#454]
Git may be configured to highlight "whitespace errors" in diffs, such as trailing space. 

I assume that the trailing space is added by `util.inspect()` or whatever is used by `tap`. So maybe  postprocessing of `util.inspect()` output to remove the trailing space is the way to go. And we could report this problem upstream to fix `util.inspect()` in future releases of node (which won't make life easier for those using older releases).

**Comment by isaacs** [comment]
I think this would be fixed along with #450 by moving away from using util.inspect and creating a userland module instead.

**Comment by isaacs** [comment]
Done in v13.
