### ISSUE TITLE
Earliest compatible node version is not 0.10

### ISSUE THREAD

**Issue by ZJONSSON** [tapjs/tapjs#459]
The README states that tap `works on any version of Node.js back to v0.10.`   In reality the library now uses `const` and fat arrow functions and does not work for node version prior to `4`.

It might be helpful to update the  README to explicitly state the earliest node version supported (I think it's 4) and possibly provide a link to the latest possible version of tap that  that supports v0.10 and up.

Any library that wants to maintain v0.10 backwards compatibility tests will have to pin tap to an old version.
For example I'm not able to use the latest version [here](https://travis-ci.org/ZJONSSON/node-unzipper/builds/399718363) and will have to revert back to the old tap.

**Comment by isaacs** [comment]
Yes, that is an oversight in the documentation. Node 0.10 is out of LTS, and insecure to continue using. Doc patch welcome, or I’ll fix soon.

**Comment by isaacs** [comment]
d7bd496cb21d080512a059634e68ebd0a05f1f84

**Comment by ZJONSSON** [comment]
Thanks @isaacs !
