### ISSUE TITLE
Add hint to which error mechanism caught an error

### ISSUE THREAD

**Issue by martinheidegger** [tapjs/tapjs#460]
In the code there are various places that catch errors in a test. Particular of pain for me are the `uncaughtException` and `unhandledRejection` handlers: An error occurred in my test and I wasn't sure if that was because of a promise result of a third-party library or an unexpected exception, it turned out to be an `unhandledRejection`... It would have been really helpful to know where a particular error was raised.

**Comment by isaacs** [comment]
I agree.  Each of the mechanisms should decorate the error with an indicator of where it was intercepted.

**Comment by isaacs** [comment]
It's not well documented, but it'll show up in the error reports now, as of 12.2.1.  I tried to make the strings somewhat self-explanatory.  Let me know if you get around to using it and have any suggestions :)
