### ISSUE TITLE
Explanations for TODO and SKIP

### ISSUE THREAD

**Issue by NonBinarySearch** [tapjs/tapjs#461]
This used to be in the library but was removed in [this commit](https://github.com/tapjs/node-tap/commit/30c9a0ced753be63fd57b994cfbe8d9e52041905). It would be nice to add them to the library again since it is included in the TAP specification (both 12 and 13).

**Comment by NonBinarySearch** [comment]
Nevermind, you just need to pass in a string in extra. Wish this is more clearly documented.

**Comment by isaacs** [comment]
I think that's how it's always been, isn't it?

What code were you running that you expected to emit a todo/skip message but didn't?  Maybe I could just make that work.

**Comment by NonBinarySearch** [comment]
Well it's working now. Basically I want to print something like this

```
ok 1 message # TODO explanation
```

which you can do with the library using the following code:

```
t.ok(true, "message", {todo : "explanation"});
```

I think a long time ago there was a `res.explanation` which is derived from `extra.explanation`, like from [this commit](https://github.com/tapjs/node-tap/pull/122/commits/900774a897888d4eeb59f1111b452680d942d7ad), I didn't realise that there was a refactor mentioned in the OP that changed how this works.
