### ISSUE TITLE
tap is not waiting for t.tearDown to finish

### ISSUE THREAD

**Issue by jsardev** [tapjs/tapjs#462]
Is `async/await` supported by `tearDown` method? Because it looks like it's not. Take a lot at this example:

```js
const { test } = require('tap');

const someAsyncFunc = () => new Promise(resolve => setTimeout(resolve, 500));

test('suite setup', t => {
  console.log('setting up...');
  t.end();
});

test('test', t => {
  console.log('testing stuff...');

  t.tearDown(async () => {
    await someAsyncFunc();
    console.log('test teardown...');
  });

  t.end();
});

test('suite teardown', t => {
  console.log('shutting down...');
  t.end();
});
```

The result is:

```
TAP version 13
setting up...
# Subtest: suite setup
    1..0
ok 1 - suite setup # time=2.128ms

testing stuff...
# Subtest: test
    1..0
ok 2 - test # time=0.495ms

shutting down...
# Subtest: suite teardown
    1..0
ok 3 - suite teardown # time=0.31ms

test teardown...
1..3
# time=511.285ms
```

As you can see - another test is launching before the previous one actually ended. Is this a bug or is this an expected behaviour?

**Comment by isaacs** [comment]
Yeah, `teardown` functions aren't waited for.  They're just synchronously called.  I think it's a good feature request for them to pause when a promise is returned, but the implementation at the moment is just an event handler.  `t.teardown(fn)` just does `t.on('teardown', fn)`.

**Comment by jsardev** [comment]
@isaacs Would be awesome! I don't have much time this month, but in the next one if no one will take it I'll try to implement this feature 👍

**Comment by isaacs** [comment]
Done in v13

**Comment by jsardev** [comment]
> I don't have much time this month, but in the next one if no one will take it I'll try to implement this feature

Wow, when will I learn that I shouldn't tell that I'll be able to take some work if I'm not totally sure about it? :sweat_smile: Thank you @isaacs for implementing this!

**Comment by isaacs** [comment]
@sarneeh No worries!  We're all overly optimistic :)
