### ISSUE TITLE
Uncaught errors not handled correctly when piping to a reporter

### ISSUE THREAD

**Issue by jaydenseric** [tapjs/tapjs#463]
With `test.js`:

```js
const t = require('tap')

throw new Error('Uncaught!')

t.test('A test.', t => {
  t.pass('Ok!')
  t.end()
})
```

Running:

```
node test | tap-mocha-reporter spec
```

Results in:

```
$ npm run repro

> fake@0.0.0 repro /Users/jaydenseric/Sites/fake
> node test | tap-mocha-reporter spec


/Users/jaydenseric/Sites/fake/test.js:3
throw new Error()
      ^
Error
    at Object.<anonymous> (/Users/jaydenseric/Sites/fake/test.js:3:7)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)

  0 passing (NaNms)
```

Issues:

- The `0 passing` is colored green and there is no red on the screen; it looks like nothing is wrong.
- The `NaNms`.
- That the script exits cleanly without an error. I have had Travis builds pass that had zero tests run due to a nasty error!

If this turns out to be conceptually unfixable, the issues should be caveated in the docs when explaining the node script piping to a reporter approach.

I can't use the `tap` bin script because I need to test native ESM via `.mjs`, something it can't handle yet: https://github.com/tapjs/node-tap/issues/409 😢

**Comment by isaacs** [comment]
In this case, the error is being thrown before tap has instrumented the process object to handle uncaughtExceptions.  (It does this on the first test creation, to avoid messing up cases where people want to require('tap') to use the exported classes.)

Consider the difference if you run this script instead:

```js
const t = require('tap')

t.test('A test.', t => {
  t.pass('Ok!')
  t.end()
})

throw new Error('Uncaught!')
```
Then piping to the spec reporter works fine.
```
$ node t.js | tap-mocha-reporter spec

    ok 1 - Ok!
    1..1
A test.
  ✓ A test.
  1) Uncaught!

  1 passing (17.595ms)
  1 failing

  1) A test. Uncaught!:
     Error: Uncaught!
      at Object.<anonymous> (t.js:8:7)
```

If you are worried about an uncaught exception happening before any tests have been added, you can run `t.patchProcess()` as soon as tap is loaded.

(Fwiw, `.mjs` support landed on 12.3.)

**Comment by jaydenseric** [comment]
Wow, `t.patchProcess()` is a great tip! I look forward to trying it out. I'll probably put it first thing in my test file anytime I lead with non-test code.

**Comment by isaacs** [comment]
You could also put your non-test setup stuff in a `t.test()` block.  I do that sometimes just to keep stuff organized.  (For bonus points, if it's an async function, you can `await` any promises, and you don't have to bother with having to call `t.end()`.)
