### ISSUE TITLE
Problem with timeout and test with promise

### ISSUE THREAD

**Issue by jbergknoff-rival** [tapjs/tapjs#472]
I expect a test's timeout to cut off execution at that point, and report a failure. Instead, what I'm seeing is that the timeout fires, but the test doesn't stop. Example with tap@12.0.1:

```
const tap = require('tap');

tap.test(
    { timeout: 1000 },
    async (t) => {
        return new Promise(
            (resolve) => {
                setTimeout(() => {}, 3000);
            }
        );
    }
);
```

Output:

```
TAP version 13
# Subtest
    not ok 1 - timeout!
      ---
      expired: ''
      timeout: 1000
      ...
    
    1..1
    # failed 1 test
not ok 1 # time=1023.387ms
  ---
  timeout: 1000
  ...

1..1
# failed 1 test
# time=3013.534ms
```

The first "failed 1 test" output is printed at the one-second mark, but the test continues until the three-second mark when the `setTimeout` fires and the rest is printed. Is this the intended behavior? Is it waiting on open handles or something? Is there an option to make the test abort upon timeout?

**Comment by isaacs** [comment]
It is indeed waiting on open handles.

You can either run the test with the tap runner, and pass in `-b` or explicitly set a bailout when it times out.  Something like this should work:

```js
const tap = require('tap');

tap.test(
    { timeout: 1000 },
    async (t) => {
        t.on('timeout', () => t.bailout('timeout'))
        return new Promise(
            (resolve) => {
                setTimeout(() => {}, 3000);
            }
        );
    }
)

tap.on('timeout', console.error)
```

**Comment by isaacs** [comment]
Note that a bailout will abort the entire test run, so if you just wanna forcibly exit and abort that one test file, you can just do `process.exit(1)` instead.
