### ISSUE TITLE
Reading .env files.

### ISSUE THREAD

**Issue by lgertel** [tapjs/tapjs#484]
Hello everyone!

I have a specific service in my application that i wish to test using tap. Inside of it, there are some files that declares constants using require with arguments that comes from .env.

It seems that the tap command doesn't load them.
What i'm missing?

Thanks

**Comment by isaacs** [comment]
`.env` files aren't automatically injected into the environment.  It has to be done by some bit of code somewhere, probably whatever is running your application.  You can do this in your test script if you'd like, probably something like this?

```bash
env $(cat .env) tap test/*.js
```

I wouldn't be opposed to a feature request to add environs to the tap process somehow, but it'd be a new feature.
