### ISSUE TITLE
No diff when comparing Map instances

### ISSUE THREAD

**Issue by jaydenseric** [tapjs/tapjs#489]
When asserting `Map` instances are equal, like this:

```js
t.test('Maps are the same', t => {
  t.strictDeepEqual(new Map([['a', 'a']]), new Map([['a', 'a']]))
  t.end()
})
```

A passing test looks ok:

<img width="235" alt="screen shot 2018-12-19 at 6 49 20 pm" src="https://user-images.githubusercontent.com/1754873/50206221-d2fd5c80-03be-11e9-8c61-f2539780789c.png">

A failing test like this however:

```js
t.test('Maps are the same', t => {
  t.strictDeepEqual(new Map([['a', 'a']]), new Map([['b', 'b']]))
  t.end()
})
```

Displays without a diff of what is wrong like this:

<img width="359" alt="screen shot 2018-12-19 at 6 43 34 pm" src="https://user-images.githubusercontent.com/1754873/50205940-0be90180-03be-11e9-9d9a-0320bc34bd08.png">

Ideally there would be a visual diff comparing the expected and actual map keys/values.

If that is too difficult to achieve, the `+ expected` and `- actual` labels should not display.

**Comment by isaacs** [comment]
Yeah, this is a shortcoming of the formatter in tap-mocha-reporter.  That module is in dire need of refactoring/rewriting anyway.

**Comment by isaacs** [comment]
Landed in v13, using the tcompare module.
