### ISSUE TITLE
Is it safe to use `silent` in a test's options?

### ISSUE THREAD

**Issue by m90** [tapjs/tapjs#490]
I was trying to add a one-time `before` and `after` hook to a series of tests. I was surprised to find out this is available in the Mocha-like DSL, but not in the standard `tap` API.

Looking at the code here: https://github.com/tapjs/node-tap/blob/92c3940650300cbdd9d62fab73e1296ffa3168de/lib/mocha.js#L61 it looks like these hooks are just tests that do not report. This seems to be done by passing an option of `slient: true`.

This lets me write something like

```js
tap.test('suite', t => {
    t.test('before', {silent: true}, t => {
        prepareThings()
        t.end()
    })
    // lots of tests
    t.test('after', {silent: true}, t => {
        cleanupThings()
        t.end()
    })
    t.end()
})
```

I am wondering one thing though: `silent` as an option is currently not documented, so I wonder if it is safe for me to use it as an option? Is there a better way of doing this? The solutions in https://github.com/tapjs/node-tap/issues/325 did not really fit my usecase.

**Comment by isaacs** [comment]
It's an implementation detail, and not generally a good idea, if only because it makes the output a bit misleading.  But there's no plans to remove that, and I'd accept a doc patch to add it, provided it had the caveat about it not be a great idea to silence test output at that level.
