### ISSUE TITLE
Use c8 for coverage instead of nyc

### ISSUE THREAD

**Issue by isaacs** [tapjs/tapjs#493]
This should produce the same coverage output, but run much faster.

Need https://github.com/bcoe/c8/pull/59 to land so we can do `--100`.

**Comment by isaacs** [comment]
Either wait for Node v10 to fall off LTS, or fork based on Node version and use nyc/c8 as appropriate.

**Comment by brody2consult** [comment]
> wait for Node v10 to fall off LTS

According to [c8 Supported Node.js Versions](https://github.com/bcoe/c8#supported-nodejs-versions) it should be possible to use c8 on Node.js back to 10.12.0, which came before LTS (10.13.0) and security updates (10.14.0). And according to [Node.js Release Schedule](https://github.com/nodejs/Release#release-schedule), Node.js pre-10 will reach EOL this year.

> use nyc/c8 as appropriate

Any reason to run coverage on Node.js pre-10?

**Comment by isaacs** [comment]
Oh, I guess we can do it as of node version 10, then!

**Comment by isaacs** [comment]
> Any reason to run coverage on Node.js pre-10?

Yeah?  I personally think you should always run tests with coverage.  It's going to become the default in tap v13.

**Comment by brody2consult** [comment]
> I personally think you should always run tests with coverage.

Got it (missed the built-in test coverage).

"Use nyc/c8 as appropriate" would solve this problem, which would go away with Node.js 8 EOL in less than 1 year. Hope this would not add too much complexity:)

> Need [bcoe/c8#59](https://github.com/bcoe/c8/pull/59) to land so we can do `--100`.

Ugly alternative would be to make a temporary fork

**Comment by isaacs** [comment]
I have it on excellent authority that the c8 PR will land long before I get around to doing any of this :)

**Comment by mohd-akram** [comment]
Any update on this?

**Comment by coreyfarrell** [comment]
You should be able to use `c8 tap --no-cov` now (be sure to `npm i -D c8`).

I'm not aware of any firm plans to move forward with switching to c8 now, as of right now the tap v15 WIP branch is upgrading nyc to 15.x.  Any further updates will be posted here.

**Comment by eljefedelrodeodeljefe** [comment]
I'd also favour making the coverage backend configurable. Running with no-cov and piping, works, however not with --watch.

I face a lot of challenges with `{"type": "module"}`, that got solved through c8 (but not in the watch scenario)

**Comment by isaacs** [comment]
This is in tap 18. `npm i tap@pre` to get it. Be sure to read through the [changelog](https://node-tap.org/changelog/#18.0), as a lot has changed.

**Comment by bennycode** [comment]
@isaacs do you have a link to the commit where the switch from `nyc` to `c8` was happening? I also want to swtich to `c8` and could learn from it. In the [linked changelog](https://node-tap.org/changelog/#18.0) I just found this entry (without a link to the code changes):

> Options related to nyc are removed, as nyc is no longer used

**Comment by isaacs** [comment]
@bennycode Well, there isn't so much "a" commit as much as "completely rewrote tap, using @tapjs/processinfo, which uses the V8 coverage API directly". When building the @tapjs/run component, I made it pull in C8's `Report` class to generate the coverage reports.

If you're just switching from nyc to c8, and you're using nyc directly like `nyc <command>`, you can just do `c8 <command>` instead, as they have pretty much the exact same API. If you're using nyc internals, well, it's a whole different thing, so you might want to take a look at how @tapjs/processinfo works.

**Comment by bennycode** [comment]
Thanks a lot for your answer! 

Switching from `nyc` to `c8` was way easier than I expected. If I don't provide a config option, `c8` automatically looks for a [.nycrc.json](https://github.com/bcoe/c8/pull/100) file. I had mine named [nyc.config.js](https://github.com/istanbuljs/nyc#configuration-files), so all it took was a rename and removing the  `"require": ["ts-node/register"]` option from my config. 

I can now run my tests with good ol' Jasmine in a TypeScript project that has ESM import/export syntax:

```json
{
  "scripts": {
    "test": "c8 --config=.c8rc.coverage.json ts-node-esm ./node_modules/.bin/jasmine --config=jasmine.json"
  }
}
```

Thanks for your help! 👍
