### ISSUE TITLE
Re-architect test output reporters

### ISSUE THREAD

**Issue by isaacs** [tapjs/tapjs#494]
The current set of test output reporters is more than a little bit jank.

- It lives in a separate repo, which parses the test output into a completely different object format, just to be able to use the Mocha reporters (which are way out of date now, and mostly gimmicks other than spec)
- People only seem to use classic, tap, and spec anyway.  Better to just implement classic and spec in a good way.
- Provide good tests for reporters!  It's valuable, and deserves good coverage.

**Comment by evanlucas** [comment]
We use the xunit reporter quite heavily to integrate with GitLab's PR widget that shows test failures and such (https://docs.gitlab.com/ee/ci/yaml/README.html#artifactsreportsjunit). Are you planning on removing that one?

**Comment by isaacs** [comment]
@evanlucas Not anymore! lol

But seriously, I'll probably keep the ones that are easy to implement correctly and have a clear utility.  Xunit is pretty trivial and used by a lot of stuff, so I don't expect to drop it.  Runway and nyan cat are marked for removal, for sure.

**Comment by jsumners** [comment]
Another vote to keep xunit. I use it to get result artifacts into CircleCI's interface.

**Comment by isaacs** [comment]
As it happens, all the old test reporters will stick around, and I'll just add a few new ones that are fancier and more responsive.

**Comment by isaacs** [comment]
I'm calling this done for now.  It can keep improving, but by keeping around the older tap-mocha-reporter reports, and supporting React.Component style reporting with treport, it's looking pretty good, and there's a framework for adding new reporters.  You can also now do stuff like `-R my-tap-reporter-stream-or-component` and it'll load it either as a CLI program or a module.
