### ISSUE TITLE
track which test file loads which source modules

### ISSUE THREAD

**Issue by isaacs** [tapjs/tapjs#496]
This would be useful for `--watch` and `--only-changed`, so probably should just be a thing we do?

**Comment by jsumners** [comment]
This would be fantastic. I currently use `nodemon` to fake it. This is probably the biggest advantage of Ava over Tap on my team. Ava will recognize which tests have had code changed and only re-run those tests when using its watch mode.

**Comment by isaacs** [comment]
Hm, using `find-imports` isn't going to work for this, because child processes.

I think it's better to just look at the coverage graph that nyc generates.

**Comment by isaacs** [comment]
- [ ] add `--generate-process-tree` option to nyc, to generate the process tree info without displaying it.
- [ ] enable this whenever coverage is on
- [ ] track the pids of each spawned child test
- [ ] after the run, ingest the process tree info and link to the coverage info to see which files got some coverage from each test run.
- [ ] write this info somewhere, along with hashes of each source file, and each test file
- [ ] when run with the `--only-changed` option, run any tests where the test or any covered file has a different hash

Not sure if this is worth getting into v13.0 or if it should wait for v13.1.  There's already a lot of stuff on deck, and this could come in a later minor version bump.

**Comment by jsumners** [comment]
Would that mean the following is possible:

```
$ tap —watch —only-changed —cov 'test/**/*.test.js'
```

**Comment by isaacs** [comment]
@jsumners Yes!  But in v13, that'll probably be just `tap -w`  It already loads all the js files in test, coverage is on by default, and watching will imply `--only-changed`.  I guess if you had files in test that you _don't_ want run (like `test/not-a-test.foo.js` or something), then you'd need the glob still.

**Comment by isaacs** [comment]
One thing I still need to wrap my brain around is how to do `--100` if you're only running what changes.  Maybe it'll just run nyc with a `--include` to only cover the source files that changed.

**Comment by jsumners** [comment]
👍

Yes, I normally have fixtures and such in the test tree that get excluded by the glob.

**Comment by isaacs** [comment]
```js
    const testLinkTree = {}
    const pids = []

    tap.on('subtestAdd', t =>
      t.on('process', proc =>
        pids.push(proc.pid)))

    process.on('exit', () => {
      fs.readdirSync('.nyc_output/processinfo').forEach(f => {
        const info = require(process.cwd() + '/.nyc_output/processinfo/' + f)
        if (pids.indexOf(+info.pid) === -1)
          return

        const testfile = info.argv[1]
        const cov = require(info.coverageFilename)
        const files = Object.keys(cov)
        testLinkTree[testfile] = files
      })
      console.log(testLinkTree)
    })
```

**Comment by isaacs** [comment]
This is actually done now, because nyc v14 will log the "external id" of each test run in the `.nyc_output/processinfo/index.json` file.  Not doing anything with it yet, but the framework is in place.  This also means that re-running a test with `--nyc-arg=--clean=false` will still clean out _just_ the coverage info related to that test run, if it was ever run in the past, so no duplicate info.
