### ISSUE TITLE
Run scripts in a worker_thread instead of child_process.spawn

### ISSUE THREAD

**Issue by isaacs** [tapjs/tapjs#497]
This is pretty experimental, but it'd probably be hecka fast to run in Workers instead of spinning up a child proc for each test file.

We'll have to shim some stuff, so there'd need to be a wrapper script to set up argv, env, etc. and then load the main.  (It can get these things via `workerData`.)

Don't bother figuring out how to spawn_wrap to instrument nyc into a worker.  Just rely on c8 eventually being there, since it'll span thread boundaries.

**Comment by Santinell** [comment]
API for module `worker_thread` becomes `Stable`.
I think it's a great news.

**Comment by coreyfarrell** [comment]
I'm investigating ways for nyc to apply in workers, nothing concrete so far.  To do it reliably I think will require additional functionality to worker threads.

**Comment by isaacs** [comment]
Tap 18 has `t.worker()` enabled by default now.

Tbh, it's often slower than `t.spawn()`, just because the test startup time is really dominated by typescript compilation and node startup in most cases, and the child procs have IPC anyway, so.... yeah. Idk.

But it's there, you can play around with it. `npm i tap@pre` to get it. Be sure to read through the [changelog](https://node-tap.org/changelog/#18.0), as a lot has changed.
