### ISSUE TITLE
Preload esm for all javascript test files

### ISSUE THREAD

**Issue by isaacs** [tapjs/tapjs#503]
Just make `-r esm` the default `nodeArgs` option in bin/run.js.  Bonus: also does the ""right"" thing for mjs files.

This does mean that tests will have to be run with `node -r esm test.js` to perfectly match, but only if they use es modules.

**Comment by isaacs** [comment]
Landed in 12.5

**Comment by Twipped** [comment]
Is there a way to disable this? We don't use ESM in any of our services, and apparently one of our modules has a bug that only exists in their ES build but is fine in their CJS code. So our tests run fine in node plain, but crash in tap.

**Comment by isaacs** [comment]
> Is there a way to disable this? We don't use ESM in any of our services,
> and apparently one of our modules has a bug that only exists in their ES
> build but is fine in their CJS code. So our tests run fine in node plain,
> but crash in tap.
>
Yes.

Put `--no-esm` on the command line, or `esm: false` in `.taprc`, or `"tap":
{"esm": false}` in `package.json`.
