### ISSUE TITLE
Syntax errors on node 4

### ISSUE THREAD

**Issue by leongold** [tapjs/tapjs#508]
Hey,

Release `12.4.0` (and upwards) cause syntax error when running against node 4:

```
/home/travis/build/snyk/snyk-docker-plugin/node_modules/tap/node_modules/ts-node/node_modules/arg/index.js:3
function arg(opts, {argv, permissive = false, stopAtPositional = false} = {}) {
                   ^
SyntaxError: Unexpected token {
```

```
$ node --version
v4.9.1
$ npm --version
2.15.11
$ nvm --version
0.34.0
```

**Comment by isaacs** [comment]
Node v4 hit its [LTS end of life on 2018-04-30](https://github.com/nodejs/Release#end-of-life-releases).  It hasn't been supported for almost a year now.  I recommend using tap v11, or upgrading your node platform to a version that is still receiving regular bug fixes and security updates.  Node v10 is currently in active LTS status, and will be supported through April 2021.
