### ISSUE TITLE
v ^12.5.0 produces error when calling rewire module.__set__

### ISSUE THREAD

**Issue by mfolkeseth** [tapjs/tapjs#509]
I'm not sure why, but from version 12.5.0 of tap, using rewire's `module.__set__` produces the following error ***ReferenceError: _ff9‍ is not defined***.

A full description of the issue is [here](https://github.com/jhnns/rewire/issues/158). Not sure whether the issue belongs here or over at `rewire`

**Comment by isaacs** [comment]
Yeah, this looks suspiciously like an esm issue.

Does the test work if you do `node test/data_test.js` directly?

Ping @jdalton

**Comment by mfolkeseth** [comment]
Yea, `node test/data_test.js` works just fine.

This is our test script `"test": "NODE_ENV=test tap $(find test -name '*.js')"`

**Comment by jdalton** [comment]
Hi @mfolkeseth!

I've patched the `esm` issue at https://github.com/standard-things/esm/commit/38849cee4f39a2d3c2d803c2bdc0c5e75a219f88.
I'll update this issue when I've published a release.

**Update:**

[v3.2.5](https://github.com/standard-things/esm/releases/tag/3.2.5) is released 🎉

**Comment by jdalton** [comment]
**Update:**

[v3.2.5](https://github.com/standard-things/esm/releases/tag/3.2.5) is released 🎉

**Comment by mfolkeseth** [comment]
Thanks a lot @jdalton!

Thanks for solving the issue 🎉 
I'll close this 👍
