### ISSUE TITLE
 Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by IamTheHttp** [tapjs/tapjs#510]
Hey,

**Tap Version:** 12.5.3

**tap.js file:**
```
import tap from 'tap';

tap.test('My 2nd test', (test) => {
  test.same(true, true, 'lol');

  test.equal({lol:111}, {foo:'bar'}, 'ehehe');
  test.end();
});

```

Command ran:
 tap tap.js --reporter=spec

Output/Error:

TypeError: Cannot read property 'split' of undefined
    at unifiedDiff (.../tap-mocha-reporter/lib/reporters/base.js:398:24)

The specific line code:

```
  var lines = (err.diff.split('\n').slice(2) ||
    diff.createPatch('string', err.actual, err.expected)
     .split('\n').slice(4));

```
It seems that err.diff is not defined, so running a .split() on undefined causes this problem.
Am I doing something wrong? Missing a flag or something?

**Comment by isaacs** [comment]
You are doing nothing wrong.  Fixed now.  `npm i tap@latest` and it should start working.  (The bug is in the `tap-mocha-reporter` lib, which is slated for replacement as soon as I can.)
