### ISSUE TITLE
Running test on node.js nightly snapshots and release candidates fails with TypeError: Invalid Version: 

### ISSUE THREAD

**Issue by trygve-lie** [tapjs/tapjs#515]
I am running tests in cron on Travis against node.js nightly snapshots and release candidates and after updating tap to the latest release these have suddenly started breaking with the following:

```js
> tap test/*.js
/home/travis/build/trygve-lie/abslog/node_modules/esm/esm.js:1
var __global__ = this;(function (require, module, __shared__) { var __shared__;const e=module,t={Array:global.Array,Buffer:global.Buffer,Error:global.Error,EvalError:global.EvalError,Function:global.Function,JSON:global.JSON,Object:global.Object,Promise:global.Promise,RangeError:global.RangeError,ReferenceError:global.ReferenceError,Reflect:global.Reflect,SyntaxError:global.SyntaxError,TypeError:global.TypeError,URIError:global.URIError,eval:global.eval},r=global.console;module.exports=(function(e){var t={};function r(i){if(t[i])return t[i].exports;var n=t[i]={i:i,l:!1,exports:{}};return e[i].call(n.exports,n,n.exports,r),n.l=!0,n.exports}return r.d=function(e,t,r){Reflect.defineProperty(e,t,{configurable:!0,enumerable:!0,get:r})},r.n=function(e){return e.a=e,function(){return e}},r(r.s=2)})([(function(e,t){var r;t=e.exports=H,"object"==typeof process&&process,r=function(){},t.SEMVER_SPEC_VERSION="2.0.0";var i=256,n=Number.MAX_SAFE_INTEGER||9007
TypeError: Invalid Version: 10.15.2.0

/home/travis/build/trygve-lie/abslog/node_modules/esm/esm.js:1
var __global__ = this;(function (require, module, __shared__) { var __shared__;const e=module,t={Array:global.Array,Buffer:global.Buffer,Error:global.Error,EvalError:global.EvalError,Function:global.Function,JSON:global.JSON,Object:global.Object,Promise:global.Promise,RangeError:global.RangeError,ReferenceError:global.ReferenceError,Reflect:global.Reflect,SyntaxError:global.SyntaxError,TypeError:global.TypeError,URIError:global.URIError,eval:global.eval},r=global.console;module.exports=(function(e){var t={};function r(i){if(t[i])return t[i].exports;var n=t[i]={i:i,l:!1,exports:{}};return e[i].call(n.exports,n,n.exports,r),n.l=!0,n.exports}return r.d=function(e,t,r){Reflect.defineProperty(e,t,{configurable:!0,enumerable:!0,get:r})},r.n=function(e){return e.a=e,function(){return e}},r(r.s=2)})([(function(e,t){var r;t=e.exports=H,"object"==typeof process&&process,r=function(){},t.SEMVER_SPEC_VERSION="2.0.0";var i=256,n=Number.MAX_SAFE_INTEGER||9007
TypeError: Invalid Version: 10.15.2.0

test/log.js ........................................... 0/1
  not ok test/log.js
```

Here the output from `node --version` is `v10.15.2-rc.0`, but the error message yelds `TypeError: Invalid Version: 10.15.2.0`. My assumption is that there is something (esm.js?) here which parses the node.js version which gets it wrong and then breaks due to not finding it to be a legal version.

The above is from here: https://travis-ci.org/trygve-lie/abslog/jobs/501096606

Its pretty consistent in all my repos. Some examples:
https://travis-ci.org/trygve-lie/objobj/builds/501415711
https://travis-ci.org/metrics-js/process/builds/501135972
https://travis-ci.org/trygve-lie/ttl-mem-cache/builds/501092474
https://travis-ci.org/trygve-lie/abslog/builds/501096587

**Comment by isaacs** [comment]
ping @jdalton

Yeah, looks like esm is to blame here.  That should be a valid version, must be getting munged somewhere along the way, I'd guess.

**Comment by jdalton** [comment]
Thanks for the ping. I have an idea of where the issue is. I'll patch/release asap (within a day or two).

**Update:**

Bug in https://github.com/standard-things/esm/blob/master/src/util/strip-prerelease-tag.js.

**Update:**

Since `esm` is already using `node-semver` I can solve it by just parsing it or using [`SemVer.coerce()`](https://github.com/npm/node-semver#coercion).

**Comment by jdalton** [comment]
**Update:**

Bug in https://github.com/standard-things/esm/blob/master/src/util/strip-prerelease-tag.js.

**Comment by trygve-lie** [comment]
Thanks for the quick response =)

**Comment by jdalton** [comment]
`esm` [v3.2.11](https://github.com/standard-things/esm/releases/tag/3.2.11) is released :tada:

**Comment by trygve-lie** [comment]
Awesome! I can confirm this fixes it. I did re-run one of the above tests: https://travis-ci.org/metrics-js/process/builds/501135972

Thanks a lot :100:
