### ISSUE TITLE
12.5 significantly slower than 12.4

### ISSUE THREAD

**Issue by jsumners** [tapjs/tapjs#516]
I have a very simple test repository at https://github.com/jsumners/tap-slow-test

The same code consistently takes about twice as long to test with Tap 12.5 as it does with Tap 12.4. This is causing people on my team to consider 12.5 a no-go. My completely wild guess is it has to do with the ESM loader. Is it possible to disable this loader? We do not use ESM modules.

<img width="1614" alt="package json tap-slow-test 2019-03-05 08-17-06" src="https://user-images.githubusercontent.com/321201/53808120-6efb2680-3f1f-11e9-9902-e2f831672188.png">

**Comment by isaacs** [comment]
It isn’t currently, but I already have a switch in v13. I can backport that and cut a v12.6 release soon. In the meantime, stick to 12.4. Sorry for the inconvenience.

**Comment by jsumners** [comment]
Thank you very much.

**Comment by isaacs** [comment]
Word from @jdalton is that this has to do with esm blowing away its cache when coverage is turned on.  He's digging into a way to make esm and nyc play nice together.

**Comment by jdalton** [comment]
Relevant code [standard-things/esm/src/caching-compiler.js#L173-L181](https://github.com/standard-things/esm/blob/a42303e739bcbc010b9bc60d6493bf92f9c4fc44/src/caching-compiler.js#L173-L181).

**Comment by isaacs** [comment]
In the meantime, update to tap v12.6, and add `--no-esm` if you prefer.

**Comment by jdalton** [comment]
Patched https://github.com/standard-things/esm/commit/94a8e7cb73fd959452144d7b5f17ff5ebc736f83;

**Update:**

`esm` [v3.2.12](https://github.com/standard-things/esm/releases/tag/3.2.12) is released 🎉

**Comment by jdalton** [comment]
**Update:**

`esm` [v3.2.12](https://github.com/standard-things/esm/releases/tag/3.2.12) is released 🎉

**Comment by jsumners** [comment]
Awesome. Thanks for the work guys.
