### ISSUE TITLE
ESM modules breaking tests

### ISSUE THREAD

**Issue by djMax** [tapjs/tapjs#517]
At the least, I think this is a semver violation, but not sure the root cause. As of tap 12.4.0 our tests work fine, with 12.5, they all fail with this:

```
> tap --node-arg=-r --node-arg=@babel/register "tests/test_startup.js"

tests/test_startup.js ................................. 1/2 5s
  start app for test_startup
  not ok Unexpected token import
    stack: |
      SyntaxError: Unexpected token import
          Object._compile (node_modules/pirates/lib/index.js:99:24)
          Object.newLoader [as .js] (node_modules/pirates/lib/index.js:104:7)
      From previous event:
          GbService.configure (node_modules/@gasbuddy/service/src/Service.js:108:26)
          <anonymous>
    type: SyntaxError
    tapCaught: returnedPromiseRejection
    test: start app for test_startup

total ................................................. 1/2
```

I'm not sure the logic behind adding esm to tap, but it breaks babel in some way.

**Comment by isaacs** [comment]
@jdalton, is this related to the stuff that you were just working on to get it playing more nicely with NYC?

**Comment by jdalton** [comment]
How does `tap` order the `--node-arg`  additions. Is `esm` loaded after or before?

**Comment by isaacs** [comment]
`esm` is loaded first, then whatever other node-arg arguments get appended to that.

**Comment by jdalton** [comment]
@isaacs Perfect! (`esm` has scenario tests with `@babel/register`)

@djMax Could you produce a small repro. That would help me diagnose the issue and get a fix out.

**Comment by isaacs** [comment]
In the meantime, update to tap v12.6, and add `--no-esm` if you prefer.

**Comment by jdalton** [comment]
@djMax I tried to simulate a repro and could not reproduce the issue on my end. If you manage to create a repro please feel free to post back here or at [standard-things/esm/issues](https://github.com/standard-things/esm/issues).

**Comment by djMax** [comment]
This module: https://github.com/gas-buddy/service if you install tap@12.5.0, will fail

**Comment by delvedor** [comment]
I had a similar problem as well, and this is my log:
```
.../node_modules/tap/lib/stack.js:1
TypeError: Cannot read property 'value' of undefined
    at Object.Module._extensions..js (module.js:586:10)
```

It happens only in Node v6. Updating to `tap v12.6.0` and using `--no-esm` fixes the issue.

**Comment by jdalton** [comment]
@djMax Thanks, digging in.

**Update:**

Patched https://github.com/standard-things/esm/commit/8b8bcd10a422ba06f94ab5056c14849ab3f04e47

**Update:**

`esm` [v3.2.12](https://github.com/standard-things/esm/releases/tag/3.2.12) is released 🎉 

@delvedor If you have a small repro I'll dig into that too 💪

**Comment by jdalton** [comment]
@djMax Patched https://github.com/standard-things/esm/commit/8b8bcd10a422ba06f94ab5056c14849ab3f04e47.

**Comment by jdalton** [comment]
**Update:**

`esm` [v3.2.12](https://github.com/standard-things/esm/releases/tag/3.2.12) is released 🎉

**Comment by delvedor** [comment]
@jdalton thanks! Unfortunately, I haven't. In my project I'm running `tap` in three different test suites and only one of them is failing. In none of them I'm using `esm`. So I have no idea what is causing this issue.

**Comment by jdalton** [comment]
What version of Node 6 are you using?

**Comment by delvedor** [comment]
`v6.17.0`

**Comment by jdalton** [comment]
Thanks @delvedor!

I narrowed down the issue to an engine bug in Node 6 I have to guard against. It seems in Node 6 a generator may not always return an object with `.value` or `.done` and may return `undefined` instead.

**Update:**

Related to this V8 bug https://bugs.chromium.org/p/v8/issues/detail?id=5322 with the `--harmony` flag.

**Update:**

Patch https://github.com/standard-things/esm/commit/23a163a70849db4ca285aeee814096cab87fdd1e;

**Update:**

`esm` [v3.2.14](https://github.com/standard-things/esm/releases/tag/3.2.14) is released 🎉

**Comment by jdalton** [comment]
Related to this V8 bug https://bugs.chromium.org/p/v8/issues/detail?id=5322.

**Comment by jdalton** [comment]
**Update:**

`esm` [v3.2.14](https://github.com/standard-things/esm/releases/tag/3.2.14) is released 🎉
