### ISSUE TITLE
tap.error does not use custom inspect

### ISSUE THREAD

**Issue by delvedor** [tapjs/tapjs#519]
Hello!
Not sure if this is intended or it is a bug.
When I use the `.error` assertion, in the error log I see the entire object even if I'm using a custom inspect function.
Following the code to reproduce the behavior.
```js
'use strict'

const tap = require('tap')
const { inspect } = require('util')

class Box extends Error {
  constructor () {
    super()
    this.hello = 'world'
    this.winter = 'is coming'
    this.foo = 'bar'
  }

  [inspect.custom] () {
    return {
      hello: this.hello,
      winter: this.winter
    }
  }
}

const box = new Box()
console.log(box)
tap.error(box)
```

The log:
```
{ hello: 'world', winter: 'is coming' }
TAP version 13
not ok 1 - (unnamed test)
  ---
  found:
    name: Error
    stack: |-
      Error
          at ...
    hello: world
    winter: is coming
    foo: bar
  at:
    line: 25
    column: 5
    file: prova.js
  stack: |
    ...
  source: |
    tap.error(box)
  ...

1..1
# failed 1 test
# time=9.223ms

```

Is this intended? If so, how can I hide certain properties?

Thanks!

**Comment by isaacs** [comment]
Interesting.  Yes, tap does not use util.inspect or the util.inspect.custom symbol.

In version 13, it's using a custom type in tap-yaml, so it's theoretically possible to do that.  (In version 12 and before, it'd be very challenging.)  My concern would be that the output might hide things that you'd want to see in the results, though.

In both v13 and before, I believe you could hide things by making the properties non-enumerable, but of course this is a bit of a pain.

```js
class Box extends Error {
  constructor () {
    super()
    this.hello = 'world'
    this.winter = 'is coming'
    Object.defineProperty(this, 'foo', { value: 'bar', enumerable: false })
  }
}
```

Note that, since `message` and `stack` are so important (and typically non-enumerable anyway) tap-yaml always shows them, so those would be there regardless.

**Comment by isaacs** [comment]
Also, this applies to any time that an error appears in the yaml diagnostics.  So for example, all of these would show the same type of thing:

```js
throw box
t.equal(box, { not: 'the box' })
t.pass('this is fine', { diagnostic: true, box })
```

**Comment by delvedor** [comment]
I tried making the property non-enumerable, but it didn't work.
```js
'use strict'

const tap = require('tap')

class Box extends Error {
  constructor () {
    super()
    this.hello = 'world'
    this.winter = 'is coming'
    Object.defineProperty(this, 'foo', { value: 'bar', enumerable: false })
  }
}

const box = new Box()
console.log(box)
tap.error(box)
```
This is the log:
```
{ Error
    ...
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3) hello: 'world', winter: 'is coming' }
TAP version 13
not ok 1 - (unnamed test)
  ---
  found:
    name: Error
    stack: |-
      Error
          ...
    hello: world
    winter: is coming
    foo: bar
  at:
    line: 25
    column: 5
    file: test.js
  stack: |
    Object.<anonymous> (test.js:25:5)
  source: |
    tap.error(box)
  ...

1..1
# failed 1 test
# time=9.729ms

```

> My concern would be that the output might hide things that you'd want to see in the results, though.

I agree, but in the same way, some properties might pollute the output making it very hard to read.
In my case, I'm adding to the error instance a big metadata object, which also contains an agent keep alive instance.
I want the user to be able to inspect the agent via `err.meta.agent`, but if the user logs `err` I don't want them to have a very long and unreadable log.

**Comment by isaacs** [comment]
Making it non-enumerable works in v13, not in v12 and before.  New YAML parser.

```
$ node b.js
{ Error
    at Object.<anonymous> (/Users/isaacs/dev/js/tap/b.js:12:13)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:862:12)
    at internal/main/run_main_module.js:21:11 hello: 'world', winter: 'is coming' }
TAP version 13
not ok 1 - (unnamed test)
  ---
  found:
    !error
    name: Error
    message: ""
    stack: |-
      Error
          at Object.<anonymous> (/Users/isaacs/dev/js/tap/b.js:12:13)
          at Module._compile (internal/modules/cjs/loader.js:799:30)
          at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
          at Module.load (internal/modules/cjs/loader.js:666:32)
          at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
          at Function.Module._load (internal/modules/cjs/loader.js:598:3)
          at Function.Module.runMain (internal/modules/cjs/loader.js:862:12)
          at internal/main/run_main_module.js:21:11
    hello: world
    winter: is coming
  at:
    line: 14
    column: 5
    file: b.js
  stack: |
    Object.<anonymous> (b.js:14:5)
  source: |
    console.log(box)
    tap.error(box)
    ----^
  ...

1..1
# failed 1 test
# time=22.355ms
```

**Comment by isaacs** [comment]
Ok, latest v13 includes this, v13.0.0-rc.12.  You can `npm install tap@next` to get it, but be aware it's very much beta right now.  If you use snapshots, you'll have to regenerate them, the reporter is all different, dropped support for Node v6 and before, etc.  I like it better already, but you may find rough edges, and feedback is welcome.

It still will always print `name`, `message`, and `stack`, since those are pretty essential to its error-ness.  But anything else will respect the inspect results.

**Comment by isaacs** [comment]
Oh, also, there's a changelog at https://github.com/tapjs/node-tap/blob/v13/docs/changelog/index.md if you want to see what else changed.

**Comment by delvedor** [comment]
Thanks!!

Unfortunately, I need to support Node v6 for a while in the main projects which I'm working on *([elasticsearch-js](https://github.com/elastic/elasticsearch-js), [fastify](https://github.com/fastify/fastify) and [find-my-way](https://github.com/delvedor/find-my-way))*, but I will try v13 as soon as I have the occasion.

Thank you for all your great work!
