### ISSUE TITLE
t.rejects unexpectedly triggers afterEach

### ISSUE THREAD

**Issue by paulmelnikow** [tapjs/tapjs#525]
Hi!

I'm using `afterEach` to register a cleanup hook that runs after each test.

When I use `t.rejects` in the middle of one of my tests, that creates an additional subtest. That means the cleanup fires in the middle of my test.

```js
const { test, afterEach } = require('tap')

afterEach(done => {
  console.log('in after each!')
  nock.restore()
  nock.cleanAll()
  nock.enableNetConnect()
  nock.activate()
  done()
})

test('get with reply callback returning callback without headers', async t => {
  const scope = nock('http://example.com')
    .get('/')
    .reply(() => [401, 'This is a body'])

  await t.rejects(async () => got('http://example.com/'), {
    statusCode: 401,
    body: 'This is a body',
  })

  // afterEach runs once here ...

  scope.done()

  // ... and a second time after this function returns
})
```

This makes it impossible to make more assertions about the state after the `t.rejects` returns.

In the above example `scope.done()` is intended to check the post-reject, pre-cleanup state, but it's unexpectedly testing the post-cleanup state instead.

It seems like it would be less surprising for `t.rejects` _not_ to trigger the hooks, though if there were a way to turn them off, that could work too.

**Comment by isaacs** [comment]
Fixed in version 13 (coming as soon as node v6 hits EOL, so, in a few weeks.)

**Comment by paulmelnikow** [comment]
Amazing! Thanks so much!
