### ISSUE TITLE
Typescript support broken for mixed .ts/.js projects

### ISSUE THREAD

**Issue by kyegupov** [tapjs/tapjs#526]
Recently, Tap has introduced support for running `.ts` files, like this:

https://github.com/tapjs/node-tap/blob/1871736bfaf39dd7b1be8de4b9359e2eeaa1e4ef/bin/run.js#L748-L753

However, imagine a project being slowly migrated from JS to TS. There are some `.js` tests that would refer to `.ts` code. But, see the code above: ts-node won't be used for `.js` tests and it will not be able to load `.ts` modules they reference.

The proper way to solve it would be to either always use ts-node (if available) to run files. Or, at least, to have some kind of `--force-ts-node` flag.

**Comment by isaacs** [comment]
Try this: `tap --node-arg=-r --node-arg=ts-node/register`

In version 13, you can put this in your package.json, even:

```json
{
  "tap": {
    "node-arg": ["-r", "ts-node/register"]
  }
}
```

**Comment by isaacs** [comment]
You can also add `require('ts-node/register')` to the top of all your js files, which would make them able to require() a ts file.
