### ISSUE TITLE
Tests with process.on('warning') break starting with version 12.5

### ISSUE THREAD

**Issue by belochub** [tapjs/tapjs#528]
Starting with version 12.5 the tests listening to the `'warning'` event on `process` started failing when there are more than one warning emitted in the file. Simplified reproduction:
```js
'use strict';

const tap = require('tap');
const util = require('util');

const fn = () => {};

const deprecated1 = util.deprecate(fn, 'msg1');
const deprecated2 = util.deprecate(fn, 'msg2');

tap.test('deprecated1 warns about deprecation', test => {
  test.plan(1);
  process.once('warning', () => {
    test.pass();
  });
  deprecated1();
});

tap.test('deprecated2 warns about deprecation', test => {
  test.plan(1);
  process.once('warning', () => {
    test.pass();
  });
  deprecated2();
});
```

The second `'warning'` event here is not emitted when the test is being run using the `tap` command.

This probably has something to do with esm introduction since I've also tested it with v12.6 using the `--no-esm` flag and it doesn't fail in that case.

**Comment by isaacs** [comment]
Yeah, that's super weird.  I wrote up a minimal reproduction (that doesn't involve tap) and posted it over at the esm repo.  JDD is usually pretty responsive to stuff like this, but in the meantime, if you're not using esm, you can just add `--no-esm` to your tests, I guess.  (Or, if you're using v13, you can put `"tap":{"esm":false}` in your package.json.)

https://github.com/standard-things/esm/issues/775

**Comment by isaacs** [comment]
Old issue, no longer relevant.
