### ISSUE TITLE
Clarify which versions support Node 4

### ISSUE THREAD

**Issue by paulmelnikow** [tapjs/tapjs#529]
Hi! Thanks for this useful library.

I've picked up maintenance of a stable library which uses a very old version of tap and I'd like to upgrade to the latest version that supports Node 4. Could you clarify which version that is?

The `package.json` in master is showing >= 4:

https://github.com/tapjs/node-tap/blob/1871736bfaf39dd7b1be8de4b9359e2eeaa1e4ef/package.json#L14-L16

The latest 12.x release does not support Node 4. I haven't tried running the version in master.

I don't see anything in the changelog, and I'm seeing conflicting information in #508 and #479.

**Update:** We decided to drop Node 4 and 6. Leaving this open in case it's useful for someone else.

**Comment by isaacs** [comment]
Welcome to the future :)  (Er, well, the present.)

Yeah, once node versions fall off of LTS, it's very hard to justify continuing to support them.  I don't go out of my way to break them, but sometimes a dep will drop support without me realizing it.  v13 will only support node v8 and above.
