### ISSUE TITLE
show me the stringified exception

### ISSUE THREAD

**Issue by tokuhirom** [tapjs/tapjs#53]
node-tap shows

  thrown:  true

But if it shows stringified exception value, it's more useful.

**Comment by andrewdeandrade** [comment]
@tokuhirom Can you provide more details, including (1) an example file that I can run to see the current output and (2) what you would prefer it to look like (when you say 'stringified', do you mean the `message` property?)

**Comment by isaacs** [comment]
This isn't really relevant any more in tap 1.x
