### ISSUE TITLE
tap-fail

### ISSUE THREAD

**Issue by ghost** [tapjs/tapjs#532]
So Today, I  make a presentation for my company about test using tap, and why do you don't need to use mocha, but people ask why the master if fail on CI? 

My answer was I do no?

Now I try to see Travis but I can't, so my question is? Why tap is failing master CI Travis?

I love so much tap, I believe that is important to fix fail on the master.

**Comment by isaacs** [comment]
This will be fixed on v13.  The simple way to fix it would be to remove the browser testing, since that never worked reliably anyway.

**Comment by isaacs** [comment]
Actually, this turned out to be easy enough to do, so now it's passing on travis :)
