### ISSUE TITLE
Feature Request: snapshot file stability.

### ISSUE THREAD

**Issue by coreyfarrell** [tapjs/tapjs#535]
As discussed at https://github.com/istanbuljs/nyc/pull/1075#discussion_r277020841 snapshot files should have a stable order.  This should include both `t.jobs > 1` and situations where a single test runs `t.matchSnapshot` in 2 callbacks that might not always occur in the same order (assuming both calls to `t.matchSnapshot` include an explicit snapshot label).

**Comment by isaacs** [comment]
Yep.  Done in v13, I intend to backport for v12. c9d2276

**Comment by isaacs** [comment]
894263944598e8d89195ea1b597f4584d93def32 on v12.  Published to 12.6.3.
