### ISSUE TITLE
Feature Request (v13): command-line flag to update snapshots

### ISSUE THREAD

**Issue by coreyfarrell** [tapjs/tapjs#537]
This would be helpful to avoid needing `cross-env` while easily supporting `pretest` and `posttest` scripts.  For example:
```json
{
  "scripts": {
    "pretest": "./pretest-build.js",
    "posttest": "./run-reports.js",
    "test": "tap -j1",
    "snap": "npm test -- --write-snapshots"
  }
}
```
In this setup `npm run snap` would not bypass the pretest/posttest scripts and if additional `tap` arguments are wanted they are specified only in the `test` script.  Obviously the current solution to this is to have `"snap": "cross-env TAP_SNAPSHOT=1 npm test"` such as https://github.com/istanbuljs/nyc/pull/1084.

**Comment by isaacs** [comment]
This is already in v13!  It's just spelled `--snapshot` :)
