### ISSUE TITLE
tap command should look a exit status from test case.

### ISSUE THREAD

**Issue by tokuhirom** [tapjs/tapjs#54]
tap command returns success when node.js segmentation fault-ed.

**Comment by isaacs** [comment]
Yes, this is a bug.  It looks like it should be checking the exit status, but apparently that's not working.

**Comment by isaacs** [comment]
Oh, I see.  The exit status actually is 0, but it passes SIGABRT to indicate that it was an abort.  I'll have it check for that as well.
