### ISSUE TITLE
Watching for changes results in infinite loop of retries

### ISSUE THREAD

**Issue by jsumners** [tapjs/tapjs#541]
1. `tap -n -w 'test/**/*.test.js` on a suite of tests that all pass. 
1. Change the covered code to introduce a failure in one of the tests
1. Watch tap re-run the same test ad infinitum

What _should_ happen, in my opinion, is that the test fails and then tap waits for a new change before rerunning the test.

**Comment by isaacs** [comment]
It just is so eager to see if it’s passing yet!

Hm, it should be including the failures in the NEXT set, but not triggering it as if it’s a new change, so that’s a bug.
