### ISSUE TITLE
Detailed output should include child test descriptions

### ISSUE THREAD

**Issue by thlorenz** [tapjs/tapjs#55]
When running the below with `node tapme.js`

``` javascript
// tapme.js
var test = require('tap').test;

test('parent test description', function (t) {
  t.plan(2)
  t.ok(true, 'test in parent')
  t.test('child test description', function (t) {
    t.plan(1)
    t.ok(true, 'test in child')  
  })
})
```

it outputs:

```
TAP version 13
# parent test description
ok 1 test in parent
ok 2 test in child

1..2
# tests 2
# pass  2

# ok
```

It would be nice if it could include the child test description before test 2, e.g., :

```
TAP version 13
# parent test description
ok 1 test in parent
# child test description  
ok 2 test in child

[...]
```

If you agree that this is a valid request I'd be willing to fix it myself and submit a PR, just wanted to get your opinion on this first.

**Comment by isaacs** [comment]
Yes.  Child test names should be emitted as comments.

**Comment by thlorenz** [comment]
Any plans on pulling this in or suggestions in case improvements are needed?
