### ISSUE TITLE
Add Windows to your travis-ci

### ISSUE THREAD

**Issue by coreyfarrell** [tapjs/tapjs#554]
Hi @isaacs would you mind adding Windows to your CI?  Any reason you can think of that `tap` without a glob wouldn't work on Windows?  See https://github.com/istanbuljs/spawn-wrap/pull/82#issuecomment-491258325

**Comment by isaacs** [comment]
There's no reason it wouldn't work on Windows, but it's possible that it's getting tripped up by slashes or some other thing.  I'm re-downloading a VM now, I'll take a look.

I've found that the travis windows support occasionally gets unresponsive or times out.

**Comment by isaacs** [comment]
Turns out the regexp is testing against the filename, but not sensitive to `\` style paths.
