### ISSUE TITLE
t.matchSnapshot sensitive to object key order (v13)

### ISSUE THREAD

**Issue by coreyfarrell** [tapjs/tapjs#555]
t.matchSnapshot seems to be sensitive to the order keys were added to an object.  Any solution to this?  For example with the following test generate snapshots, then reverse the order of properties: `t.matchSnapshot({n2: 'v2', n1: 'v1'});`.  The object is deepEqual to the snapshot value but this fails.

```js
const t = require('tap')

t.test('snapshot test', t => {
  t.matchSnapshot({n1: 'v1', n2: 'v2'});
  t.end();
});
```

**Comment by coreyfarrell** [comment]
The specific use case is in `istanbul-lib-processinfo`.  My plan is to simplify initialization of the fields at https://github.com/istanbuljs/istanbul-lib-processinfo/blob/2c2086a96d6977264d7c0f7b6252fbb562c65391/index.js#L36-L44

The following should be functionally equivalent (given the assumption that key insertion order is an implementation detail):
```js
Object.assign(this, defaults, fields)
```

This does change the order which fields are assigned.

**Comment by isaacs** [comment]
I'd approach this by passing a `sort` option to [tcompare.format](https://github.com/tapjs/tcompare), and then having the default snapshot stringifier pass that option.  I can see how it's a violation of the expectation in this case.

**Comment by coreyfarrell** [comment]
Unfortunate side effect, enabling `sort` by default is likely a breaking change for any project that uses `t.matchSnapshot(obj)` - the results which were previously unsorted are now sorted.  I think this is a good change, just seems like it might violate semver.

**Comment by isaacs** [comment]
Since it was ambiguous before, I don't know that it's clear that it is actually a breaking change.  For comparison, I also shipped the "sort the snapshot file itself" change as a patch, and no one seemed to mind.  Since anyone using snapshots can probably just regenerate them easily enough, it's probably fine?

**Comment by coreyfarrell** [comment]
It's probably fine if no-one else pointed this out in the past few days.  When sorting the snapshot file didn't cause old snapshots to fail, so that's different.  Sorting the object keys makes the old snapshots fail.  As you pointed out regenerating is easy enough so it's probably fine, just something I noticed so I wanted to mention it.
