### ISSUE TITLE
Tests breaking since esm@3.2.23

### ISSUE THREAD

**Issue by gr2m** [tapjs/tapjs#557]
I got a plenty of notifications from Greenkeeper that tests are failing with the latest tap versions, but they also fail with the one before https://github.com/search?q=%22An+in-range+update+of+tap+is+breaking+the+build%22+created%3A%3E2019-05-16&type=Issues

I could narrow down the problem to `esm`. When I run the tests with `node` instead of `tap` there are no problems. When I downgrade `esm` to 3.2.22, the tests pass again.

I’m not familiar with `esm`, got any idea what it could be?

It looks as if it chokes on this syntax

```js
class MyClass {
        // ...
	[Symbol.iterator]() {
		// ^^
	}
}
```

Maybe you could pin `esm` to 3.2.22 until the problem is resolved? I will investigate the issue further and try to come up with a minimal test case that I can file on the `esm` repo itself

**Comment by gr2m** [comment]
I got bit by https://github.com/standard-things/esm/issues/807. I think pinning to `3.2.22` would be reasonable, unless you require any features added from `3.2.23` or `3.2.24`

**Comment by jdalton** [comment]
`esm` [v3.2.25](https://github.com/standard-things/esm/releases/tag/3.2.25) is released :tada:

**Comment by gr2m** [comment]
confirmed 🎉 thanks @jdalton, that was quick!
