### ISSUE TITLE
Setting 100: true in taprc does not automatically enable check-coverage

### ISSUE THREAD

**Issue by coreyfarrell** [tapjs/tapjs#558]
Running `tap --100` causes 100% coverage to be enforced.  I expected the same to work by setting `"100": true` in my `.taprc`.  This only works if I also set `"check-coverage": true`.

**Comment by isaacs** [comment]
That's because `100` is an alias, not an actual config value. But given this expectation, maybe it'd be good to unpack aliases in the confit parsing? I should probably add a convenience method to jackspeak to do this.

**Comment by coreyfarrell** [comment]
Ahhh I see only setting `"check-coverage": true` works.  I'll do that in my `.taprc`, but the current behavior is unexpected.

**Comment by isaacs** [comment]
Added support for this in v14.1, just published.  Depended on adding an update method to jackspeak, but this is a cleaner way to do it than how I was parsing config files anyway.
