### ISSUE TITLE
Can no longer specify file globs in .taprc

### ISSUE THREAD

**Issue by evanlucas** [tapjs/tapjs#559]
on `tap@12.x`, it was possible to specify the files in the .taprc file like so:

```
files:
- test/biscuits/**/*.js
```

With `tap@14.x`, that no longer works. 

We are ultimately want to be able to specify not only the specific directories that have tests that need to be run, but also specify the ordering in which they are run. Is that possible without passing each individual glob to the command line?

Thanks!

**Comment by isaacs** [comment]
Ah yeah. That's an unintended result of parsing shorthands in config files. I'll add `--files` as an option to fix that.
