### ISSUE TITLE
Vulnerability in  lodash.flattendeep:4.4.0?

### ISSUE THREAD

**Issue by dmitriz** [tapjs/tapjs#563]
Just reporting some potential vulnerabilities  in`tap`'s dependencies found by running sonatype-depshild against my repository:

https://github.com/dmitriz/tiny-cps/issues/15
https://github.com/dmitriz/tiny-cps/issues/14

**Comment by isaacs** [comment]
I don't see any advisories in those links against the versions of any modules that tap uses.  Am I missing something?

**Comment by dmitriz** [comment]
Don't know if that is related but a spammer (or hacker?) was attracted to an issue created by the "DepShield". It this app legitimate?

https://github.com/dmitriz/gently-copy/issues/84

**Comment by isaacs** [comment]
Yeah these are all either false positives or unrelated to tap.  Closing this issue.  Please tell your security provider to update their advisory about debug to reflect 2.6.9 as fixed, and explain to them that lodash is not the same as lodash.flattendeep or lodash.throttle.

**Comment by dmitriz** [comment]
Thank you, this warning seems indeed to be inaccurate upon inspection and already fixed in the version `tap` is using. Apologies for the confusion!
