### ISSUE TITLE
Fails to find .js files when given a directory on Windows

### ISSUE THREAD

**Issue by JoeDoyle23** [tapjs/tapjs#57]
When trying to run tap (current version on NPM) on Windows using, I just get the following result:

```
> tap ./tests
total ................................................... 0/0

ok
```

If I specify a specific .js file in the tests folder, it runs just fine.

I dug into this and found that on line 162 of tap-runner.js is the following check:
    } else if ((st.mode & 0001) == 0) {
        return cb()
    }

I debugged this and when provided just the directory, the st.mode was 0x41B6.  In the Node source it looks like this would be a check against UV_FS_SYMLINK_DIR?  But since this is a real directory and not a symlink, this is true, and the directory is not processed further. Making this check false, allows the directory to drop down to line 167 where it runs as expected.

I'd submit a pull request, but I'm new to the internals of Node and I have no idea what exactly this is a check for.

**Comment by rmg** [comment]
It looks like this was fixed upstream about 2 years ago.
