### ISSUE TITLE
Snapshots, coverage and custom formatSnapshot

### ISSUE THREAD

**Issue by fleg** [tapjs/tapjs#571]
First of all, thank you for quick #570 fix.

For global custom formatting I place overriding of the `formatSnapshot` function in separate file (init.js) and then require it with following args `--node-arg -r --node-arg ./init.js`.
Presence of `const tap = require('tap');` inside init.js somehow breaks down snapshot loading when tap runned with coverage. I guess is related with `fullname` property in `Test` class
https://github.com/tapjs/node-tap/blob/c03d5f85852b04bebcf1a788039649b545e1a2d1/lib/test.js#L1213-L1219

Repo with code to reproduce the bug: https://github.com/fleg/tap-cov-issue
Snapshot generated with `npm run snap`.
`npm run test` for run test without coverage is ok.
`npm run coverage` for run test with coverage fails with error:
```
Snapshot file not found: /home/fleg/js/tap-cov-issue/tap-snapshots/node-test.js-TAP.test.js
```
It try to load snapshot from `node-test.js-TAP.test.js`, when actual snapshot inside `test.js-TAP.test.js`

```
$ node -v
v8.4.0
$ tap -v
14.2.3
$ npm -v
5.3.0
$ uname -a
Linux flegdev 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by isaacs** [comment]
Should be fixed on the latest v14 release.  Thanks for the very clear report and reproduction case 😄

**Comment by fleg** [comment]
Thank you, it works fine now!
