### ISSUE TITLE
Bundled scoped dependencies breaks npm 3

### ISSUE THREAD

**Issue by rmg** [tapjs/tapjs#572]
Release 14.2.3 bundled `treport` and `ink` which in turn have some dependencies that are scoped packages.

Unfortunately, this combination breaks `npm install` with npm@3 (see npm/npm#9175 among others), which is what ships with node 6.

This came up in an old project that hasn't been updated in a few years and despite using pinned dependency versions still managed to pull in the latest and greatest `tap` release via its extended dependency tree and broke our CI for maintenance releases.

Given the problems fixed by bundling the deps in the first place and how this is specific to npm <=3, I'm not sure if this would be worth fixing. At the very least, this issue documents it in case others go searching ;-)

Here's the error message from `npm install tap@14.2.3`, which will be similar to what users will see if the run in to this and start googling..

```
npm ERR! Darwin 18.6.0
npm ERR! argv "/Users/rmg/.nvs/node/6.17.1/x64/bin/node" "/Users/rmg/.nvs/node/6.17.1/x64/bin/npm" "install" "tap@14.2.3"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! path /Users/rmg/deleteme/node_modules/.staging/@types/prop-types-ffa50f63
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/Users/rmg/deleteme/node_modules/.staging/@types/prop-types-ffa50f63' -> '/Users/rmg/deleteme/node_modules/tap/node_modules/@types/prop-types'
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/rmg/deleteme/node_modules/.staging/@types/prop-types-ffa50f63' -> '/Users/rmg/deleteme/node_modules/tap/node_modules/@types/prop-types'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rmg/deleteme/npm-debug.log
```

**Comment by isaacs** [comment]
So, yeah, npm 3 and node 6 are both not supported by the latest node-tap anyway.  Sadly, this is definitely wontfix.

Thanks for documenting it here, though, in case others run into it.
