### ISSUE TITLE
Performance issue with specy reporter

### ISSUE THREAD

**Issue by fleg** [tapjs/tapjs#574]
Looks like tests execution time positively related with number of printed asserts.
To reproduce this, I made some copies of simple test file with 100 asserts, and run it with tap.
```js
const t = require('tap');

t.test('test', (t) => {
	t.test('foo', (t) => {
		for (let i = 0; i < 50; i++) {
			t.ok(true, `${i} is ok`);
		}

		t.end();
	});

	t.test('bar', (t) => {
		for (let i = 0; i < 50; i++) {
			t.notOk(false, `${i} is not ok`);
		}

		t.end();
	});

	t.end();
});
```

Repo with code: https://github.com/fleg/tap-cov-issue

`test-slow` runs tap with specy reporter
`test-fast` runs tap with base reporter

```
$ time npm run test-slow
...
Suites:   37 passed, 37 of 37 completed
Asserts:  3700 passed, of 3700

real	4m45.441s
user	4m53.924s
sys	0m2.596s
```

```
$ time npm run test-fast
...
Suites:   37 passed, 37 of 37 completed
Asserts:  3700 passed, of 3700
Time:     15s

real	0m16.258s
user	0m18.412s
sys	0m1.100s
```
If I create more copies of test file, to increase count of printed rows, I guess base reporter will slow down too.

```
$ node -v
v8.10.0
$ tap -v
14.2.5
$ npm -v
5.6.0
$ uname -a
Linux fleg-pc 4.4.0-148-generic #174~14.04.1-Ubuntu SMP Thu May 9 08:17:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by isaacs** [comment]
I mean, it's printing more than 100x more output when you use specy rather than base, and pretty much the only thing this test does is print to stdout.  I'm not sure why you'd be surprised that a 100x more verbose reporter would be slower?

**Comment by fleg** [comment]
Ok, but spec reporter printing as much rows as specy reporter and doing it about 19 times faster

```
  3700 passing (14s)

real	0m14.414s
user	0m14.644s
sys	0m0.704s
```

**Comment by fleg** [comment]
If you run specy reporter, you can see how it gets slower and slower when more and more rows are printed.
In my example, with specy reporter, it took less than 1 second to print first 100 asserts, and around 20 seconds to print last 100 asserts.

Profiling results for first and last executed file:
[first.log](https://github.com/tapjs/node-tap/files/3323881/first.log)
[last.log](https://github.com/tapjs/node-tap/files/3323882/last.log)

**Comment by isaacs** [comment]
Ah, yeah, I see what you're saying.

The difference appears to be due to using the `<Static>` feature in Ink.  specy has an array of lines that it repeatedly appends to.   spec is just dumping to stdout as it can.  That's why specy can maintain the status lines at the bottom, whereas spec leaves you wondering what's going on.

The implementation of Static is simple, but the rendering logic has an O(n^3) nested array scan to decide what to render, which gets pretty taxing as the number of lines increases.

I posted [an issue](https://github.com/vadimdemedes/ink/issues/205) about this on the ink repo.  In the meantime, I'd recommend using `spec` instead.

**Comment by fleg** [comment]
Ok, thank you. I think I will use `base`, it just a little bit slower than spec, but has prettier diffs.

**Comment by vadimdemedes** [comment]
@fleg Thank you for such a detailed and easy-to-reproduce issue! I was able to speed up log printing by 70% in `specy` reporter (from 187s down to 51s). Will push a new release of Ink shortly!

**Comment by fleg** [comment]
@vadimdemedes Thank you for fast reply and fix. I guess ~40s gap with spec reporter is just React overhead?

**Comment by vadimdemedes** [comment]
That overhead accounts for more like React + Ink + writing *a lot* of output to `stdout`.
