### ISSUE TITLE
Provide something like TEST_THREAD_ID to parallel tests

### ISSUE THREAD

**Issue by Fishrock123** [tapjs/tapjs#578]
This is mostly a request out of my desire to have more stable tmp directory handling for tests.

I quite like what Node's tmpdir common test helper does compared to other options. 
_(Aside: perhaps node-tap should have this functionality built-in.)_

In particular, it also handles parallel tests quite nicely by picking up an env variable and naming dirs with that to prevent conflicts. See: https://github.com/nodejs/node/blob/master/test/common/tmpdir.js

It would be nice for this reason and perhaps others if node-tap could support an ENV var (or perhaps something else, pending worker_threads) such as `TEST_THREAD_ID`.

**Comment by isaacs** [comment]
Does env.TAP_CHILD_ID do what you need?

**Comment by Fishrock123** [comment]
Sounds like it would. I'll check but it might be a couple days.

In that case it should probably be in the 'parallel tests' section of the docs.
I would be willing to do the docs, I think.

**Comment by isaacs** [comment]
Good call!  Done.
