### ISSUE TITLE
Support method to await completion of all subtests

### ISSUE THREAD

**Issue by coreyfarrell** [tapjs/tapjs#581]
I'm exploring migration of istanbuljs monorepo testing to tap.  I often use async test functions so I don't have to call `t.end()`.  Consider the following scenario:

```js
t.test('section', async t => {
  await t.test('subtest 1', async t => { /* ... */ });
  await t.test('subtest 2', async t => { /* ... */ });
  await t.test('subtest 3', async t => { /* ... */ });
});
```

I suspect this style of test setup will block subtests from running simultaneously.  The idea of this request is to be able to do rewrite the above:
```js
t.test('section', t => {
  t.test('subtest 1', async t => { /* ... */ });
  t.test('subtest 2', async t => { /* ... */ });
  t.test('subtest 3', async t => { /* ... */ });
  return t.drain();
});
```

In this example `t.drain()` would return a promise that resolves when the test queue for `t` becomes empty with all tests passed (reject if any test failed).  In theory this should allow:
```js
t.test('section', async t => {
  t.test('subtest 1a', async t => { /* ... */ });
  t.test('subtest 1b', async t => { /* ... */ });
  t.test('subtest 1c', async t => { /* ... */ });
  await t.drain();
  t.test('subtest 2a', async t => { /* ... */ });
  t.test('subtest 2b', async t => { /* ... */ });
  t.test('subtest 2c', async t => { /* ... */ });
  await t.drain();
});
```
So `section` would run subtest 1a, 1b and 1c together, wait for them to complete, then run 2a, 2b and 2c together.

FWIW I actually rewrote the test which prompted this request to not use a sub-test.  I was converting from a mocha test where all tests were in a single file, I ended up just moving the subtests to a separate test file.  Either way I feel like this could be generally useful for any situation where promise based testing is combined with sub-tests.  I use `t.drain` mostly as an example, I'm not sure that's a great name.

**Comment by isaacs** [comment]
I could see how this might be handy.

(In fact, even in the second/third examples, all the tests will run sequentially, unless you do `t.jobs = 3`.)

I'd want to noodle on the best name for this kind of method.  Of course another approach is to just put the sections into subtests of their own, and then have those subtests set a `t.jobs` number > 1.

```js
t.test('section', t => {
  t.test('subtest 1', t => {
    t.jobs = 3
    t.test('subtest 1a', async t => { /* ... */ });
    t.test('subtest 1b', async t => { /* ... */ });
    t.test('subtest 1c', async t => { /* ... */ });
    t.end()
  })
  t.test('subtest 2', t => {
    t.jobs = 3
    t.test('subtest 2a', async t => { /* ... */ });
    t.test('subtest 2b', async t => { /* ... */ });
    t.test('subtest 2c', async t => { /* ... */ });
    t.end()
  })
  t.end()
});
```

**Comment by isaacs** [comment]
`drain` can actually be accomplished just by awaiting the promise returned by a test.  If a test is not buffered, then it'll only run on its own, and all parallel buffered tests will wait for it.  In tap 18, there's support for silent unbuffered tests, so you can do this to break them up and make the tests all wait for the "drain" test:

```js
  t.jobs = 999
  t.test('subtest 1a', async t => { /* ... */ });
  t.test('subtest 1b', async t => { /* ... */ });
  t.test('subtest 1c', async t => { /* ... */ });
  t.test('drain', { silent: true, buffered: false }, t => t.end());
  t.test('subtest 2a', async t => { /* ... */ });
  t.test('subtest 2b', async t => { /* ... */ });
  t.test('subtest 2c', async t => { /* ... */ });
  t.test('drain', { silent: true, buffered: false }, t => t.end());
```

If you want to have it not even _create_ that second batch of tests until the drain has been resolved, you can do that by awaiting it:

```js
  t.jobs = 999
  t.test('subtest 1a', async t => { /* ... */ });
  t.test('subtest 1b', async t => { /* ... */ });
  t.test('subtest 1c', async t => { /* ... */ });
  await t.test('drain', { silent: true, buffered: false }, t => t.end());
  t.test('subtest 2a', async t => { /* ... */ });
  t.test('subtest 2b', async t => { /* ... */ });
  t.test('subtest 2c', async t => { /* ... */ });
  await t.test('drain', { silent: true, buffered: false }, t => t.end());
```

Totally open to creating a `drain(){ return this.test('drain', { silent: true, buffered: false }, t => t.end()) }` alias method.
