### ISSUE TITLE
Istanbul default excludes not working

### ISSUE THREAD

**Issue by jaydenseric** [tapjs/tapjs#585]
According to [the istanbul docs](https://github.com/istanbuljs/nyc#using-include-and-exclude-arrays):

> The default `exclude` list is defined in the [test-exclude module](https://github.com/istanbuljs/istanbuljs/blob/master/packages/test-exclude/default-exclude.js).

The defaults contain `test{,-*}.{js,cjs,mjs,ts}` and `**/*{.,-}test.{js,cjs,mjs,ts}`, so I don't know why such files are being coverage checked in my projects:

<img width="494" alt="Screen Shot 2019-08-08 at 7 29 32 pm" src="https://user-images.githubusercontent.com/1754873/62691898-f12dd080-ba12-11e9-9419-be0dadafab55.png">

The workaround is to add a `.nycrc.json` file to your project like this:

```json
{
  "exclude": ["**/*.test.*"]
}
```

**Comment by coreyfarrell** [comment]
The docs on github show `master`, unfortunately right now this is different from the currently released version.  The default excludes for the current version of nyc can be viewed at https://github.com/istanbuljs/istanbuljs/blob/test-exclude%405.2.3/packages/test-exclude/index.js#L176-L184 (test-exclude@5.2.3).

The additional default excludes will be provided as part of test-exclude@6.0.0 and nyc@15.0.0.  No ETA on the full release of these new versions, progress can be followed at istanbuljs/nyc#1104.

**Comment by isaacs** [comment]
As of tap 14.7.2, it'll also explicitly exclude any test files it runs.  Should fix this issue for you.
