### ISSUE TITLE
tcompare.has/tcompare.hasStrict

### ISSUE THREAD

**Issue by fleg** [tapjs/tapjs#590]
I'm just wondering, why tap does not contain asserts equivalent to tcompare.has and tcompare.hasStrict functions.

**Comment by isaacs** [comment]
That's a good question.  Before tcompare existed, tap used `t.has` as an alias to `t.match`.  I think it'd be good to create a `t.hasStrict`, but changing `t.has` will definitely be semver-major, since it'll make currently-passing tests start to fail.
