### ISSUE TITLE
Default CLI --test-regex doesn't pickup test.js or test.mjs files

### ISSUE THREAD

**Issue by jaydenseric** [tapjs/tapjs#593]
The default CLI `--test-regex` pattern doesn't pickup `test.js` or `test.mjs` files:

https://regex101.com/r/W7Xv7Q/1

This is surprising, as other tools do by default, and it's a common pattern.

**Comment by isaacs** [comment]
Huh.  Yeah, that'd be nice if that worked.

Seems like this addresses it without also picking up stuff like `lib/test.js`?

```
((\/|^)(tests?|__tests?__)\/.*|\.(tests?|spec)|^\/?tests?)\.([mc]js|[jt]sx?)$
```
