### ISSUE TITLE
Sponsor button in repo does not work

### ISSUE THREAD

**Issue by pke** [tapjs/tapjs#597]
This repo features a "Sponsor" button that I wanted to happily click to send some money.
However, clicking it raises an error

```
Some errors were encountered when parsing the FUNDING.yml file:

Some users provided are not enrolled in GitHub Sponsors. Apply to the beta.
Learn more about formatting FUNDING.yml.
```

There is no `FUNDING.yml` in the project root, maybe you can fix that?

**Comment by isaacs** [comment]
Please let github know that you want `isaacs` added to the sponsorship beta :)

**Comment by isaacs** [comment]
(the FUNDING.yml file is [here](https://github.com/tapjs/node-tap/blob/master/.github/FUNDING.yml).)

**Comment by pke** [comment]
Already mentioned you in my waitlist request ;)
But you yourself applied for funding too?

**Comment by isaacs** [comment]
I did.

I guess the proper place to advocate is in the waitlist request like you've already done, not by emailing support. https://github.blog/2019-06-12-faq-with-the-github-sponsors-team/#how-does-the-waitlist-work
