### ISSUE TITLE
Coverage report of one liner differs from multiliner

### ISSUE THREAD

**Issue by pke** [tapjs/tapjs#600]
This code is being complained about missing coverage of line (2) despite covering all the cases.

```js
function selectArrayValue(array, selector, resolveSubItem = item => item) {
  if (!array || !selector || !resolveSubItem) {
    return
  }
  // ...
```

```bash
Suites:   2 passed, 2 of 2 completed
Asserts:  14 passed, of 14
---------------------|----------|----------|----------|----------|-------------------|
File                 |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
---------------------|----------|----------|----------|----------|-------------------|
All files            |    92.86 |    96.15 |      100 |      100 |                   |
 selectArrayValue.js |    54.55 |     87.5 |      100 |      100 |                 2 |
---------------------|----------|----------|----------|----------|-------------------|
```

This is the same code, just in separate `if` statements (don't mind the bad code of return not in a block):

```js
function selectArrayValue(array, selector, resolveSubItem = item => item) {
  if (!array) return
  if (!selector) return
  if (!resolveSubItem) return
  // ...
```

[Repo](https://github.com/pke/supertrumpf)

**Comment by isaacs** [comment]
Run `tap --coverage-report=html` and see the report in more detail. 

My first guess would be: are you hitting the case when all of them are true?

**Comment by pke** [comment]
This first yielded an empty report. I guess because the watcher was still running while I executed the tap command. 
I then ran it from the commandline specifying the `test/*.test.js` pattern and it created the report. No uncovered line showed up. All green.
Restarted VSCode and there then also everything was green.

So I guess its either VSCode or Windows related, that NYC gets its cache out of sync.
