### ISSUE TITLE
direct git dependency is breaking our build process

### ISSUE THREAD

**Issue by ghost** [tapjs/tapjs#605]
One by one our developers are noticing if they delete their node_modules folder (or developers setting up a project for the first time), they can no longer install the node modules. 
The reason for this, we have tracked down to a change in node-tap, v14.7.1 with the introduction of the direct git dependency:
`"source-map-support": "github:tapjs/node-source-map-support#node-header-length-change",`
Our network/security dept prevents our development PC's from pulling anything on port 22, which results in npm failing to resolve this specific dependency. 
When can this dependency be changed back to an officially tagged version of node-source-map-support?

**Comment by isaacs** [comment]
I'm waiting for this PR to land: https://github.com/evanw/node-source-map-support/pull/255

But I can push a release that bundles the dep so you don't have to rely on git stuff in the meantime.
