### ISSUE TITLE
Wrong branches coverage configuration 

### ISSUE THREAD

**Issue by jrpedrianes** [tapjs/tapjs#606]
Hi,

Seems that the branches configuration option is broken, always is configured with a 100%.
Here: 
https://github.com/tapjs/node-tap/blob/a46f0a53daffb980530b9e62750dababc0c2e9aa/bin/run.js#L278

I think that the correct would be:
`'--branches=' + options.branches,`

**Comment by isaacs** [comment]
Yeah, that bit of code had a few bugs in it.  Fixed on latest release, thanks for finding it :)
