### ISSUE TITLE
How start some process before tests and stop it after tests end?

### ISSUE THREAD

**Issue by Santinell** [tapjs/tapjs#608]
Hello!

Currently I am using real Mongodb on remote server.
When I use --jobs=1 filling database with basic data takes 9s for each test file (~30s for 3 files in sum)
When I start 3 tests in parallel when each test creates and fill its own test database. It takes
about 40-50 seconds in sum.
So I am looking for variant to speed tests up.

I want to try start `mongodb-memory-server` before all my test files, run tests in parallel 
and stop server after tests (no matter success or fail). Maybe it will reduce tests time.

**Comment by isaacs** [comment]
I've recently run into a similar issue with two projects now where I have to set up a bunch of fixtures and then run tests against them.  I've been just doing it in a `00-setup.js` and tearing down in a `zz-cleanup.js` test, but this doesn't allow for parallel tests, obviously.

You could use subfolders with this approach:

```
test/
  tap-parallel-not-ok
  00-setup.js
  tests/
    tap-parallel-ok
    do-something.js
    do-something-else.js
  zz-cleanup.js
```

but that's a big clunky.

I'm thinking of adding something like `tap --before=test/fixtures/setup.js --after=test/fixtures/teardown.js`, do you think that would work in your case?  (You could of course put the configs in `package.json` with `{ "tap": {"before":"test/fixtures/setup.js", "after":"test/fixtures/teardown.js"}}` so that you don't have to specify it each time.)

**Comment by Santinell** [comment]
Thanks for your workaround, I will try.

About before and after scripts - I think it would be more flexible if we could setup and run tap with special file, like this:

```javascript
const tap = require('tap');

tap.beforeAll(() => {
  // run some process or do something
});

tap.runTests('**/*.test.js', { jobs: 4 }); // there could be worker_threads or spawn
// we can await it, make this function synchronous or make beforeAll and afterAll as event listeners

tap.afterAll(() => {
  // stop some process or do something else
});
```
Maybe even `tap.beforeAll` and `tap.afterAll` is not so necessary if we could put some code before and after running tests.

**Comment by isaacs** [comment]
Ok, so, with tap 14.9, you can do this:

```
tap --before=setup-mongodb-server.js --after=teardown-mongodb-server.js
```

I recommend setting up the DB locally, as a detached child process, and storing the `pid` to a file.  Then the teardown script can kill the child process.

```js
// before.js
const fs = require('fs')
const {spawn} = require('child_process')
const child = spawn('mongodb', ['some', 'args'], {
  detached: true, // don't SIGHUP when the parent proc exits
  stdio: ['ignore', 'pipe', 'pipe'],
})
fs.writeFileSync('.pidfile', String(child.pid))
child.stderr.pipe(process.stderr)
child.stdout.on('data', (chunk) => {
  // got data, maybe look at it to verify that it started up ok
  child.unref() // let the process close normally
})
```

```js
// after.js
const fs = require('fs')
const pid = +fs.readFileSync('.pidfile', 'utf8')
process.kill(pid, 'SIGTERM')
```

**Comment by isaacs** [comment]
You can also put the before/after configs in package.json to make it easier, so it ends up looking like this:

```json
{
  "scripts": {
    "test": "tap"
  },
  "tap": {
    "before": "start-mongo.js",
    "after": "kill-mongo.js"
  }
}
```

Then you can do stuff like `npm run test test/foo.js` to just run one test file, and it'll still do the proper startup/teardown bits.

**Comment by Santinell** [comment]
Cool, thanks!
