### ISSUE TITLE
Running files in the same process

### ISSUE THREAD

**Issue by Raynos** [tapjs/tapjs#61]
Is there a flag or an option to not spin up a new process per test file.

I'd be nice to do an integration test without resetting the environment each time.

**Comment by isaacs** [comment]
No, tap does not do this.  You can, however, have one test that does the setup, and then require()s all the other tests, and then does the teardown.

**Comment by Raynos** [comment]
Would you be open to a PR that implements this?

**Comment by isaacs** [comment]
No, tests should be the main module, not something require()'d by tap.  It's easy enough to do in your own test files in the cases where it's relevant.
