### ISSUE TITLE
'same' test fails on bigint

### ISSUE THREAD

**Issue by bingomanatee** [tapjs/tapjs#610]
I'm writing a numeric utility library and when using 'same' comparison between bigints, it fails; even in situations where the equivalent test framed as 'ok' succeeds:

        const bigNum = numb(2n ** 53n);
        ln.ok(bigNum.isValid);
        ln.ok(bigNum.value === 2n ** 53n); // <--- passes
       ln.same(bigNum.value, 2n ** 53n); /// <--- fails

**Comment by coreyfarrell** [comment]
This issue is fixed in tap v14 by the release of tcompare 3.0.5.
