### ISSUE TITLE
coverage-map can cause issues with `all: true`

### ISSUE THREAD

**Issue by coreyfarrell** [tapjs/tapjs#615]
I've created a branch on my 'tap issues' demo repository.  See https://github.com/coreyfarrell/tap-win-timeout/tree/coverage-map

Specifically an issue occurs when tap `coverage-map` is enabled and `include` is configured via nyc configuration (verified with `nyc.config.js` and `package.json#nyc`).  This results in nyc's `--all` functionality not working, which is weird as I expected that tap coverage maps would not be used for the nyc master process (the one which processes `--all`).  In the linked repository the coverage report does not mention file2.js, though I expected that file to be reported as not having any coverage.

Edit: Interesting note if I remove `include` from the nyc config and add to `.taprc`:
```yaml
nyc-arg:
  - "--include=\"lib/**\""
```
This fixes the coverage (file2.js appears as uncovered) but is undesirable:
* passing globs through the command-line is a bit scary (I assume these arguments are not interpreted by the shell but still).
* nyc.config.js is sometimes used to generate dynamic `include` options, for example if posix / win32 code is in separate files the include can negate the source which is not for the current platform.

**Comment by isaacs** [comment]
Nyc is no longer used by tap, as it's going through the built in v8 coverage stuff to be able to handle esm. It would be nice to have an `--all` flag, but since v8 only knows about the files it loads, it's a bit tricky.
