### ISSUE TITLE
assert.throws when throwing an object (not an Error)

### ISSUE THREAD

**Issue by abernier** [tapjs/tapjs#62]
Hi,

I want to test that my couchDB's `validate_doc_update`  function rejects unidentifed users:

``` javascript
module.exports = function (newDoc, oldDoc, userCtx, dbCtx) {
  if (!userCtx || !userCtx.name) {
    throw {unauthorized: "Fuck off!"};
  }
}
```

I don't know tap very well, but I'm pretty sure I should use `assert.throws`:

``` javascript
tap = require('tap')

validate_doc_update = require('./validate_doc_update')

icognitoCtx = {
  db: 'foo'
  name: null,
  roles: []
}

tap.test('Reject unidentified users', function (t) {
  t.throws(
    function () {
      validate_doc_update({}, {}, icognitoCtx);
    },
    {unauthorized: "Go away!"},
    'should stay polite and tell you to go away (not to fuck off)'
  )
});
```

My problem is this test passes despite `{unauthorized: "Fuck off!"}` does not equal `{unauthorized: "Go away!"}`...

Looking at [the code](https://github.com/isaacs/node-tap/blob/master/lib/tap-assert.js#L118), it seems tap deals with `Error`s only, not objects like the ones couchDB likes, eg: `{forbidden/unauthorized: 'message'}`

Do you see any work around for this?

thank you

**Comment by isaacs** [comment]
Hm.  Not at the moment, but I'd accept a patch to make it treat any non-Error object using `assert.has()`, so you can specify arbitrary fields.

**Comment by abernier** [comment]
Well, I don't know tap enough for now in order to submit a patch.

If it can help someone else, here is my work around:

``` javascript
tap.test('Reject unidentified users', function(t) {
  var er;
  try {
    validate_doc_update({}, {}, incognitoCtx);
  } catch(e) {
    er = e;
  }

  t.ok(er, 'An error has been thrown');
  t.deepEquals(
    er,
    {unauthorized: "Go away!"},
    'should stay polite and tell you to go away (not to fuck off)'
  )

  t.end()
});
```
