### ISSUE TITLE
tap@14.10.2 failing npm install

### ISSUE THREAD

**Issue by mikecbrant** [tapjs/tapjs#620]
Not sure if this is even something that node-tap has control over, but it seems that since issue of 14.10.2 I am getting npm install issue coming for same directory renaming step of npm install for each install attempt. This is being triggered by install of tap's babel dependency.

The error is as follows:

```
$ npm i -P tap@14.10.2
npm ERR! code EPERM
npm ERR! syscall rename
npm ERR! path C:\Users\mbrant\git\devops\node_modules\tap\node_modules\@babel\.helper-builder-react-jsx.DELETE\node_modules\@babel
npm ERR! dest C:\Users\mbrant\git\devops\node_modules\tap\node_modules\@babel\helper-builder-react-jsx\node_modules\@babel
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\mbrant\git\devops\node_modules\tap\node_modules\@babel\.helper-builder-react-jsx.DELETE\node_modules\@babel' -> 'C:\Users\mbrant\git\devops\node_modules\tap\node_modules\@babel\helper-builder-react-jsx\node_modules\@babel'
npm ERR!  [OperationalError: EPERM: operation not permitted, rename 'C:\Users\mbrant\git\devops\node_modules\tap\node_modules\@babel\.helper-builder-react-jsx.DELETE\node_modules\@babel' -> 'C:\Users\mbrant\git\devops\node_modules\tap\node_modules\@babel\helper-builder-react-jsx\node_modules\@babel'] {
npm ERR!   cause: [Error: EPERM: operation not permitted, rename 'C:\Users\mbrant\git\devops\node_modules\tap\node_modules\@babel\.helper-builder-react-jsx.DELETE\node_modules\@babel' -> 'C:\Users\mbrant\git\devops\node_modules\tap\node_modules\@babel\helper-builder-react-jsx\node_modules\@babel'] {
npm ERR!     errno: -4048,
npm ERR!     code: 'EPERM',
npm ERR!     syscall: 'rename',
npm ERR!     path: 'C:\\Users\\mbrant\\git\\devops\\node_modules\\tap\\node_modules\\@babel\\.helper-builder-react-jsx.DELETE\\node_modules\\@babel',
npm ERR!     dest: 'C:\\Users\\mbrant\\git\\devops\\node_modules\\tap\\node_modules\\@babel\\helper-builder-react-jsx\\node_modules\\@babel'
npm ERR!   },
npm ERR!   stack: "Error: EPERM: operation not permitted, rename 'C:\\Users\\mbrant\\git\\devops\\node_modules\\tap\\node_modules\\@babel\\.helper-builder-react-jsx.DELETE\\node_modules\\@babel' -> 'C:\\Users\\mbrant\\git\\devops\\node_modules\\tap\\node_modules\\@babel\\helper-builder-react-jsx\\node_modules\\@babel'",
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'C:\\Users\\mbrant\\git\\devops\\node_modules\\tap\\node_modules\\@babel\\.helper-builder-react-jsx.DELETE\\node_modules\\@babel',
npm ERR!   dest: 'C:\\Users\\mbrant\\git\\devops\\node_modules\\tap\\node_modules\\@babel\\helper-builder-react-jsx\\node_modules\\@babel',
npm ERR!   parent: 'tap'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mbrant\AppData\Roaming\npm-cache\_logs\2019-11-26T19_51_06_256Z-debug.log
``` 

My environment is as follows:

OS: Windows 10 Pro Version 1903
node: 13.01
npm: 6.13.1

I have tried installs both in git bash and windows CMD shell, including with admin privileges. 
I have also tried all the typical npm troubleshooting (`npm cache clean --force`, `rm -rf node_modules`, etc.). Regardless as to shell or npm install state, I am alwasy able to successfully install 14.10.1, but not 14.10.2.  14.10.2 always ends with same `EPERM` error on same directory renaming operation.

**Comment by isaacs** [comment]
I believe this is scoped `bundleDependencies` triggering a weird edge case in the npm v6 CLI.

You can try `npm i tap@unbundled` to see if that lets you move forward. (Note: this will cause problems if tap is used alongside react of any version other than 16.)

**Comment by mikecbrant** [comment]
So what are other implications are there in taking the `unbundled` distribution?  How does this distribution differ from `latest`?

**Comment by myleskelman** [comment]
Same issue here.

**Comment by NetsydeMiro** [comment]
Same issue here.  Falling back to 14.10.1 for now.

**Comment by alex-ppg** [comment]
> I believe this is scoped `bundleDependencies` triggering a weird edge case in the npm v6 CLI.
> 
> You can try `npm i tap@unbundled` to see if that lets you move forward. (Note: this will cause problems if tap is used alongside react of any version other than 16.)

This actually did not resolve the issue for me. Version 14.10.1 installs just fine, however `npm i tap@unbundled` as well as the bundled version result in the EPERM issue.

**Comment by jsumners** [comment]
This seems to be a Windows only issue. I don't see this happening on macOS or Linux. But every one of this project's Windows builds fails -- https://github.com/ldapjs/node-ldapjs/pull/585/checks?check_run_id=338082433#step:4:1

**Comment by bcomnes** [comment]
Ran into this today in GitHub Actions windows environment.

**Comment by bcomnes** [comment]
Adding `npm i tap@unbundled` in front of the previously failing `npm i` step allowed for the installation to proceed without error on windows in that GH windows-latest environment.

**Comment by ghost** [comment]
same issue with tap 14.10.2 on windows 10 home version, tried everything but it fails
 node -v
v12.14.1
npm -v
6.13.4

**Comment by coreyfarrell** [comment]
Please update to the latest version of tap (currently 14.10.6).  This issue is fixed in that version.

**Comment by coreyfarrell** [comment]
I'm closing this as it's been a couple months and nobody has spoken up to say it's still an issue.  If I'm wrong speak up and we will investigate further.

**Comment by shfrmn** [comment]
@coreyfarrell I'm experiencing this issue with `tap@15`. Installation for `tap@unbundled` works fine. Is there a reason it is kept on version 14? Thanks!
