### ISSUE TITLE
[docs] Section "Working with TAP Output Files" — parsing into an object

### ISSUE THREAD

**Issue by revelt** [tapjs/tapjs#626]
The Section "Working with TAP Output Files", https://node-tap.org/docs/tap-files/#working-with-tap-output-files should mention how to parse the raw output files into JS objects, à la `JSON.parse` style. Ideally we should post a tiny example program, "file read, string-in, object-out".

**Comment by isaacs** [comment]
There isn't really a canonical way to do that, but a https://github.com/tapjs/tap-parser example would probably be good there (or just a link to that module).  Patch welcome!

**Comment by revelt** [comment]
I ended up writing a raw Tap parser, https://www.npmjs.com/package/tap-parse-string-to-object — thank you anyway
