### ISSUE TITLE
a process throttling option

### ISSUE THREAD

**Issue by revelt** [tapjs/tapjs#634]
We should consider adding an optional throttling feature.

I noticed a pattern: you code something for 5 minutes, (MacBook Pro) fans are off. Then you run a quick unit test, suddenly fans turn on at full speed. Tests finish quickly, by the time you come back to code, fans turn off. 

All this fan turning on and off is distracting and will vary from machine to machine.

What if we allowed users **to set throttling** in a Tap config file, something like:

```yaml
...
throttle: 0.85
...
```

User could tweak the threshold for maximum setting where until laptop fans would still not get triggered.

**Comment by coreyfarrell** [comment]
I'm not sure this can be done reliably as an arbitrary percentage.  How many CPU cores does your MacBook Pro have?  One thing you could try is setting `jobs: 1` (some number less than your total CPU core's).  So my ThinkPad has 8 CPU cores, if I set `jobs: 6` in theory it should restrict my tests to 75%.  Even this would not be 100% reliable, for example if the code I were testing spawned a lot of worker subprocesses or used worker threads then it could easily exceed the expected maximum CPU usage for the number of jobs.

**Comment by revelt** [comment]
Thank you Corey, very logical idea. I'll close, unless anybody wants to implement this, in which case we can reopen. But there are more burning issues than this..
