### ISSUE TITLE
TAP_JOB_ID proposal

### ISSUE THREAD

**Issue by fleg** [tapjs/tapjs#638]
Hi. I’m using tap for integration testing of pretty large service (7 node.js instances communicating with each other, 4 databases on 2 DBMS). For now I’m not using parallel tests. Passing all tests with service deployment took about 12 minutes. There will be more tests in future, so I’ve started thinking about parallel tests. I tried to use the approach described in the documentation, with `TAP_CHILD_ID  `for altering ports and databases names. It sped up tests for about 45%, which is already quite good, but I think it could work better. Every test before the execution deploys the service; the process took about 20 seconds. What if we deploy n services before tests execution and then tests will just reuse the already deployed services. It requires the connection of the running test with the free service at this moment. `TAP_CHILD_ID `will not work, I propose making, for example, `TAP_JOB_ID `variable which vary from 1 to n.
What do you think?

Example for 11 tests and 4 jobs:

| TAP_JOB_ID |       |       |        |
|------------|-------|-------|--------|
| 1          | test1 | test5 | test9  |
| 2          | test2 | test6 | test10 |
| 3          | test3 | test7 | test11 |
| 4          | test4 | test8 |        |

**Comment by isaacs** [comment]
You know, I initially saw the title and thought "this person doesn't know about TAP_CHILD_ID, it's a support request, I'll get to it when I have time..." but no, I can see how that'd be useful in some scenarios.

Here's what's tricky about this: we don't know what "job" a test will fall in when it's created.  It's not like there are swim-lanes or anything, we just check to see if there are `< this.jobs` current tests running, and if not, go ahead and spawn it.

So, to do this, we'd have to switch from a very naive yapool usage (where we just keep running jobs in a pool, pull them out when done, and add new ones if there's room) to a set of "workers" or something, that each pluck the next job off the queue when their current one finishes.  (See the comment at the top of `lib/test.js`.)

The _nice_ thing about the pool impl is that it lets us do this:

```js
const t = require('tap')
t.jobs = 2
t.test(fn)
t.test(fn)
t.test(fn)
t.test({ buffered: false }, fn)
t.test(fn)
t.test(fn)
t.test(fn)
```

In this case, when it hits the unbuffered test in the queue, it doesn't proceed until _all_ parallel tests in the pool are finished, at which point it re-fills up the pool with running tests.  (This is fundamentally similar, though more elaborate, when using a `tap-parallel-not-ok` file in a folder to mark tests as not parallelizable.)

So you'd have to have the job workers just sitting around doing nothing, and then get signaled to go back to work when it's done.

Not impossible, but quite possibly less elegant.

**Comment by isaacs** [comment]
Another approach that occurred to me would be to have the pool entry just keep an incrementing number attached to each entry in the pool, and set `TAP_JOB_ID` equal to `poolItemIncrementingValue % this.jobs`.  There wouldn't be _actual_ swim lanes in any sense, but it'd look like there were.

But this won't work because:

```js
// fast fn finishes in 10ms
// slow fn finishes in 10s
t.jobs = 4
t.test(slow) // child=1, job=1
t.test(slow) // child=2, job=2
t.test(fast) // child=3, job=3
t.test(fast) // child=4, job=4
t.test(fast) // child=5, job=1 
t.test(fast) // child=6, job=2
```

Here, children 5 and 6 will claim to be in job 1 and job 2, but child1 and child2 are still going, so if the job id is used to identify a resource or something, they'd conflict.

Yet another approach would be to assign the job id from a departing job to the new job being added to the queue (or to pool.length+1 for unbuffered tests and new tests filling up the pool).  Could be a tricky juggling act to get it just right though, if we do have the contract that there are no two tests running at the same time with the same job id.

**Comment by fleg** [comment]
> You know, I initially saw the title and thought "this person doesn't know about TAP_CHILD_ID

Well, next time I will be more specific with title.

> Not impossible, but quite possibly less elegant.

My thoughts exactly, after several hours of trying to implement this feature.

Eventually I came up with this pretty dumb and naive, but working solution. Require this code via `--node-arg -r --node-arg parallel.js` and pass jobs count via `JOBS` env.
```js
const fs = require('fs');
const lockfile = require('lockfile');
const onExit = require('signal-exit');
const tap = require('tap');

module.exports = () => {
	const jobs = Number(process.env.JOBS);
	let job = null;

	for (let i = 0; i < jobs; i++) {
		try {
			lockfile.lockSync(`.test_${i}.lock`);
			job = i;
			break;
		} catch (err) {}
	}

	if (job === null) {
		throw new Error('eh');
	}

	process.env.JOB_ID = job;

	onExit(() => {
		lockfile.unlockSync(`.test_${job}.lock`);
	});
};
```

**Comment by isaacs** [comment]
Yikes, lockfiles will do the trick but... oof, that's some overhead.

Another idea would be to just create a pseudo swim-lane type jobId map, and assign the child test to the first job that's not currently in use.

```
// initialize lane tracker
const lanes = new Map([...new Array(jobs + 1).fill(null).map((n, i) => [i, n])])
let currentLane = 0

// when creating a new child...
while (lanes.get(currentLane) !== null) {
  currentLane = (currentLane + 1) % jobs
}
lanes.set(currentLane, child)
env.TAP_JOB_ID = child.jobId = currentLane

// when the process ends...
lanes.set(child.jobId, null)
```

**Comment by fleg** [comment]
Yeah, nice try, but this would not work with `--node-arg -r --node-arg parallel.js` approach, each test will contain it own lane tracker and all tests will end up with `env.TAP_JOB_ID === 0`. I guess, there is no way to implement this outside tap core without using locks, shared memory, etc.
