### ISSUE TITLE
Error [ERR_REQUIRE_ESM] with Node.js 13

### ISSUE THREAD

**Issue by ozonep** [tapjs/tapjs#653]
I created new project using ESM, since Node 13.2+ supports it without any flags.
Instead of using .mjs extension I added "type: module" to package.json.
With this setup "tap" throws an error, when I try to run "tap test/test.js":

`Error [ERR_REQUIRE_ESM]: Must use import to load ES Module`
`require() of ES modules is not supported.`
`require() of /index.js from /test/test.js `

even though I only use imports everywhere and in test.js import of index.js looks like this:
`import {fastify} from '../index.js';`
If I delete "type: module" & change extensions to ".mjs" everything works just fine. 

Is it Node.js or "tap" issue? 

Node version: 13.10.1
npm: 6.13.7
tap: 14.10.6

**Comment by ozonep** [comment]
Argh, ok, that's known problem, discussed here:
https://github.com/standard-things/esm/issues/868

I guess 'esm' package is abandoned & will never be fixed.

**Comment by ozonep** [comment]
Will be fixed by #651 
For now just manually disable ESM by '--no-esm'.

**Comment by coreyfarrell** [comment]
Note the PR you referenced will not be part of tap v14, that is going into tap v15 (it is a breaking change).  Does manually disabling user-land ESM solve the issue for you?

**Comment by ozonep** [comment]
Yeah, I see that.
Adding --no-esm fixes the issue => it's a problem with "esm" package, probably it doesn't support "type: module" field...

**Comment by coreyfarrell** [comment]
I think it's that the `esm` module doesn't really support `.js` files the same way as it supports `.mjs` files.  Setting `type: module` but still using `.mjs` would work without disabling the `esm` package.

On a more important note based on what you said `--no-esm` is the right choice for your tests to run correctly.  You want your tests to load your code via the node.js native ES module loader, the `esm` package bypasses this.  So absolutely I recommend setting `--no-esm` for any module which provides `type: module` or has production code with `.mjs` extension.

**Comment by aquator** [comment]
I think I have a workaround, at least it seems to be working for me:

Just put a _package.json_ to your **test root**, it can be an empty json document like `{}`.

I have `"type": "module"` set for the project, and I can use `tap --coverage` for testing. AFAIK _esm_ traverses the project tree until first _package.json_ is found. and this way it is getting tricked, as it finds the one without `"type": "module"` first.

**Comment by donmccurdy** [comment]
I'm seeing this error with node-tap v15, running tests written in TypeScript. My test includes the following import:

```ts
// index.test.ts
import { Geometry } from 'three/examples/jsm/deprecated/Geometry';
```

... which is a `.js` file (with type definitions) annotated with `{type: 'module'}`. The error below is printed:

```
$ tap test/*.test.ts --ts | tap-spec
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/donmccurdy/Documents/Projects/three-to-cannon/node_modules/three/examples/jsm/deprecated/Geometry.js
require() of ES modules is not supported.
require() of /Users/donmccurdy/Documents/Projects/three-to-cannon/node_modules/three/examples/jsm/deprecated/Geometry.js from /Users/donmccurdy/Documents/Projects/three-to-cannon/test/index.test.ts is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename Geometry.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/donmccurdy/Documents/Projects/three-to-cannon/node_modules/three/examples/jsm/package.json.
```

Notably, I'm not explicitly writing `require()` anywhere, I guess that's output of the compiled TS test file? And the `Geometry.js` file is both outside my project and intended for use in browsers, so `.cjs` is not an option. It sounds like the `--no-esm` option no longer exists, is something else required for TS?

- tap v15.0.9
- node v14.15.4

> **EDIT:** Related: https://github.com/tapjs/node-tap/issues/679
