### ISSUE TITLE
Create option to set ts-node --project option

### ISSUE THREAD

**Issue by alemagio** [tapjs/tapjs#659]
Hi, recently I worked on a Typescript project using tap. It's great, I only had one issue:

when running typescript tests and my tsconfig.json file is not in the root of the project there is no easy way to tell tap where it can take that file.
ts-node has an option '--project' where it is possible to specify a path for that file.
Do you think it would be possible to add that option, or another way, to tell tap where the typescript config file is located?

As a workaround I've used the TS_NODE_PROJECT env variable in my package.json script but it's not ideal.

**Comment by isaacs** [comment]
The `--tsconfig=<filename>` option will be in next tap@pre release.
