### ISSUE TITLE
If "skip" is in name of test, test is marked as skipped, even though it isn't skipped

### ISSUE THREAD

**Issue by acdibble** [tapjs/tapjs#664]
I have [a class I'm testing](https://github.com/acdibble/range/blob/master/test/LazyRange/skip.test.ts#L4) with a member function named `skip`. When you put `skip` in the title of a test, it will mark it as skipped in the output, even though the test runs:
![image](https://user-images.githubusercontent.com/21286068/79050198-bd9de880-7c28-11ea-88ce-f3efc42f179e.png)
If I replace `skip` in the test name with something else, it does not exhibit this behavior.

**Comment by juergba** [comment]
Have a look at the [tap specification](http://testanything.org/tap-version-13-specification.html).

> Skipping tests
If the directive starts with # SKIP, the test is counted as having been skipped.

Your `tap.test('LazyRange#skip', async (suite) => {` contains such a directive `#skip` and is correctly parsed and reported as skipped.

**Comment by coreyfarrell** [comment]
The specification doesn't say anything about escaping but `tap.test('LazyRange\\#skip', ...)` does not get reported as a skipped test.  Might be that we need to escape any `#` in the title with a backslash.

**Comment by juergba** [comment]
Or maybe the space does matter. The specification shows `# skip`, not `#skip`.

**Comment by isaacs** [comment]
Yeah, I think requiring the space is fine, I'll land tapjs/tap-parser#71.  Also, node-tap should stubbornly refuse to put `#skip` or `#todo` in the name of a test if it's not marked as a skip in the options.  Maybe we could just replace the `#` with `%` or or `_` or something (or just removing it), so it's still clear to humans what it's about?  There's already precedent, we do this for `\n` for example.
