### ISSUE TITLE
How to let tap know of custom types?

### ISSUE THREAD

**Issue by jerrythomas** [tapjs/tapjs#672]
`node-jq` typescript definitions are missing a parameter input. By creating a custom @types folder with the corrected types solves this for build. 

However tap is not aware of these custom types. How do I modify the tap configuration so sthat it can also run without errors?

[Reproducible example](https://github.com/jerrythomas/custom-types-ts-tap)

```bash
npm run build
```
 works without errors

```bash
npm test
```
fails with the error 
```text
Argument of type '{ input: string; output: string; }' is not assignable to parameter of type 'Partial<IOptions>'
```text

**Comment by isaacs** [comment]
With tap v18, basically anything you can provide to `ts-node` will be handled transparently by tap, since it just uses the `ts-node/esm` loader.

Check it out with `npm i tap@pre`. Be sure to read the [changelog](https://node-tap.org/changelog/#18.0) as a lot has changed.
