### ISSUE TITLE
TypeScript dependency is bloating the library

### ISSUE THREAD

**Issue by coreybutler** [tapjs/tapjs#678]
Is the [TypeScript dependency](https://github.com/tapjs/node-tap/blob/master/package.json#L53) actually necessary in this library? That lone modules makes up 2/3 of the `node_modules` footprint (and doubles the size of the library overall).

**With TypeScript**
![image](https://user-images.githubusercontent.com/770982/84980215-11302500-b0f7-11ea-8381-8e33fa29ed32.png)

**Without TypeScript**
![image](https://user-images.githubusercontent.com/770982/84980179-fa89ce00-b0f6-11ea-8a88-cdb6c1022fab.png)

The unit tests appear to yield the exact same outcome with or without the library, and I don't _think_ any of the other modules are depending on it (I'm not a TS user).

I may be missing something, but this seems like a needless waste of space.

**Comment by ghost** [comment]
Bingo; I was wondering why too -- unless for TypeScript typings support later on in which case it should be at most a devDependency.

Definitely a waste of space in the current artefact.

**Comment by isaacs** [comment]
Huh, yeah, looks like when we switched to using `ts-node`, it no longer needs to have typescript as a dep.  (Maybe it used to once upon a time?)

I think you're right, it can be removed.

**Comment by coreybutler** [comment]
@isaacs I was assuming the same - this seems like it was probably a remnant from a past requirement. Given this seems to just be a one-line deletion, maybe it's less hassle to change it yourself? I'd be happy to PR it though, if you prefer.

**Comment by coreyfarrell** [comment]
From what I can tell typescript is a peer dependency of ts-node so it is probably needed.

**Comment by isaacs** [comment]
Oh, I spoke too soon.  Typescript is a peer dep of ts-node.

Removing it breaks the `test/run/ts.js` test.  My guess is that `require.resolve('typescript')` is finding something elsewhere on your machine if it doesn't break any tests to remove it?

In any event, it is indeed huge, and we could probably make it an optional-but-not-installed-by-default dep by just catching the error.  If we're going to go that route, though, we should probably not install `ts-node` either, and just raise a useful error if no ts-node is found.

After all, anyone writing tests in `.ts` files probably already has `typescript` and `ts-node` in their project's dev deps, and we can avoid the weight for anyone who isn't using it.  In any event, though, that's a breaking change for sure, so we can get to it in v15.

**Comment by coreybutler** [comment]
I'm not sure why the tests would pass when removing it, since I didn't _think_ I have TS anywhere else.... but maybe I overlooked something. If I get a chance, I'll run the tests in a clean environment. Regardless, making it optional in v15 seems like a solid plan to me.

**Comment by coreyfarrell** [comment]
Letting the user install `typescript` and `ts-node` also allows them to choose which version gets installed so this seems like a plus.  I don't use typescript but I've heard they play fast and loose with semver (semver-minor changes are sometimes viewed by many as breaking).

**Comment by ghost** [comment]
FWIW, I created [tappity-tap](https://www.npmjs.com/package/tappity-tap), a self-contained bundle consisting of tap together with TypeScript `.d.ts` typings, as, being an avid TypeScript developer, I prefer types to be in lock-step with the correct version of the runtime package.

What astounds me is that the **unpacked size is 86.1 MB** [(see metrics here on npm)](https://www.npmjs.com/package/tappity-tap). The implication of this is that any developer using tap sustains an installation payload of over 85 megabytes. This is totally ludicrous.

Appears that from humble minimalist beginnings, tap has become a totally bloated library.

_Justin Johansson, [@indiescripter on Twitter](https://twitter.com/IndieScripter)_

**Comment by coreyfarrell** [comment]
@indiescripter TypeScript causes most of the install size bloat.  Just the [typescript](https://www.npmjs.com/package/typescript) package has an unpacked size of 54MB.  I agree it will be nice to reduce the size of tap, that is the reason we're discussing not bundling TypeScript.  Since you are targeting TypeScript support this is not the place to complain about install size.

**Comment by ghost** [comment]
Hi @coreyfarrell, sorry if sounded overly complaining; really meant it as constructive criticism though realise it didn't come over that way & do acknowledge that tap is OSS that people can use free-of-charge & for which contributors have donated their time for free.

If there is a way of unbundling TypeScript, that would be +ve move; understand that some things may appear easy by not always straightforward.

**Comment by jsumners** [comment]
I loathe TS. And I default all of my `tap` installs to disabling the TS loader. But I really couldn't care much less about the size of the testing library. It's not harming any production deploy, and all package managers implement some sort of local cache nowadays. If it's really a big issue, managers like `pnpm` will abstract this size annoyance away.

That being said, I am totally on board for making it an optional dependency with a runtime error. We do the same in `pino` for prettification support. It works well for the majority of users. We get occasional complaints, but they are few and far between.

**Comment by IlyaSemenov** [comment]
Besides bloating, on modern installs with Typescript 4 as the main interpreter `tap` pulls Typescript 3.9 for no apparent reason.

**Comment by jsumners** [comment]
The reason is very plainly apparent -- https://github.com/tapjs/node-tap/blob/4d926fb5e07eceac0f83830e6e0abe2eecdbe39b/package.json#L53

**Comment by IlyaSemenov** [comment]
@jsumners A package.json entry is not a _reason_, it's a _cause_.

node-tap itself can work fine with TS4, there were no breaking changes. I just tested it against typescript@4.0.2.

**Comment by jsumners** [comment]
You asked for the reason. I gave it to you. If you don't want to understand it, that's on you. 


https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004

**Comment by isaacs** [comment]
Tap v15 will reference typescript and ts-node as optional peerDependencies, so that they'll be exposed to tap by pnpm, but not installed by default (except when using npm v7, and a _different_ version of typescript is already present in the tree).

Also, typescript support now requires passing the `--ts` flag on the command line, or setting `{ "tap": { "ts": true } }` in the package.json file.  `.tsx` support requires enabling _both_ typescript _and_ jsx.
