### ISSUE TITLE
'bin' is not recognized as an internal or external command on Windows 7 box

### ISSUE THREAD

**Issue by thomaswhite** [tapjs/tapjs#68]
I just checked out the code on a  Windows 7 box and installed dependent modules. Running the 'npm test' produced the following output:

D:\2013\github\node-tap>npm test

> tap@0.4.0 test D:\2013\github\node-tap
> bin/tap.js test/*.js

'bin' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0

What am I missing?

**Comment by isaacs** [comment]
Oh, that should probably be `node bin/tap.js test/*.js`

**Comment by thomaswhite** [comment]
thanks, it works now.
