### ISSUE TITLE
watch + coverage-report = signal fail

### ISSUE THREAD

**Issue by ahmadnassri** [tapjs/tapjs#686]
seems like there's a collision between running with `--watch` and attempting to generate coverage reports at the same time:

```json
  "scripts": {
    "test": "tap test --100 --coverage-report=lcov --no-browser",
    "test:watch": "tap --watch --coverage-report=lcov --no-browser",
  }
```

resulting repl:

![image](https://user-images.githubusercontent.com/183195/88352159-d5583300-cd26-11ea-8664-1334f89a26a2.png)

**Comment by isaacs** [comment]
Repl is completely redesigned, this is no longer relevant in tap 18.
