### ISSUE TITLE
Lifecycle events and Typescript

### ISSUE THREAD

**Issue by aldis-ameriks** [tapjs/tapjs#690]
Is Typescript supported with lifecycle events?
e.g.
`tap --before=before-tests.ts`

It seems that the file does not get transpiled and fails.
I couldn't find a definitive answer in docs or past issues.

**Comment by ibnumusyaffa** [comment]
Hi, any ideas why it does not work ?

```

> typescript-esm-tsx-starter@1.0.0 test
> NODE_ENV=test LOG_MODE=test tap run --passes  --before=src/tests/utils/setup.ts --include='src/tests/**/*.test.+(js|ts|jsx|tsx)'


Asserts:  0 pass  0 fail  0 of 0 complete
Suites:   0 pass  0 fail  0 of 3 complete

/home/ibnu/personal/ecommerce-starterkit/node_modules/pirates/lib/index.js:101
    loaders[ext] = Module._extensions[ext] = function newLoader(mod, filename) {
```

**Comment by isaacs** [comment]
@ibnumusyaffa Please post a new issue for new problems, and include the details requested in the issue template. Whatever problem you're having, it's almost certainly not related to the original problem here.
