### ISSUE TITLE
Enable TS users to specify tsconfig file for ts-node

### ISSUE THREAD

**Issue by Ethan-Arrowood** [tapjs/tapjs#697]
I have a project with multiple tsconfig files (tsconfig.dev.json, tsconfig.prod.json, tsconfig.testing.json) that all extend from one base config tsconfig.base.json. 

ts-node looks for a tsconfig.json file by default for compiler options, but also allows users to specify one directly using `--project` (https://www.npmjs.com/package/ts-node#loading-tsconfigjson). 

I'd like to see if we could add a cli option such as `--ts-project` which would be piped down to the `ts-node` process I believe is executed here: https://github.com/tapjs/node-tap/blob/4d926fb5e07eceac0f83830e6e0abe2eecdbe39b/bin/run.js#L652-L668

If this feature is given a 👍 by the maintainers I'd be happy to try and contribute it.

**Comment by KabutoYamato** [comment]
you can use a register for that, in that way i use a tsconfig dedicated for tsnode and other for builds

tn.register.js
```javascript
const tnode = require("ts-node")

tnode.register({
    compiler: 'ttypescript',
    project: './tsconfig.TsNode.json',
    files: true
});


```


after creating your register you can use it in .taprc file
```
ts: true
test-regex: Tests/(.+)\.tap\.ts
node-arg: 
    - --require=./tn.register.js
```

**Comment by jordanbtucker** [comment]
Even better, tap could allow users to specify arguments passed to ts-node like it does for node.

```bash
tap --ts-node-arg=--project=test/tsconfig.json
```

**Comment by isaacs** [comment]
In tap 18, ts-node is used strictly as a loader, which I'm pretty sure means the way to specify the tsconfig file is with the `TS_NODE_PROJECT` env.

I'll add a `--tsconfig` option to the `@tapjs/typescript` plugin to set that env.
