### ISSUE TITLE
Hooks to enable custom test runners

### ISSUE THREAD

**Issue by jamestalmage** [tapjs/tapjs#700]
`node-tap` has structured itself in a way that lends itself to extension just by nature of how simply the core works: Launch child processes which produce well specified outputs on standard streams.

We handle the default supported file types in a series of `if`/`then` switches [here](https://github.com/tapjs/node-tap/blob/4d926fb5e07eceac0f83830e6e0abe2eecdbe39b/bin/run.js#L652-L695). I don't think it would take much work to convert that code block to something pluggable. For each file, just search the list of installed plugins until one says it can handle the file, and the plugin is responsible for spawning the child process and handing it back for reporting output.

In particular, I think this would be great for polyglot projects. Providing testing for additional languages, like Lua, could be as simple as defining a plugin to launch a [TAP compliant runner](https://github.com/Olivine-Labs/busted/issues/642) for those files. I'm envisioning the simplest plugins might be as easy as specifying supported file extensions, and a command line definition:

```js
// lua-plugin.js
import {GenericCommandLinePlugin} from 'node-tap/plugins-helpers'

export default new GenericCommandLinePlugin({
  supportsFile: (filename) => /_spec\.lua/.test(filename),
  cmd: (filename) => `lua ${filename} -o tap`
})
```

You sort of already support this with the [executable runner](https://github.com/tapjs/node-tap/blob/4d926fb5e07eceac0f83830e6e0abe2eecdbe39b/bin/run.js#L690-L692). But I think it would be great to let TAP handle the file globbing, watching, report generation, etc, and allow plugins to contribute to coverage data and watcher data as well. We would just need a well specified way for plugins to contribute that data. TAP is already well defined, we'd just need to specify how plugins should contribute coverage and watcher data.

I think coverage information is also pretty easy. Runners should just dump coverage data to `.coverage` folder in a supported format. 

I am not clear on how easy file watching would be. How do we communicate which non-test sources were `require()`d during a test run for `js` code? Presumably all it would take to enable plugins to engage in watch support would be documenting the means and format of child processes communicating that up to the parent process. 

Of all the test runners available out there, I feel like `node-tap` is the one best situated to become the defacto runner for polyglot projects. I think this could provide a pretty amazing developer experience.

**Comment by isaacs** [comment]
This is pretty much accomplished in tap 18 with plugins. For example, typescript support is provided by the `@tapjs/typescript` plugin, and if that's disabled, tap won't run `.ts` files (or `tsx`, `mts`, etc.)

A plugin can export a [`testFileExtensions` array](https://node-tap.org/plugins/#testfileextensions) and a [`loader` module identifier](https://node-tap.org/plugins/#loader).

Check it out with `npm i tap@pre`. Be sure to read the [changelog](https://node-tap.org/changelog/#18.0) as a lot has changed.
