### ISSUE TITLE
TypeScript ESM support

### ISSUE THREAD

**Issue by L2jLiga** [tapjs/tapjs#703]
*Problem*:
Currently it seems to be impossible to use `tap` when using TypeScript with ESM.

*Possible solution*:
`ts-node` provides experimental [`support for ESM`](https://github.com/TypeStrong/ts-node/issues/1007) via [Node's loader hooks](https://nodejs.org/api/esm.html#esm_experimental_loaders) and it would be awesome if tap can support such loaders by default.

**Comment by rgrannell1** [comment]
> _Problem_:
> Currently it seems to be impossible to use `tap` when using TypeScript with ESM.

It's not that easy, but not impossible:-. For an example, see:

https://github.com/rgrannell1/kohl/tree/6a8d66f8fc5d855fc048c2e531dea4839728557c

https://raw.githubusercontent.com/rgrannell1/kohl/6a8d66f8fc5d855fc048c2e531dea4839728557c/tests/Body/Body.test.tsx

at the moment I:
- set `type: module` in the package.json file
- run tap against the compiled target code `npx tsx && npx tap dist/tests --no-esm --no-coverage`

and things work pretty well. I hope this helps

**Comment by L2jLiga** [comment]
Yeah, I understand that it wouldn't be easy, as of now my workaround - run test files with ts-node instead of tap.

**Comment by calebboyd** [comment]
It looks like the following configuration works fine with tap 15 (coverage is not yet supported with the loader option in nyc)

```json
  "tap": {
    "test-regex": "src\\/.*test\\.ts",
    "node-arg": "--loader=ts-node/esm"
  },
```

For the OOBE I think all that would need to happen is the for the `--ts` flag to use the loader instead of the require hook.. But the APIs are currently marked experimental.

**Comment by alex996** [comment]
As an aside, `--no-esm` is no longer a valid option:

```
Error: invalid argument: --no-esm
Run `tap --help` for usage information
```

```json5
/* package.json */
"tap": "^15.1.6",
```

**Comment by isaacs** [comment]
@alex996 That's because the use of `@std/esm` is no longer an option (it doesn't work in recent nodes, and isn't widely used any longer).

This is the same as  https://github.com/tapjs/node-tap/issues/807, I believe.  At least, the solution to #807 will be the solution to this.
