### ISSUE TITLE
Support .taprc{.yml,.yaml}

### ISSUE THREAD

**Issue by jsumners** [tapjs/tapjs#706]
A little quality-of-life request: support `.taprc.yml` and/or `.taprc.yaml` file names. This would allow editors to recognize the format of the file and behave accordingly.

**Comment by jsumners** [comment]
@isaacs if I were to work on this, would you consider it?

**Comment by isaacs** [comment]
I'd kind of prefer not to have multiple different filenames to have to look for.  This is always a thing about eslint that annoys me, actually.  (Is it `.eslintrc`?  `eslintrc.json`?  `.eslintrc.js`? Etc.)

You can configure most editors to treat `.taprc` as a yaml file.

**Comment by jsumners** [comment]
I think it is better developer experience to not have to configure an editor to recognize an extensionless file as a certain type.
