### ISSUE TITLE
Question: Way to determine complete test coverage?

### ISSUE THREAD

**Issue by dchambers** [tapjs/tapjs#707]
I've been using `tap --100`, and it's a game changer! I love the fact I can lift side-effects out of the code I choose to test, and get guidance so I can know I've tested it completely, yet `tap` doesn't bother me about the stuff I don't want to unit test 💯.

However, I worry that I may have missed some files accidentally that I would like to cover, but just don't realise it. Is there a way to look at the full test coverage regardless of the coverage-map?

I thought I might be able to force `tap` to do this for me by setting a custom coverage-map that says that all test files cover all source code, like so:

```js
const glob = require('glob')

const allSourceFiles = glob
  .sync('src/**/*.ts*')
  .filter((f) => !f.match(/\.(test|spec).tsx?$/))
  .filter((f) => !f.match('/generated/'))

module.exports = () => allSourceFiles
```

but it didn't seem to work for me. Any guidance here please?

**Comment by isaacs** [comment]
There's two ways I've done this in the past. 

If you have a coverage map that maps every test to every file, then that's not particularly useful. (It's the same as not having a coverage map!)

But you can have a single test suite that had this mapping, and all it does is require() every file. We've done this with npm to track our progress towards 100% test coverage in npm v7. 

Here's the coverage map file: https://github.com/npm/cli/blob/latest/test/coverage-map.js

And here's the "load all" test: https://github.com/npm/cli/blob/latest/test/lib/load-all.js

Then in "normal" tests in ci and dev, we aren't failing for missing coverage (but we _are_ failing if coverage slips below 100% for any unit we've written new tests for), and we use `npm run check-coverage` to track our progress towards covering every unit. 

This is of course rather elaborate and makes sense for a project of npm's scope and complexity. A much simpler approach is to set `--nyc-arg=--all`, if your project follows some basic conventions, but may not work for unusual cases.

**Comment by dchambers** [comment]
Thank you so much for taking the time to respond, but also for sharing such an excellent piece of software ❤️.
