### ISSUE TITLE
test-ignore option is not honored if a path is given via CLI

### ISSUE THREAD

**Issue by coreyfarrell** [tapjs/tapjs#708]
```sh
npm init -y
npm i -D tap
mkdir test
echo 'require("tap").fail()' > test/test.cjs
echo 'require("tap").pass()' > test/test.js
echo 'test-ignore: ".cjs$"' > .taprc
```

Then run `npx tap`, see that only `test/test.js` is executed.  Now run `npx tap test`, this will fail as `test/test.cjs` is executed.

**Comment by isaacs** [comment]
Working as expected with the `include` and `exclude` globs in tap 18.
