### ISSUE TITLE
runs fine standalone, fails with tap when using ts-node / npx tap --no-ts --node-arg=--require=./node_modules/.bin/ts-node

### ISSUE THREAD

**Issue by craigphicks** [tapjs/tapjs#711]
`test/hello.js` has content
```
//import {tap} from './lib/testlib'
import tap from 'tap'
tap.pass('hello')
```
works well called with 
```
npx tap --no-ts --node-arg=--require=./node_modules/.bin/ts-node test/hello.ts
```
and also called with 
```
npx ts-node test/hello.ts
```

However, if I change the content of `test/hello.ts` to 
```
import {tap} from './lib/testlib'
//import tap from 'tap'
tap.pass('hello')
```
where 'test/lib/testlib' has content
```
import tap from 'tap'
export {tap}
```
then calling with 
```
npx tap --no-ts --node-arg=--require=./node_modules/.bin/ts-node test/hello.ts
```
now fails, but calling with 
```
npx ts-node test/hello.ts
```
still works.

I can't see anything in the documentation that mentions any limitations on the way `tap` is imported.  Is there a workaround?

**Comment by isaacs** [comment]
This is likely to be either fixed or otherwise invalidated depending on how https://github.com/tapjs/node-tap/issues/807 lands.  Leaving it open, but might end up being more work than it looks like.

**Comment by craigphicks** [comment]
Closing in favor of #807.
