### ISSUE TITLE
snapshot function write silently transforms `bigint` data to `undefined`

### ISSUE THREAD

**Issue by craigphicks** [tapjs/tapjs#712]
... when it should complain loudly.  As is, the match test will always pass `bigint` data on match, even when it differs from the viewpoint of the test program.

**Comment by jsumners** [comment]
Can you provide an example test to illustrate the issue?

**Comment by coreyfarrell** [comment]
This issue is fixed by the release of tcompare 3.0.5.  Once you upgrade you will have to regenerate any snapshots which include `bigint` data.
