### ISSUE TITLE
tap's internal unhandledRejection & uncaughtException takes over and prevents any internal app captures from executing

### ISSUE THREAD

**Issue by ahmadnassri** [tapjs/tapjs#722]
I know this techincally belong in https://github.com/tapjs/async-hook-domain, but I'm opening here for more visibility.

tap's async-hook, takes over `unhandledRejection` and `uncaughtException` for a meaningful reason to the library's purpose... however, in the case of `unhandledRejection` it takes over completely, and does not allow your app's built-in `unhandledRejection` funciton to even trigger.

###### `app.js`

```js
process.on('unhandledRejection', () => {
  // this will do something else as intended per business logic
})
module.exports = () => {

  Promise.reject('this should be handled internally')

  return 'success'
}
```

######  `no-tap.js`

```js
const app = require('./app.js')
const assert = require('assert')

const result = app()
assert.strictEqual(result, 'success')
```

###### `with-tap.js`
```js
const app = require('./app.js')
const { test } = require('tap')

test('should be successful', assert => {
  assert.plan(1)

  const result = app()
  assert.equal(result, 'success')
})
```

this is also true for `uncaughtException`:

###### `app.js`

```js
process.on('uncaughtException', () => {
  // this will do something else as intended per business logic
})

module.exports = (result) => {

  result = 'success'

  throw new Error('this should be handled internally')
}
```

###### `no-tap.js`

```js
const app = require('./app.js')
const assert = require('assert')

let result
app(result)
assert.strictEqual(result, 'success')
```

###### `tap.js`

```js
const app = require('./app.js')
const { test } = require('tap')

test('should be successful', assert => {
  assert.plan(1)

  let result
  app(result)
  assert.strictEqual(result, 'success')
})
```

Note that `app.js` is always included BEFORE `tap`, and the `process.on` are the first thing executed, yet tap still takes over due to the async hooks.

if you're wondering what the real world usage here, there are a few, but the most basic one, is capturing failures in a live system for the purpose of formating / storing / forwarding the logs, then throwing out the errors again to kill the process (as intended)

this will be impossible to write test for in tap given the current behavior

**Comment by isaacs** [comment]
Hm.  You can use [`t.expectUncaughtException()`](https://node-tap.org/docs/api/asserts/#texpectuncaughtexceptionfn-expectederror-message-extra) which is a bit of an odd duck, since it's only checked at the _end_ of the test.

Currently it only supports actually uncaughtException type errors, but it would be trivial to add a `t.expectUnhandledRejection()` option, or just have `t.expectUncaughtException()` handle both.  Which do you think makes the most sense?  I'd lean towards making it a separate method, just in the interest of being explicit.

All that said, if you're testing uncaught exceptions and unhandled rejections and such, using `assert` _may_ just be the way to go anyway, since you're clearly mucking around in some very lowlevel junk.

**Comment by ahmadnassri** [comment]
> All that said, if you're testing uncaught exceptions and unhandled rejections and such, using assert may just be the way to go anyway, since you're clearly mucking around in some very lowlevel junk.

that's exactly what I ended up doing ... the convience of a test runner's report and coverage handling is lost to manual workaround, which is okay I guess for a small library https://github.com/ahmadnassri/node-uncaught-extender/commit/269015c1c7eb23073bd5bed2073b5cd02d579917

that said, one of the biggest criticism of Jest and others is taking over the global context and sowalloing up exceptions and rejections, if there is a path to avoid doing that in `tap` _(or at least allowing it to be enabled/disabled it behind a CLI flag?)_ it would be for the best.

**Comment by isaacs** [comment]
You may want to try using `libtap` directly, which allows you to use the same TAP library functions without a global runner or CLI.  You can still run your tests with the `tap` CLI, but have more control over what gets injected into the global process in your test environment.  @coreyfarrell likely has some examples of tests using libtap that you can refer to.

**Comment by coreyfarrell** [comment]
I'm not sure if libtap let's you disable unhandled handling and I'm not going to be able to check it (not on computers much currently).  If it doesn't I'd be good with a semver-minor to let it be disabled without changing the default functionality.

**Comment by isaacs** [comment]
A lot has changed in the last 2 years in this space, and I'm not sure this is still an issue, since async-hook-domain uses the newer error handling bits in node now.
