### ISSUE TITLE
Is it possible to run only tests without any additional jobs.

### ISSUE THREAD

**Issue by ansavchenco** [tapjs/tapjs#723]
I have only one test. Here is the test and my config.
```typescript
require('dotenv').config();
import tap from 'tap';
import { createMercuriusTestClient } from 'mercurius-integration-testing';
import { GetAllContainersWithSpecimensDocument } from '../graphql/generated';
import { app } from '../app';

tap.test('works', async (t) => {
  const client = createMercuriusTestClient(app);
  const res = await client.query(GetAllContainersWithSpecimensDocument);
  t.equal(res.errors, undefined);
  t.end();
});
```
```yaml
test-regex: .*\.test\.ts
coverage: false
no-coverage-report: true
```
This is the result that is printed in the console when I run it.
```
 PASS  src/tests/bacis.test.ts 1 OK 114.04ms
              
  🌈 SUMMARY RESULTS 🌈  
                         
Suites:   1 passed, 1 of 1 completed
Asserts:  1 passed, of 1
Time:     13s
```

As you can see, the whole run took 13s, even though after about 4 seconds all assertions have already been passed.
What has been happening during that time. I disabled code coverage checks and report generations.

How can I make `tap` command run only tests and do nothing else?

**Comment by coreyfarrell** [comment]
Can you test with the tap 15 pre-release?  A number of changes were made which should reduce overhead.

**Comment by ansavchenco** [comment]
Tested this on `v14.11.0` and it didn't helped. 

It looks like `tap` has nothing to do with this problem cause when I run this exact test with `jest` it says the following, hangs for about 10 seconds and then exits.
```
Jest did not exit one second after the test run has completed.
This usually means that there are asynchronous operations that weren't stopped in your tests.
```
I thinks `createMercuriusTestClient` and the way it performs queries is the reason of this strange delay after all assertions have been passed. `tap` just silently waits for mercurius client to complete some async operations.

Closing this issue for now. Thanks!
