### ISSUE TITLE
--watch & --browser will not work if --nyc-arg overrides paths

### ISSUE THREAD

**Issue by ahmadnassri** [tapjs/tapjs#724]
when using `--nyc-arg` to override `nyc` default paths (`report-dir` and `temp-dir`) the `--browser` and `--watch` flags break since they are hard-coded to expect the default values of: `./coverage` and `./.nyc_output` respectivly ...

reccomendations: _(at least one of the following would make most sense, dealer's choice)_

- docs: indicate in `--watch`, `--browser` _(and any other similar)_ docs that they will not work if paths are changed
- throw a warning in terminal when detecting `--nyc-arg` with `temp-dir` or `report-dir`
- actually parse `temp-dir` or `report-dir` and use the values in internal calls to `opener` and test watch...

**Comment by isaacs** [comment]
I like the third option the best.  Unfortunately, as more of the Node ecosystem moves to the (sadly, imo not ready for prime time) native ESM module system, we're probably going to have to ditch NYC for C8, which means that anything we do here will have to be completely re-done soon.

Still, patch welcome.  Wouldn't be hard to look for `--report-dir` and `--temp-dir` in the `options['nyc-arg']` array and parse them out.  Only tricky bit is that you might get either `{ 'nyc-arg': ['--report-dir=./foo'] }` or `{'nyc-arg': ['--report-dir', './foo']}` depending on whether the user does `tap --nyc-arg=--report-dir=./foo` or `tap --nyc-arg=--report-dir --nyc-arg=./foo`.  But that's not too terribly hard to accomplish.

**Comment by isaacs** [comment]
All dirs are now relative to `config.globCwd` in tap 18. Basically, wherever it finds its first config file, or a package.json file, or a `.git` folder, it assumes "that is the project", and puts its `.tap` directory there. Then everything it uses is in that directory, test filenames are printed relative to that dir, etc.

`npm i tap@pre` to get it. Be sure to review the [changelog](https://node-tap.org/changelog/#18.0), a bunch of stuff has been updated.
