### ISSUE TITLE
bind-obj-methods 2.0.1 broke old versions of node

### ISSUE THREAD

**Issue by bahamat** [tapjs/tapjs#727]
* tap says engines `node>=4`
* tap has a dependency of `bind-obj-methods ^2.0.0`
* bind-obj-methods `2.0.1` requires engines `node>=10`

* The bind-obj-methods dependency should be changed to be =2.0.0
* A version of tap that depends on bind-obj-methods 2.0.1 or greater should be a major version change

See also isaacs/bind-obj-methods#5

**Comment by isaacs** [comment]
Should be fixed.  Just published a 2.0.2 which reverts the change, and a 3.0.0 which brings it back, and deprecated 2.0.1 so it won't be the default resolution by npm.
