### ISSUE TITLE
Please fix deprecated dependencies

### ISSUE THREAD

**Issue by ilg-ul** [tapjs/tapjs#729]
Installing a package which depends on tap@14.11.0 triggers warnings:

```console
ilg@wks ~ % npm install xpm@next
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
```

These two deprecated dependencies are also used by tap:

```console
ilg@wks ~ % npx npm-remote-ls tap | grep request
npx: installed 112 in 3.238s
   │  └─ request@2.88.2
ilg@wks ~ % npx npm-remote-ls tap | grep har-validator
npx: installed 112 in 2.804s
   │     ├─ har-validator@5.1.5
ilg@wks ~ % 
```

Could you fix those dependencies?

BTW, I don't think that it is very useful for npm to complain about deprecated indirect dependencies, since there is not much the author of the top package can do to fix them.

**Comment by tilleps** [comment]
```shell
$ npm ls request
auth@ /opt/htdocs/development/sso/libdev
└─┬ tap@15.0.9
  └─┬ coveralls@3.1.0
    └── request@2.88.2
```

```shell
$ npm ls har-validator
auth@ /opt/htdocs/development/sso/libdev
└─┬ tap@15.0.9
  └─┬ coveralls@3.1.0
    └─┬ request@2.88.2
      └── har-validator@5.1.5
```

Possibly might be able to resolve this by switching over to coveralls-next: https://github.com/jtwebman/coveralls-next

**Comment by ilg-ul** [comment]
BTW, to get rid of the warnings, in xpm I followed the approach used by npm and I included all dependencies via `boundleDependencies`.

**Comment by isaacs** [comment]
Fixed on tap 18, mostly by rewriting everything lol.  `npm i tap@pre` to use it, but be sure to read through the [changelog](https://node-tap.org/changelog/#18.0), as there have been a lot of updates.
