### ISSUE TITLE
Time execution length skewed by beforeEach and afterEach

### ISSUE THREAD

**Issue by ematta** [tapjs/tapjs#731]
The `time` metrics produced by tap result in skewed results. First, if you have a `beforeEach` block, the first test time will be significantly higher than subsequent subtests (even if they do the same routine). Here is an example test:

```javascript
const tap = require('tap');

tap.test('check if before/after mutate test times', t => {
  t.beforeEach(done => {
    done();
  });
  t.afterEach(done => {
    done();
  });
  t.test('first test', t => {
    t.ok(true);
    t.end();
  });
  t.test('second test', t => {
    t.ok(true);
    t.end();
  });
  t.test('third test', t => {
    t.ok(true);
    t.end();
  });
  t.test('fourth test', t => {
    t.ok(true);
    t.end();
  });
  t.done();
});
```

Results: 

```shell
TAP version 13
# Subtest: check if before/after mutate test times
    # Subtest: first test
        ok 1 - expect truthy value
        1..1
    ok 1 - first test # time=2.873ms
    
    # Subtest: second test
        ok 1 - expect truthy value
        1..1
    ok 2 - second test # time=0.735ms
    
    # Subtest: third test
        ok 1 - expect truthy value
        1..1
    ok 3 - third test # time=0.625ms
    
    # Subtest: fourth test
        ok 1 - expect truthy value
        1..1
    ok 4 - fourth test # time=0.564ms
    
    1..4
ok 1 - check if before/after mutate test times # time=17.921ms

1..1
# time=24.71ms
```

You will see in the results that the first test time is `2.609ms` while the subsequent tests are `0.73ms`, `0.635ms`, and `0.836ms` respectively. If we subtract the times from tests 2-3 we see that test 1 is `0.408ms` which is closer, but still too fast for it to be right. All the tests do the exact same routine (`t.ok(true) `) so I am expecting a time range between 0.6 to 0.8 seconds.

Now, if we introduce an `afterEach` delay we see that each test adopts the `afterEach` time delay for it's `time` metric:

```javascript
const tap = require('tap');
const delay = ms => new Promise(resolve => setTimeout(resolve, ms));

tap.test('check if before/after mutate test times', t => {
  t.beforeEach(done => {
    done();
  });
  t.afterEach(async done => {
    await delay(500);
    done();
  });
  t.test('first test', t => {
    t.ok(true);
    t.end();
  });
  t.test('second test', t => {
    t.ok(true);
    t.end();
  });
  t.test('third test', t => {
    t.ok(true);
    t.end();
  });
  t.test('fourth test', t => {
    t.ok(true);
    t.end();
  });
  t.done();
});
```

Results:

```shell
TAP version 13
# Subtest: check if before/after mutate test times
    # Subtest: first test
        ok 1 - expect truthy value
        1..1
    ok 1 - first test # time=507.917ms
    
    # Subtest: second test
        ok 1 - expect truthy value
        1..1
    ok 2 - second test # time=505.286ms
    
    # Subtest: third test
        ok 1 - expect truthy value
        1..1
    ok 3 - third test # time=503.668ms
    
    # Subtest: fourth test
        ok 1 - expect truthy value
        1..1
    ok 4 - fourth test # time=502.596ms
    
    1..4
ok 1 - check if before/after mutate test times # time=2027.743ms

1..1
# time=2031.953ms
```

In this example, each adopt the `500ms` timing from `afterEach` and the first test is no longer a multiple of each other test. 

The expectation is that each test `time` metrics is reflective of just the test itself, independent of `beforeEach`/`afterEach`.

**Comment by abalam666** [comment]
Hello,
I have the same very annoying behavior, I have lost two days on this issue.
`afterEach` is triggerring before the end of my test without any reason.
I have to add the `await delay(XXX)` trick too, but i don't think it's the better approach.
Any help would be appreciated.
I'm using tap 15.0.0

PS: Thank you @ematta for having created this issue 👍

**Comment by isaacs** [comment]
Not an issue in tap 18.  Get it with `npm i tap@pre`.  Be sure to review the [changelog](https://node-tap.org/changelog/#18.0), as there have been many many updates in this version.
