### ISSUE TITLE
Missing deprecation warnings from docs and release notes

### ISSUE THREAD

**Issue by jsumners** [tapjs/tapjs#733]
It seems that all synonyms have been deprecated:

https://github.com/tapjs/node-tap/blob/84ff0dd507f6c965c2b1520f45fab1b458c7163c/lib/tap.js#L20-L36

This information has been left out of the release notes for v15 (https://github.com/tapjs/node-tap/releases/tag/v15.0.0). Also, the documentation (https://node-tap.org/docs/api/asserts/) does not call out that the synonyms should not be used.

**Comment by jsumners** [comment]
Ah! I see that "Deprecate aliases." in the release notes is meant to cover this. I think this is a bit too vague. I didn't put the two together until I saw the commit message for https://github.com/tapjs/node-tap/pull/649 in the blame log.

Regardless, the website docs still promote these aliases as viable.

**Comment by isaacs** [comment]
Yeah, the docs should be updated.  Patch welcome, or I'll get to it next week most likely.
