### ISSUE TITLE
 missing coverage report when testing ES Modules with tap (15.x) -> workaround?

### ISSUE THREAD

**Issue by mashpie** [tapjs/tapjs#735]
AFAIK coverage report with ESM is not (yet... easy...) supported by nyc/istanbul, right? Or does tap have any issues with handling ESM although officially supported since 15.x?

After some research, I found #616 and tried the workaround with `c8`, which seems to be perfectly working. To better describe the issue and workaround, I've set up a demo repo https://github.com/uscreen/tap-esm-coverage-issue

So any feedback, whether this is "the way" or "one way" or "no way" to handle that use case, is much appreciated. Thanks!

**Comment by coreyfarrell** [comment]
See https://github.com/istanbuljs/esm-loader-hook.  This depends on features of nodejs that are experimental so it is not included in nyc or tap.

**Comment by isaacs** [comment]
@coreyfarrell Perhaps `tap` could list @istanbuljs/esm-loader-hook as  an optional peer dep and use it if present?  Then it'd be a bit easier to opt into.  What do you think?

**Comment by isaacs** [comment]
@mashpie As a workaround if you're using tap today, you can `npm install @istanbuljs/esm-loader-hook -D`, and add this to your package.json file:

```json
{
  "tap": {
    "test-env": {
      "NODE_OPTIONS": "--experimental-loader @istanbuljs/esm-loader-hook"
    }
  }
}
```

**Comment by coreyfarrell** [comment]
Node is very spammy with experimental warnings for every process that uses the loader argument.  I often use it only on individual child processes which actually test esm, avoid the warning for test processes which have cjs only.

Autoloading when installed would be a problem for libraries that support node 10 but include/test conditional exported esm in 12+.  Tap itself is an example of this?

Finally I know that nodejs is changing the loader hooks, the current module will break at some point.

**Comment by mashpie** [comment]
Thanks @isaacs and @coreyfarrell ! (btw.: agree to spammyness a lot) 

quickly added istanbuljs hook (https://github.com/uscreen/tap-esm-coverage-issue/commit/e8efebbdda64724915c84d3b48a3721717adb1b2) and re-tried. 

```sh
❯ tap test.mjs
```

is not reporting any coverage. I guess `test-env` isn't set correctly, because invoking with `cross-env` finally reports fine.

```sh
cross-env 'NODE_OPTIONS=--experimental-loader @istanbuljs/esm-loader-hook'
```

(although spamming output with experimental warnings now :) )

will investigate env settings further... meanwhile, maybe you could enlighten me: what's wrong with just using `c8` as it seems to do the job?

**Comment by mcollina** [comment]
I went with `tap --node-arg='--no-warnings' --node-arg='--experimental-loader' --node-arg='@istanbuljs/esm-loader-hook' test/*test.js`

**Comment by coreyfarrell** [comment]
I use https://www.npmjs.com/package/suppress-experimental to deal with the warnings.  This silences experimental warnings without blocking other potentially useful warnings.

**Comment by JamesKyburz** [comment]
adding this to package.json works too

```json
  "tap": {
    "node-arg": [
      "--no-warnings",
      "--experimental-loader",
      "@istanbuljs/esm-loader-hook"
    ]
  }

 ```

**Comment by noahehall** [comment]
i went with 
![image](https://user-images.githubusercontent.com/10324554/130371692-73be84d3-74de-4fb8-b2b7-d74ae02c1f0c.png)

**Comment by noahehall** [comment]
I went with 
![image](https://user-images.githubusercontent.com/10324554/130373055-f8f31f01-63a6-426f-8d41-9efc4cfcc9f2.png)


which produces
![image](https://user-images.githubusercontent.com/10324554/130372993-d4cbd62e-60f8-4149-9f61-bf8206091aa8.png)

commit to reproduce, `.taprc` `.tapcoverage.map.js`  [can be found here](https://github.com/noahehall/nodeproto/tree/1f389275cdd844fe699ecc8ca25924c5baf7cf2f)

however, line coverage still reports 0 when I use `--experimental-loader @istanbuljs/esm-loader-hook||suppress-experimental` 

any help here would be appreciated, thx!

**Comment by noahehall** [comment]
got it to work
![image](https://user-images.githubusercontent.com/10324554/130717790-ea4852df-b776-416e-bcc8-7201798f10cb.png)


thx for the help!

**Comment by matthiasg** [comment]
> got it to work ![image](https://user-images.githubusercontent.com/10324554/130717790-ea4852df-b776-416e-bcc8-7201798f10cb.png)
> 
> thx for the help!

@noahehall  any more details on what you had to do ?

**Comment by christian-bromann** [comment]
Can anyone provide an example for Tap + TypeScript + ESM?

**Comment by rogerta** [comment]
The workaround mentioned by @JamesKyburz on [May 21](#issuecomment-845992674) does not work with node 16 (active LTS version).  It did work with node 14.  When I say "does not work" I mean the coverage output looks like this:

```
Suites:   24 passed, 24 of 24 completed
Asserts:  2965 passed, of 2965
Time:     1s
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |                   
----------|---------|----------|---------|---------|-------------------
```

Specifically I've tried these combinations:

node `16.13.1` and node-tap `15.0.10`
node `16.13.1` and node-tap `15.1.5`

My package.json file uses `"type": "module"`.  I didn't find any issues here (nor in nyc) specifically about node 16.

**Comment by bcomnes** [comment]
None of these experimental loader solutions are working in node 17 for me. Only thing that works is wrapping tap: `c8 tap --no-coverage`

**Comment by rogerta** [comment]
Thanks @bcomnes .  Using c8 also works with node `16.13.1`.

**Comment by andersk** [comment]
`@istanbuljs/esm-loader-hook` no longer works in Node.js ≥ 16.12.0 due to an incompatible change in the experimental ESM loader hook API (istanbuljs/esm-loader-hook#6).

**Comment by isaacs** [comment]
See also: #807 (that issue is this problem, plus typescript, but it's all connected; just closing issues in favor of tracking it in one place)
