### ISSUE TITLE
In 15, `--ts` has no effect

### ISSUE THREAD

**Issue by midgleyc** [tapjs/tapjs#736]
I appreciate that this a major release, but I couldn't see anything in the release notes that I should change to fix this. I see that typescript support is now disabled by default, but I should still be able to enable it, right?

An example run is at https://github.com/midgleyc/east-mysql2/pull/50/checks?check_run_id=2269679406

The project uses typescript, and has typescript installed. On tap 14, running "npx tap --ts" compiled and ran the tests; on tap 15 I get the error:
```
SyntaxError: Cannot use import statement outside a module
```

It appears that the tests are not being compiled.

Running an individual test with `npx ts-node tests/connect-params.ts` still works.

To run all the tests, I can use `npx tap --node-arg="-r" --node-arg="ts-node/register"` -- this works whether or not `--ts` is present. It always finds the `.ts` files and does not compile them.

**Comment by isaacs** [comment]
Ah, it was only loading typescripts when `--jsx` was specified.  Fixed in 15.0.2.
