### ISSUE TITLE
Error: Cannot find module 'treport/types'

### ISSUE THREAD

**Issue by zkldi** [tapjs/tapjs#739]
Looks like this line: https://github.com/tapjs/node-tap/blob/main/bin/jack.js#L8

require()'s a module that isn't included in package.json? Installing the package from npm no longer works without resolving this dependency yourself.

**Comment by zkldi** [comment]
Update: looks like grabbing tap from npm didn't install treport properly, but seems like an environment issue. Will close unless ends up replicable?

**Comment by challet** [comment]
Hi @zkldi, could you elaborate on this environment issue please ? I'm currently facing the same issue

**Comment by zkldi** [comment]
Hi, no worries.

I had to uninstall `tap` and then reinstall it. If you're updating from tap-14, it seems to mess up the dependencies.

**Comment by breck7** [comment]
I ran into this issue as well. `npm uninstall tap` and then `npm install tap` seemed to fix it. I had earlier tried to just bump the version in `package.json` and then `npm install` but that didn't fix it. Thanks @zkldi !
