### ISSUE TITLE
Puppeteer library fails with ExecutionContext error when using the TAP CLI

### ISSUE THREAD

**Issue by victor-solvethex** [tapjs/tapjs#741]
I'm running a test suite which uses the puppeteer library to execute tests against a headless Chrome.

The thing is that when I import 'tap', compile the code and run it with the `node` cli everything goes fine, but when I try to execute the code using `tap --ts src/index.ts`, the puppeteer library starts yelling something like:

```
> tap --ts src/index.ts

 FAIL  src/index.ts
 ✖ Evaluation failed: ReferenceError: cov_rsz3v8w4c is not defined     at __puppeteer_evaluation_script__:1:11

  test: "Submit form correctly"
  stack: >
    ExecutionContext._evaluateInternal
    (node_modules/puppeteer/src/common/ExecutionContext.ts:273:13)

    ExecutionContext.evaluate (node_modules/puppeteer/src/common/ExecutionContext.ts:138:12)
  at:
    line: 273
    column: 13
    file: node_modules/puppeteer/src/common/ExecutionContext.ts
    function: ExecutionContext._evaluateInternal
```

I could open an issue on the puppeteer repo but I think the issue here is that TAP is doing something magic behind the scenes with the Node execution context that I would like to know,

thanks!

**Comment by coreyfarrell** [comment]
You need to add `/* istanbul ignore next */` before any function which will be executed remotely.  I don't know puppeteer but in psuedo-code:
```js
/* istanbul ignore next */
puppeteer.executeScript(() => window.location = '/newpage.html')
```

The `istanbul ignore next` prevents code coverage from being added to the anonymous function which gets stringified then executed in the browser.  As an alternative you could use `tap --no-cov` to disable coverage entirely.
