### ISSUE TITLE
How to specify reporter as Treport when running tests as a node process

### ISSUE THREAD

**Issue by vipulgupta2048** [tapjs/tapjs#742]
I am trying to use and run my tests just like the getting started guide.  

```
// test/hello-world.js
const tap = require('tap')
tap.pass('this is fine')
```

When running this test using node, is there any way to specify a specific reporter? In my bigger usecase, I have to run the tests as part of a bigger application which doesn't allow for `npm test` to run which in turn calls the `Tap` CLI and uses Treport. I am looking for any solutions at this point, as Treport's summary feature is something that interests me quite a bit and I want to use it if possible. 
    
```
$ node test/hello-world.js
```

**Comment by isaacs** [comment]
The easiest way would be to pipe it to tap, and use the `-` filename argument to tell it to read from stdin.

```bash
$ node test/hello.js | tap -
```

You can actually pipe any TAP data through `node-tap`, and it'll treat it just as if it was a test.

```
# run my tests, but specify an output file to save all the raw TAP data
# handy because a lot of tools can do stuff with TAP data
tap -o test-output.tap test/*.js

# some time later...
cat test-output.tap | tap  -
```

But if you _want_ the reports, why not just run the file with the tap bin?

```
tap test/hello-world.js
```
