### ISSUE TITLE
node-tap reports less tests with --reporter classic

### ISSUE THREAD

**Issue by trivikr** [tapjs/tapjs#753]
## Describe the bug
node-tap reports less number of tests run with --reporter classic as compared to default reporter

This issue was noticed in https://github.com/nodejs/undici/issues/800#issuecomment-836740169

## Steps to reproduce
```console
$ git clone git@github.com:nodejs/undici.git

$ cd undici

$ node -v
v16.1.0

$ ./node_modules/.bin/tap test/*.js --no-coverage
 PASS  test/abort-event-emitter.js 20 OK 140.209ms
 ...
 PASS  test/tls.js 26 OK 982.401ms

                         
  🌈 SUMMARY RESULTS 🌈  
                         

Suites:   62 passed, 62 of 62 completed
Asserts:  6200 passed, of 6200
Time:     7s

$ ./node_modules/.bin/tap test/*.js --no-coverage --reporter classic
test/abort-controller.js ............................ 40/40
...
test/validations.js ................................. 10/10
total ........................................... 6177/6177

  6177 passing (6s)

  ok
```

#### Observed behavior
The number of tests reported being run with `--reporter classic` is 6177, which is different from number 6200 reported in default reporter.

#### Expected behavior
The number of tests reported should not be different based on the reporter selected.

**Comment by isaacs** [comment]
This is a counting bug in the old reporter, but not one that I'll ever fix. The new reporter is doing the correct thing.
