### ISSUE TITLE
Proposal: t.approx

### ISSUE THREAD

**Issue by zkldi** [tapjs/tapjs#758]
or `t.isApproximately`, etc.

Testing the result of functions that return decimals is quite difficult with the current asserts. I think it would be nice to have a `t.approx(r, v, d?)` like function which would assert that `Math.abs(r - v) < 0.01 or d`. Similarly, this could be useful inside t.match for testing properties that are decimals.

This can be done with custom assertions, but it's a pain with TypeScript and I think this is a common enough use case that it could be baked in.

This might be more appropriate for `tcompare`, but I'm not too sure on how the internals of this is all laid out.

Thanks!

**Comment by zkldi** [comment]
Hey, I've looked into `libtap` and have a working implementation of this with a signature of

```js
approximately (found, wanted, message, toDecimalPlaces = 2, extra)
```

That said, I can't really figure out how the testing in `libtap` works, so I've refrained from making a PR without tests or anything just yet.

*****
Regardless, is this a feature you'd be interested in accepting? A lot of the tests I write work with floats, and `t.equal` just doesn't cut it.

**Comment by isaacs** [comment]
Yeah, I've run into this with floats, too. 

I think it's not such a great fit for tcompare.match at least by default, since it could lead to ints passing wrongly. Like, if you expect a counter to be `2` and get `2.0000001`, something may have gone horribly wrong. But it could be an option to tcompare, like `decimalPrecision` with a default like `Infinity` that means `must be ===`.

**Comment by isaacs** [comment]
And I like `t.approx` as an assertion method, it's as terse as possible while being easy enough to read and guessable/memorable.

**Comment by zkldi** [comment]
I think it would be confusing/breaking to implement this in `t.match`, so my plan was just to implement it as an assertion method. I have a working (i think?) implementation on a fork of `libtap`, but I couldn't figure out how to actually write tests for it :sweat_smile:

**Comment by isaacs** [comment]
This would be pretty easy to do as a [plugin](https://node-tap.org/plugins/) in tap v18, but I don't think it's quite generally useful enough to add as a built-in.

Closing, but if you want to write that plugin or need any help, I'm happy to assist where I can.
