### ISSUE TITLE
--before and --after hooks do not support TypeScript

### ISSUE THREAD

**Issue by zkldi** [tapjs/tapjs#761]
Code that handles this is around here-ish: 

https://github.com/tapjs/node-tap/blob/b78575f5344285714d9d3812ba09f65f0cc49728/bin/run.js#L793

I'm not familiar enough with the codebase to know if this is an easy fix or not, but it'd be quite useful for typescript integration.

**Comment by FikriRNurhidayat** [comment]
I have the same problem here. I tried to add global setup and global teardown, but it just didn't work.

```js
import db from "../../src/lib/db";
import roles from "../fixtures/roles";
import { Ryan, Fikri } from "../fixtures/users";

async function setup() {
  await db.insert([Ryan, Fikri]).into("users");
  await db.insert(roles.map((name) => ({ name }))).into("roles");
  await db.destroy();
}

setup();
```

Here's my overall script:

```bash
tap --before=test/config/setup.ts --after=test/config/teardown.ts test/**/*.test.ts
```

**Comment by zkldi** [comment]
Hi. As a temporary fix, you could set your --before and --after scripts to be the below `.js` files:

```js
// setup.js
const { execSync } = require("child_process");
const path = require("path");

execSync(`ts-node ${path.join(__dirname, "./setup.ts")}`);
```


```js
// teardown.js
const { execSync } = require("child_process");
const path = require("path");

execSync(`ts-node ${path.join(__dirname, "./teardown.ts")}`);
```

It's definitely a questionable hack, but it works for the time being. (`ts-node` also needs to be installed, also there are definitely better ways to pass a path into a shell)

**Comment by isaacs** [comment]
Yeah, I think when `--ts` is specified, it should probably run `.ts` and `.tsx` before/after modules using ts-node.  Patch welcome.

1. Make the `beforeAfter` method take a third argument, `options`
2. If `options.ts` is true, then put `'-r', tsNode` in the list of arguments to `process.execPath`, before the module path.

**Comment by isaacs** [comment]
162c1a8
