### ISSUE TITLE
Per-testcase snapshot file?

### ISSUE THREAD

**Issue by retorquere** [tapjs/tapjs#762]
I often need to adjust snapshots of just a few tests (a single js script with many tests generated dynamically) -- I can select the tests to run using environment vars, but I'd need to be able to update only those snapshots.

**Comment by retorquere** [comment]
Also -- the single snapshot grows very big; it looks like it's going to be 200M when my test suite will finish.

**Comment by isaacs** [comment]
Yeahhh... that'd be a breaking change, but maybe worthwhile.  I have some tests with massive snapshots as well.  I tend to follow a "snapshot the world, don't check them too much, but when they change unexpectedly, go digging and figure out why".

The tricky thing is knowing what constitutes a "test case".  I'd much rather a few massive files than a massive number of files, just performance-wise, it'd be brutal to have to load a thousand snapshot files when running tests, but loading 1000 snapshots in a 200Mb file is pretty snappy.

Is it possible to break up your auto-generated tests into multiple auto-generated files?

**Comment by retorquere** [comment]
In my case the testcase output changes because the desired behavior changes. I understand the performance implications, but that is less important than being able to easily change or delete a single test case. 

I do currently generate the testcases as separate .js files and thereby separate snapshots, but I'd prefer to be rid of that.

**Comment by isaacs** [comment]
Looking into this, I don't think this would actually be that hard to accomplish, without changing the default behavior.

Would something like this work for you?

```js
const { resolve } = require('path')
t.test('foo', async t => {
  t.snapshotFile = resolve(__dirname, 'tap-snapshots', 'foo.test.cjs')
  t.matchSnapshot('foo')
})

t.test('bar', async t => {
  t.snapshotFile = resolve(__dirname, 'tap-snapshots', 'bar.test.cjs')
  t.matchSnapshot('bar')
})

t.test('baz', async t => {
  t.snapshotFile = resolve(__dirname, 'tap-snapshots', 'baz.test.cjs')
  t.matchSnapshot('baz')
})
```

**Comment by isaacs** [comment]
Published on 15.2.3 (just realized this should've been 15.3, since it's a feature addition, but hopefully I've sacrificed enough to the SemVer gods over the years for them to forgive this transgression).

**Comment by retorquere** [comment]
> Would something like this work for you?

It absolutely would, because `foo` would be established as a loop variable. I'll start doing some tests (ha!), will let you know.

**Comment by retorquere** [comment]
Works like a charm -- this massively simplifies my test setup. Thanks!

I take it that even if I set up async tests this way, they're still all running on a single core if I assemble these tests in a single file? How can I kick off tests on multiple cores from a script using the API rather than the CLI?

**Comment by retorquere** [comment]
I think that involves tap.spawn but I cannot find any documentation or samples on how to use it.

**Comment by isaacs** [comment]
> I take it that even if I set up async tests this way, they're still all running on a single core if I assemble these tests in a single file? How can I kick off tests on multiple cores from a script using the API rather than the CLI?

Set `t.jobs` to the number of tests you want run in parallel, and pass `{ buffer: true }` in the options for each one that you want to parallelize. Example: https://github.com/tapjs/tap-parser/blob/main/test/parser.js docs: https://node-tap.org/docs/api/parallel-tests/#parallel-tests-from-the-api

**Comment by isaacs** [comment]
Oh, I guess the key is "buffered", not "buffer", and it's on by default if `t.jobs > 1`.  So literally all you have to do is set `t.jobs` to some number > 1

**Comment by retorquere** [comment]
This runs the tests in as many separate processes, not just async? That doc says

> slow function that makes a network request or processes a file 

which sounds like it assumes I/O-bound tests, which in javascript I would normally associate with async, not multiprocessing. How does node-tap get the test code into a different process without being provided with a code file?

I am testing cpu-bound code so to get any speedup from parallelization I need the tests to be spread over the available cores. I thought tap.spawn would let me do that but I don't understand how it works, and I keep getting 

```
not ok 1 - test unfinished
...
not ok 2 - child test left in queue: t.spawn import
not ok 3 - child test left in queue: t.spawn merge
not ok 4 - child test left in queue: t.spawn other
```

almost immediately after start.

**Comment by isaacs** [comment]
Yes, you'd have to split cpu-bound activities into separate files.  `t.jobs=N` will only parallelize child tests, and is only relevant if they're bound on IO.

You could also run the CPU-heavy stuff in a [worker thread](https://nodejs.org/api/worker_threads.html) for each test.

```js
const {
  Worker, isMainThread, parentPort, workerData
} = require('worker_threads')

if (isMainThread) {
  const t = require('tap')
  t.jobs = 8
  for (let i = 0; i < 10; i++) {
    t.test(`worker ${i}`, t => {
      t.plan(2)
      const worker = new Worker(__filename, { workerData: i })
      worker.on('message', m => t.same(m, { index: i }))
      worker.on('exit', code => t.equal(code, 0, 'exited successfully'))
    })
  }
} else {
  const index = workerData
  const start = Date.now()
  while (Date.now() < start + 500) {
    // slow CPU-bound activity
  }
  // halfway through we post a message, I guess
  // these can be whatever you want to assert on,
  // or skip this bit.
  parentPort.postMessage({ index })
  while (Date.now() < start + 1000) {
    // slow CPU-bound activity
  }
}
```

This test finishes in about 2 seconds, assuming you have at least 8 CPUs to use.  The first all run in parallel, then the next 2 run right behind those.

**Comment by isaacs** [comment]
Note that you really have to be doing a _lot_ of CPU intensive stuff for Workers to be faster, and if you have a lot of test files, then your CPUs will all be busy anyway.  But it's another thing to try that will speed it up in some rare scenarios, which it sounds like you have ;)

**Comment by retorquere** [comment]
I write a bibtex parser that only parses input delivered to it as a string; there are a fair few input files my test suite must read, but once read, my parser is strictly cpu-bound, and parsing bibtex (without actually executing it) is pretty heavy work.

**Comment by retorquere** [comment]
What does `t.plan(2)` do?

**Comment by retorquere** [comment]
I think I have it done, inlcuding a piscina pool, so I can just let 'er rip. This is ridiculously cool, and it only took a few hours to switch from jest. Not only is te code cleaner, it runs some 10-12% faster than what I had.

Thanks so much!

**Comment by retorquere** [comment]
Can I still trigger the colorful output that the `tap` cli shows from my own script?
