### ISSUE TITLE
Slow performance

### ISSUE THREAD

**Issue by thefrana** [tapjs/tapjs#764]
Hi,
I tried Tap with TypeScript, but the performance is really bad.

Dependencies:
```json
"devDependencies": {
  "@types/tap": "^15.0.5",
  "tap": "^15.0.9",
  "ts-node": "^10.0.0",
  "typescript": "^4.3.2"
},
```

My config:

```json
"tap": {
  "ts": true,
  "no-coverage": true
},
```

Test file:
```ts
import t from 'tap'

t.test('Assert true', async (t) => {
   t.ok(true)
})
```

TS config:
```json
{
   "compilerOptions": {
      "module": "commonjs",
      "target": "es2018",
      "lib": ["es2018"],
      "declaration": true,
      "declarationMap": true,
      "sourceMap": true,
      "experimentalDecorators": true,
      "emitDecoratorMetadata": true,
      "esModuleInterop": true,
      "composite": true,
      "incremental": true
   },
}

```

Results with `time npx tap test.spec.ts`:
```
 PASS  test.spec.ts 1 OK 13.372ms

                         
  🌈 SUMMARY RESULTS 🌈  
                         

Suites:   1 passed, 1 of 1 completed
Asserts:  1 passed, of 1
Time:     2s
npm test -- test.spec.ts  4.51s user 0.37s system 173% cpu 2.803 total
```

It is a really simple test, but it took over 2 seconds to process. Why? Can I somehow speed it up? Also, why the test itself took 13 ms, but the overall time is this different?

Thanks

**Comment by zkldi** [comment]
This is mostly startup time, I'm pretty sure.

**Comment by formula1** [comment]
For what it's worth, I have a simply ts server that I built and it also has a slow startup. I think it's needs to compile all the typescript into JavaScript before running it. I don't think this is an issue with node-tap

**Comment by isaacs** [comment]
Not much to be done about TypeScript being slow, I'm afraid.  It produces type-safe code, not fast code.
