### ISSUE TITLE
`import` statement getting highlighted without a reason 

### ISSUE THREAD

**Issue by hood** [tapjs/tapjs#766]
I'm using tap with a very simple TS project. Whenever a test fails, an import statement gets randomly highlighted instead of the line of the failing test.

Example:
https://i.imgur.com/n8AxTlq.png

**Comment by isaacs** [comment]
This is no longer a problem in tap 18. `npm i tap@pre` to use it, but be sure to read through the [changelog](https://node-tap.org/changelog/#18.0), as there have been a lot of updates.
