### ISSUE TITLE
tap command not found

### ISSUE THREAD

**Issue by Divepit** [tapjs/tapjs#774]
After following the getting started guide which consists of the steps

1. Installing `npm install tap --save-dev`
2. Updating the package.json

The `npm test` command will work, hoever using the `tap` command will result in the error `-bash: tap: command not found`

**Comment by zkldi** [comment]
You should use `npm install -g tap` to get a global `tap` command.
You might have to run that command with sudo, depending on how your stuff is setup.

**Comment by punkish** [comment]
> You should use npm install -g tap to get a global tap command.

Thanks for this info, however, this is not what is indicated in the published manual which very clearly says (what the OP wrote)

```
Installing Tap[#](https://node-tap.org/basics/#installing-tap)

You know the drill.

npm install tap --save-dev
"Zero Patience Just Get Going" Guide[#](https://node-tap.org/basics/#%22zero-patience-just-get-going%22-guide)

Write a test file like this:

…

Run it like this:

$ tap run
```
