### ISSUE TITLE
Webpack and Tap compatibility issue

### ISSUE THREAD

**Issue by NasserTahani** [tapjs/tapjs#776]
In order to test the application using Webpack bundler, importing tap as ESM gives this error:
` SyntaxError: Cannot use import statement outside a module`
The problem resolved with converting .js files to .mjs or inserting `'type':'module`' in package.json. It solves the problem of importing tap as ESM but Webpack cannot bundle the project that throws the following error:
```
Failed to load 'E:\demo\webpack.config.js' config
[webpack-cli] ReferenceError: require is not defined
```
How can we use Webpack and Tap to bundle tested solutions?

The sample.test.js file:
```
import tap from 'tap';
tap.pass('it is tap!');
```

**Comment by isaacs** [comment]
If your project is `"type":"module"`, then any file ending in `.js` will be interpreted as ESM, and thus will not have a `require()` function (unless you create one with `import {createRequire} from 'module';const require=createRequire(import.meta.url)`, that is).

Tap v18 now supports ESM and CJS natively, as well as typescript in all its various flavors. You can get it with `npm i tap@pre`. Be sure to review the [changelog](https://node-tap.org/changelog/#18.0) as many things have been updated.
