### ISSUE TITLE
Branch coverage failing when updating (patch or minor) from 14.10.7 

### ISSUE THREAD

**Issue by karfau** [tapjs/tapjs#780]
I do not understand why test coverage is suddenly failing in the following PRs, that only attempt to upgrade tap:

- https://github.com/karfau/runex/pull/73 (updating to 14.10.8)
- https://github.com/karfau/runex/pull/74 (updating to 14.11.0)

The output in the github actions looks as follows:
![image](https://user-images.githubusercontent.com/135657/138412686-e023873a-7218-41f8-a24f-149ed5fac60b.png)

But the uncovered lines mentioned in that report do not contain any code, it's just doc comments:
- https://github.com/karfau/runex/blob/d1ae18d176ae87e340f29f0386ec52a919cd38b9/index.js#L52
- https://github.com/karfau/runex/blob/d1ae18d176ae87e340f29f0386ec52a919cd38b9/index.js#L191

Is it possible there is some transpilation going on and is there a way to look at the transpiled files to figure out what is going on?

**Comment by isaacs** [comment]
I think this is due to a shortcoming in NYC that was fixed in the version used by tap 15.  It should be better on the latest version, assuming you're not using ESM.

**Comment by karfau** [comment]
I don't really understand your reply. My description explicitly states that the affected version is 14.x.
And the update to v15 (or higher?) is not possible/easy for the affected repo...
