### ISSUE TITLE
Custom declaration file not taken into account when running tap --ts

### ISSUE THREAD

**Issue by gboston** [tapjs/tapjs#781]
I have a custom type file index.d.ts which isn't picked up when running : 

```sh
tap --ts
```

When I build the project via tsc it runs fine. The only way to solve it is by explicilty referencing the file, with the following line:

```ts
/// <reference types="../types/" />
```

**Comment by isaacs** [comment]
In tap 18, anything that's understood by ts-node will be understood by tap.

`npm i tap@pre` https://node-tap.org/changelog/#18.0
