### ISSUE TITLE
Support for Node v17

### ISSUE THREAD

**Issue by mcollina** [tapjs/tapjs#783]
Unfortunately import-jsx is currently broken in Node.js v17 due to a change in OpenSSL.

Read up at: https://github.com/vadimdemedes/import-jsx/issues/16

**Comment by targos** [comment]
It's what's causing https://github.com/npm/cli/issues/3919

**Comment by mcollina** [comment]
Yes exactly.

**Comment by jsumners** [comment]
Is this addressed by c9851e4f8c2a5545b446a3397d410f076465689c and 576e05c0cd77a41f56f8fb25cf2eaef9beb2b6d1 ?

**Comment by mcollina** [comment]
It seems like it solved it.
