### ISSUE TITLE
Let's find a helper-maintainer for this project

### ISSUE THREAD

**Issue by revelt** [tapjs/tapjs#784]
Dear users and maintainers of this package and everybody who came here,

We have quite a backlog of GH issues, some of them untriaged for a few years. Documentation PR's pending since May. Also, there are bigger challenges such as coverage on Node 16+. 

Let's kindly encourage Isaac Z. Schlueter to organize somebody to help him maintain this program.

For example, Sindre Sorhus, the creator of `ava`, the nemesis of `tap`, got Mark Wubben on board. They both are featured in a nice table at the bottom of the readme.

Same here, we need to find a person who would proactively take care of this repo — to personally guarantee to:

- triage any issues within 24 hours, 
- review any PR's within a week,
- coordinate the feature roadmap, tempting us with future goodies, and 
- engage the existing and prospective users of `tap` on social media

If a helper-maintainer person starts to slack off, we would also agree on a complaints procedure, where, worst case, they'd risk being banished to the "Former" bullet list at the bottom of the readme and Mr. Schlueter would organize a search for another helper-maintainer.

Thumb up if you agree.

**Comment by zkldi** [comment]
Not sure about this. Isaac seems like a pretty busy guy but the outstanding issues/prs on this repo aren't amazingly important.

Almost all the outstanding PRs are documentation typos, for one.

That, and node-tap seems like a relatively finished project. It doesn't really seem to need much more in terms of features.
That said, if there was enough demand I think a community fork would be significantly preferable.

**Comment by isaacs** [comment]
If anyone wants to help out, I'm always open to contributors.  Otherwise, like most of my OSS projects, it'll be updated whenever my attention cycles back to it, usually in furious bursts once every 6-12 months or so.
