### ISSUE TITLE
treport@3 and import-jsx breaks private NPM mirrors

### ISSUE THREAD

**Issue by snyamathi** [tapjs/tapjs#786]
@isaacs we use a private NPM mirror, disallowing direct reads to github for security reasons.

`node-tap => treport => tap@github:tapjs/node-tap#isaacs/update-the-world`

is causing issues because the requested versions of `import-jsx` and `treport=>tap` are not published to NPM.

Can you publish these, even with a pre-release tag rather than using a github url?

Specifically https://github.com/tapjs/node-tap/commit/0e152b2b27f445504537e64444897e16a78e255f#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R30 is a breaking change for us.

Given that this library is part of an org and not a personal repo, we should probably also go through a PR review process as well so the rest of the maintainers can at least have a look at these sorts of changes before they go in. Normal version bumps are one thing, but I'm curious how the rest of the maintainers feel about using a GH url. It sounds like that's what https://github.com/tapjs/node-tap/issues/784 is trying to accomplish. I understand you can't be expected to do all this by yourself.

Thanks for your time, I know maintaining these packages can be a burden and your contributions are appreciated :)

-----

References:

https://github.com/tapjs/node-tap/blob/13ae7f17d991dc87828f528b9565e2da2cdece36/package.json#L30
https://github.com/tapjs/node-tap/blob/13ae7f17d991dc87828f528b9565e2da2cdece36/package.json#L48
https://github.com/tapjs/treport/blob/88f23a10bd6e02dc9dcd886eab8ce6db1795c89d/package.json#L23

**Comment by isaacs** [comment]
Should be fixed on 15.1.4.  Sorry for the shuffling around, ended up having to fork import-jsx to get it working on Node 17, and I'd hoped that the PR would land before having to publish a fork.  But `@isaacs/import-jsx` exists now, so you should be fine.
