### ISSUE TITLE
Help on mocks

### ISSUE THREAD

**Issue by 112RG** [tapjs/tapjs#787]
Hi sorry to be writting this here but I think this is the best place to ask. Just wanting to say thanks for this awesome library I am trying
to switch to it from jest.

Now in jest I can mock redis by doing

```
jest.mock('ioredis', () => require('ioredis-mock/jest'))
```

I am trying todo the same in tap like

```
  t.mock('ioredis', {
    redis: {
      client: () => 'bar'
    }
  })
```

But I am unable to get it working. My hope is to inject ioredis-mock where ioredis is imported.

Thanks once again

**Comment by lukekarrys** [comment]
You will need to mock the file you are testing and pass the `ioredis` mock to that.

```js
t.test('test', () => {
  const myFile = t.mock('../lib/myfile.js', {
    ioredis: { redis: { client: () => 'bar' } },
  })
  // do stuff with myFile
})
```

I found this report interesting but I just made a proposal for a feature that I think would make this easier: #790.

**Comment by 112RG** [comment]
Ah thankyou thats a good way of doing it.
