### ISSUE TITLE
[feat proposal] `t.mockAll`

### ISSUE THREAD

**Issue by lukekarrys** [tapjs/tapjs#790]
### Problem

`t.mock` replaces all requires with the passed in mock object. This creates a problem when two files both require the same module, and want to assert the results of that module.

*`a.js`*
```js
const log = require('proc-log')
module.exports = (fn) => {
  log.notice('a', 1)
  log.notice('a', 2)
  fn()
}
```

*`b.js`*
```js
const log = require('proc-log')
module.exports = () => {
  log.notice('b', 1)
  log.notice('b', 2)
}
```

*`test/index.js`*
```js
t.test('without mock all', async t => {
  const notices = []
  const a = t.mock('../a.js', {
    'proc-log': {
      notice: (...args) => notices.push(args)
    }
  })
  // whoops i forgot to mock `proc-log` for `b` also
  a(require('../b.js'))
  // this will fail
  t.strictSame(notices, [
    ['a', 1],
    ['a', 2],
    ['b', 1],
    ['b', 2],
  ])
})
```

### Proposal

This is solvable in a lot of ways without needing anything from `tap`, but I've found that in non-trivial application I'm doing a lot of creating a mock object and passing it around between tests and files in order to keep the same object reference to assert.

I'm proposing a `t.mockAll` function that would take the same key/value object of paths/value that `t.mock` does. When called `t.mockAll` would mock all requires to those paths for the lifetime of `t`.

```js
t.skip('with mock all', async t => {
  const notices = []
  t.mockAll({
    'proc-log': {
      notice: (...args) => notices.push(args)
    }
  })
  const a = t.mock('../a.js')
  a(t.mock('../b.js'))
  t.strictSame(notices, [
    ['a', 1],
    ['a', 2],
    ['b', 1],
    ['b', 2],
  ])
})
```

### Questions

- Should `t.mock` win against conflicts with `t.mockAll`? Or throw an error similar to if `t.mock` cant find a path?
```js
t.skip('conflicting mocks', async t => {
  const notices = []
  t.mockAll({
    'proc-log': {
      notice: (...args) => notices.push(args)
    }
  })
  // Would this overwrite mockAll?
  const a = t.mock('../a.js', {
    'proc-log': {
      notices: () => {}
    }
  })
  a(t.mock('../b.js'))
  t.strictSame(notices, [
    ['a', 1],
    ['a', 2],
    ['b', 1],
    ['b', 2],
  ])
})
```

- In my proposal example above, I'm using `t.mock` for the require of `../b.js`. Would it be a bad idea if worked the same if you used `require` instead? It wouldn't work if you did `require` at the top of the file and then called `t.mockAll` later in the file, so that feels little unexpected.
```js
t.skip('just requires', async t => {
  const notices = []
  t.mockAll({
    'proc-log': {
      notice: (...args) => notices.push(args)
    }
  })
  // would this work also?
  const a = require('../a.js')
  a(require('../b.js'))
  t.strictSame(notices, [
    ['a', 1],
    ['a', 2],
    ['b', 1],
    ['b', 2],
  ])
})
```

**Comment by isaacs** [comment]
So, the behavior would be something like:

```js
// foo module
console.log([require('a'), require('b')])
```

```js
t.mockAll({ a: '1' })
t.mock('foo', { b: '2' }) // logs [ '1', '2' ]
```

I think `t.mock()` explicit mocks should always override the object set in `mockAll`, since that's more local to the module loading.

For subsequent calls to `mockAll` should they merge in or completely replace?

```js
t.mockAll({ a: '1' })
t.mockAll({ b: '2' })
t.mock('foo') // logs ['1', '2']? or [<actual a value>, '2']?
```

**Comment by isaacs** [comment]
> In my proposal example above, I'm using t.mock for the require of ../b.js. Would it be a bad idea if worked the same if you used require instead? It wouldn't work if you did require at the top of the file and then called t.mockAll later in the file, so that feels little unexpected.

It's also pretty much impossible to do with `import`, since you need to be able to get at the loader in order to play those sorts of games. And it's possible to do with `require`, but... ew, gross.

It's not in tap 18 yet, but I think it's a good idea, and won't be too hard to do. Keeping the issue open for now.
