### ISSUE TITLE
Tap does not generate html file when it runs with `coverage-report`

### ISSUE THREAD

**Issue by Kcchouette** [tapjs/tapjs#793]
Hello

I'm using a JS project which use tap to check coverage.

Here the use case that fail:

1. clone the project
2. install dependency (here `tap`, I have v 15.1.5)
3. run `NODE_PATH=$PWD/lib ./node_modules/.bin/tap --coverage --coverage-map=map.js --coverage-report=html`

Before the 3rd point, I have no `.nyc_output` folder (which is by default, as I didn't launch tap before the 3rd point).
The command is failing silently.
The file `lcov.info` is empty (and will stay empty, if I continue to try to execute the 3rd point)

If I slightly change the command by removing `--coverage-report=html`, it will succeed
And after this change, I can correctly launch `NODE_PATH=$PWD/lib ./node_modules/.bin/tap --coverage --coverage-map=map.js --coverage-report=html`

**Comment by isaacs** [comment]
Yeah, it's kind of a wart in the UI, I agree.

When run with `tap --coverage-report=<style>`, and no positional arguments, tap says "oh, you just want the coverage report, not to run any tests", and tries to just regenerate the report from the existing coverage info without re-running anything.  This made sense when tap _required_ some positional arguments to run tests.

Then later, in mimicking the patterns of jest, mocha, and others, tap adopted a "find tests and run them" behavior when run without any positional arguments, so you could just run "tap" with no arguments.  But it wasn't clear what to do about `tap --coverage-report=<style>` to _just_ run the report without running tests.

A possible workaround here is to put `"tap": {"coverage-report": "html"}` in your `package.json` file, or `coverage-report: html` in your .taprc file, and then run it without the explicit `--coverage-report` cli option.

Moving forward (as a SemVer major breaking change), we really need to figure out what to do about that wart.  It's very handy to be able to _just_ generate the coverage report after a test run, without having to re-run tests, but that's clearly conflicting with the fact that positional arguments are no longer needed.

**Comment by isaacs** [comment]
This is now a thing.  `tap report <type>` will run the report.  `tap --coverage-report=<type>` will run tests, and generate the report type.  `npm i tap@pre` to get it. Be sure to review the [changelog](https://node-tap.org/changelog/#18.0), a bunch of stuff has been updated.
