### ISSUE TITLE
Coverage not picking up all source files even with nyc-arg --all flag

### ISSUE THREAD

**Issue by paambaati** [tapjs/tapjs#796]
@isaacs Related to https://github.com/tapjs/node-tap/issues/615

When using `tap` with `nyc-arg` `--all`, the coverage report should include all source files. However, it still includes only the source files that tests have touched, which is the default behavior in `nyc`.

I've created a minimal reproduction here – https://github.com/paambaati/tap-coverage-repro#readme

**Comment by paambaati** [comment]
Quick update – after some digging, I've found that this PR (see https://github.com/paambaati/tap-coverage-repro/pull/1/files) fixes this issue.

**tl;dr of the fix**
This isn't a `tap` issue, but an `nyc` issue. `nyc` does not know how to parse TypeScript files, so the key is to extend the configuration from [`@istanbuljs/nyc-config-typescript`](https://www.npmjs.com/package/@istanbuljs/nyc-config-typescript) – see https://github.com/istanbuljs/nyc#typescript-projects

However, including the `--extends` configuration under `nyc-arg` in `.taprc` isn't working though.

```yaml
# .taprc
nyc-arg:
  - --extends='@istanbuljs/nyc-config-typescript'
```

Leaving this issue open so the above issue can be tracked.

**Comment by isaacs** [comment]
See also: #807
