### ISSUE TITLE
Using `import` in a file with the `--before` flag

### ISSUE THREAD

**Issue by onosendi** [tapjs/tapjs#802]
Tests are fine until I try to use `import` in a file with the `--before` flag. I get:
```
SyntaxError: Cannot use import statement outside a module
```

.taprc
```yaml
before: ./__tests__/before.test.ts
ts: true
```

\_\_tests\_\_/before.test.ts
```js
import foo from 'bar';
```

Any way around this?

**Comment by isaacs** [comment]
What if you name `before.test.mjs`?

**Comment by onosendi** [comment]
> What if you name `before.test.mjs`?

I tried that. It works, but I'm calling `knex.migrate.latest()` which loads migration files, then I get the same error:
```
SyntaxError: Cannot use import statement outside a module
```

**Comment by onosendi** [comment]
I ran into a similar issue with `jest` as well. I don't understand, am I doing something awkward?

**Comment by onosendi** [comment]
Looks like this fixes it:

before.test.mjs
```js
import 'ts-node/register';

...
```

I'm still unable to import any helpers from local ts files though.

**Comment by isaacs** [comment]
I believe that this _may_ be related to the constellation of issues in #807.

**Comment by onosendi** [comment]
I think if the `--before` flag respected the `--node-arg=--require=@babel/register` (or whatever) this would work?
