### ISSUE TITLE
t.mock and ES Modules fails

### ISSUE THREAD

**Issue by acardinale** [tapjs/tapjs#804]
Hi everyone,
I am writing a test using mock and I get the following error
```
 FAIL ​ test/queue.js 1 failed of 1 203.744ms
 ✖require() of ES Module /home/app/queue.js not supported. Instead change the require of queue.js in null to
a dynamic import() which is available in all CommonJS modules.

  node_modules/append-transform/index.js  
  62 |                  }
  63 | 
> 64 |                  hook(module, filename);
     | ---^
  65 |          };
  66 |  }
  67 | 
```

my code is

```
const myQueue= t.mock(../queue.js');
```

How can I solve it? Thanks!

**Comment by isaacs** [comment]
Here's how it'll work: https://github.com/tapjs/node-tap/issues/808

For now (ie, v16.0 and before), sorry, not supported.  You can maybe use http://npm.im/mock-import to mock it manually, but there's no `t.mock` for it just yet.
