### ISSUE TITLE
Create release notes for Tap v16

### ISSUE THREAD

**Issue by mcollina** [tapjs/tapjs#811]
As titled, the v16 release does not have a release inside Github!

**Comment by isaacs** [comment]
https://github.com/tapjs/node-tap/releases/tag/v16.0.0

**Comment by isaacs** [comment]
Does anyone have an action that can be dropped in to create GH releases automatically from tags with a link to the changelog release notes?  I'm not going to remember to do that each time, clearly.

**Comment by mcollina** [comment]
I usually use https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes. Not perfect but require no setup in the repo.
