### ISSUE TITLE
Mocha API with import

### ISSUE THREAD

**Issue by julien-f** [tapjs/tapjs#818]
Hello,

I was wondering if you would consider exposing a `tap/mocha` for ease of use with import:

```js
import { describe, it } from 'tap/mocha'
```

Current version is not to bad though, so only add it if you think it's really worth it :slightly_smiling_face: 

PS: I'm using this API obviously because I'm converting existing tests but also because I really don't like to add `t.end()` to all my tests :sweat_smile:

**Comment by isaacs** [comment]
> PS: I'm using this API obviously because I'm converting existing tests but also because I really don't like to add t.end() to all my tests 😅

These days, I often just make everything `t.test('message', async t => ...)` and then the promise takes care of it :)

But sure, seems like a reasonable request.  I'll go take a look at #822

**Comment by julien-f** [comment]
Thank you!
