### ISSUE TITLE
Test unfinished

### ISSUE THREAD

**Issue by avin-kavish** [tapjs/tapjs#819]
I'm getting test unfinished in the below scenario. It says that one out of two asserts failed but there is only one assert in the code.

```tsx
t.test('...', () => {
  const client = new Client()

  const builder = new Builder(
    client,
    '',
    {}
  )

  builder.then(console.log)

  t.same(client.callState.get[0], 'xxx')
})
```
It works if `builder.then(console.log)` is removed.

**Comment by isaacs** [comment]
You have to end the test in one of three ways.

1. Call `t.end()` when you're done.
2. Set a plan with `t.plan(number)` to specify how many assertions you expect (it'll end when it gets the planned amount, and fail if it gets too many)
3. Return a promise from the test function (eg, by doing `t.test(name, async t => ...)`)

Also, you are calling the `t.same()` on the _root_ tap object, it should be on the one passed into the test function.

Here's how I'd write it:

```js
t.test('...', async t => { // <-- take subtest as argument, make this an async function
  const client = new Client()

  const builder = new Builder(
    client,
    '',
    {}
  )

  // why does your constructor return a thenable object?
  // are you subclassing Promise or something?
  const result = await builder

  t.same(client.callState.get[0], 'xxx')

  // subtest auto-ends when async function returned promise resolves
})
```

Alternatively, if I'm wrong about `Builder` returning a promise-like, you could do this:

```js
t.test('...', t => {
  const client = new Client()

  const builder = new Builder(
    client,
    '',
    {}
  )

  builder.then(console.log)

  t.same(client.callState.get[0], 'xxx')

  t.end() // <-- end explicitly
})
```

**Comment by avin-kavish** [comment]
Thanks! It's a snippet from a fluent query builder api. It's thenable because, thening it is what fires the query. :)

Actual usage is like, `await serviceClient.collection('blogs').eq('title', 'Title').gt('age', 10)`

**Comment by isaacs** [comment]
Cool.  If it's a Promise, I usually `await` it into a local const, and then do some assertions to make sure I got what I expect.

```js
t.test('some useful description of what is being tested', async t => {
  const result = await new Builder(new Client(), '', {})
  t.equal(result.foo, 'bar', 'or whatever')
  t.match(result, {some: {fields: { expected: 'to be here'}}})
  // etc
})
```

**Comment by avin-kavish** [comment]
right, what I understand is that there shouldn't be any pending callbacks when the test function finishes executing or else the test is considered unfinished. (which makes sense)

In this case I am checking that the `Builder` is internally invoking methods of the `Client` correctly. Speaking of which, is there a function mocking utility in tap? I've had to roll my own function mocking code, hence the `client.callState.get[0]`
