### ISSUE TITLE
hurdles to creating a tap extension

### ISSUE THREAD

**Issue by nlf** [tapjs/tapjs#820]
as @isaacs is aware, i've been working on writing [an extension for tap](https://github.com/npm/tap-nock) that integrates [nock](https://github.com/nock/nock#readme). during the process i encountered some challenges:

1. the readily available pattern to extend `tap` is to modify the `Test` prototype. access to the `Test` class itself is only available from the root `tap` object, this isn't hugely problematic though since it's probably unlikely a user would want an extension only available for a single test. i solved this by making my main export a function that accepts the root tap object and attaches a new function to the `Test` prototype [^1]
2. the `Test` constructor uses [bind-obj-methods](https://github.com/isaacs/bind-obj-methods#readme) on the prototype, replacing the existing functions with a bound version of themselves. this binding process drops additional properties that may be attached to the function. for my specific use case, the desire was to have both `t.nock()` and `t.nock.snapshot()`. to solve this one i had to somewhat abuse javascript [^2]
3. also specific to my use case, i had the desire for my extension to be able to perform an assertion when the user's test code is complete. the only available option for this was `t.teardown()`, which works effectively but when errors are thrown in a teardown the stack is not super helpful out of the box. i solved this by attaching an `at` property on the thrown error indicating the specific line of code that called my extension. for this to be effective, i had to create an error object and extract the file and line from the stack at the time `t.nock()` is called [^3][^4]. this one is probably difficult to help with aside from exporting a helper that returns the `{ file, line }` object necessary (i.e. hide the stack trace parsing internally)
4. also related to the use of `t.teardown()`, when writing tests for my extension we discovered that the teardown functions are not run on the root tap object without manual intervention [^5].
5. when making the required change in order for these teardown functions to be run, we additionally learned that they have no effect on when the 'end' event is emitted. to get around this one, i had to keep my internal teardown functions synchronous so as to be sure they've completed after i call `test.end()` since the 'end' event could not be used. it would be good to make teardowns delay the 'end' event, or potentially make the `end()` method return a promise that resolves when everything is really done.
6. as part of `t.nock.snapshot()` i wanted to be able to write my snapshot data in the same location tap's own snapshots are written. to do so, i had to use `t.snapshotFile` and manually change the file extension [^6]. i'm not sure if there's a reasonable way to make this better, but i was thinking maybe a function that allows you to specify a package name and file extension and get back a path you can write data to. maybe this isn't used enough to worry about codifying though?
7. snapshots must be handled on the root test object so as to ensure that we write one file one time for a full suite of tests, making sure that we don't overwrite snapshot data from previous tests. this is fine, and even looping over `t.parent` until you get a `null` isn't that bad, but it would've been convenient if there was a reference to the root test object somewhere on its children

[^1]: https://github.com/npm/tap-nock/blob/main/lib/index.js#L17-L20
[^2]: https://github.com/npm/tap-nock/blob/main/lib/index.js#L6-L15
[^3]: https://github.com/npm/tap-nock/blob/main/lib/manager.js#L81-L83
[^4]: https://github.com/npm/tap-nock/blob/main/lib/errors.js#L19-L35
[^5]: https://github.com/npm/tap-nock/blob/main/test/snapshot.js#L41
[^6]: https://github.com/npm/tap-nock/blob/main/lib/recorder.js#L28-L29

**Comment by isaacs** [comment]
This is super helpful!

I'll start putting together a todo list/roadmap for tap 18 (tap v17 will just be a few updates to more tightly comply with the TAP14 spec).

**Comment by isaacs** [comment]
Progress on next gen tap is happening in https://GitHub.com/tapjs/tapjs

There's even a nock plugin there ;)

https://github.com/tapjs/tapjs/tree/main/src/nock

**Comment by isaacs** [comment]
Thanks again for this issue.

Tap 18 is good enough to use, though still prerelease until a new ts-node ships (the install is a bit terribly slow until that happens, because it has to fetch so much stuff from git).

`npm i tap@pre` to get it. Be sure to review the [changelog](https://node-tap.org/changelog/#18.0), a bunch of stuff has been updated.

The nock extension `@tapjs/nock` is published to the registry, but not included by default. `tap plugin add @tapjs/nock` to get it. Works pretty much identically to tap-nock.
