### ISSUE TITLE
.taprc arg parsing - "Cannot find module <project-path>/null"

### ISSUE THREAD

**Issue by wkrueger** [tapjs/tapjs#823]
I followed this path from the docs:

  - Created a `.taprc` file with `npx tap --dump-config`. Looked faster to check on the available options.

Running `tap` then outputted the following error:

```
Error: Cannot find module '...\repos\_personal\api-migrate\null'
```

The error is tracked down at `settings.js`:

```js
if (process.env.TAP_LIBTAP_SETTINGS) {
  const overrides = require(process.env.TAP_LIBTAP_SETTINGS)
  const type = typeof overrides
```

Here, `TAP_LIBTAP_SETTINGS` is set to `"null"` (null string), therefore triggering the if branch.

Fixed it by commenting the related line on `.taprc`.

While this is a minor issue, it impacts the "happy path" while trying out the lib through the docs.

Maybe (?)
  - generate `.taprc` with lines commented
  - change .taprc arg parsing

Thanks!

**Comment by isaacs** [comment]
Ah, yeah, I see how that could happen. That's no good 😅
