### ISSUE TITLE
Typescript support for version +15.2

### ISSUE THREAD

**Issue by gabrielfernandes-codes** [tapjs/tapjs#825]
Are there any plans to update types to support the new methods added at the 15.2.x version? Currently, I am trying to use the 16.x version and I can't use determined methods as `hasProp` that were included previously.

**Comment by isaacs** [comment]
That'd be a question for DefinitelyTyped, as I don't maintain the types here.

The next major release of node-tap will be written in TypeScript, so it won't be an issue.
