### ISSUE TITLE
Colorful output on running a tap file

### ISSUE THREAD

**Issue by avin-kavish** [tapjs/tapjs#826]
When I run a test file using `ts-node path/to/test.ts`, I don't get colored output as show in the [docs](https://node-tap.org/docs/getting-started/#hello-world-test-program). I only get colors when I run tap cli. Am I missing some configuration or is it bugged?

**Comment by isaacs** [comment]
That colored output is only for the documentation benefit, by doing ```` ```tap ```` for the code block.  If you want pretty colored output, you'll have to use a reporter of some kind, which the `tap` cli does by default.

A reporter that just colorizes the raw TAP stream would be neat, though :)
