### ISSUE TITLE
Ignoring coverage of certain functions

### ISSUE THREAD

**Issue by avin-kavish** [tapjs/tapjs#828]
I tried doing this to disable coverage of a function,

```
/* istanbul ignore next */
export async function foo() {}
```
but it didn't work. Does `node-tap` support ignoring like this?

**Comment by isaacs** [comment]
I would expect that to work.  Are you using tap's built-in nyc coverage, or c8 or something else?

**Comment by isaacs** [comment]
Also, is this typescript, esm that's compiled to common js, or native esm with node?

**Comment by avin-kavish** [comment]
This is typescript that has module target of common js.

**Comment by avin-kavish** [comment]
I was using tap's built-in nyc coverage, but switched to c8 after I opened this issue. I couldn't find a way to get tap to check coverage for all files and not just the files that were loaded through the tests.

**Comment by isaacs** [comment]
As of version 18, tap now uses c8-ish coverage, so `/* c8 ignore ... */` is the thing to use.  (It uses c8 for reporting, but generates the coverage data by talking to the V8 inspector API directly, so as to not dump quite so much to disk.)

`npm i tap@pre` to get it. Be sure to review the [changelog](https://node-tap.org/changelog/#18.0), a bunch of stuff has been updated.
