### ISSUE TITLE
Inconsistant behavior with CLI options

### ISSUE THREAD

**Issue by collintime** [tapjs/tapjs#836]
I'm working in a large application which used Mocha for about a third of it's legacy tests. I was able to convert 100% of our tests to `tap@16.3.0` using `mochaGlobals()` and some clever find/replace.

Now I'm observing some very un-taplike behavior which I'd love some feedback on. I've had no success reproducing these issues in a fresh project, so I'll very briefly describe what I'm seeing. Hopefully I'll be able to provide more info in the future.

Running the entire suite with something like `tap $(find src -name *.spec.js) --jobs=1 --timeout=60 --bail` results in a dozen or so errors: `no tests found`, `test unfinished`, or even FAIL `OK`. However, once I run these failing tests individually, they pass!

After some digging, I discovered the `-C` option, which somehow causes the entire suite to pass! I even added an explicit `Tap.ok(false)` to confirm failures could occur with a `-C`. 

All the failing tests are using `mochaGlobals()`. Is there anything I can do to narrow down the underlying issues? I suspect these old tests are polluting some unknown global state or causing a race condition, but finding it has been challenging.

Love the project, sorry about this vague issue :(

Node 14, Big Sur

Thanks

**Comment by isaacs** [comment]
So if it works with `-C`, but not otherwise, then it would appear to be something in the reporter.  Can you try these options and let me know what the result is?

```
tap $(find src -name *.spec.js) --jobs=1 --timeout=60 -R classic -d classic-output
tap $(find src -name *.spec.js) --jobs=1 --timeout=60 -R speccy -d speccy-output
```

If both of those pass, then try this, just to rule out "outputting the tap causes it to not fail":

```
tap $(find src -name *.spec.js) --jobs=1 --timeout=60 -R base -d base-output
# this one uses the base reporter, but without color
tap $(find src -name *.spec.js) --jobs=1 --timeout=60 -R base -C -d base-nocolor-output
```

**Comment by isaacs** [comment]
Can't reproduce it, but it might be worth trying on v18 once there's a mocha dsl plugin. `npm i tap@pre` to get it. Check out the [changelog](https://node-tap.org/changelog/#18.0) first, though, a bunch of stuff has been updated.
