### ISSUE TITLE
Do we support specifying a single test to run

### ISSUE THREAD

**Issue by TommyDew42** [tapjs/tapjs#838]
Hi! First of all, thank you for creating such an amazing unit testing package!

I know we can target a single file when we run tests:
```sh
npx tap ./tests/my-module.test.js
```

I'm wondering if we can target a single test when running tests?
I was looking at the [CLI](https://node-tap.org/docs/cli/#cli) documentation and the closest I could find was the `--only` flag.

**Comment by isaacs** [comment]
Maybe you're looking for this?

```
  -g<pattern> --grep=<pattern>
                         Only run subtests tests matching the specified pattern.

                         Patterns are matched against top-level subtests in each
                         file. To filter tests at subsequent levels, specify
                         this option multiple times.

                         To specify regular expression flags, format pattern
                         like a JavaScript RegExp literal. For example: '/xyz/i'
                         for case-insensitive matching.

                         Can be set multiple times
```

Note that `-i` will invert the grep patterns, making them _exclude_ patterns. 

Sorry, the cli docs leave much to be desired.
