### ISSUE TITLE
16.3.1 version breaks windows install on node 14

### ISSUE THREAD

**Issue by codeflyer** [tapjs/tapjs#843]
The update to 16.3.1 breaks the install of the project that uses `tap` on window machine with node 14.21.0.

How to reproduce:

Create a project with this package.json and run `npm i` 
```
{
  "name": "project-name",
  "version": "0.0.1",
  "scripts": {
  },
  "devDependencies": {
    "tap": "^16.3.1"
  }
}
```

The installation works fine with a fixed version of `tap` to `16.3.0`

This is the error thrown during the installation

```
npm ERR! code EPERM
npm ERR! syscall rename
npm ERR! path D:\a\mercurius-gateway\mercurius-gateway\node_modules\tap\node_modules\@babel\.generator.DELETE\node_modules\@jridgewell
npm ERR! dest D:\a\mercurius-gateway\mercurius-gateway\node_modules\tap\node_modules\@babel\generator\node_modules\@jridgewell
npm ERR! errno -404[8](https://github.com/mercurius-js/mercurius-gateway/actions/runs/3468637949/jobs/5794677217#step:4:9)
npm ERR! Error: EPERM: operation not permitted, rename 'D:\a\mercurius-gateway\mercurius-gateway\node_modules\tap\node_modules\@babel\.generator.DELETE\node_modules\@jridgewell' -> 'D:\a\mercurius-gateway\mercurius-gateway\node_modules\tap\node_modules\@babel\generator\node_modules\@jridgewell'
npm ERR!  [OperationalError: EPERM: operation not permitted, rename 'D:\a\mercurius-gateway\mercurius-gateway\node_modules\tap\node_modules\@babel\.generator.DELETE\node_modules\@jridgewell' -> 'D:\a\mercurius-gateway\mercurius-gateway\node_modules\tap\node_modules\@babel\generator\node_modules\@jridgewell'] {
npm ERR!   cause: [Error: EPERM: operation not permitted, rename 'D:\a\mercurius-gateway\mercurius-gateway\node_modules\tap\node_modules\@babel\.generator.DELETE\node_modules\@jridgewell' -> 'D:\a\mercurius-gateway\mercurius-gateway\node_modules\tap\node_modules\@babel\generator\node_modules\@jridgewell'] {
npm ERR!     errno: -4048,
npm ERR!     code: 'EPERM',
npm ERR!     syscall: 'rename',
npm ERR!     path: 'D:\\a\\mercurius-gateway\\mercurius-gateway\\node_modules\\tap\\node_modules\\@babel\\.generator.DELETE\\node_modules\\@jridgewell',
npm ERR!     dest: 'D:\\a\\mercurius-gateway\\mercurius-gateway\\node_modules\\tap\\node_modules\\@babel\\generator\\node_modules\\@jridgewell'
npm ERR!   },
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'D:\\a\\mercurius-gateway\\mercurius-gateway\\node_modules\\tap\\node_modules\\@babel\\.generator.DELETE\\node_modules\\@jridgewell',
npm ERR!   dest: 'D:\\a\\mercurius-gateway\\mercurius-gateway\\node_modules\\tap\\node_modules\\@babel\\generator\\node_modules\\@jridgewell',
npm ERR!   parent: 'tap'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.
```

The error is thrown in CI (eg here https://github.com/mercurius-js/mercurius-gateway/actions/runs/3468637949/jobs/5794677217) and locally (tried with 2 different windows machines)

**Comment by isaacs** [comment]
Well that's weird.  It looks like an npm issue, does it still happen if you `npm install -g npm` to get npm v7 or higher prior to your project install?  (Not saying that's "the fix", but it'll give me a clue about what to dig into.)

**Comment by driimus** [comment]
v9 appears to also be causing issues with installs (see npm/cli#5856). `npm i -g npm@8` (or v7) would do the trick, here are some CI runs https://github.com/driimus/ff-type-provier-private/actions

**Comment by climba03003** [comment]
`@jridgewell/gen-mapping` should be the one causing the problem.
It is nested dependencies from `babel`.

https://github.com/tapjs/node-tap/compare/v16.3.0...v16.3.1

You can see that `@babel/generator@7.17.7` using `source-map` without any problem.
Once it reached `@babel/generator@7.20.4` using `@jridgewell/gen-mapping`. NPM start failing.

**Comment by Uzlopak** [comment]
I quite dont understand why tap is even installing dependencies, as tap is bundled with all the node_modules in the final tar file, which gets published on npm.

**Comment by jonesbusy** [comment]
Hi,

Same issue here. Upgrade from tap 16.3.0 to 16.3.1 break NPM install on windows (and works on WLS/linux) 

```
11:48:58.376+01:00] - npm ERR!    { Error: EPERM: operation not permitted, rename 'C:\jenkins\workspace\temp\*******-test\node_modules\tap\node_modules\@babel\.generator.DELETE\node_modules\@jridgewell' -> 
[11:48:58.376+01:00] - 'C:\jenkins\workspace\temp\*******-test\node_modules\tap\node_modules\@babel\generator\node_modules\@jridgewell'
[11:48:58.376+01:00] - npm ERR!      errno: -4048,
[11:48:58.376+01:00] - npm ERR!      code: 'EPERM',
[11:48:58.376+01:00] - npm ERR!      syscall: 'rename',
```

I'm using node V8

Regards,

**Comment by isaacs** [comment]
This is definitely an npm v6 bug. It's unlikely to ever be fixed (or put another way, it _has_ been fixed, by rewriting pretty much all of the code involved with resolving and reifying package trees in npm v7, but the "fix" is a rewrite, so it isn't something that can ever be backported).

Making matters worse, npm v9 and higher _also_ triggers the bug, so updating from npm v6 to npm v9 is a two-step process.

In the immediate term, this seems to work:

- npm i -g npm@7
- if this is the first time doing a global install, restart cmd or powershell to pick up the newly created folder in the `%PATH%` env
- npm i -g npm@latest
- npm i tap@latest

Still poking at this to see if there's a way tap can arrange its bundles to work with older npm.

Note: the next major version of tap will require node >=16, so this won't be an issue.  (It'll be replaced with a maybe worse issue, "tap doesn't even run on that node version" lol.)

**Comment by Uzlopak** [comment]
@isaacs 
Can you use npm 8 to generate a lockfile Version 2? Current release has a lockfile v3

**Comment by isaacs** [comment]
Yeah, the lockfile version is actually not the problem though.  It has to do with `@babel/generator` having a dependency on some `@jridgewell/...` modules, and being bundled.  Not sure why that's a problem, but it's actually an issue if the deps are all updated (which happened in 8b104bd2).

I got a working tap artifact by:
1. backing out 8b104bd2
2. installing the update to jackspeak (instead of a mass update)
3. installing with npm v7 to get a backwards-compatible lockfile (maybe npm 8 would've worked? not sure)

I'll publish now.

**Comment by isaacs** [comment]
It's been fun to hear from so many people that like using tap on older node versions on windows, though, I had no idea it was this popular there.  Should really figure out some way to get usage metrics that's not sneaky and doesn't require breaking anyone's builds 😅

**Comment by Uzlopak** [comment]
Thanks. Our fastify cicd pipeline run now again. :)
