### ISSUE TITLE
How do I test that an object only has certain properties?

### ISSUE THREAD

**Issue by officer-rosmarino** [tapjs/tapjs#847]
Hi, I'm new to Tap and i'm trying to test the response from an API.

Forgive me if this is explained in the docs, but I'm not finding the right answer..

I want to test that the JSON object returned by the API contains ONLY the fields that I specificy, and no more than that.
This is because I want to make sure that I do not accidentally expose some properties.
For instance, I might have the API `/user/me` that return the user object. Say that the user I retrieve from the database is `{username: 'mike', password: 'qwerty', location: 'USA', age: 21}`

I want to make sure that I do not accidentally expose the password in the future. How can I do it? Is it possible?

**Comment by isaacs** [comment]
Definitely possible.

You can use the `t.same()` or `t.sameStrict()` method, which test that the object has only the exact shape specified and no extra/missing properties. Or, you can use `t.match()`, and include `{password: undefined}` to assert that the property is either missing or explicitly undefined.

**Comment by officer-rosmarino** [comment]
Close, but no cigar. Probably I wasn't clear. `t.same()` seems to test also for the values. I, instead, want to check that the fields are there, but the values might differ (the API returns a random object, so I cannot predict what is there).

So for instance, I want to make sure that the response has an `username`, a `location`, and an `age` field, and nothing else. This is my first requirement. Second would be to check the type (string, integer) if possible.
If tomorrow i edit the same API and by accident i return an object that has `username`, a `location`, an `age` field and a `password` (or any other field) the test should fail (independently from the actual value that each of these fields have).

**Comment by isaacs** [comment]
Ahh, I see.  Yeah, I was misunderstanding it.

There's no pre-baked method that does exactly that (loosely match specified fields, but don't allow additional fields), as it's kind of an unusual case.  Usually if you are loose about the values, you're also loose about the object shape.

I'd do it like this:

```js
t.test('object only has known fields', async t => {
  const obj = await getTheObjectFromTheApiSomehow()
  t.match(obj, {
    username: String,
    location: String,
    age: Number,
  }, 'types should match')

  // using a Set here because the order doesn't matter, but
  // the inclusion of the fields does.  If you do care about the
  // order, could just compare the arrays, but then it's a bit more
  // brittle, because the API could change the object key order
  // and then the test would start failing.
  t.strictSame(new Set(Object.keys(obj)), new Set(['username', 'location', 'age']),
    'should have exactly the keys we expect')
})
```

**Comment by isaacs** [comment]
I'm in the middle of rewriting tcompare (the module that drives these comparison methods) as part of tap v18.  If there was a "match exactly these fields, but loosely", what would you guess that it might look like?

It could be relegated to using the `matchOptions` method, something like this:

```js
t.test('object only has known fields', async t => {
  const obj = await getTheObjectFromTheApiSomehow()
  t.match(obj, {
    username: String,
    location: String,
    age: Number,
  }, 'types should match', {
    matchOptions: {
      rejectExtraFields: true // <-- not a great name for this option, just sketching
    }
  })
})
```

or there could be some sugar like:

```js
t.matchOnly(obj, {
  username: String,
  location: String,
  age: Number,
})
```

What do you think?

**Comment by isaacs** [comment]
Actually, I think it might be easier to do the separate method, so there'd be a `MatchOnly` class that extends `Same` and uses the test method from `Match`, sort of like how `HasStrict` extends `Has` but uses the `Strict` test method.

**Comment by isaacs** [comment]
<details><summary>i was wrong</summary>
Is it a concern if the object has an unspecified property, but the value is set to `null` or `undefined`?  `match()` doesn't differentiate between "not present" and null/undefined currently, so it'd be tricky if it had to have that capability.

So, for example:

```js
// these pass because undefined matches both null and missing
t.matchOnly({a:1}, {a:Number})
t.matchOnly({a:1, b:undefined}, {a:Number})
t.matchOnly({a:1}, {a:Number, b:undefined})
t.matchOnly({a:1, b:null}, {a:Number})
t.matchOnly({a:1}, {a:Number, b:null})

// these fail, because false does not match undefined
t.matchOnly({a:1, b:false}, {a:Number})
t.matchOnly({a:1}, {a:Number, b:false}) // (this one fails t.match() as well)
```
</details>

**Comment by isaacs** [comment]
Oh, I lied, apparently `Same` _does_ detect different object shapes, so `MatchOnly` will as well.

**Comment by isaacs** [comment]
This is available in tap@18. `npm i tap@pre` to get it. Be sure to review the [changelog](https://node-tap.org/changelog/#18.0), a bunch of stuff has been updated.
