### ISSUE TITLE
Update TypeScript type definition

### ISSUE THREAD

**Issue by itsdonnix** [tapjs/tapjs#848]
It looks like the TypeScript type definition for tap is not updated in `@types/tap` . I found the last version of `@types/tap` to be `15.0.7` which does not match the latest `node-tap` version I am using which is `16.3.2`.

Thank you

[DefinitelyTyped/types/tap - GitHub](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/tap)
[@types/tap - npm](https://www.npmjs.com/package/@types/tap)

**Comment by OneCricketeer** [comment]
See https://github.com/tapjs/node-tap/issues/825#issuecomment-1155404538
