### ISSUE TITLE
node-tap shouldn't use graceful-fs by default

### ISSUE THREAD

**Issue by othiym23** [tapjs/tapjs#85]
Because `tap` uses `glob`, as a byproduct of loading the `glob` module, `graceful-fs`'s polyfills are patched onto `fs` globally. Among other things, this means that `fs.chown()` starts swallowing `EPERM`. Reasonable people may disagree about the usefulness of this error when running as a non-privileged user (when `chown` is never going to work, at least on OS X), but the silent failure was surprising and cost me an hour or two of debugging and led me to believe the problem was in Node itself. Is there a way to use `graceful-fs` in `glob` without poisoning the `fs` module for `tap` users?

**Comment by isaacs** [comment]
There's no way to make graceful-fs work without monkey-patching.  I've spent the last year dealing with issues around this.

You can do `npm install tap --no-optional` to prevent the installation of glob's optional dep on graceful-fs.  Probably a better idea is just to not have glob use graceful-fs.
