### ISSUE TITLE
How to mock/spy console ?

### ISSUE THREAD

**Issue by paolomainardi** [tapjs/tapjs#850]
Hi everyone! Sorry if the questione have been already asked before, I couldn’t find anything related tho.
I am using this library una recent project instead of Jest and wow! I really like it.

just wondering anyway how to mock/spy console in a similar way: https://dev.to/zirkelc/how-to-test-console-log-5fhd

Thanks for your help!

**Comment by isaacs** [comment]
I usually do it like this:

```js
t.test('console stuff', t => {
  const {error} = console
  t.teardown(() => console.error = error)
  const errorLog = []
  console.error = (...m) => errorLog.push(m)

  doStuffThatLogsStuff()
  t.match(errorLog, [['expected', 'message']])
  t.end()
})

**Comment by isaacs** [comment]
A fancier spy method is a good idea for a plugin in the next major of tap, though.

**Comment by paolomainardi** [comment]
Wow. Thanks a lot @isaacs I am so noob that I never thought that something can be mocked like this, mind blowing.
thanks!

**Comment by isaacs** [comment]
Sometimes the simple old ways are best, happy to pass it on.

I will leave this open as a reminder to do a spy plugin tho. I've written those four lines enough times, they probably ought to be A Thing.

**Comment by ruckonic** [comment]
@isaacs Is this already finished?

**Comment by isaacs** [comment]
Not yet, but I am building the new tap in https://GitHub.com/tapjs/tapjs and posting updates to #821 if you wanna follow along

**Comment by paambaati** [comment]
Very excited about this functionality landing in core tap.

For anybody else that cannot wait for it to land, here’s another way to do it —

https://github.com/paambaati/codeclimate-action/blob/0a6ab7b3365b14f0176c394790a09bc60184a122/test/main.test.ts#L86

**Comment by isaacs** [comment]
Would it maybe be better to just have an optional plugin that exposes sinon in some way? A straightforward way would be to have a plugin add a t.sinon property, and do some automatic cleanup on test teardown. Sinon is a lot, but I'm not sure it makes sense to end up replicating all of its functionality. 

I think the thing to include built in by default would be just a very simple kind of spy that lets you capture the calls.

```ts
const getLogs = t.capture(console, 'log')

// this logs nothing:
console.log('hello', 123)
console.log(true)

// returns: [
//   ['hello', 123],
//   [true],
// ]
t.match(getLogs(), expectedLogs)
```

Then if you want to assert it was called n times, or whatever, look at the returned array.

**Comment by paambaati** [comment]
@isaacs I actually like the `capture` API a lot. How would mocks work?

Also, now that Node has a built-in test runner, will tape 18 leverage the built-in? The native mocking story is pretty great right now.

**Comment by isaacs** [comment]
Oh, wow, I didn't even notice that they'd added a mock function wrapper to the `node:test` builtin, and here I am almost done with writing a nearly identical implementation, lol. Guess I could just copy their interface a bit.

Where I'd landed was this:

- `t.capture(obj, method, impl = () => {})` overrides the existing `obj[method]` with the supplied impl.  (So you can pass it in as the third arg if you want to spy on it without changing behavior, eg `t.capture(console, 'log', console.log)`.)
- `t.capture(..)` returns a function that sets the list of calls back to `[]`, and returns the ones that have been called so far.
- Each entry in the returned `results` is an object with:
    - `args` array of arguments
    - `at` a CallSiteLike object (from @tapjs/stack, basically the same as a native JavaScript CallSite, but instead of functions like `fileName()`, `lineNumber()`, and so on, it has properties with those values, automatically looks up sourcemap origins, parses eval origins, etc.)
    - `returned` the return value (if it successfully returned, this might be `undefined` of course)
    - `threw: true` if it threw  (Doesn't actually capture the error, though, since that would obscure the callsite of the throw, which can be annoying.  I'm open to changing that, though, if someone has a case where they need to get the error that was thrown and handled elsewhere, maybe?  Like if you want to verify that one component throws something, and that the throw is handled, then you can't just use `t.throws(...)` to get it, because it gets handled before making it to the test, and that's the behavior you want to test?  I don't feel strongly about it, but I do feel strongly that it should be exactly one or the other, since making that a config feels too subtle and clunky to me.)

So slightly different than what I sketched in the previous comment, but not far off, and way more informative.

The main difference is that instead of looking at `console.log.calls`, you grab the function returned by `t.capture()` and call it to get the list of calls since the last time you looked.  And, instead of inventing property names like `call.target`, all the extra stuff (other than args and return/throw) are hanging on the `at` property with the same standard names that the `CallSite` class uses, which matches how everything tracks call sites in tap.  

> now that Node has a built-in test runner, will tape 18 leverage the built-in?

(I assume you mean "tap" 18, "tape" is a different thing.)  No, tap is still going to be its own thing.  The node built-in test lib is a very lean test runner for simple cases, but tap intends to be way more of a batteries-included kitchen-sink type of "all the things" test library.

But, since the `node:test` module outputs TAP to stdout, and the node test reporter reads TAP from a subprocess's stdout, it's already trivial to use node-tap's runner with node:test tests, or vice versa.  I could definitely see cases where it might be nice to mix and match, especially once the plugin-able tap is released.  For example, you might have a bunch of relatively small util functions that can be tested fully with `node:test` without any problem, but then have a plugin to do react components, and another to drive puppeteer for integration tests.  Or just use tap's runner so that you can automatically run typescript and get the benefit of change tracking and `--watch`.  That flexibility is really the beautiful thing about TAP as a protocol.

**Comment by isaacs** [comment]
Alrighty, wrote this up as 2 plugins, one minimal one that'll be included by default, and another that'll be optional if you want all that sinon provides.

The sinon one creates a sinon sandbox the first time you access the `t.sinon` property, and so you can do `t.sinon.whatever()` and it'll just work, and unregister everything when the test ends.  I thought for a moment about trying to figure out how to replace sinon's assertions with tap assertions, but meh.  Too hard.  If you want sinon, use sinon, it's pretty good.  (This is similar to how the `@tapjs/nock` plugin will work as well, you can add it optionally, and then you get all of nock's goodness, constrained to a single test, by calling `t.nock(...)` or `t.nock.snapshot()`.)

The one that's built in by default will let you do `const results = t.intercept(obj, property)`, and then you can call `results()` to get the list of all the get/set operations that happened.  You can also replace it with a specific value or getter/setter by doing `t.intercept(obj, property, { value: 'whatever' })`, which is really handy for temporarily setting stuff like `process.version` for a single test (eg, if it's used in cli help output or user-agent strings or something).  Can also set a global, so you could even do `t.intercept(global, 'process', { value: myFakeProcess })` and then it'll restore at the end of the test.  That could even be useful if you just wanted to figure out why something isn't the value you expect, by tracking all the call sites where it's accessed.

`t.capture(obj, 'method', replacementMethod = () => {})` is similar, but the results method returns the args/at/returned/threw result discussed above.

https://github.com/tapjs/tapjs/tree/main/src/intercept
https://github.com/tapjs/tapjs/tree/main/src/sinon

**Comment by isaacs** [comment]
> How would mocks work?

@paambaati I'm not sure what you mean, exactly.

"Mock" in tap lingo means "mock dependencies".  The existing `t.mock()` method takes a module name and object of module references to override, but it predates node esm modules, and so is require()-only.

In the upcoming version, there'll be `t.mockRequire()` (which is essentially the same as the current `t.mock()`) and `t.mockImport()` which has the same sort of behavior, but it's an async method, and loads modules with `import()`.

Sometimes when people say "mock" they mean this kind of interception/capturing behavior, which `t.capture()` and `t.intercept()` can do quite easily by providing a replacement function implementation or property descriptor.

Another thing people sometimes mean when they say "mock" is setting up and tearing down fixtures.  That's done with `t.testdir({ dir: { filename: 'contents' } })` thing today, provided in the upcoming v18 version by the `@tapjs/fixture` plugin.

Mocking HTTP requests won't be built in by default, but there'll be the `@tapjs/nock` plugin (or today, you can use `@npmcli/tap-nock`, which `@tapjs/nock` is based on), so you can either record and snapshot requests, or use explicit mock responses, by interfacing with Nock.

Is there something else I'm missing?  I think that about covers it lol

**Comment by paambaati** [comment]
I think you’ve covered most of the things about mocks. Some additional questions, if you don’t mind —

1. How would one mock class constructors?
2. How would one mock class methods? Both static and dynamic?

I suppose documenting these upfront would be massively helpful. I’d love to contribute to the docs, as I also maintain an eslint plugin for tap — https://github.com/getoslash/eslint-plugin-tap

**Comment by isaacs** [comment]
> I also maintain an eslint plugin for tap

Oh, cool, I didn't know there was such a thing, thanks :)

> How would one mock class constructors?

I usually just mock the entire class, by mocking the module that provides it.

```js
const whateverModule = t.mock('../src/whatever', {
  '../src/some-class-thing': {
    SomeClass: class MockedClass {
      constructor () { console.log('in the mock') }
    }
  }
})
```

> How would one mock class methods? Both static and dynamic?

You'll be able to use `t.capture()` on an individual object if you want:

```js
const obj = new SomeClass()
const results = t.capture(obj, 'some-method', () => { console.log('mocked method') })
```

I hadn't really ever had a need to just swap out one method in a class prototype _without_ either mocking the entire class or just that method on an instance, but I suppose this would work as well:

```js
import SomeClass from '../wherever/some-class.js'
const results = t.capture(SomeClass.prototype, 'classMethod', () => console.log('mocked method'))
// ...
t.match(results(), [
  { args: ['expected'] },
  { args: ['method calls'] },
])
```

There isn't really a straightforward way to swap out _just_ the constructor of a class, without some very sneaky Proxy/Reflect incantations.

**Comment by isaacs** [comment]
Oh, I guess it's not all _that_ sneaky.  This seems to work pretty reliably to construct an object from the `Foo` prototype, but actually use the `MockFoo` constructor method.

```js
class Foo {
  original = true
  constructor () {
    console.log('original foo ctor')
  }
  bar() {
    return 'in bar'
  }
}

class MockFoo {
  mock = true
  constructor () { console.log('mock foo ctor') }
}

// Reflect.construct(ctor, [...args], prototype source)
const foo = Reflect.construct(MockFoo, [], Foo)

console.log(foo instanceof Foo, foo, foo.bar())

/*
mock foo ctor
true Foo { mock: true } in bar
*/
```

This is pretty different from capturing an object method though.  I'm not sure how this would be useful in a convenient test API, or what that would even look like, exactly.

**Comment by ruckonic** [comment]
How can work that when need mock an bindings modules eg `node:fs`?

```js
test('mocking esm module', async (t) => {
  const fs = await import('node:fs')

  const readFile = t.capture(fs, 'readFile')

  someModuleThatUseReadFile()

  t.equal(readFile.calls.length, 1)
})
```

**Comment by isaacs** [comment]
@ruckonic That approach won't work, because when you import a module like `node:fs`, it's loaded as named exports, not an object with properties that can be modified.  Also, even if the module was using `require()`, it could have done `const { readFile } = require('node:fs')`, so it would get a reference to the original before you capture it.

You'd have to do this instead, to load the module and hijack the fs import/require:

```ts
import * as fs from 'node:fs'
t.test('mocking esm module', async t => {
  const results = t.capture(fs, 'readFile', fs.readFile)
  const someModuleThatUseReadFile = await t.mockImport('../src/some-module-that-use-readfile', { fs })
  someModuleThatUseReadFile()
  t.equal(results().length, 1)
})
```

**Comment by isaacs** [comment]
Actually, making this just a bit easier (maybe?), added a `t.captureFn` method that just wraps a function and returns the wrapped version, similar to node:test's `mock` method, so you could also do it this way:

```ts
import * as fs from 'node:fs'
t.test('mocking esm module', async t => {
  const someModuleThatUseReadFile = await t.mockImport('../src/some-module-that-use-readfile', {
    fs: {
      ...fs,
      readFile: t.captureFn(fs.readFile),
    }
  })
  someModuleThatUseReadFile()
  t.equal(fs.readFile.calls.length, 1)
})
```

**Comment by isaacs** [comment]
This is in `tap@pre`, and I love it. Using the heck out of it everywhere.

https://node-tap.org/plugins/intercept/
