### ISSUE TITLE
json5 vulnerability in 16.3.2

### ISSUE THREAD

**Issue by larsknutson** [tapjs/tapjs#852]
Hi everyone! 

There is a vulnerability in the bundled dependencies of 16.3.2 with json5. I have tried overriding this locally but am not having any success. Json5 needs to be updated to >=2.2.2. Is there a way to fix this without a new release in @isaacs/import-jsx as well as here?

For context of what I did: 
`"devDependencies": {
        "json5": "^2.2.2"
    },"overrides": {
        "tap@16.3.2": {
            "@isaacs/import-jsx@4.0.1": {
                "@babel/core@7.17.8": {
                    "json5": "$json5"
                }
            }
        }
    }`

Thank you!

**Comment by theoludwig** [comment]
Hey! :wave:

Indeed, I opened a PR to fix this: #851.
Hopefully, it get merged and released soon. :smile:

friendly ping @isaacs

**Comment by theoludwig** [comment]
This issue can now be closed.
Ref: https://github.com/tapjs/node-tap/pull/851#issuecomment-1377017307
