### ISSUE TITLE
Add consumer-only mode

### ISSUE THREAD

**Issue by jammi** [tapjs/tapjs#853]
Now since there's `node:test` available in the newest Node.JS releases, please add a mode for formatting its tap output, since node-tap seems to be the nicest TAP suite out there. I'd suggest something like `node --test | tap --stdin` to consume what node's own tap output produces and then format that as if node-tap itself produced it.

**Comment by isaacs** [comment]
This is actually already supported!  Test files are just programs that output TAP, so it just works.

```js
// t.mjs
import * as t from 'node:test'
import { ok } from 'node:assert'

t.test('ok', async () => {
  ok(true, 'this is fine')
})
```

```bash
$ tap t.mjs 
 PASS ​ t.mjs 1 OK 391.898ms


                         
  🌈 SUMMARY RESULTS 🌈  
                         

Suites:   ​1 passed​, ​1 of 1 completed​
Asserts:  ​​1 passed​, ​of 1​
Time:​   ​447.52ms​
```

**Comment by isaacs** [comment]
You can also do this:

```
$ node --test | tap -
```

But of course then it won't be using node-tap's runner, it's just parsing stdin serially, so if you're relying on how it handles parallel tests, arguments, etc, then that's not going to be as powerful.

**Comment by yeldiRium** [comment]
> You can also do this:
> 
> ```
> $ node --test | tap -
> ```
> 
> But of course then it won't be using node-tap's runner, it's just parsing stdin serially, so if you're relying on how it handles parallel tests, arguments, etc, then that's not going to be as powerful.

I'm looking to use node-tap as a consumer and report-generator for other TAP-producers, and this feature is important for that. Is piping a TAP stream into `tap -` an intended and supported use-case? I can't find anything about it in the CLI's help output or on the website.

**Comment by isaacs** [comment]
Yes, treating stdin as a TAP producer is 100% supported, has been since the first release.

You can even mix it in with other files, like `node --test | tap file.js - other-file.js`
