### ISSUE TITLE
Debugging missing coverage version 16.3.3

### ISSUE THREAD

**Issue by JJ** [tapjs/tapjs#854]
After refactoring [a module](https://github.com/JJ/nodeo) to use ES6, `tap` now returns 0% coverage:

```text
                         
  🌈 SUMMARY RESULTS 🌈  
                         

Suites:   ​2 passed​, ​2 of 2 completed​
Asserts:  ​​​46 passed​, ​of 46​
Time:​   ​433.179ms​
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |                   
----------|---------|----------|---------|---------|-------------------
```

The only possibly weird thing this module has is "abstract"-like base classes: 

```js
import { ABTException } from "../abt_exception.js";

export class Chromosome {
  constructor() {
    if (new.target === Chromosome) {
      throw new ABTException("Fitness");
    }
  }

  get fitness() {
    return this.fitness;
  }
}
```

`tap` is launched with `tap test/unit/*.test.js`, nothing fancy. Any idea?

**Comment by isaacs** [comment]
Node's built in esm handling broke tap's approach to coverage pretty much entirely. Until the next major tap version is done, you can `npm install c8 -D` and run your tests as `"c8 tap --no-coverage"`.

**Comment by JJ** [comment]
Is there any downgrade possible here that does not have too many vulnerabilities? Thanks anyway for answering.

**Comment by isaacs** [comment]
C8 works fine, but if you want to keep using the built-in nyc, you can just not use esm or compiled typescript. Up to you, really, but idk how any downgrade would help.

**Comment by isaacs** [comment]
Coverage is flawless now on tap 18.  `npm i tap@pre` to get it. Check out the [changelog](https://node-tap.org/changelog/#18.0) first, though, a bunch of stuff has been updated.
