### ISSUE TITLE
Coverage map not working in ES Module

### ISSUE THREAD

**Issue by l0ner** [tapjs/tapjs#857]
Hi

I have a library I'd like to generate coverage map for, the problem is that the whole library is an ES module, and the `package.json` is set accordingly:

```json
{
	...
	"type": "module"
	...
}
```

I have created a coverage map file as described in [the docs](https://node-tap.org/docs/coverage/coverage-map/), which gives me the following error every time I run the tests suite:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module tests/coverage.js from node_modules/tap/bin/run.js not supported.
Instead change the require of coverage.js in node_modules/tap/bin/run.js to a dynamic import() which is available in all CommonJS modules.
```

I have replaced the loading of the coverage file on [line 636 of the `run.js`](https://github.com/tapjs/node-tap/blob/d20aff1ee73d54d733a76bf41b17bcd25009a6ad/bin/run.js#L636) with the following:

```js
let coverageMap = null;
const req = require('require-esm-in-cjs');
if(options['coverage-map']) {
	try {
		coverageMap = require(path.resolve(options['coverage-map']));
	}
	catch(e) {
		if(e.code === "ERR_REQUIRE_ESM")
			coverageMap = req(path.resolve(options['coverage-map']));
		else
			throw e;
	}
}
```

But that requires having [require-esm-in-cjs](https://www.npmjs.com/package/require-esm-in-cjs) as a dependency.

One could use the dynamic `import()` as suggested in the error message, but that is asynchronous, which means we might not have loaded it before reaching the place where it is called.

Now the error is gone. But the coverage report generated by tap is empty, so something is still wrong.

My coverage map:

```js
export default testFile => {
	return testFile
		.replace(/\.test\.js$/, '.js')
		.replace(/tests/, 'src');
};
```

**Comment by ruckonic** [comment]
use [c8](https://github.com/bcoe/c8) for add coverage to esm

**Comment by isaacs** [comment]
workin on it #821 ;)

**Comment by isaacs** [comment]
This is available now if you want to try it.

```
npm i tap@pre
```

[Changes](https://node-tap.org/changelog/#18.0)
