### ISSUE TITLE
Enable coverage checks for TS node16 modules (feature request)

### ISSUE THREAD

**Issue by ilg-ul** [tapjs/tapjs#858]
I have a project with the main code in TS and the test code in JS, using modules.

If I compile the TS into CommonJS code with the following `tsconfig.json`...

```json
  "compilerOptions": {
    "rootDir": "src",
    "outDir": "dist",
    "sourceMap": true,
    "declaration": true,
    "target": "es2020",
    "lib": [
      "es2020"
    ],
    "typeRoots": [
      "./node_modules/@types",
      "./typings"
    ],
    "module": "commonjs",
    "moduleResolution": "node16",
     "strict": true,
    "alwaysStrict": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "forceConsistentCasingInFileNames": true
  },
```

... the tests are fine, including 100% coverage:

```console
> npm run test-tap100 -s

tests/tap/010-mock-console.js ......................... 7/7
tests/tap/020-logger-single.js .................... 186/186
tests/tap/030-logger-multi.js ..................... 184/184
tests/tap/040-is-level.js ........................... 72/72
tests/tap/050-buffer.js ........................... 108/108
tests/tap/060-logger-empty.js ....................... 25/25
tests/tap/070-logger-default.js ....................... 2/2
tests/tap/080-undefined.js .......................... 38/38
total ............................................. 622/622

  622 passing (2s)

  ok
------------|---------|----------|---------|---------|-------------------
File        | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
------------|---------|----------|---------|---------|-------------------
All files   |     100 |      100 |     100 |     100 |                   
 src        |     100 |      100 |     100 |     100 |                   
  index.ts  |     100 |      100 |     100 |     100 |                   
 src/lib    |     100 |      100 |     100 |     100 |                   
  logger.ts |     100 |      100 |     100 |     100 |                   
------------|---------|----------|---------|---------|-------------------
```

If I change `tsconfig.json` into...

```json
    "module": "node16",
```

... add `  "type": "module" ` to `package.json` to read the TS compiled code as ES, the tests also pass, but the coverage counters are all 0:

```console
> npm run test-tap100 -s

tests/tap/010-mock-console.js ......................... 7/7
tests/tap/020-logger-single.js .................... 186/186
tests/tap/030-logger-multi.js ..................... 184/184
tests/tap/040-is-level.js ........................... 72/72
tests/tap/050-buffer.js ........................... 108/108
tests/tap/060-logger-empty.js ....................... 25/25
tests/tap/070-logger-default.js ....................... 2/2
tests/tap/080-undefined.js .......................... 38/38
total ............................................. 622/622

  622 passing (666.937ms)

  ok
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |                   
----------|---------|----------|---------|---------|-------------------
```

I understand that the `node16` configuration in TS is a recent feature, that might require some adjustments in `tap`, and I think I can live for a while without the coverage tests, but it would be nice to know that, at a certain point, support for `node16` modules will also be available in `tap` (otherwise a great tool!).

Thank you!

**Comment by ilg-ul** [comment]
For completeness, here is the project I'm referring to:

- <https://github.com/xpack/logger-ts/commits/v5.0.5-pre-cjs>

(I added the `v5.0.5-pre-cjs` tag for this specific configuration which still uses CommonJS, since I plan to migrate the package to modules)

**Comment by ilg-ul** [comment]
For those who also face this problem, a possible workaround is to disable coverage in `tap` and use [`c8`](https://github.com/bcoe/c8). 

The npm script do do this is:

```json
    "test-coverage-c8": "c8 tap --ts --reporter=classic --timeout 600 --no-coverage \"tests/tap/*.js\"",
```

**Comment by isaacs** [comment]
Yeah, this is the reason why I've been doing a depth-first traversal through all my modules converting them to hybrid typescript implementations.

The next rewrite of Tap will address this. In the meantime, I'm using c8.

**Comment by ilg-ul** [comment]
> all my modules converting them to hybrid typescript implementations.

Yes, TypeScript is definitely the way to go, but it might be only the cherry on the cake, the major hurdle now is the migration to ES6 modules, since it is a one way street, and once one of your major dependencies did it, you have to do it too. But I think that in the end we'll be fine, TypeScript compiled into `node16` code seems a solid foundation for the next few years.

BTW, I think you are a super-hero for writing npm in those early days, without async/await and without classes. 👍 

> The next rewrite of Tap will address this. In the meantime, I'm using c8.

Great! I'm not familiar with the Tap internals, perhaps it would be easier to use c8 too.

Another feature that might be worth considering for the next Tap rewrite is to allow us to write the tests also in TS; now my tests are still in JS; the mix is functional, but having everything in TS would be even better.

Good luck with your rewrites!

**Comment by isaacs** [comment]
My approach has been varied somewhat for different modules, but the general pattern I'm following is:

1. If it's not worth rewriting the code in ts (sometimes it's just easier to write a .d.ts by hand) then I at least port the _tests_ to TS so that I'm testing the types, and have a reminder to keep them in sync.  (Eg: https://github.com/isaacs/node-lru-cache or https://github.com/isaacs/minipass)
2. If I do write the code in TS, I usually port the tests as well, but sometimes it's not really worth it.  In those cases, I'm using a hybrid setup so you can `require()` or `import` the package, for example: https://github.com/isaacs/minimatch https://github.com/isaacs/mkdirp https://github.com/isaacs/rimraf
3. All net new code is using the hybrid setup, and typescript end to end, for example: https://github.com/isaacs/path-scurry

**Comment by isaacs** [comment]
And for the most part, using these tap options: https://github.com/isaacs/minimatch/blob/main/package.json#L73-L81

```json
{
    "coverage": false,
    "node-arg": [
      "--no-warnings",
      "--loader",
      "ts-node/esm"
    ],
    "ts": false
  }
```

these scripts: https://github.com/isaacs/minimatch/blob/main/package.json#L28-L42

```json
{
    "preversion": "npm test",
    "postversion": "npm publish",
    "prepublishOnly": "git push origin --follow-tags",
    "preprepare": "rm -rf dist",
    "prepare": "tsc -p tsconfig.json && tsc -p tsconfig-esm.json",
    "postprepare": "bash fixup.sh",
    "pretest": "npm run prepare",
    "presnap": "npm run prepare",
    "test": "c8 tap",
    "snap": "c8 tap",
    "format": "prettier --write . --loglevel warn",
    "benchmark": "node benchmark/index.js",
    "typedoc": "typedoc --tsconfig tsconfig-esm.json ./src/*.ts"
  }
```

and these exports: https://github.com/isaacs/minimatch/blob/main/package.json#L13-L24

```json
{
    ".": {
      "import": {
        "types": "./dist/mjs/index.d.ts",
        "default": "./dist/mjs/index.js"
      },
      "require": {
        "types": "./dist/cjs/index-cjs.d.ts",
        "default": "./dist/cjs/index-cjs.js"
      }
    }
  }
```

**Comment by ilg-ul** [comment]
Right, you are authoring core packages, and afford not to have dependencies, thus compiling TS into commonjs and adding a module wrapper is probably the best strategy.

I initially also considered this path, but it did not work, since for us, mere mortals, who depend on other packages, there comes a day when one of the dependencies is migrated to ES modules and sooner or later we have to do it too. 

Thus my updated strategy is to compile TS into node16, and forget about commonjs. And do it as soon as possible, to minimize the pain.

Till now I successfully used Tap in all my JS projects, and tried to achieve 100% coverage. I know that there are alternate solutions, like mocha & c8, but I'd still  prefer Tap, so it would be great to be able to use it for TS projects compiled into ES modules, with TS tests, and have coverage support and a good integration (for example Tap reporting the location of the errors in TS source files).

**Comment by ilg-ul** [comment]
BTW, thank you for the links, they provide a lot of useful details. 👍

**Comment by isaacs** [comment]
Sure, happy to help!

Yeah, I really like using tap for tests, as well.  Things mostly still "just worked" when using TS, because istanbul can interpret the source maps well enough, but ESM throws that all out the window, because it has a completely different interface for instrumenting/transpiling code.

One problem with C8 is that it just uses node's built-in `NODE_V8_COVERAGE` environment variable, so _everything_ gets covered, whether needed or not. That means that your coverage output covers everything in node_modules, and there's no way to do coverage maps, etc.  And since it doesn't support the istanbul-lib-processinfo interface, there's no way to use that coverage info in other ways besides just reporting, which means `tap --changed`, watch, etc, aren't possible.

I got https://github.com/tapjs/processinfo pretty close to complete, which uses V8's coverage support more directly, and can thus decide what to cover and what not to, and then outputs the processinfo data that tap can use for other things later.  And it works on both CJS and ESM, which is nice.  But the rest of tap has to be updated to use it, of course.

In addition, I'd like to have node-tap be completely written in TS, and support a plugin interface, so that it's easier to extend in novel ways.  So if you wanted to, say, have a plugin that creates a nock server for tests, or hook into the react testing library, or whatever, we could do that easily, without having to continually bloat the core library, _and_ get the appropriate type-hinting in your editor, so it'll know that `t.nock({ ... })` is a thing, etc.

That's what kicked off the depth-first traversal through all my libraries.  I'm nearing completion on node-glob v9 now, just working on addressing some performance issues with its algorithm so I can faithfully claim that it is the fastest globbing library in JavaScript.  It's very close, just falls over when there's multiple instances of `**` in the pattern, like if you do `./**/../*/**/../../?/**` or something.

**Comment by ilg-ul** [comment]
> I really like using tap for tests, as well.

FYI, node-tap served as inspiration for the initial release for µTest++; now the project got deeper into modern C++, but still has some resemblances with Tap:

- <https://github.com/micro-os-plus/micro-test-plus-xpack/#examples>

> ... support a plugin interface ...

That is nice, but probably beyond my current needs, which are CLI applications.

I just completed the migration to TS for all my utility packages, and I'll start soon work on converting [`xpm`](https://www.npmjs.com/package/xpm) (which complements `npm` and adds support for managing projects using language neutral source packages and multi-platform binary packages).

But my task is much simpler, since all my code is already organised in classes, so the migration to TS basically means adding the explicit typed definitions of the class members.

Also, I found it very helpful to have my code pass the validation with [standardJS](https://standardjs.com). Now I switched to their TS variant (ts-standard), which also looks great. Highly recommended!

**Comment by ilg-ul** [comment]
I tried to migrate the tests to TS, but could not make them work. :-(

I managed to compile everything, but it was not easy, I had to add a second `tests/tsconfig.json`, configured to leave the output in `tests/out`.

However, trying to run the tests resulted in an error:

```
> @xpack/logger@6.0.0 test-tap /Users/ilg/My Files/WKS Projects/xpack.github/npm-modules/logger-ts.git
> tap --ts --reporter=classic --timeout 300 --no-coverage "tests/tap/*.ts"

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /Users/ilg/My Files/WKS Projects/xpack.github/npm-modules/logger-ts.git/tests/tap/010-mock-console.ts
    at new NodeError (internal/errors.js:322:7)
    at Loader.defaultGetFormat [as _getFormat] (internal/modules/esm/get_format.js:71:15)
    at Loader.getFormat (internal/modules/esm/loader.js:105:42)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:31)
    at async Loader.import (internal/modules/esm/loader.js:177:17)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
    at async handleMainPromise (internal/modules/run_main.js:59:12) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}

tests/tap/010-mock-console.ts ......................... 0/1
  not ok tests/tap/010-mock-console.ts
    env:
      TS_NODE_COMPILER_OPTIONS: "{}"
    file: tests/tap/010-mock-console.ts
    timeout: 300000
    command: /Users/ilg/.nvm/versions/node/v14.21.2/bin/node
    args:
      - -r
      - /Users/ilg/My Files/WKS
        Projects/xpack.github/npm-modules/logger-ts.git/node_modules/ts-node/register/index.js
      - tests/tap/010-mock-console.ts
    stdio:
      - 0
      - pipe
      - 2
    cwd: /Users/ilg/My Files/WKS Projects/xpack.github/npm-modules/logger-ts.git
    exitCode: 1

```

I admit that I do not understand how things should work, for example how does tap know where the compiled JS files are.

**Comment by ilg-ul** [comment]
I expect the above issue preventing tests written in TS to run via `tap` to be caused by the use of ES6 modules, so I'll wait for the rewrite.

Till then, since having the tests in TS is definitely an advantage, I found a workaround: instead of pointing `tap` to the original `.ts` files, as explained in the documentation, I compiled them separately and pointed `tap` to the resulting `.js` files. It is not perfect, since the errors do not refer to the original `.ts` files, but, for a while, I can live with it.

There was another small issue with running the tests through the `ts-standard` validator, since it complained about the calls to the `test()` functions:

```console
// 030-logger-multi.ts:32
test('logger level all', (t) => {
...
}

  /Users/ilg/My Files/WKS Projects/xpack.github/npm-modules/logger-ts.git/tests/tap/030-logger-multi.ts:32:1: Promises must be awaited, end with a call to .catch, end with a call to .then with a rejection handler or be explicitly marked as ignored with the `void` operator. (@typescript-eslint/no-floating-promises)
```

Although the Tap documentation does not mention this, since TS allows top-level awaits, I used `await test(...)` and the validator no longer complained.

For completeness, initially I tested the workaround to silence the rule (with `// eslint-disable-next-line @typescript-eslint/no-floating-promises`), but I guess the `await` is preferred.

With these changes the project is now fully written in TS, compiled into `node16`, which means ES6 modules. All tests pass, including 100% coverage; as you explained, `c8` reports all files, including the tests themselves. Not a big problem, but still a small nuisance.

**Comment by ilg-ul** [comment]
After some reading, trying to understand how these things work, I managed to run `.ts` tests without having to manually compile them. (First I managed to directly run `.ts` files with `mocha`, since it is better documented, and later applied the same recipe to `tap`).

The problem resides in how `ts-node` works. The current version was updated to support ES6 modules, just that it must be explicitly instructed to use them.

To achieve this I added the following configuration in `package.json`:

```json
  "tap": {
    "check-coverage": false,
    "coverage": false,
    "files": [
      "tests/tap/*.ts"
    ],
    "node-arg": [
      "--loader=ts-node/esm"
    ],
    "reporter": "classic",
    "timeout": 30,
    "ts": true
  },
```

The magic is provided by the `node-arg` option.

With this option added, `tap` successfully runs `.ts` tests with ES6 modules, and nicely reports errors in the original files (but throws an ExperimentalWarning).

I don't know what would be the best strategy for `tap`, probably you can detect when ES modules are used and add this option automatically.

To conclude, the good news is that, except coverage (which can be done via `c8`), everything else in Tap seems functional, including running tests with ES6 modules; explicitly passing this option is acceptable until a final solution will be implemented.

**Comment by isaacs** [comment]
This is available in tap@18. `npm i tap@pre` to get it. Be sure to review the [changelog](https://node-tap.org/changelog/#18.0), a bunch of stuff has been updated.

**Comment by ilg-ul** [comment]
Thank you, Isaac.
