### ISSUE TITLE
`--test-regex` and `--ts`/`--no-ts` flags work in an unexpected way

### ISSUE THREAD

**Issue by inga-lovinde** [tapjs/tapjs#859]
From https://node-tap.org/docs/cli/:
```
  --test-regex=<pattern> A regular expression pattern indicating tests to run if
                         no positional arguments are provided.

                         (...)

                         Note that .jsx files will only be run when --jsx is
                         enabled, .ts files will only be run when --ts is
                         enabled, and .tsx files will only be run with both --ts
                         and --jsx are enabled.
```
So user's assumption here is that unless `--ts` is enabled (or if `--no-ts` is enabled), .ts files will *not* be run, and having .ts files in their project directory will not affect node-tap results.

```
  --ts                   Automatically load .ts and .tsx tests ts-node module.
                         Note: you must provide ts-node as a dependency
                         yourself, tap does not automatically bundle it.
                         (Default: false)

  --no-ts                switch off the --ts flag
```
This slightly contradicts the documentation for `--test-regex`, and unclear: is `--ts` responsible for loading .ts tests, or is it responsible for loading ts-node module?

Actual (unexpected) implementation:
* node-tap will always attempt to run .ts files;
* `--ts` and `--no-ts` flags only affect whether node-tap [will run them with ts-node](https://github.com/tapjs/node-tap/blob/v16.3.4/bin/run.js#L683-L699) or, as "js files", [with plain node](https://github.com/tapjs/node-tap/blob/v16.3.4/bin/run.js#L709-L721).

So running `tap --no-ts` in a directory that contains `.test.ts` files, results in node failing to parse .ts file as plain JS, and node-tap reporting failed test suites. Which is probably not what most users expect from `tap --no-ts`.

**Comment by isaacs** [comment]
This logic has been completely reimagined in tap v18.

`--include` is a glob (or array of path globs, really) that specifies what files will be included.  Defaults to "all the test lookin type things".

`--exclude` is the same thing, but in reverse. Anything that matches an exclude pattern won't be included.

The default extensions loaded are defined by plugins, so if you disable the `@tapjs/typescript` plugin, then it won't load ts, tsx, cts, mts, or jsx files.

The `--test-regexp` and `--ts` flags are gone.

`npm install tap@pre` to get it.
