### ISSUE TITLE
Is there any special trick to use `t.throws()` with async functions?

### ISSUE THREAD

**Issue by ilg-ul** [tapjs/tapjs#865]
I might be doing something stupid, but I could not make` t.throws()` work with async functions.

Here is a small test I did (in TypeScript, which accepts top awaits):

```
import { strict as assert } from 'node:assert'
import * as util from 'node:util'
import { test } from 'tap'

await test('throws', async (t) => {

  const syncFunc =  (flag: boolean): void => {
    if (flag) {
      assert(false)
    }
  }

  const setImmediatePromise = util.promisify(setImmediate);

  const asyncFunc = async (flag: boolean): Promise<void> => {
    if (flag) {
      assert(false)
    }
    await setImmediatePromise()
  }

  t.throws(() => { syncFunc(true) }, '1')

  t.throws(async () => { await asyncFunc(true) }, '2')

  // This might be useless or plainly wrong, but I tried it too.
  await t.throws(async () => { await asyncFunc(true) }, '3')

  try {
    await asyncFunc(true)
    t.fail('4 not ok')
  } catch (error) {
    t.pass('4 ok')
  }

  t.end()
})
```

The result is:

```
  sync and async throws
    ✓ 1
    1) 2
    2) 3
    ✓ 4 ok
```

In other words, the assertion is thrown and catched as expected by regular code, but `t.throws()` fails to identify it properly.

For now I'll use regular code to check exceptions, but, if possible, it would be nice to be able to use the more compact `t.throws()` with async functions too.

**Comment by isaacs** [comment]
You can use `t.rejects`. `t.throws` expects an immediate throw, but a failing async function returns a failing promise instead of throwing synchronously.

**Comment by ilg-ul** [comment]
Ah, ok, so this was the trick I missed.

Thank you.

If there is nothing that can be done to make `t.throws()` work with async functions directly, you can close this ticket.

**Comment by isaacs** [comment]
Yeah, I mean, async functions don't throw, so the failed assertion is technically correct 😅

**Comment by ilg-ul** [comment]
Perhaps you can make this explicit in the documentation, since the current explanation was not clear for me.
