### ISSUE TITLE
`--test-regex` not working in Windows

### ISSUE THREAD

**Issue by eemeli** [tapjs/tapjs#866]
In the repo [eemeli/yaml-types](https://github.com/eemeli/yaml-types/) I'm using TS sources in `src/`, but transpiling them to JS in `dist/` with `tsc` before running tests. To make this work, I'm using this invocation, with no `.taprc` file:
```
tap --test-regex '\.test\.js$'
```

In Linux & MacOS this works fine, but my CI tests are [failing in Windows](https://github.com/eemeli/yaml-types/actions/runs/4701499618/jobs/8337593471) with this error:
```
not ok 1 - no tests specified
```

Is `tap` supported on Windows?

**Comment by isaacs** [comment]
It is, but quotes are weird on the windows command line. I recommend using just `tap` as the command, and adding `"tap": { "test-regex": "\\.test\\.ts" }` in package.json, or put the config in a yaml .taprc file. 

Coverage with ts and esm is also somewhat broken in the current release of tap (which will be addressed in the next major, that's been my motivation to get onto yaml 2). You can see the setup I've been using [here](https://github.com/isaacs/path-scurry/blob/main/package.json) to get coverage with c8.

**Comment by eemeli** [comment]
Thank you! By moving the config to `"tap"` in package.json I was able to make it work: eemeli/yaml-types#2.
