### ISSUE TITLE
Tests not running on all files when put into npm scripts

### ISSUE THREAD

**Issue by tilleps** [tapjs/tapjs#868]
# Overview

Encountered a strange behavior of tests not running on all matched files when running the commands via npm scripts or within a separate shell script

## Working

Working commands via command line - runs all test files (Working as intended)
```sh
tap lib/**/*.test.mjs
npx tap lib/**/*.test.mjs
```

Result:
```sh
$ npx tap lib/**/*.test.mjs
 PASS  lib/first.test.mjs 18 OK 7.228ms
 PASS  lib/second.test.mjs 2 OK 28.163ms
```

## Not working

However it only matches a single file when put into `package.json` scripts (NOT working as intended):
```js
{
  "scripts": {
    "test": "tap lib/**/*.test.mjs"
  }
}
```

Result:
```sh
$ npm run test

> tap lib/**/*.test.mjs

 PASS  lib/first.test.mjs 18 OK 7.189ms
```

## Workaround

Appears to work if using the `--files` option instead of using the positional arguments
```sh
{
  "scripts": {
    "test": "tap --files=lib/**/*.test.mjs"
  }
}
```

Result:
```sh
$ npm run test

> tap --files=lib/**/*.test.mjs

 PASS  lib/first.test.mjs 18 OK 8.244ms
 PASS  lib/second.test.mjs 2 OK 28.176ms
```

## Notes

Using the following tap configuration in `package.json` to get the coverage report to work with `.mjs` files:
```js
{
  "tap": {
    "node-arg": [
      "--no-warnings",
      "--experimental-loader",
      "@istanbuljs/esm-loader-hook"
    ]
  }
}
```

**Comment by isaacs** [comment]
This smells like shell expansion confusion. What operating system and shell are you seeing this in?

**Comment by tilleps** [comment]
Right on the nose!

```sh
$ sw_vers
ProductName:		macOS
ProductVersion:		13.3.1
ProductVersionExtra:	(a)
BuildVersion:		22E772610a
```
```sh
$ echo $0
-zsh
```

### Other things that did NOT work
```js
{
  "scripts": {
    "test": "tap -- lib/**/*.test.mjs"
  }
}
```
Clearing npm cache and reinstalling
```sh
npm cache clean -f
npm install
```

## Solution

It turns out it is the way NPM run-scripts runs the commands and how macOS (OS X) behaves with glob(*).  The solution is to quote the arguments:

```sh
{
  "scripts": {
    "test": "tap 'lib/**/*.test.mjs'"
  }
}
```

https://medium.com/@jakubsynowiec/you-should-always-quote-your-globs-in-npm-scripts-621887a2a784

**Comment by isaacs** [comment]
Yeah, on macOS, sh is bash, and bash has globstar turned off by default. Glad I could help :)

**Comment by isaacs** [comment]
The explicit loader hook won't be needed in tap 18, btw. Also typescript will Just Work.
