### ISSUE TITLE
How to make .match() require all fields?

### ISSUE THREAD

**Issue by tomaszferens** [tapjs/tapjs#870]
Currently this will pass:

```ts
t.match({ id: "abcdefgh", value: "some value" }, { id: String });
```

How to make it throw because it's missing the `value` field?

**Comment by isaacs** [comment]
Next version has `t.matchOnly()` which does this. (There's also `t.matchStrict()` and `t.matchOnlyStrict()`.)

`npm i tap@pre` to get it, or just wait until we get ts-node squared away and I'll be publishing it  on `@latest`.

**Comment by isaacs** [comment]
Note: it's [semver major, and a big one](https://node-tap.org/changelog/#18.0), but a huge improvement overall.
