### ISSUE TITLE
semver 6.0.0 - 6.3.0 vulnerability

### ISSUE THREAD

**Issue by ForbiddenEra** [tapjs/tapjs#872]
```
#~: npm audit fix
npm WARN audit fix semver@6.3.0 node_modules/tap/node_modules/semver
npm WARN audit fix semver@6.3.0 is a bundled dependency of
npm WARN audit fix semver@6.3.0 tap@16.3.7 at node_modules/tap
npm WARN audit fix semver@6.3.0 It cannot be fixed automatically.
npm WARN audit fix semver@6.3.0 Check for updates to the tap package.

up to date, audited 510 packages in 904ms

43 packages are looking for funding
  run `npm fund` for details

# npm audit report

semver  6.0.0 - 6.3.0
Severity: moderate
semver vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
fix available via `npm audit fix`
node_modules/tap/node_modules/semver

1 moderate severity vulnerability

To address all issues, run:
  npm audit fix
```

overrides in my `package.json` won't work with `tap`; any other package using `semver` gets overridden fine.. 

it seems you are publishing your module with `npm_modules` included and/or `package-lock.json`, though I don't see the latter in `node_modules/tap`, but the former is, even though `node_modules/semver` exists.

please avoid publishing with your dependencies, it's not needed with `npm` and can cause issues; also, I suggest updating or overriding whichever dependency you're using that uses `semver@6.0.0`-`semver@6.3.0` to `semver@6.3.1`

thanks!!

**Comment by isaacs** [comment]
No longer an issue with version 18. `npm i tap@pre` to get it. Check out the [changelog](https://node-tap.org/changelog/#18.0) first, though, a bunch of stuff has been updated.
