### ISSUE TITLE
Extract coverage reporting from C8

### ISSUE THREAD

**Issue by isaacs** [tapjs/tapjs#877]
We're not using the cli aspects, and it's kind of bloated to have yargs and its various deps in there, when everything else in here uses jackspeak, which has conflicting versions of several things.

**Comment by isaacs** [comment]
Yeah, probably not going to do this.

Rebuilding the whole reporting system is not even nearly worth the effort, when istanbul style html reports are so nice, and all the other report styles are perfectly fine and well tested for what they do. So, definitely still going to be using istanbul, no matter what.

`istanbul-lib-report` _does_ have a mechanism for specifying that it should capture the report details to a string rather than dumping to stdout, which would be nice to use, but isn't exposed anywhere, and reimplementing everything above it so that I _can_ get access to it, is really a lot of extra code, which currently already exists in c8 and works fine.

In the end, just having yargs in the `node_modules` folder isn't so bad, and the hack of monkeypatching `stdout.write` works perfectly well, it's just a bit ugly. Not worth the trouble.

**Comment by ekynoxe** [comment]
Hi @isaacs I know this was closed, but it seems mildly related to what I'm trying to find.
I'm upgrading tap to v18 in a number of our repos and we use coverage thresholds with c8 and tap 16.
I can't find any detail in the docs about that, but I may be looking in the wrong place. Rather than create an issue straight away, I thought I'd comment here.

Would you have any pointers? and/or would prefer I open a dedicated issue?
Thanks

**Comment by isaacs** [comment]
Dedicated issue probably best.

**Comment by isaacs** [comment]
Dedicated issue would be best. 

I haven't added cov thresholds, it's 100 or nothing lol. It wouldn't be terribly hard to do, not opposed to it, just haven't had a need for it. A workaround for now would be:

```
tap blah blah blah --allow-incomplete-coverage --coverage-report=none
c8 report --temp-dir .tap/coverage (threshold args)
```

Add a new issue for cov thresholds, and I'll get to it soon. Or dive into `src/run/` in this repo and send a PR ;)

**Comment by ekynoxe** [comment]
Hi @isaacs thanks for the suggestion. This is actually not difficult to write in our test script, so no need for an extra issue. The following works well for our use case:

`tap && c8 report --check-coverage --temp-directory .tap/coverage --statements 97.67 --branches 85.71 --functions 100 --lines 97.67`

Thanks!
