### ISSUE TITLE
t.strictDeepEqual

### ISSUE THREAD

**Issue by andrewrk** [tapjs/tapjs#88]
can haz?

**Comment by ghost** [comment]
User of node-tap here. Thought deepEqual was also checking for type but figured out it doesn't so I started looking in here. Found this opened issue that confirmed my thought so digged a little. Node-tap is using deep-equal module without any options on deepEqual()'s call (see https://github.com/substack/node-deep-equal#deepequala-b-opts). Could be forked, edit and pull-requested, but node-tap repository seems quite inactive (3 pending pull requests) ...

**Comment by ghost** [comment]
Nevermind, gonna give it a try as I need it.

**Comment by isaacs** [comment]
Landed on master.  Thanks!
