### ISSUE TITLE
Mock function in a class

### ISSUE THREAD

**Issue by andreafassina** [tapjs/tapjs#887]
Hi I need to mock a function called in a class

here is the class `src/auth/auth.service.ts`
```
import { createRandomString } from '../common/utils';
import { hash } from 'bcrypt';

export class AuthService {
  async forgotPassword(user) {
    const token = createRandomString();
    const hashedToken = await hash(token, 10);
    // Save the hashed token on DB
    await this.recoveryToken.save({ token: hashedToken, userId: user.id });
    // Send email to user with NOT hashed token
    await this.mailService.sendResetPassword(user.email, token);
  }

  async resetPassword(password, token) {
    const hashedToken = await hash(token, 10);
    const exist = await this.recoveryToken.findOne({
      token: hashedToken,
    });
    if (!exist) throw new UnauthorizedException('Invalid password reset token'); // => always throw this error
   
    ....
  }
}
```

here is the `src/common/utils.ts`
```
export const createRandomString = (length = 32): string => {
  return randomBytes(length).toString('hex');
};
```

Here is the test `auth.e2e.test.ts`
```
const mockRecoveryToken = 'someRandomString';
const { AuthService } = mock('../../src/auth/auth.service', {
    '../../src/common/utils': {
    createRandomString: () => {
      console.log('called mocked createRandomString()');
      return mockRecoveryToken;
    },
  },
});
const mockAuthService = new AuthService()
await mockAuthService.forgotPassword(user);

const response = await http.post('/auth/reset-password', {
  token: mockRecoveryToken,
  password: newPassword,
});
equal(rightToken.statusCode, HttpStatus.OK); // => expected 200, actual 401
```

I can see from the console the message `called mocked createRandomString()`, but in the DB the hashed token is always different. So it seems that the mocked fn is called, but the returned value is always a random string not the mocked one.

There is something I have missed?

**Comment by isaacs** [comment]
Are you using tap 16 or 18?

It looks like you're using mockRequire, not mockImport. Since you're calling it "mock" and it's not spitting a deprecation warning at you, I'm guessing it's tap v16? This can behave weirdly if your code is compiling as ESM rather than CommonJS.

Can you add a console.log to show the randomstring that it's actually hashing? I mean, whatever is emitting that console.log in your mock, is definitely returning the known string. But that must not be the createRandomString implementation that's being called, if it's getting something different.

**Comment by andreafassina** [comment]
Yes tap 16, but nothing wrong with your package. It was a bad implementation on my side, I'm feel like a dumb.
I'm using `hash` from bcrypt and of course the hased string is always different, so I have to find the token by userId. Sorry for wasting your time

**Comment by isaacs** [comment]
No worries! Glad you figured it out :)
