### ISSUE TITLE
Document that `tap@18` drops Node.js 14 support?

### ISSUE THREAD

**Issue by s100** [tapjs/tapjs#898]
Congratulations on the release of `tap@18`!

It seems that internally `tap@18` makes use of a new package `@tapjs/core`, which [makes use](https://github.com/tapjs/tapjs/blob/37093f504984c495e2e609478429d83914658947/src/core/src/test-base.ts#L1257) of the [nullish coalescing assignment operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_assignment):

```js
extra.bail ??= this.bail
```

...which is only supported in Node.js 15+. This means that `tap@18` has now dropped support for Node.js 14. This is totally fine, it's out of LTS anyway, but I feel that this is worth documenting in the [change log for v18](https://node-tap.org/changelog/#18.0).

**Comment by isaacs** [comment]
Agreed.
