### ISSUE TITLE
`tap build` failing when adding external plugin

### ISSUE THREAD

**Issue by jasonk** [tapjs/tapjs#899]
The changes that were added in https://github.com/tapjs/tapjs/commit/ccc165ee872d1c7861972a5b0c9ba8ecfcfbea72 that were intended to fix #891 don't fix the problem.

The root cause of the problem is that there is no reason to sort the `pluginNames` array at all.  Since it's just mapping over an array that was just sorted the order of the names will be stable across builds without the sort.  If that sort changes the order of the names then the names will not match with the right plugins and cause this problem.

**Comment by isaacs** [comment]
Ahhh, yes.

What I reproduced was a _different_ bug, albeit subtly similar.

Reproducing now, fix will be out shortly, sorry about the confusion on my part.
