### ISSUE TITLE
lcov support

### ISSUE THREAD

**Issue by llafuente** [tapjs/tapjs#90]
Hi,

I found www.coveralls.io, for automatic code coverage using travis-ci. I found it pretty useful to know where your code isn't covered by tests (and it's another green icon in the readme, always a good thing :+1: )

coveralls.io use https://github.com/cainus/node-coveralls that need LCov as input, so it will be good to support LCov output

note: maybe it's already possible and I just cant find the way.

**Comment by wavded** [comment]
@llafuente I'm curious about the same thing, namely lcov support, have you found a workaround that works with node-tap?

**Comment by llafuente** [comment]
Not atm.

I'm now using: [ass](https://github.com/lloyd/ass) with node-tap
I dont know exactly how difficult it could be to generate a lcov report... but it's should be trivial...

Small tutorial

```
npm install ass@0.0.4 --save-dev
```

I recomend that version, new one require node-canvas to generate badges
1. create a javascript to run all your tests like: [code-coveraje.js](https://github.com/llafuente/class/blob/master/test/code-coverage.js)
2. add to every test file before any require

``` js
require('ass');
```
1. "npm coverage" support [package.json](https://github.com/llafuente/class/blob/master/package.json)

here you can see a [report](https://rawgithub.com/llafuente/class/master/coverage.html) for one of my projects, it's more than enough for me... and easy to setup.

**Comment by wavded** [comment]
Thanks much @llafuente, I'll check it out!

**Comment by isaacs** [comment]
Coverage will be done soon, via another package that groks and wraps child_process.spawn calls cleverly.

**Comment by ghost** [comment]
@isaacs Any news regarding this support you can share?

**Comment by rmg** [comment]
@bucaran coverage support was added when this issue was closed. There's even a section in the readme for it, including specific support for coveralls.io.

**Comment by ghost** [comment]
@rmg Sweet! Thanks.
