### ISSUE TITLE
Website stuck on v16 due to caching (service worker)

### ISSUE THREAD

**Issue by TimonVS** [tapjs/tapjs#908]
For some reason, on my laptop I keep seeing the old docs website for v16.3.1. After a hard reload, it briefly shows the website for v18, but after a refresh it's back to the old site. The same goes for "Empty cache and hard reload". I noticed that `index.html` is proxied through a service worker, which is probably the culprit. This problem doesn't occur on my phone, or in any other browser (probably because I didn't open the website before v18 was released).

<img width="2560" alt="CleanShot 2023-09-20 at 14 13 02@2x" src="https://github.com/tapjs/tapjs/assets/876666/25bebf98-b2e3-4f16-9e37-3ccd10b4237b">

https://github.com/tapjs/tapjs/assets/876666/763cfe50-21a5-42e8-9acb-b02d762b851f

[node-tap.org.har.zip](https://github.com/tapjs/tapjs/files/12672941/node-tap.org.har.zip)

**Comment by isaacs** [comment]
So weird. Maybe I can tell netlify to send some cache control headers to bust it?

**Comment by TimonVS** [comment]
It's probably a Service Worker related issue, which might not be solved by busting the cache. Maybe this will work: https://developer.chrome.com/docs/workbox/remove-buggy-service-workers/. I think you should be able to create `sw.js` hosted at `http(s)://node-tap.org/sw.js` and put the code in there. I'm not a 100% sure this will solve the problem, but I can at least check it for you :)

**Comment by isaacs** [comment]
Ah, found the culprit. The former website was using a gatsby offline plugin.

Thankfully, it uses a static URL for its service worker, and so the no-op sw.js should fix things.

I also am not using any localstorage or anything, so also set the `Clear-Site-Data: "storage"` header, which should clear it out as well, even if the sw.js isn't re-loaded.

Lmk if that fixes the site.  If so, it'll be in the next release, just need to finish up some other stuff before landing it on main.

**Comment by TimonVS** [comment]
This fixed the issue! Thank you so much! 😄

**Comment by isaacs** [comment]
Oh, thank _you_ for finding the problem, the solution, and verifying the fix 😅
