### ISSUE TITLE
pnpm cannot find builtin plugins, loaders

### ISSUE THREAD

**Issue by Ethan-Arrowood** [tapjs/tapjs#915]
Hey folks! I'm having a hard time upgrading my tap@16 to tap@18. Repo is open source: https://github.com/ethan-arrowood/socket

I've started by removing `@types/tap` and upgrading `tap` to `tap@latest` (which installs v18.1.1). Then I changed the test command to `tap run test/*.test.ts` and after running `pnpm test` I get this error:

```
❯ pnpm test

> @arrowood.dev/socket@0.0.2 test /Users/ethanarrowood/Documents/github/ethan-arrowood/socket
> tap run test/*.test.ts

node:internal/process/esm_loader:97
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@tapjs/node-serialize' imported from /Users/ethanarrowood/Documents/github/ethan-arrowood/socket/node_modules/.pnpm/@tapjs+test@1.1.0_@tapjs+core@1.1.0_@types+node@18.17.5/node_modules/@tapjs/test/test-built/dist/esm/index.js
Did you mean to import @tapjs+node-serialize@1.0.0_@tapjs+core@1.1.0/node_modules/@tapjs/node-serialize/dist/commonjs/index.js?
    at new NodeError (node:internal/errors:399:5)
    at packageResolve (node:internal/modules/esm/resolve:889:9)
    at moduleResolve (node:internal/modules/esm/resolve:938:20)
    at defaultResolve (node:internal/modules/esm/resolve:1153:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v18.16.0
 ELIFECYCLE  Test failed. See above for more details.
```

So I started adding the missing deps, after adding a number of them, the typescript never actually works. The packages I had to add (because `pnpm test` told me to are: `@tapjs/node-serialize`, `@taps/mock`, and `@tapjs/processinfo` (in that order). Afterwards, here is the typescript issue:

```
2> test/index.test.ts
/Users/ethanarrowood/Documents/github/ethan-arrowood/socket/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.17.5_typescript@5.2.2/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
test/index.test.ts(24,11): error TS2339: Property 'equal' does not exist on type 'Test<BuiltPlugins, TestBaseOpts> & BuiltPlugins'.
test/index.test.ts(35,13): error TS2339: Property 'resolveMatch' does not exist on type 'Test<BuiltPlugins, TestBaseOpts> & BuiltPlugins'.
test/index.test.ts(42,7): error TS2339: Property 'equal' does not exist on type 'Test<BuiltPlugins, TestBaseOpts> & BuiltPlugins'.
test/index.test.ts(47,13): error TS2339: Property 'resolves' does not exist on type 'Test<BuiltPlugins, TestBaseOpts> & BuiltPlugins'.
test/index.test.ts(49,13): error TS2339: Property 'rejects' does not exist on type 'Test<BuiltPlugins, TestBaseOpts> & BuiltPlugins'.
test/index.test.ts(56,7): error TS2339: Property 'equal' does not exist on type 'Test<BuiltPlugins, TestBaseOpts> & BuiltPlugins'.
test/index.test.ts(73,11): error TS2339: Property 'equal' does not exist on type 'Test<BuiltPlugins, TestBaseOpts> & BuiltPlugins'.
test/index.test.ts(85,13): error TS2339: Property 'resolves' does not exist on type 'Test<BuiltPlugins, TestBaseOpts> & BuiltPlugins'.
test/index.test.ts(86,13): error TS2339: Property 'resolves' does not exist on type 'Test<BuiltPlugins, TestBaseOpts> & BuiltPlugins'.
test/index.test.ts(88,7): error TS2339: Property 'equal' does not exist on type 'Test<BuiltPlugins, TestBaseOpts> & BuiltPlugins'.
test/index.test.ts(110,13): error TS2339: Property 'equal' does not exist on type 'Test<BuiltPlugins, TestBaseOpts> & BuiltPlugins'.
test/index.test.ts(123,15): error TS2339: Property 'resolves' does not exist on type 'Test<BuiltPlugins, TestBaseOpts> & BuiltPlugins'.
test/index.test.ts(125,15): error TS2339: Property 'resolveMatch' does not exist on type 'Test<BuiltPlugins, TestBaseOpts> & BuiltPlugins'.
test/index.test.ts(127,15): error TS2339: Property 'resolves' does not exist on type 'Test<BuiltPlugins, TestBaseOpts> & BuiltPlugins'.

    at createTSError (/Users/ethanarrowood/Documents/github/ethan-arrowood/socket/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.17.5_typescript@5.2.2/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/Users/ethanarrowood/Documents/github/ethan-arrowood/socket/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.17.5_typescript@5.2.2/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/Users/ethanarrowood/Documents/github/ethan-arrowood/socket/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.17.5_typescript@5.2.2/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/Users/ethanarrowood/Documents/github/ethan-arrowood/socket/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.17.5_typescript@5.2.2/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/Users/ethanarrowood/Documents/github/ethan-arrowood/socket/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.17.5_typescript@5.2.2/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at require.extensions.<computed> (/Users/ethanarrowood/Documents/github/ethan-arrowood/socket/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.17.5_typescript@5.2.2/node_modules/ts-node/src/index.ts:1621:12)
    at Object.newLoader [as .ts] (/Users/ethanarrowood/Documents/github/ethan-arrowood/socket/node_modules/.pnpm/pirates@4.0.6/node_modules/pirates/lib/index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12) {
  diagnosticCodes: [
    2339, 2339, 2339,
    2339, 2339, 2339,
    2339, 2339, 2339,
    2339, 2339, 2339,
    2339, 2339
  ]
}
```

I really wanna make this work (and take full advantage of the new tap version), but I'm really not sure how to fix this. Can someone help me out? Thank you ❤️

**Comment by isaacs** [comment]
You sure you got 18.1.1 and not 18.1.0? I thought I fixed that bug already, it should be requiring @tapjs/node-serialize from the `tap` package.

**Comment by isaacs** [comment]
Ohhhhhh pnpm. Ugh.

Ok, I think I know what's going on here. pnpm isolates deps, so that the dependencies of one thing don't ever see the dependencies of their parent, and I'm depending on `tap` pulling in all the things, and then all the things being able to see one another as a result. But, `@tapjs/node-serialize` (et al) aren't actually visible from the `@tapjs/test` package, because they're not listed as deps.

The good news is, I think I can make it work by just ensuring that all the default plugins are depended on by `@tapjs/test` as well. I'll try that and report back here when I get it working with pnpm.

**Comment by isaacs** [comment]
Ugh number 2, the loaders. The built Test class needs to resolve those to their full import urls, because the _runner_ needs to be able to provide an argument that node can load from the cwd, and you don't directly depend on those things, so they're not accessible.

**Comment by Ethan-Arrowood** [comment]
Ah! Yes let me know! happy to help debug if you need.

**Comment by isaacs** [comment]
Ah, and I can't do the resolution in the build script, because then the pre-built copy that ships will have paths like `/Users/isaacs/dev/tapjs/tapjs/src/mock/dist/esm/import.mjs`, so tap will only work out of the box if you're a mac user named isaacs lol

**Comment by isaacs** [comment]
Ok, yeah, verified in a pnpm project by hand-editing the built files, the following two changes will fix this:

- in `./scripts/default-build.mts` (the thing that builds the distributed `Test` class with all the default plugins), set all of the current versions of the builtin plugins as dependencies in `src/test/package.json`. This will ensure that pnpm links them to that location.
- in `src/run/src/test-args.ts`, resolve all the `--import`/`--loader` arguments to their full urls, relative to the location of the `@tapjs/test/built` module. This will resolve to either the builtin plugin (since that'll be the copy linked by pnpm into the `@tapjs/test` folder), or the version of whatever userland plugin that was installed at the top level.

Now just have to make the build scripts actually do that, and write tests for them.

**Comment by isaacs** [comment]
Ok, one other small patch did need to be made to make this work, but 18.1.3 should behave properly when installed with pnpm, provided that `typescript` is a dep at the top level, so that ts-node can find it.
