### ISSUE TITLE
Breakage between 16.x and 18.x version for .taprc

### ISSUE THREAD

**Issue by waterkip** [tapjs/tapjs#917]
My regular (every so many weeks) CI job failed for one of my modules using tap. It seems the following configuration options are no longer valid:

```
coverage: false
rcfile: .taprc
test-regex: ^t\/.*.([mc]js|[jt]sx?)$
```

No deprecation warning exists on the old options, and tests now fail. The changelog only refers to test-regexp. The other fields are not mentioned in the changelog or the documentation.

Please allow a transition period for old fields, including documentation, so users can transition without too much breakage.

**Comment by isaacs** [comment]
Adding a documentation page for transitioning from 16 would be a good idea, I'll write that up today. 

For your case, try:

```
disable-coverage: true
allow-empty-coverage: true
include:
 - t/*.@([mc]js|[jt]s?(x))
```
