### ISSUE TITLE
Disable coverage

### ISSUE THREAD

**Issue by waterkip** [tapjs/tapjs#918]
> Coverage is always generated, and less than full coverage (or no coverage) is considered a test failure

This is a very opinionated option. Please allow any author to determine this for themself.

I would like to return to the configuration option as mentioned in https://github.com/tapjs/tapjs/issues/917

**Comment by piotr-cz** [comment]
At this moment it's possible to disable coverage globally in tap 18.1.x in .taprc file with `disable-coverage: true`, but it's not possible to re-enable it back in cli with --disable-coverage=false:

```
Error: Flag --disable-coverage does not take a value, received 'false'
```

**Comment by waterkip** [comment]
It still exists with 1, so it is a failure.:

`npm run test ; echo $?` echo's 1.

You need:

```
disable-coverage: true
allow-incomplete-coverage: true
allow-empty-coverage: true
```

To have no coverage. Disable coverage should take care of that IMO. Or just `coverage: false` as in the 16.x version.

**Comment by isaacs** [comment]
You can turn off a Boolean flag with `--no-disable-coverage`

**Comment by isaacs** [comment]
> This is a very opinionated option. Please allow any author to determine this for themself.

Yes, tap is opinionated, the documentation is overwhelmingly clear about this. https://node-tap.org/#why-tap%3F

**Comment by waterkip** [comment]
Yes, and you broke this in the upgrade.

**Comment by isaacs** [comment]
@waterkip What did I break in which upgrade?

I mean, I supposed I made it less opinionated by loosening the restriction on coverage. But isn't that what you were asking for? It seems like you're dissatisfied about something, and I can't figure out what you're actually trying to say. Can you try using more words and making a specific request?
