### ISSUE TITLE
xunit/ JUnit reporter in v18

### ISSUE THREAD

**Issue by piotr-cz** [tapjs/tapjs#919]
Please consider bringing back the *JUnit* reporter which was available in tap 16.x.
This is the only unit tests report format supported by GitLab.

Reference: GitLab Docs > [Unit test reports](https://docs.gitlab.com/ee/ci/testing/unit_test_reports.html)

**Comment by piotr-cz** [comment]
I've noticed that there might be a `xunit` format type in [tap-mocha-reporter](https://github.com/tapjs/tap-mocha-reporter) and followed instructions in [CLI-Based Reporters](https://node-tap.org/reporter/#cli-based-reporters):

```shell
npm install --save-dev tap-mocha-reporter
npx tap --reporter tap-mocha-reporter --reporter-arg xunit
```

however it seems that format type is not being passed or docs example is incorrect:

```
Unknown format type: undefined

Available format types:

classic doc dot dump json jsonstream
landing list markdown min nyan progress
silent spec tap xunit
node:events:495
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_CANNOT_PIPE]: Cannot pipe, not readable
```

**Comment by piotr-cz** [comment]
I've tried to create [Custom Reporter](https://node-tap.org/writing-custom-reporters/), but failed.

I think it's a good idea create a JUnit reporter as a separate package that would serve as an example for Custom Reporters

**Comment by isaacs** [comment]
Maybe there should be a `tap-mocha-reporter` plugin that exposes all of these as valid `--reporter` options?

**Comment by isaacs** [comment]
I think it's getting confused because tmr exports a stream, but is also a bin that can be piped to. 

Maybe it'd be better to check for the bin first. If you install it globally (so it's not importable) then it works. But that's kind of a jank workaround, tbh.

**Comment by isaacs** [comment]
Created a new issue for the idea of exposing tap-mocha-reporter in some nice way. In the meantime, going to just make it prefer the executable detection over the stream type, so that at least tmr will work for you for now.

**Comment by piotr-cz** [comment]
I still think that it would be valuable to create *JUnit* reporter as a standalone package to give full example how to use [@tapjs/reporter library](https://node-tap.org/writing-custom-reporters/), perhaps utilizing Ink.

I mean [docs](https://node-tap.org/writing-custom-reporters/) are useful, but whole process is not completely straightforward.

**Comment by isaacs** [comment]
Tap 18.2 now supports `--reporter junit`. Ink is really not the best solution for this kind of report, because it's just text, so it's more straightforward to just parse the TAP and output the appropriate XML.

Some standalone ink reports would be good, though. There's a kind of tiny hello world example in the monorepo at `src/dummy-plugin`, but it's very minimal. A better test would be a standalone thing that does something actually fancy. I was considering making a `spec` style reporter as a standalone plugin, if there's demand for it.

**Comment by piotr-cz** [comment]
Thank you.
IMO best motivation to create a standalone reporter package is a need for one,
The [dummy-plugin](https://github.com/tapjs/tapjs/tree/main/src/) should be enough to start with.

**Comment by piotr-cz** [comment]
The junit reporter isn't listed as an option when using `npx tap --help`.
Source: https://github.com/tapjs/tapjs/blob/main/src/config/src/jack.ts#L311
