### ISSUE TITLE
--files CLI command does not work in v 18

### ISSUE THREAD

**Issue by Andriy-Kulak** [tapjs/tapjs#922]
Hi thanks for writing this library. 

i switched from v 16 to 18 and now my cli command `--files=./test/auth3.test.ts` does not work. I want to isolate a specific file and I am having trouble seeing any examples that work. No examples of how to get `--include` to work in the documentation either. 

filenames is still references in docs so why doesn't it work? https://node-tap.org/cli/#--files%3D%3Cfilename%3E

Can someone please assist?

**Comment by Andriy-Kulak** [comment]
ok! i figured this out. if you want to add a specific file you want to test, just add it to the end of the command and it should work. Example: `tap ./test/auth3.test.ts`

**Comment by isaacs** [comment]
Oh, if `--files` is in the docs and not implemented, then that's a bug. But yes, `tap run <file>` (or just `tap <file>` if the filename isn't a tap subcommand), will do what you want.

**Comment by isaacs** [comment]
Yeah, that's just an oversight.  `--files` does nothing.  Will correct in the next release.
