### ISSUE TITLE
Coverage info written to stdout when using junit reporter

### ISSUE THREAD

**Issue by piotr-cz** [tapjs/tapjs#929]
Steps to reproduce:

*Case 1*

```shell
npx tap --coverage-report=cobertura --reporter=junit > rspec.xml
```

Above creates valid file `./.tap/cobertura-coverage.xml`
Above creates invalid file `./rspec.xml` with contents:

```xml
<?xml version="1.0" encoding="UTF-8" ?>
cobertura report: xxx\.tap\report\cobertura-coverage.xml
<testsuites id="20230929_095243183" name="TAP Tests" tests="32" failures="0" assertions="22" skipped="0" time="9.712432">
  <!-- ... --->
</testsuites>
```

*Case 2*

```shell
npx tap --reporter=junit > rspec.xml
```

Above creates invalid file `./rspec.xml` with contents:

```xml
<?xml version="1.0" encoding="UTF-8" ?>
------------------------------|---------|----------|---------|---------|----------------------------
File                          | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s          
------------------------------|---------|----------|---------|---------|----------------------------
<!-- ... -->
<testsuites id="20230929_095353356" name="TAP Tests" tests="32" failures="0" assertions="22" skipped="0" time="9.694362">
</testsuites>
```

I think a solution could be to add an option to allow passing a file name that reporter output should written into.

**Comment by isaacs** [comment]
Hm, yes, a reporter filename would be nice for a lot of reasons. Would be good to also be able to run with the normal reporter, but output junit to a file.

Alternatively, we could _always_ write certain reporters to a known filename, like how `--coverage-report=cobertura` writes to a file.

**Comment by isaacs** [comment]
Alternatively, maybe the text coverage report should be written to stderr instead of stdout? Or have a switch for that?

**Comment by piotr-cz** [comment]
I'd prefer the filename option than text coverage as a stderr.
Saving reports to known/ default filename seems odd, as junit uses xml, while tap uses text

**Comment by isaacs** [comment]
A workaround in the meantime would be to run it once to get coverage info, then replay to output the xml.

```
tap -Rsilent ; tap replay -R junit --coverage-report=none > rspec.xml
```

The first run could be any reporter you like, it's just there to generate coverage and print that report. Could even just have it optional, or do it like this:

```
tap -R junit --coverage-report=none > rspec.xml || tap replay
```

Where the first run does no coverage report, and then the replay only happens if the first run exits with a status code (ie, if coverage is missing, tests failed, etc.)

**Comment by piotr-cz** [comment]
Thank you, adding `--reporter-file` option fixed this issue

**Comment by isaacs** [comment]
Whoa, neat trick I just realized:

```
tap --reporter-file >(tee file.out)
```

That tee can be anything, and I'm working on a module to turn ANSI into HTML for tap's docs, and found this just works:

```
tap --reporter-file >(node dist/esm/bin.mjs > output.html)
```

UNIX is fun 😄

**Comment by piotr-cz** [comment]
Yeah, Windows is not so fun
