### ISSUE TITLE
How to check presence/values of symbols used as object keys?

### ISSUE THREAD

**Issue by towerofnix** [tapjs/tapjs#930]
Consider these hypothetical `.same()` comparisons:

```js
t.same(
  {[Symbol()]: 123},
  {[Symbol()]: 123});
// -> {match: true}
// expected error because Symbol() !== Symbol()

t.same(
  {[Symbol.for('cool_symbol')]: 123},
  {[Symbol.for('cool_symbol')]: 456});
// -> {match: true}
// expected error because 123 !== 456
```

I've written "expected", but of course, that's not exactly right. Symbols *can* be used to store "hidden", internal values, which is behavior that libraries may depend on - and which test cases shouldn't need to watch out for. (Weak maps are arguably better suited for internal per-arbitrary-object storage, but that's an implementation detail up to each library author to decide.)

Still, within the scope of a given program/library/etc with full control across the lifetime of an object, it's reasonable to want to test for the presence and values stored on symbol properties of an object.

I might have overlooked something, but going over the implementation [in same.ts](https://github.com/tapjs/tapjs/blob/main/src/tcompare/src/same.ts), I didn't see anything handling symbols specially (except a check for [symbol *values*](https://github.com/tapjs/tapjs/blob/3451d284b3528f37c6f4fee8422428b13258bddb/src/tcompare/src/same.ts#L102-L103) - not applicable here). *(Edit: I'm not familiar with the updated codebase of node-tap 18, and I realized that `same.ts` doesn't itself handle walking a tested object! So, I don't know enough to comment anything for sure based on tap's source code. My bad. 😓)*

My real-world example is matching the details of an error object thrown, which is an `AggregateError` and includes errors each of which is "decorated" with a symbol value storing the index from an original array. See pseudocode illustration:

```js
export function decorateErrorWithIndex(fn) {
  return (x, index, array) => {
    try {
      return fn(x, index, array);
    } catch (error) {
      error.message = `(#${index + 1}) ${error.message}`;
      error[Symbol.for('decorate.index')] = i;
      throw error;
    }
  };
}

function mapOrThrowAggregate(array, callback) {
  const decoratedCallback = decorateErrorWithIndex(callback);
  const errors = [];
  const results = [];

  for (let index = 0; index < array.length; index++) {
    try {
      results.push(decoratedCallback(array[index], index, array));
    } catch (error) {
      errors.push(null);
    }
  }

  if (errors.length) {
    throw new AggregateError(errors, `Errors mapping items`);
  } else {
    return results;
  }
}

function assertString(value) {
  if (typeof value !== 'string') {
    throw new TypeError(`Expected string, got ${typeof value}`);
  }
}

t.throws(
  () => mapOrThrowAggregate(
    ['foo', 'bar', 123, undefined, 'baz'],
    assertString),
  {
    message: `Errors mapping items`,
    errors: [
      {
        message: /Expected string, got number/,
        [Symbol.for('decorate.index')]: 2,
      },
      {
        message: /Expected string, got undefined/,
        [Symbol.for('decorate.index')]: 3,
      },
    ],
  });
```

The above code passes as the thrown `AggregateError` does match the pattern I provided to `t.throws()`... but if I change the values associated with those `Symbol.for('decorate.index')` properties, it *still* passes. tcompare isn't checking the symbol-based keys at all, and so I don't have a way to test for the decorated indexes (read: positions of items in source array) at all - except to kludge that into the message-testing regular expression, which is very much against the principles of any decorating-utility.

As far as I can tell, the only way to verify these symbols would be... well, to check them manually:

```js
// boilerplate since t.throws() is no longer sufficient...
let caughtError;

try {
  caughtError = null;
  mapOrThrowAggregate(
    ['foo', 'bar', 123, undefined, 'baz'],
    assertString);
} catch (error) {
  caughtError = error;
}

// first perform basic match
t.same(caughtError, {
  message: `Errors mapping items`,
  errors: [
    /Expected string, got number/,
    /Expected string, got undefined/,
  ],
});

// now check symbol properties manually
t.equal(caughtError?.errors?.[0]?.[Symbol.for('decorate.index')], 2);
t.equal(caughtError?.errors?.[1]?.[Symbol.for('decorate.index')], 3);
```

Apart from artificially ballooning the planned assertion count (or using a subtest), the boilerplate (no `t.throws()` anymore) and optional chaining (lest the test itself crash) are not great to work with. This also has poor diff output. And as usual, above is only demonstrative pseudocode - the real test case looks more like:

```js
t.throws(
  () => withPropertiesFromObject({
    object: input.value([['abc', 1], ['def', 2], [123, 3]]),
    properties: input.value(['abc', 'def', 123]),
  }),
  {message: `Errors in input options passed to withPropertiesFromObject`, errors: [
    {message: 'object: Expected an object, got array'},
    {message: 'properties: Errors validating array items', errors: [
      {
        [Symbol.for('hsmusic.sugar.index')]: 2,
        message: /Expected a string, got number/,
      },
    ]},
  ]});
```

...and would be comparably more painful to check manually!

I don't mind if there's no clear way forward at the moment, but I wanted to share this summary and example of using symbols as keys and where current testing utilities (as far as I can tell) fall short.

**Comment by isaacs** [comment]
Indeed, this is a shortcoming. The code that tcompare evolved out of predates the `Symbol` type, and I've just never had a use for comparing against them since usually symbol properties are effectively private properties, but it's definitely worth doing.

I'll get it into the 18.4 version today, with an opt-in `t.compareOptions = { includeSymbols: true }` to use it.  One question, are these symbols enumerable properties?  If not, then we'll have to add another flag to tell it to include non-enumerable properties in the comparison.

**Comment by towerofnix** [comment]
That's awesome, thanks a bunch for the quick response and integration into next release!

Yes, the particular properties in question are enumerable (as they're just set with bog-standard `foo[symbol] = value` syntax). I imagine it'll save someone's butt one day to support a non-enumerable properties comparison as well, but that wouldn't be needed for the test cases I'm working on now.

**Comment by isaacs** [comment]
Actually, playing with this a bit, since it's only pulling enumerable hasOwn properties by default, I think just including symbols always is the better default, so no need for an `includeSymbols` compare option.  As you wrote up top, that's the expected behavior, strings and symbols should just be equivalently handled.

By way of convenience, since I'm in there, should loose matching (ie, `t.match()`, but not `t.same()` or `t.has()`) consider `Symbol('x')` and `Symbol.for('x')` to be a match? That'd be useful if you wanted to verify symbol properties where the symbol isn't exported. It's a bit weird, though, because for example you can't do anything like that to match string property keys against a regexp or something, they just have to match exactly.

**Comment by towerofnix** [comment]
Thanks again!

That's interesting to think about. In principle I think it makes sense, but yeah, it's a little limited... and it's possibly an unexpected "gotcha" to be aware of when deciding whether `t.same()` or `t.match()` is appropriate for the test you're working on. (That goes in either direction. It's easily explainable - `same` gets stricter comparisons than `match` - but is just a detail that isn't very obvious.)

It reminds me of situations where I want to check that a value is an instance of a particular constructor *and* has particular property values - values which need to be matched by regular expression or object pattern. Mainly with thrown errors, again, as in matching an error with a regex `message` and another error-pattern `cause` *and* is specifically a `TypeError`. But it applies for similar situations, like "this should be a `Duck`, *and* its name should be `/Jeremy/i` and its number of children `4`".

The symbol situation a little closer to, say, "the `typeof` this value is `string` *and* its `length` is `14`". We're looking for "the `typeof` this value is `symbol` *and* its `description` matches `/^my ( cool){2,} regexp?$/i`". Honestly, I don't know if it's exactly possible to perform "loose" matches like this in the first place, since strings are primitives and `'foo' instanceof String === false`... but I figure, whatever answer would work for the string situation, would probably also work for symbols! And offer a whole lot more dynamism within pattern-based matching, instead of focusing too hard on special-case capabilities for `Symbol` vs `Symbol.for`. (Special-case capabilities that you, as a prospective test reader/writer, just have to memorize 🙀)

But there's always an argument to be made that that kind of dynamic capability is better suited for individual assertions. I generally disagree - deep optional chaining isn't pretty :) - but I'm also personally prone to introducing complexity into systems/syntax that benefitted from being simple. Sometimes that's an okay priority to shift away from, doing so raises the bar for thoroughly understanding whatever is going on - worth being aware of for unit tests, where a major goal is being super clear to understand (and thus debug).

(I'd make that same argument against custom behavior for symbol matching in `t.same` vs `t.match`. I figure, if you're going to introduce complexity, it should be as much "learn once, apply many times" as the opportunity provides - heightening the learning-floor as minimally as possible, at the same time as making the capability-ceiling rise, relatively, far higher up!)
