### ISSUE TITLE
t.plan plus t.resolves (or t.rejects) causes "test assertion after Promise resolution" error

### ISSUE THREAD

**Issue by ekynoxe** [tapjs/tapjs#937]
With tap >= 18.0.0 we have issues in our repositories which can be boiled down to these minimal cases:

```
import tap from 'tap'
tap.test('fails resolve', async t => {
  t.plan(1)
  await t.resolves(new Promise(r => setTimeout(r, 1000)))
})
```

```
> fails resolve > test assertion after Promise resolution
```

```
import tap from 'tap'
tap.test('fails reject', async t => {
  t.plan(1)  
  await t.rejects(Promise.reject(() => new Error('should reject')))
})
```

```
> fails reject > test assertion after Promise resolution
```

With tap 16.3.8, both tests above pass successfully.

**Comment by isaacs** [comment]
Thanks for the repro! I'll take a look today.

**Comment by isaacs** [comment]
Ok, got a test for this that goes through every possible combination of plan, promise return, and explicit end(), and found some cases where it's getting confused. Will be fixed in next release.

**Comment by ekynoxe** [comment]
Thanks @isaacs !
