### ISSUE TITLE
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'tap-yaml' 

### ISSUE THREAD

**Issue by sinedied** [tapjs/tapjs#939]
I just updated to tap@18.4.2, and now I get this error when trying to run my tests:

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'tap-yaml' imported from /Users/sinedied/projects/azure-search-open-ai-javascript/node_modules/@tapjs/config/dist/esm/index.js
```

This seems to come from the `@tapjs/config` module, and looking at its package.json it seems that the `tap-yaml` dependency is missing even though it's using it.

**Comment by sinedied** [comment]
`tap-parser` also seems to be missing BTW.

If I `npm -D tap-yaml tap-parser` then it works, but looking at the docs it doesn't seems that adding these manually should be needed.

**Comment by isaacs** [comment]
Ah, yeah, I need to add a check that it's got all the internal deps set up. I'm guessing you're using pnpm?

**Comment by sinedied** [comment]
No, I'm using regular NPM (v9.8.1)

**Comment by isaacs** [comment]
Ok, well, that's weird then. 🤔 

What does this output?

```
npm ls @tapjs/config @tapjs/test
```

**Comment by isaacs** [comment]
This looks to be a symptom related to #940. If the fix for that issue doesn't fix this as well, then the dependency declarations made and enforced in 15c924e2 should address it.

**Comment by sinedied** [comment]
> Ok, well, that's weird then. 🤔
> 
> What does this output?
> 
> ```
> npm ls @tapjs/config @tapjs/test
> ```

```
npm ls @tapjs/config @tapjs/test
azure-search-openai-javascript@1.0.0 /Users/sinedied/projects/azure-search-open-ai-javascript
└─┬ search@1.0.0 -> ./packages/search
  ├─┬ @tapjs/nock@3.1.7
  │ └─┬ @tapjs/core@1.3.7
  │   └── @tapjs/test@1.3.7
  └─┬ tap@18.4.2
    ├─┬ @tapjs/core@1.3.6
    │ └── @tapjs/test@1.3.6 deduped
    ├─┬ @tapjs/run@1.4.2
    │ ├─┬ @tapjs/config@2.4.2
    │ │ └── @tapjs/test@1.3.6 deduped
    │ ├─┬ @tapjs/reporter@1.3.2
    │ │ ├── @tapjs/config@2.4.2 deduped
    │ │ └── @tapjs/test@1.3.6 deduped
    │ └── @tapjs/test@1.3.6 deduped
    └── @tapjs/test@1.3.6
```

**Comment by sinedied** [comment]
~~Sorry but this should be reopened, #940 is completely different issue altogether.~~

I currently solved that one by removing ALL `tap` dependencies first in my NPM workspace, them reinstalling it.
It turned out that the update from tap@16 to tap@18 in a monorepo caused the issue.
