### ISSUE TITLE
Support tsconfig with moduleResolution: node10 

### ISSUE THREAD

**Issue by npdev453** [tapjs/tapjs#943]
I sometime need to integrate tests with `tapjs` into legacy project that isn't ready for modern configs like:
```ts
        "module": "Node16",
        "moduleResolution": "Node16",
```
and it's stuck with older settings:
```ts
        "module": "CommonJS",
        "moduleResolution": "node",
```

I've tried various approaches (that I can found here in issues): multiple tsconfigs (.json + .build.json), different configs, version and etc. 
But I encounter issues with every combination: or `eslint` goes broken, or `tapjs` types was missed, or `node-fetch@3` starting to be no-able-to-`require` `esm` module, or `vscode` started to miss types...

What frustrates me the most is that a testing library should be able to function in any project without being locked to specific versions or config. This constraint makes integration more challenging.

**Comment by isaacs** [comment]
It should be able to load perfectly fine with those settings.  When you `require()`, node gets the module from the `exports.$path.require`, and tsc (thinking it's node 10 lol) will resolve types using the top level `main` and `types` fields, which point to the same files.

What actually happens? What command are you running, with what specific configs, and what error occurs? A minimal repro would be helpful.

**Comment by npdev453** [comment]
> It should be able to load perfectly fine with those settings. When you `require()`, node gets the module from the `exports.$path.require`, and tsc (thinking it's node 10 lol) will resolve types using the top level `main` and `types` fields, which point to the same files.
> 
> What actually happens? What command are you running, with what specific configs, and what error occurs? A minimal repro would be helpful.

Sure, https://github.com/npdev453/repro-tapjs-943-legacy

Build output (`tsc`)

```ts
[3:52:12 AM] File change detected. Starting incremental compilation...

node_modules/@tapjs/core/dist/commonjs/tap.d.ts:15:10 - error TS2305: Module '"@tapjs/test"' has no exported member 'Test'.

 import { Test, TestOpts } from '@tapjs/test';
 ...
```

Lint output: (eslint)

```
> repro-tapjs-943-legacy@1.0.0 repro:eslint
> eslint ./src

./repro-tapjs-943-legacy/src/helper.spec.ts
   5:6  error  Unsafe member access .test on an `any` value   @typescript-eslint/no-unsafe-member-access
   5:6  error  Unsafe call of an `any` typed value            @typescript-eslint/no-unsafe-call
  10:5  error  Unsafe member access .equal on an `any` value  @typescript-eslint/no-unsafe-member-access
  10:5  error  Unsafe call of an `any` typed value            @typescript-eslint/no-unsafe-call
  11:5  error  Unsafe member access .end on an `any` value    @typescript-eslint/no-unsafe-member-access
  11:5  error  Unsafe call of an `any` typed value            @typescript-eslint/no-unsafe-call
```

Vscode view: 
![image](https://github.com/tapjs/tapjs/assets/1401931/c38bbc80-9371-43c7-bbfa-607be3204174)

\+ eslint-vscode: 
![image](https://github.com/tapjs/tapjs/assets/1401931/b58cc6a6-ad0b-4afb-b5ea-c1e4e17506f6)

**Comment by npdev453** [comment]
@isaacs, wow, thanks for efficiency! 

When it will be released? Will try it soon when it happens

**Comment by npdev453** [comment]
@isaacs, seems like was not fixed.

updated to 18.4.4 in 
 https://github.com/npdev453/repro-tapjs-943-legacy
 
The same errors as before.

**Comment by isaacs** [comment]
Ah, it's not exporting the types, that's weird. The main is getting found now, but it's failing to pull in the re-exported `BuiltPlugins` types.

As a temporary workaround, `"skipLibCheck": true` will make it build, but the huge downside is that it doesn't infer any of the types properly, so 

![Screenshot 2023-10-08 at 22 32 23](https://github.com/tapjs/tapjs/assets/9287/af7114a8-4a29-4159-aeed-f418891e8cd8)

Looking into it.

**Comment by npdev453** [comment]
Know, but `"skipLibCheck": false` was added specially to highlight problem more concentrically. Autocomplete - is ours all.

(also, ESlint and CI will not happy)

**Comment by npdev453** [comment]
@isaacs 
works, thanks!
