### ISSUE TITLE
Document .tap folder

### ISSUE THREAD

**Issue by Eomm** [tapjs/tapjs#944]
The new tap 18 creates a new `.tap/` folder that is not documented:

<img width="317" alt="image" src="https://github.com/tapjs/tapjs/assets/11404065/17fe358c-35f7-42b1-bcdc-59051030316c">

The only reference I found was about `.tap/test-results/test/<*>.tap`

https://node-tap.org/cli/#-d%3Cdir%3E---output-dir%3D%3Cdir%3E

The changelog should suggest adding this folder to the `.gitignore` - is that correct?

**Comment by isaacs** [comment]
Good call. I'll write up a doc on this. When it was just coverage, it didn't seem too relevant, but more stuff has found it's way there

And yes, safe to .gitignore, probably a good idea in fact.
