### ISSUE TITLE
Offer a search functionality in test documentation website

### ISSUE THREAD

**Issue by aleccool213** [tapjs/tapjs#963]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the `CONTRIBUTING` guide on posting issues, and `CODE_OF_CONDUCT`?

- [X] yes I read the things

### Description

The docs are quite large now and it would be great to have search. I have trouble finding things.

Example:

<img width="1911" alt="image" src="https://github.com/tapjs/tapjs/assets/6475934/9c16f909-e8ba-44d3-9395-b8cbbceaf2b8">

### Example

```js
// put some example code here
```

**Comment by isaacs** [comment]
I agree, they're getting a bit unwieldy. Patch welcome, if there's a search that's easy to plug into a static eleventy site.
