### ISSUE TITLE
[BUG] `tap` exiting with exit code 1 and error "incomplete coverage"

### ISSUE THREAD

**Issue by paambaati** [tapjs/tapjs#969]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the `CONTRIBUTING` guide on posting bugs, and `CODE_OF_CONDUCT`?

- [X] yes I read the things

### This issue exists in the latest tap version

- [X] I am using the latest tap

### Description

See a failing run at https://github.com/paambaati/codeclimate-action/actions/runs/6748416570/job/18346690857?pr=707

Coverage fails with an exit code 1 – I'm unsure if this is because coverage is not 100%. I'm inclined to think this is the case, as I'm seeing this in the changelog for tap 18 –

> _(From https://node-tap.org/changelog/#configuration)_
>
> Coverage is always generated, and less than full coverage (or no coverage) is considered a test failure.

If this is the case, how do I allow coverage thresholds (now that all of those options have been removed)? Ideally there's a point of diminishing returns once coverage cross 60%-70%, and the amount of time it takes to bring coverage to 100% is not worth it for most codebases. It would be very nice to have configurable thresholds like how the old `tap` did.

### Reproduction

1. Clone the repo + branch at [paambaati/codeclimate-action@test/use-tap](https://github.com/paambaati/codeclimate-action/tree/test/use-tap?rgh-link-date=2023-11-01T10%3A42%3A34Z)
2. Install all dependencies with `npm install`
3. Run tests and generate coverage with `npm run coverage`
4. See the error occuring –

```
# ERROR: incomplete statements coverage (83.07%)
# ERROR: incomplete branches coverage (64.19%)
# ERROR: incomplete functions coverage (78.57%)
# ERROR: incomplete lines coverage (83.07%)
# { total: 22, pass: 19, skip: 3 }
# time=1621.491ms
```

### Environment

```
$ which tap
tap not found

$ npm ls tap
tap@18.5.6

$ npx tap versions
tap: 18.5.6
"@tapjs/config": 2.4.12
"@tapjs/core": 1.4.5
"@tapjs/run": 1.4.13
"@tapjs/stack": 1.2.7
"@tapjs/test": 1.3.16
tap-parser: 15.3.1
tap-yaml: 2.2.1
tcompare: 6.4.4
plugins:
  "@tapjs/after": 1.1.16
  "@tapjs/after-each": 1.1.16
  "@tapjs/asserts": 1.1.16
  "@tapjs/before": 1.1.16
  "@tapjs/before-each": 1.1.16
  "@tapjs/filter": 1.2.16
  "@tapjs/fixture": 1.2.16
  "@tapjs/intercept": 1.2.16
  "@tapjs/mock": 1.2.14
  "@tapjs/node-serialize": 1.2.5
  "@tapjs/snapshot": 1.2.16
  "@tapjs/spawn": 1.1.16
  "@tapjs/stdin": 1.1.16
  "@tapjs/typescript": 1.3.5
  "@tapjs/worker": 1.1.16

$ npx tap config list
# vim: set filetype=yaml :
color: true
coverage-report:
  - text
exclude:
  - "**/@(fixture*(s)|dist)/**"
include:
  - "**/@(test?(s)|__test?(s)__)/**/*.@(js|cjs|mjs|tap|cts|jsx|mts|ts|tsx)"
  - "**/*.@(test?(s)|spec).@(js|cjs|mjs|tap|cts|jsx|mts|ts|tsx)"
  - "**/test?(s).@(js|cjs|mjs|tap|cts|jsx|mts|ts|tsx)"
jobs: 6
reporter: base
snapshot-clean-cwd: true
timeout: 30

$ npx tap plugin list
@tapjs/after
@tapjs/after-each
@tapjs/asserts
@tapjs/before
@tapjs/before-each
@tapjs/filter
@tapjs/fixture
@tapjs/intercept
@tapjs/mock
@tapjs/node-serialize
@tapjs/snapshot
@tapjs/spawn
@tapjs/stdin
@tapjs/typescript
@tapjs/worker

$ npm ls ts-node
ts-node@10.9.1

$ npm ls typescript
├─┬ @openpgp/web-stream-tools@0.0.14
│ └── typescript@5.2.2 deduped
├─┬ tap@18.5.6
│ └─┬ @tapjs/test@1.3.16
│   ├─┬ @isaacs/ts-node-temp-fork-for-pr-2009@10.9.5
│   │ └── typescript@5.2.2 deduped
│   ├─┬ tshy@1.7.0
│   │ └── typescript@5.2.2 deduped
│   └── typescript@5.2.2 deduped
├─┬ ts-node@10.9.1
│ └── typescript@5.2.2 deduped
└── typescript@5.2.2

$ uname -a
Darwin Wintermute 22.6.0 Darwin Kernel Version 22.6.0: Wed Oct  4 21:26:43 PDT 2023; root:xnu-8796.141.3.701.17~4/RELEASE_ARM64_T8112 arm64
```

**Comment by paambaati** [comment]
Note that the `--allow-incomplete-coverage` flag seems to have no effect on the output or the exit code.

**Comment by isaacs** [comment]
>  Ideally there's a point of diminishing returns once coverage cross 60%-70%, and the amount of time it takes to bring coverage to 100% is not worth it for most codebases.

I could not possible disagree more strongly with this.

Coverage _increases_ in value dramatically as it approaches 100%. Dropping from 100% to 99.9% indicates a much more significant slip than dropping from 80% to 60%, as it indicates that now there is untested code, whereas before there was not.

If you are using `--disable-coverage`, then you must use `--allow-missing-coverage` as well. If you are setting `--no-disable-coverage` (as in your test run) but it is not fully covered, then you must add `--allow-incomplete-coverage`.

When I use these options with the repo linked, it works as intended:

```
$ tap --disable-coverage --allow-empty-coverage -Rsilent && echo ok
ok

$ tap --allow-incomplete-coverage --coverage-report=none -Rsilent && echo ok
ok
```

**Comment by paambaati** [comment]
Fair enough, I'll close this issue.
