### ISSUE TITLE
[BUG] ts-node used in first test execution even if not requested

### ISSUE THREAD

**Issue by alebianco** [tapjs/tapjs#974]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the `CONTRIBUTING` guide on posting bugs, and `CODE_OF_CONDUCT`?

- [X] yes I read the things

### This issue exists in the latest tap version

- [X] I am using the latest tap

### Description

I'm trying to setup a typescript project with tap to use tsx as a module loader and I encountered a few issues. In general I found a workaround for all problems so far, but the experience is not very straightforward

The main problem is that the first text execution (after a clean dependencies install) seems to be different to the following executions. This presents a challenge especially for CI environments

I documented the whole setup, issues and workarounds in the attached repo

### Reproduction

https://github.com/alebianco/tap-configuration-issues

### Environment

```
which tap

/Users/me/Workspace/alebianco/test/node_modules/.bin/tap

npm ls tap

tap-configuration-issues@1.0.0 /Users/abianco/Desktop/test
└── tap@18.5.8

tap versions

tap: 18.5.8
"@tapjs/config": 2.4.13
"@tapjs/core": 1.4.5
"@tapjs/run": 1.4.15
"@tapjs/stack": 1.2.7
"@tapjs/test": 1.3.16
tap-parser: 15.3.1
tap-yaml: 2.2.1
tcompare: 6.4.4
plugins:
  "@tapjs/after": 1.1.16
  "@tapjs/after-each": 1.1.16
  "@tapjs/asserts": 1.1.16
  "@tapjs/before": 1.1.16
  "@tapjs/before-each": 1.1.16
  "@tapjs/filter": 1.2.16
  "@tapjs/fixture": 1.2.16
  "@tapjs/intercept": 1.2.16
  "@tapjs/mock": 1.2.14
  "@tapjs/node-serialize": 1.2.5
  "@tapjs/snapshot": 1.2.16
  "@tapjs/spawn": 1.1.16
  "@tapjs/stdin": 1.1.16
  "@tapjs/typescript": 1.3.5
  "@tapjs/worker": 1.1.16

tap config list

# vim: set filetype=yaml :

# from .taprc
include:
  - "**/@(test?(s)|__test?(s)__)/**/*.ts"
  - "**/*.@(test?(s)|spec).ts"
  - "**/test?(s).ts"
node-arg:
  - --import=tsx
plugin:
  - "!@tapjs/typescript"

# env, cli, and defaults
color: true
coverage-report:
  - text
exclude:
  - "**/@(fixture*(s)|dist)/**"
jobs: 6
reporter: base
snapshot-clean-cwd: true
timeout: 30

tap plugin list

@tapjs/after
@tapjs/after-each
@tapjs/asserts
@tapjs/before
@tapjs/before-each
@tapjs/filter
@tapjs/fixture
@tapjs/intercept
@tapjs/mock
@tapjs/node-serialize
@tapjs/snapshot
@tapjs/spawn
@tapjs/stdin
@tapjs/worker

# if using typescript:
npm ls @isaacs/ts-node-temp-fork-for-pr-2009

tap-configuration-issues@1.0.0 /Users/abianco/Desktop/test
├── @isaacs/ts-node-temp-fork-for-pr-2009@10.9.5
└─┬ @tapjs/test@1.3.16
  ├── @isaacs/ts-node-temp-fork-for-pr-2009@10.9.5 deduped
  └─┬ @tapjs/typescript@1.3.5
    └── @isaacs/ts-node-temp-fork-for-pr-2009@10.9.5 deduped

npm ls typescript

tap-configuration-issues@1.0.0 /Users/abianco/Desktop/test
├─┬ @isaacs/ts-node-temp-fork-for-pr-2009@10.9.5
│ └── typescript@5.2.2
└─┬ @tapjs/test@1.3.16
  ├─┬ tshy@1.8.0
  │ └── typescript@5.2.2 deduped
  └── typescript@5.2.2 deduped

uname -a

Darwin xxxxxxxxxx.homenet.telecomitalia.it 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:12 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T8103 arm64 arm Darwin

```

**Comment by alebianco** [comment]
this also might relate to #965 since @tapjs/esbuild-kit cannot be used with recent versions of node (above 18 I think) and I had to rely to configure tsx as a loader manually through node-args

**Comment by isaacs** [comment]
You shouldn't need to add those extra deps directly. Just need to resolve the modules with the proper parentURL set.

**Comment by alebianco** [comment]
thank you for the very quick feedbacks

do you expect this to also solve the difference between the first execution, where ts-node is added to the list of loaders, and the following ones?

**Comment by alebianco** [comment]
everything work beautifully ❤️ thank you

**Comment by isaacs** [comment]
I'll dig into the loaders and make sure it's not adding ts-node when it shouldn't.

**Comment by alebianco** [comment]
any extra check is welcome ... but I just tried my reproduction project against the current main branch and it looks like that behaviour got solved

I only removed @tapjs/test and @isaacs/ts-node-temp-fork-for-pr-2009 from my project dependencies and now the test spawn command seems identical every time

**Comment by isaacs** [comment]
Cool, I'll close then :)

My suspicion is that you actually had two copies of `@tapjs/test`, each built with different plugin sets.

**Comment by alebianco** [comment]
It might be, I remember seeing more than a copy in the .pnpm folder ... and that would explain why the change fixes the problem

I'll try again tomorrow the older version to see if I can verify that

Thanks again 👍

**Comment by isaacs** [comment]
Oh, by the way, this might be handy for you:

```
tap plugin rm @tapjs/typescript
tap plugin add @tapjs/tsx
```

Then you should be able to get rid of the `--node-arg` options you added manually.
