### ISSUE TITLE
Tap [BUG] <title>

### ISSUE THREAD

**Issue by shipcommit** [tapjs/tapjs#975]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the `CONTRIBUTING` guide on posting bugs, and `CODE_OF_CONDUCT`?

- [X] yes I read the things

### This issue exists in the latest tap version

- [X] I am using the latest tap

### Description

I've been experiencing a timeout error whenever I try to run a test.

It doesn't seem like disconnecting from my database, or using `t.end()` makes a difference.

The test itself is successful, but then it continues after the database is disconnected until timeout

### Reproduction

**project.test.js**:

```
import { test } from 'tap';
import build from '../app.js';
import { faker } from '@faker-js/faker';
import { disconnectTestDb } from '../server.test.js';

// [Route] - /project/new-project
// [Scenario] - Valid data
test('/project/new-project, valid data', async (t) => {
  const fastify = build();

  const name = faker.company.name();

  t.teardown(() => fastify.close());

  t.teardown(async () => {
    await fastify.close();
    await disconnectTestDb(); // Close the database connection
  });

  const response = await fastify.inject({
    method: 'POST',
    url: '/project/new-project',
    payload: { name: name },
  });

  t.equal(response.statusCode, 201);
  t.equal(response.headers['content-type'], 'application/json; charset=utf-8');

  const json = response.json();
  t.equal(json.name, name);
  console.log('json:', json);

  t.end();
});
```

I assume the issue is somewhere in the test, or that I need to handle the database disconnect differently.

**server.test.js**:

```
import Fastify from 'fastify';
import pinoPretty from 'pino-pretty';
import mongoose from 'mongoose';
import dotenv from 'dotenv';
dotenv.config({ path: '.env.test' });

// Connect to MongoDB
export const connectTestDb = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);

    console.log('MongoDB Connected...');
  } catch (err) {
    console.error(err.message);

    // Exit process with failure
    process.exit(1);
  }
};

await connectTestDb();

// Disconnect from MongoDB
export const disconnectTestDb = async () => {
  try {
    await mongoose.disconnect();
    console.log('MongoDB Disconnected...');
  } catch (err) {
    console.error(err.message);
    process.exit(1); // Exit process with failure
  }
};

const stream = pinoPretty({
  colorize: true,
  translateTime: 'SYS:standard',
  ignore: 'pid,hostname',
});

const fastify = Fastify({
  logger: {
    level: 'info',
    stream: stream,
  },
});

// Run the server
fastify.listen({ port: 3000 }, function (err, address) {
  if (err) {
    fastify.log.error(err);
    process.exit(1);
  }
});

```

Output:
![Output](https://res.cloudinary.com/fredrikaurdal/image/upload/c_pad,b_auto:predominant,fl_preserve_transparency/v1700411407/Skjermbilde_2023-11-19_172832_hcwh0h.jpg?_s=public-apps)

### Environment

tap@18.6.1
Microsoft Windows NT 10.0.22631.0 x64

I can't get all of the commands to work, but I haven't installed anything else than tap via npm.

**Comment by isaacs** [comment]
The thing that's hanging is your fastify server listening on port 3000. You need to close that at some point.

**Comment by shipcommit** [comment]
You are correct, much appreciated.
