### ISSUE TITLE
[FEATURE] @tapjs/assets with builtin node test runner

### ISSUE THREAD

**Issue by qwelias** [tapjs/tapjs#977]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the `CONTRIBUTING` guide on posting issues, and `CODE_OF_CONDUCT`?

- [X] yes I read the things

### Description

Love tap, but I would also love an option of using same assertions in builtin node test runner for simpler/lightweight cases.

Would be great to have a streamlined way of integrating tap's assertions with it and potentially other submodules like snapshots.

**Comment by isaacs** [comment]
Just write your tests like you do normally, importing tap as a dev dependency, and then run them with `node --test`.

If you want tap's assertion lib to be available in node:test, that's a feature request for node, not for tap.

**Comment by isaacs** [comment]
Oh, one other thing I guess: if you just want the behavior that drives `t.same`, `t.match` etc, with the diffs and whatnot, that's all done by the `tcompare` library. You can use that and do:

```ts
import { match } from 'tcompare'
import { test } from 'node:test'

test(() => {
  const { ok, diff } = match(object, expect)
  if (!ok) {
    console.error(diff)
    throw new Error('fail')
  }
})
```

**Comment by qwelias** [comment]
Yeah that's more like it, I'm suggesting to have some glue code for integrating `tcompare` with node's native test seamlessly, without have to explicitly use `ok`, `diff`, and `throw`.

Are you opposed to the idea of managing this glue code here as part of `tapjs` project (one of `@tapjs/` modules)?

**Comment by isaacs** [comment]
To be honest, I'd rather not maintain such a thing, since I already am maintaining tap, and don't use the node:test framework. But I'm excited to see what you come up with ;)
