### ISSUE TITLE
typescript alias support

### ISSUE THREAD

**Issue by ibnumusyaffa** [tapjs/tapjs#993]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the `CONTRIBUTING` guide on posting issues, and `CODE_OF_CONDUCT`?

- [X] yes I read the things

### Description

Hi, thanks for great libs

any plan to support typescript alias ? or maybe any typescript plugin with tsx https://github.com/privatenumber/tsx (alias support by default) instead of ts-node/esm

here some example code with alias path

### Example

```js
import t from "tap"
import { doSomething } from "@/features/hello.js"
t.test("this is a child test", (t) => {
  t.pass("this passes")
  t.equal(false, doSomething())
  t.end()
})

```

**Comment by ibnumusyaffa** [comment]
my bad, tsx plugin already exist

**Comment by ibnumusyaffa** [comment]
my bad, tsx plugin already exist

**Comment by thedevbirb** [comment]
Hey I'm in the same situation where I want to use path aliases, how did you exactly solved this?

**Comment by ibnumusyaffa** [comment]
just uninstall @tapjs/typescript plugin and replace with @tapjs/tsx
