### ISSUE TITLE
[QUESTION/BUG?] How can I set properties into t.context?

### ISSUE THREAD

**Issue by ValchanOficial** [tapjs/tapjs#994]
Before(16.3.4):
There is a function that creates a server to be used during testing
```
...
const mongo = await MongoMemoryServer.create()
t.context.mongo = mongo
...
```

Now(18.6.1):
`Cannot set properties of null`
How can I use mongo inside tests?

**Comment by isaacs** [comment]
I think this might be the same issue as #981, keeping open for now until I can determine it.

But `t.context` should probably default to a null-prototype object instead of `undefined`.

**Comment by isaacs** [comment]
For now, I think you can do `t.context = { mongo: await MongoMemoryServer.create() }` and that might work fine.
