### ISSUE TITLE
[BUG] "tap": "^18.6.1"  Error: Cannot find module node_modules\tap\bin\tap.js'

### ISSUE THREAD

**Issue by Dnkfff** [tapjs/tapjs#995]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the `CONTRIBUTING` guide on posting bugs, and `CODE_OF_CONDUCT`?

- [X] yes I read the things

### This issue exists in the latest tap version

- [X] I am using the latest tap

### Description

node version is LTS for today and look at this. May it is the problem with CI\CD you are having on the main branch of repository?
![image](https://github.com/tapjs/tapjs/assets/56574536/bdb5cf7f-62f5-488d-b0b9-7c6ea8611f86)

### Reproduction

![image](https://github.com/tapjs/tapjs/assets/56574536/1bfe7a4d-cd8d-498e-aa72-3e49dff07dcc)

### Environment

```
which tap
npm ls tap
tap versions
tap config list
tap plugin list
# if using typescript:
npm ls @isaacs/ts-node-temp-fork-for-pr-2009
npm ls typescript
# posix:
uname -a
# windows (in powershell)
"$([Environment]::OSVersion.VersionString) $(('x86', 'x64')[[Environment]::Is64BitOperatingSystem])"
```

**Comment by isaacs** [comment]
This is a bug with the `mkpath`. Look in `./package.json`, and you'll find something like this:

```json
{
  "scripts": {
    "test": "node node_modules/tap/bin/tap.js ./test/*.js"
  }
}
```

Change that to:

```json
{
  "scripts": {
    "test": "tap ./test/*.js"
  }
}
```

and it'll work.

In general, it's not a good idea to poke into the internals of your dependencies.

**Comment by Dnkfff** [comment]
Thank you very much!
