### ISSUE TITLE
[BUG] tap 18 fails to run tests with esm loader

### ISSUE THREAD

**Issue by bizob2828** [tapjs/tapjs#996]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the `CONTRIBUTING` guide on posting bugs, and `CODE_OF_CONDUCT`?

- [X] yes I read the things

### This issue exists in the latest tap version

- [X] I am using the latest tap

### Description

We are trying to upgrade to tap 18 and hit a big blocker.  Our [repo](https://github.com/newrelic/node-newrelic) contains a mix of cjs and esm based tests.  It's for us to test instrumentation across the different methods.  After upgrading to tap 18 we get the following error

```sh
node:internal/process/esm_loader:34
      internalBinding('errors').triggerUncaughtException(
                                ^
[Error: ENOENT: no such file or directory, open '/path/to/esm-tap-repro/node_modules/@tapjs/test/dist/esm/@tapjs/test/test-built'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/path/to/esm-tap-repro/node_modules/@tapjs/test/dist/esm/@tapjs/test/test-built'
}
```

### Reproduction

https://github.com/bizob2828/esm-tap-repro

### Environment

```sh
❯ npm ls tap
tap-repro@1.0.0 /Users/revans/code/esm-tap-repro
└── tap@18.7.0
```

Node v20.11.0

**Comment by isaacs** [comment]
This is a IITM bug. https://github.com/DataDog/import-in-the-middle/issues/63
