### ISSUE TITLE
[BUG] t.context is undefined in t.beforeEach()

### ISSUE THREAD

**Issue by julien-f** [tapjs/tapjs#998]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the `CONTRIBUTING` guide on posting bugs, and `CODE_OF_CONDUCT`?

- [X] yes I read the things

### This issue exists in the latest tap version

- [X] I am using the latest tap

### Description

`t.context` is `undefined` in `t.beforeEach()`.

### Reproduction

```console
$ npm i tap

$ cat > index.spec.js <<EOF
const t = require('tap')

t.beforeEach(function (t) {
  t.context.foo = 'bar'
})

t.test('foo', function (t) {
  t.equal(t.context.foo, 'bar')
  t.end()
})
EOF

$ npx tap
 FAIL  index.spec.js 1 failed of 1 989ms
 ✖ foo > Cannot set properties of undefined (setting 'foo') index.spec.js:4:17

                       
  🌈 TEST COMPLETE 🌈  
                       

 FAIL  index.spec.js 1 failed of 1 989ms
 ✖ foo > Cannot set properties of undefined (setting 'foo')
    index.spec.js                     
     1 const t = require('tap')       
     2                                
     3 t.beforeEach(function (t) {    
     4   t.context.foo = 'bar'        
     ━━━━━━━━━━━━━━━━━━┛               
     5 })                             
     6                                
     7 t.test('foo', function (t) {   
     8   t.equal(t.context.foo, 'bar')
    type: TypeError
    index.spec.js:4:17

Asserts:  0 pass  1 fail  1 of 1 complete
Suites:   0 pass  1 fail  1 of 1 complete

# No coverage generated
# { total: 1, pass: 0, fail: 1 }
# time=1080.123ms
```

### Environment

- `tap@18.7.0`
- `npm@10.2.3`
- `node@18.19.0`

**Comment by MylesBorins** [comment]
I feel like https://github.com/tapjs/tapjs/commit/f105701e3500f884bd5a3a3cf0611d5a28999cb0 was an unexpected breaking change.

Previously `t.context` existed in `beforeEach` and could be extended, now it is set to `null` and has to be explicitly created. This broke my test suite
