### ISSUE TITLE
[BUG] Typo in manpage -h

### ISSUE THREAD

**Issue by James1x0** [tapjs/tapjs#999]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the `CONTRIBUTING` guide on posting bugs, and `CODE_OF_CONDUCT`?

- [X] yes I read the things

### This issue exists in the latest tap version

- [X] I am using the latest tap

### Description

Hi there! Noticed there is a small typo in the help section of the CLI. I would have submitted a PR, but I'm actually having a hard time discerning where the help docs are sourced from. Any pointers in the right direction and I can submit a fix :)

`Coverage Enfocement Options`

<img width="557" alt="Screen Shot 2024-02-02 at 12 47 53 PM" src="https://github.com/tapjs/tapjs/assets/6146261/cb91b121-7f5b-493e-90b1-c177ae944f7a">

### Reproduction

`tap -h`

### Environment

-

**Comment by piotr-cz** [comment]
@James1x0 
Which tap version is it?

**Comment by isaacs** [comment]
The text is coming from here: https://github.com/tapjs/tapjs/blob/main/src/config/src/jack.ts

**Comment by isaacs** [comment]
This is an issue in tap 16, the manpage in tap 18 doesn't have this section. Closing.
